### ISSUE TITLE
Gebruikers toevoegen aan Geoportaal team zodat ze issues in deze repository kunnen bewerken

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#1]

**Comment by gerardnienhuis** [comment]
gelukt, is ben toegevoegd :-)

**Comment by gerardnienhuis** [comment]
Wim Vliek, Reinder Hoekstra, Gerrit Jurjens, Nico Eilers, Ria Kalter, Peter Auke Nicolaij en André Weijmer ook toevoegen aan de personen die hier tekst kunnen inzien en kunnen toevoegen. Nu kan ik nog geen van alles benaderen als ik @ in de tekst toevoeg, mogelijk moeten rechten nog goed gezet worden hiervoor?

**Comment by HermanAssink** [comment]
Ria Kalter heeft zojuist via GitHub een uitnodiging ontvangen om lid te worden van het Geoportaal team. Wim Vliek is nog geen lid van GitHub. De overige namen zijn allen al lid van het Geoportaal team, met schrijfrechten. Die mensen zouden dus issues in deze repository moeten kunnen bewerken, net als jij Gerard.

**Comment by gerardnienhuis** [comment]
Hoi Herman

Ria is inmiddels ook toegevoegd: dat ging goed.

Wat moet Wim doen om lid te worden van Github?
Of moet jij nog wat doen hiervoor?

Ik hoor weer graag

Vrgr
Gerard

Van: Herman Assink [mailto:notifications@github.com]
Verzonden: vrijdag 5 februari 2016 11:50
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard)
Onderwerp: Re: [geoportaal-test] Gebruikers toevoegen aan Geoportaal team zodat ze issues in deze repository kunnen bewerken (#1)

Ria Kalter heeft zojuist via GitHub een uitnodiging ontvangen om lid te worden van het Geoportaal team. Wim Vliek is nog geen lid van GitHub. De overige namen zijn allen al lid van het Geoportaal team, met schrijfrechten. Die mensen zouden dus issues in deze repository moeten kunnen bewerken, net als jij Gerard.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/1#issuecomment-180292382.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by HermanAssink** [comment]
Wim Vliek moet zich aanmelden bij GitHub. Dat kan via [deze link](https://github.com/join).

**Comment by gerardnienhuis** [comment]
Hoi Herman
Wim zijn email adres zit er al in: kan het zijn dat hij al eerder is aangemeld?
Ik ga nu wachtwoord vergeten proberen

Vrgr
Gerard

Van: Herman Assink [mailto:notifications@github.com]
Verzonden: maandag 8 februari 2016 13:04
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard)
Onderwerp: Re: [geoportaal-test] Gebruikers toevoegen aan Geoportaal team zodat ze issues in deze repository kunnen bewerken (#1)

Wim Vliek moet zich aanmelden bij GitHub. Dat kan via deze linkhttps://github.com/join.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/1#issuecomment-181337184.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Hoi Herman
Het is inmiddels gelukt, Wim heeft nu ook toegang
Vrgr
Gerard

Van: Herman Assink [mailto:notifications@github.com]
Verzonden: maandag 8 februari 2016 13:04
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard)
Onderwerp: Re: [geoportaal-test] Gebruikers toevoegen aan Geoportaal team zodat ze issues in deze repository kunnen bewerken (#1)

Wim Vliek moet zich aanmelden bij GitHub. Dat kan via deze linkhttps://github.com/join.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/1#issuecomment-181337184.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Ria en Wim hebben toegang tot github (gisteren gecontroleerd).

Van: Herman Assink [mailto:notifications@github.com]
Verzonden: vrijdag 5 februari 2016 11:50
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard)
Onderwerp: Re: [geoportaal-test] Gebruikers toevoegen aan Geoportaal team zodat ze issues in deze repository kunnen bewerken (#1)

Ria Kalter heeft zojuist via GitHub een uitnodiging ontvangen om lid te worden van het Geoportaal team. Wim Vliek is nog geen lid van GitHub. De overige namen zijn allen al lid van het Geoportaal team, met schrijfrechten. Die mensen zouden dus issues in deze repository moeten kunnen bewerken, net als jij Gerard.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/1#issuecomment-180292382.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by HermanAssink** [comment]
Hallo Gerard, Als het klaar is dan kun jij het issue sluiten (Close). Gesloten issues worden niet verwijderd maar zijn altijd weer op te zoeken en na te lezen.
Groeten, Herman
