### ISSUE TITLE
Waarschuwing zelfde bijlage bij 1 record

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#105]
Ik had per ongeluk 2 keer dezelfde bijlage toegevoegd bij 1 record (1 statische kaart). Dat levert een crash op. Kan ik als gebruiker (voor het opslaan) gewaarschuwd worden, zodat ik die bijlage kan verwijderen. Een waarschuwing achteraf is ook prima. Dan leest de beheermodule alle bijlagen in, en negeert de 2e bijlage met dezelfde naam: na het opslaan volgt dan de melding dat er 1 of meerdere bijlagen met een zelfde naam aanwezig zijn, liefst ook met namen van bestanden erbij.

**Comment by gerardnienhuis** [comment]
kan niet worden getest: bijlagen toevoegen werkt niet meer, zie issue:
https://github.com/IDgis/geoportaal-test/issues/116

**Comment by gerardnienhuis** [comment]
Het lijkt wel te werken, maar de melding staat op de verkeerde plaats: deze melding moet komen op de plaats waar ook foutmeldingen komen (bij bijvoorbeeld verplichte items die niet zijn ingevuld). 

De gekozen achtergrondkleur kan gewoon ook standaard rood worden. Het is een teken, dat er iets fout is.

Er zijn bijlagen gekoppeld die dezelfde naam hebben. Verwijder deze bijlagen voordat je verder gaat.

**Comment by SandroNeumann** [comment]
De waarschuwing is achteraf te zien. Die waarschuwing op dezelfde plek weergeven als de andere betekent dat het een directe waarschuwing moet worden, wat relatief veel werk is.

**Comment by gerardnienhuis** [comment]
Gaan we testen Klinkt wel werkbaar deze oplossing

Verstuurd vanaf mijn iPhone

Op 4 jul. 2016 om 15:56 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

De waarschuwing is achteraf te zien. Die waarschuwing op dezelfde plek weergeven als de andere betekent dat het een directe waarschuwing moet worden, wat relatief veel werk is.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/105#issuecomment-230296436, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphP8ObDsbVqtufebbGO64pxcJkYaoks5qSRD4gaJpZM4H7uhv.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
werkt goed, issue gesloten
