### ISSUE TITLE
Beheren en rollen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#11]
Uitwerken en testen beheren: nog te controleren hoe werking gaat, als gebruikers slechts eigen data mogen zien en beheerders meer rechten hebben (b.v. mogen publiceren). Dat is nog niet te testen

opmerking nr 2 n.a.v. testen 3-2-16

**Comment by HermanAssink** [comment]
Leverancier (en beheerder?) mag metadata niet bewerken als deze gepubliceerd is.

**Comment by gerardnienhuis** [comment]
kan gesloten: 1 nieuwe wens: nummer #78
