### ISSUE TITLE
rapportage: 3 soorten uitbreidingen geodatarapport

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#110]
Naast alle info (metadata) geodata sets moet er in de rapportage ook komen te staan:

1) beschikbaarheid data en metadata (in 4 soorten):

dataset afwezig (zie hieronder)
metadata en data alleen intern
metadata extern en data niet downloadable
metadata extern en data downloadable

2) is WMS of WFS beschikbaar (ja of nee)

3) url van WMS en WFS die beschikbaar zijn

Toelichting:

Omdat bestanden ook door beheerder Geoportaal kunnen verwijderd, kunnen er ook fouten optreden.
Data verwijderd, maar services nog beschikbaar. De kans is groot, dat dit niet wenselijk is.

Daarom moet de WMS en WFS staan, als datasets niet meer aanwezig zijn (dus id en rest van de meta afwezig, maar toch beschikbaar en url daarvan in rapport vermelden. De status voor beschikbaarheid van zo'n dataset is dan "dataset afwezig".

Hierdoor kunnen eventuele fouten snel worden opgespoord en zo mogelijk gecorrigeerd.

**Comment by NicoEilers** [comment]
Kan dit al in 1.1.3 meegenomen?

**Comment by HermanAssink** [comment]
T.b.v. schatting overgezet naar 1.1.3. Als het budget overschreden dreigt te worden opnieuw bezien.

**Comment by robstek** [comment]
NB voor rasterdata verdwijnt de WFS url (zie issue #  )

**Comment by robstek** [comment]
ad 3. domein uit url weglaten, indien domeinnaam technisch lastig vast te stellen is

voorbeeld: 
http://services.geodataoverijssel.nl:80/geoserver/B42_energie/wfs
wordt:
/geoserver/B42_energie/wfs

**Comment by SandroNeumann** [comment]
Het eerste punt:

dataset afwezig (zie hieronder) 
metadata en data alleen intern
metadata extern en data niet downloadable
metadata extern en data downloadable

Dataset afwezig wordt al gedaan door issue #285, metadata extern of intern wordt gedaan door issue #359 en downloadable wordt gedaan door issue #278.

Het derde punt komt in het rapport van de services te staan en lijkt hier overbodig.

**Comment by gerardnienhuis** [comment]
@SandroNeumann  : ... Het derde punt komt in het rapport van de services te staan en lijkt hier overbodig. 

Dat is niet overbodig: het is heel erg handig als je in rapport van geodata ook direct de url van de services hebt.

**Comment by gerardnienhuis** [comment]
Rapportage blijkt alle bovenstaande wensen weer te geven. Issue kan gesloten.
