### ISSUE TITLE
melding bij opslaan record statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#112]
suggestie voor nieuwe versie, als productieversie af is, tenzij eenvoudig te realiseren is

als bestanden groot zijn en internet verbinding slecht, dan
zie je alleen aan kleurverandering dat opslaan bezig is: 
kan er na het aanklikken van die knop een melding komen

(boven de knop opslaan) met de tekst:

Het opslaan van dit record is gestart. Je kunt deze gegevens zo direct bekijken. 
Deze komen boven te staan in de lijst van zoekresultaten.

Die knoppen opslaan en annuleren kunnen dan ook weg: het opslaan is tenslotte al bezig.

Die melding kan dan weg (de hele pagina kan gesloten) als opslaan is gelukt
Je gaat dan, zoals nu ook al goed werkt, naar de beginpagina.

**Comment by SandroNeumann** [comment]
Het effect gaat wel zijn dat bij records met bijlagen die klein zijn en waar binnen een seconde is opgeslagen dat bericht ook verschijnt, maar vervolgens heel snel weg is. Als een soort flits. Dat gaat er niet heel fraai uitzien. Wil je het nog steeds?

Een alternatief zou zijn om een zandloper icoontje ergens boven of naast de knoppen te zetten. Om toch enige feedback te geven.

**Comment by gerardnienhuis** [comment]
Zandloper klinkt als goed alternatief

Kunnende knoppen opslaan en help dan ook eerst verwijderd worden

Voordat de zandloper getoond wordt?

Verstuurd vanaf mijn iPhone

Op 19 apr. 2016 om 14:47 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Het effect gaat wel zijn dat bij records met bijlagen die klein zijn en waar binnen een seconde is opgeslagen dat bericht ook verschijnt, maar vervolgens heel snel weg is. Als een soort flits. Dat gaat er niet heel fraai uitzien. Wil je het nog steeds?

Een alternatief zou zijn om een zandloper icoontje ergens boven of naast de knoppen te zetten. Om toch enige feedback te geven.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/112#issuecomment-211908466

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
Dat kan zeker.

**Comment by gerardnienhuis** [comment]
Zandloper is zichtbaar, en knoppen zijn weg. Werkt prima op deze manier.
Issue kan gesloten
