### ISSUE TITLE
Bij IE en FF ontbreken datumvermeldingen bij toevoegen statische kaart

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#114]
Als je in Internet Explorer of Firefox een datum wilt aangeven, dan zie je niet de vermelding dd mm jjjj
maar je ziet een wit invoerschermp. Dit in tegenstelling tot Chrome en Opera, waar je wel correct datumvermelding ziet bij toevoegen. 
![ie_ff_datum_vermelding_ontbreekt](https://cloud.githubusercontent.com/assets/9005444/14564205/c348271c-0325-11e6-95a5-df5a7cefcbec.jpg)

**Comment by gerardnienhuis** [comment]
hier plaatje hoe het wel goed gaat, in Chrome en Opera

![chrome_opera_datum_goed](https://cloud.githubusercontent.com/assets/9005444/14564278/0c583348-0326-11e6-855a-3246676f1a44.jpg)

**Comment by SandroNeumann** [comment]
Dat is een browser implementatie.Wat Chrome doet gebeurt automatisch wanneer de browser ziet dat het een datum veld is. FF en IE ondersteunen het datum veld niet, dus daarom blijft het leeg.

**Comment by gerardnienhuis** [comment]
Het werkt nog steeds hetzelfde: wel in Chrome en Opera, niet in IE en FF. Maar omdat picklist naast het datumveld wel allemaal werkt, is dit zo'n probleem. Issue kan gesloten worden.
