### ISSUE TITLE
Extra tekst i knop toevoegen bijlage

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#122]
De tekst aanpassen bij toevoegen bijlage (bij de i - knop, zie bijlage)

De laatste regel van de tekst is nu:

Verwijderen: klik op het gommetje.

Die tekst moet worden:

Bestanden die als bijlage zijn gekoppeld, die kan je verwijderen
met het x-je. Heb je nog geen bestand gekoppeld, dan kan je
het gommetje gebruiken.

De maximale grootte is 200 MB. Dit geldt voor individuele bestanden.
Je kan 1 bestand van 200 MB aanbieden, of 2 bestanden van 100 MB.
Wil je nog meer data toevoegen, dan kan je dit record opslaan en
daarna wijzigen. Je kan dan weer 200 MB maximaal toevoegen.

![i_knop_bijlage](https://cloud.githubusercontent.com/assets/9005444/14718915/91efd3da-07f9-11e6-8b36-126d29cca4e3.jpg)

**Comment by gerardnienhuis** [comment]
is nu goed, issue kan gesloten

**Comment by HermanAssink** [comment]
Hallo Gerard, Fijn dat je ze zo actief aan het testen bent, maar zou je niet een keer weekend houden?
Groeten, Herman

**Comment by gerardnienhuis** [comment]
volgende week vakantie, wil dit graag voor die tijd afhebben... trouwens, jij lees dit ook blijkbaar op zaterdagavond :+1:
