### ISSUE TITLE
Controle datum geldig van tot

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#125]
Er is bij het invoerscherm van statische kaarten nu geen toetsing bij de datums: 

1) De "datum geldig van" kan bij voorbeeld een latere datum zijn dan de "datum geldig tot"
2) De creatiedatum kan later zijn dan de mutatiedatum enz. 

Er zijn een aantal niet logische combinaties, die nu allemaal wel ingevoerd kunnen worden.
Wens is, dat nadat de knop opslaan wordt ingedrukt, er een waarschuwing komt, met de tekst
dat er een onlogische datum is ingevoerd.

Bij de eerste situatie komt dan de melding:

Er is een onlogische datum ingevoerd. Datum "geldig van" is later dan de datum "geldig tot".

**Comment by NicoEilers** [comment]
let op: we gebruiken geen mutatiedatum meer...

De creatiedatum kan later zijn dan de **mutatiedatum** enz. 

moet dus worden:

De creatiedatum kan later zijn dan de **publicatiedatum** enz.

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
