### ISSUE TITLE
Invullen locatie standaard uitvoeren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#129]
Wens is om de locatie van statische kaarten bij het invoeren standaard in te laten vullen (en wel te laten wijzigen, als dat zinvol is).

Bij het kiezen van een bijlage is het pad (zonder filenaam) meestal de locatie (zie figuur).
Door het invoerscherm van de bijlage eerst weer te geven, kan het pad naar de bijlage worden gebruikt, om de locatie te laten invullen. 

Worden meerdere bijlagen gebruikt, dan blijft gewoon de eerste locatie er staan. Wil een leverancier toch een andere locatie, dan kan dat achteraf alsnog aangepast worden.

![locatie_in_te_vullen](https://cloud.githubusercontent.com/assets/9005444/14720236/cb561ba0-0800-11e6-9959-9334965fa5f2.jpg)

**Comment by HermanAssink** [comment]
Om beveiligingsreden kan een webapplicatie niet bij de padnaam/filenaam van een te uploaden bestand. Deze wens kan dus technisch niet.

**Comment by gerardnienhuis** [comment]
jammer, maar er is mogelijk een alternatief: default tekst neerzetten en ieder jaar updaten

**Comment by gerardnienhuis** [comment]
nu, in 2016, wordt door een gebruiker standaard ingevoerd:
K:\BAB\Geo-informatie\2016

Als dat nu vooraf ingevuld wordt door de applicatie dan hoeven alle gebruikers dat niet zelf te doen
Betreft het dan, soms, een ander jaar, dan hoeft er maar een kleine aanpassing gedaan te worden, door de gebruiker zelf, b.v. vervang:

K:\BAB\Geo-informatie\2016
in 
K:\BAB\Geo-informatie\2015

nb: moet dan wel bij ieder jaar (eerste week van nieuwe jaar) door IDGis worden aangepast
dus in 2017 moet er komen te staan:
K:\BAB\Geo-informatie\2017

**Comment by NicoEilers** [comment]
Het blijkt goed te werken. Dit issue kan naar "beheer" omdat op 1-2-2017 de verwijzing naar K:\BAB\Geo-informatie\2016 moet veranderen naar K:\BAB\Geo-informatie\2017

merk op: niet meteen op 1-1-2017 omdat de eerste maand nog gewerkt wordt in 2016

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
