### ISSUE TITLE
Sorteren moet niet hele pagina tonen, maar alleen lijst

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#131]
Als je nu sorteert op een item in de lijst van statische kaarten, dan wordt het resultaat getoond. Dat werkt goed, maar het scherm wordt weer helemaal getoond. Liever zou je de lijst zelf compleet op het scherm zien. Dus na sorteren vooral de lijst in beeld hebben

(zie pijltje in figuur): sorteer je dan nog een keer op een ander item, dan springt het scherm niet meteen weer omhoog, maar blijft het staan op de plaats waar het staat voor het sorteren.
![blijven_staan_na_sorteren](https://cloud.githubusercontent.com/assets/9005444/14720644/c147137e-0802-11e6-8822-bbdad3eb83cc.jpg)

**Comment by SandroNeumann** [comment]
Een anchor maken van de lijst waar de pagina heen verwijst bij sorteren.

**Comment by gerardnienhuis** [comment]
werkt goed, bij sorteren komt automatisch de volledige lijst in beeld
issue kan gesloten
