### ISSUE TITLE
04474356 conversie fout gegaan: is APR

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#133]
In de metadata staat bij relation id: 04474356.APR

toch blijkt dat hier niet het type Arc view project aan is toegekend. Hoe kan dat? Is conversie wel goed gegaan? 

Gevonden met steekproef, gericht op formaten die ontbraken in laatste overzicht. Veel FH8 en FH10 gevonden die wel correct zijn geconverteerd. Gaat het soms fout bij sommige APR bestanden?

**Comment by gerardnienhuis** [comment]
Ook fout gevonden bij 04456274 (is ook APR)

**Comment by SandroNeumann** [comment]
Het metadata document dat hiervoor gebruikt werd had onder relation niet de waarde 04474356.APR, maar gewoon 04474356. Om die reden is er niks aan formaat toegekend.

**Comment by gerardnienhuis** [comment]
blijkt voor dit record inderdaad te kloppen. overige conversie-items worden steekproefsgewijs nu nog getest.

**Comment by gerardnienhuis** [comment]
testen lopen nog, resultaten worden zsm hier vermeld. Steekproeven zien er vooralsnog goed uit.

**Comment by gerardnienhuis** [comment]
testen afgerond: steekproeven laten zien dat conversie goed is afgelopen. issue kan gesloten
