### ISSUE TITLE
Stylesheet ruimtelijke bestanden geen urls wms/wfs/download tenzij downloadable

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#137]
De stylesheet van ruimtelijke bestanden (geodata) laten reageren op de tag "downloadable".
De url van wms, wfs en downloadlink alleen weergeven als in de metadata staat, dat het betreffende bestand downloadable is.

Hiermee wordt voorkomen, dat een fout die in de publicatieomgeving gemaakt is mbt wel of niet downloaden ook direct in het geoportaal in de metadata zichtbaar is.

**Comment by HermanAssink** [comment]
@gerardnienhuis Hiervoor zal niet de stylesheet, maar de metadata xml worden aangepast. Zoals bekend heeft dit ook impact op de GIS-Publicatieomgeving. We geven hiervoor z.s.m. een schatting af.

**Comment by HermanAssink** [comment]
@SandroNeumann : Hoeveel werk is het om de style sheet hiervoor aan te passen.

**Comment by gerardnienhuis** [comment]
Dit probleem is goed opgelost, steekproeven laten zien dat nu als er niet "downloadable" staat, dit ook niet in stylesheet is terug te vinden: beveiligingsrisico is hiermee niet opgelost, laag bestaat nog wel in service, moet daar ook verwijderd worden (kan nu door invullen id in downloadlink waarschijnlijk nog gedownload worden), Dat probleem wordt elders opgelost, dit issue kan gesloten worden.
