### ISSUE TITLE
Download tekst aanpassen witregels en versie nummer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#139]
Onder de knoppen download en help graag 3 regels witruimte. Er lijkt nu 1 of geen regel wit te zijn, zie plaatje.

Ook graag de tekst mbt versie verwijderen in de uiteindelijke versie
![witregel_download_na_knop_download_help](https://cloud.githubusercontent.com/assets/9005444/14781919/dbce6a7c-0ae5-11e6-983f-c70932de82d6.jpg)

**Comment by HermanAssink** [comment]
Witregels worden toegevoegd.
Versie willen we laten staan zodat de gebruiker bij problemen de gebruikte versie kan rapporteren.

**Comment by gerardnienhuis** [comment]
Nav overleg besloten de versie te laten staan. Voor de vermelding van de versie komen 2 extra witregels. Voor de versie komt andere tekst. 

Er staat nu: download-tool versie: 0.9.0

Er komt te staan: Download-tool van het Geoportaal van Overijssel, versie 0.9.0.

**Comment by gerardnienhuis** [comment]
ziet er nu goed uit, issue kan gesloten worden
