### ISSUE TITLE
mail tekst van link download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#140]
Er staat nu in de mail: 

Geachte .... 

U kunt bestand B0_6_cijferig_postcodebestand.zip downloaden via de volgende link: 
https://acc.geoportaaloverijssel.nl/download-result/614572a0-34de-4a43-83a4-6fd2227c15fd.

Deze tekst moet worden: "Je kunt ...." (stijl Overijssel, alles met je ipv u)

Tussen de tekst "Je kunt ... " en de url graag 1 regel witruimte

Na de url moeten 2 regels witruimte komen, met daarna de tekst

Deze link is 24 uur bruikbaar.

Deze mail is verzonden omdat iemand dit emailadres heeft opgegeven voor een download van een bestand uit het Geoportaal van Overijssel. Mocht jij niet de persoon zijn, die deze download heeft aangevraagd, dan kan je deze mail verder negeren. 

Zijn er vragen over de download, neem dan contact op met beleidsinformatie@overijssel.nl

**Comment by HermanAssink** [comment]
Is vergelijkbaar aan #143

**Comment by gerardnienhuis** [comment]
merk op: 

#140 gaat over bestanden die gedownload worden. 
maar; #143 gaat over de tekst die in de mail moet komen te staan

**Comment by HermanAssink** [comment]
Alleen tekstuele aanpassingen in de email.

**Comment by gerardnienhuis** [comment]
De mail tekst is nu goed, zie als voorbeeld:

Je download aanvraag 'B5_Grootschalige_recreatieprojecten' van Geoportaal Overijssel staat gereed
noreply@geoportaaloverijssel.nl [noreply@geoportaaloverijssel.nl]
Verzonden:  zondag 29 mei 2016 15:44
Aan:  
Nienhuis, G (Gerard)
Geachte Gerard test 29-5-2016, download test shp met Chrome, 

Je kunt bestand B5_Grootschalige_recreatieprojecten.zip downloaden via de volgende link: 

https://acc-download.geoportaaloverijssel.nl/download-result/fd3576ad-c3e4-4d90-b692-45858f3d241e.

Deze link is 24 uur bruikbaar.

Deze mail is verzonden omdat iemand dit emailadres heeft opgegeven voor een download van een bestand uit het Geoportaal van Overijssel. Mocht jij niet de persoon zijn, die deze download heeft aangevraagd, dan kan je deze mail verder negeren.

Zijn er vragen over de download, neem dan contact op met beleidsinformatie@overijssel.nl

issue kan gesloten worden
