### ISSUE TITLE
download maakt geen zip

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#141]
als ik de melding in de mail krijg, dat ik een zip krijg, dan verwacht ik in de download een zip op mijn harde schijf aan te treffen. Nu krijg ik een bestand, zonder extensie, wat ik niet kan openen. Pas als ik de naam wijzig in iets.zip, dan blijkt het bestand te openen: dat moet niet, ik moet direct een zip als download ontvangen: dus direct bestand incl extensie downloaden. 

nb: mail melding is nu:

U kunt bestand B0_6_cijferig_postcodebestand.zip downloaden via de volgende link: 
https://acc.geoportaaloverijssel.nl/download-result/614572a0-34de-4a43-83a4-6fd2227c15fd

die zip zit trouwens wel in het bestand iets.zip, dus dat lijkt wel correct

**Comment by gerardnienhuis** [comment]
correctie: er wordt wel altijd een zip gemaakt, allen was waarschijnlijk in de explorer van de tester de optie "verberg extensie van bekende bestanden" aangezet. Issue speelt waarschijnlijk nergens en kan gesloten worden.

**Comment by HermanAssink** [comment]
Ik heb het ook gezien. We zullen dit nog eens testen om met zekerheid vast te stellen of het probleem al of niet optreedt.

**Comment by gerardnienhuis** [comment]
het vreemde is dat het thuis niet blijkt op te treden (IE met windows 8.1). Hier op het werk bij het provinciehuis (ook IE maar windows 7) komt er geen extensie als je download. Nu kan je zelf .zip er achter zetten, maar voor gebruikers is dat heel ongewoon en foutgevoelig. Lijkt bug
![extensie_ontbreekt](https://cloud.githubusercontent.com/assets/9005444/14812590/0a2889bc-0b9e-11e6-8246-4cb5dd27c1a7.jpg)

**Comment by HermanAssink** [comment]
Zoeken we uit

**Comment by copierrj** [comment]
De server stuurt op dit moment enkel een content-type op naar de client. Het lijkt erop dat niet alle browsers hiermee tevreden zijn. Het toevoegen van een content-disposition verhelpt dit probleem waarschijnlijk.

bijbehorend download-tool issue: IDgis/download-tool#104

**Comment by gerardnienhuis** [comment]
getest met IE, FF, Chrome en Opera. Lijkt allemaal goed te werken, issue kan gesloten worden
