### ISSUE TITLE
stylesheet na download tabs en info fout

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#142]
De stylesheet die meegeleverd wordt met de download resultaten werkt niet: het bestand 
wat aangeklikt is, is bv e91220d6-86e8-4f77-b744-45ac36f58902.xml

Dat werkt niet goed: alleen de eerste tab bevat tekst en de rest van de tabs tonen een wit scherm
ook is de vormgeving niet zoals afgesproken: plaatjes en tekst zitten foutief op de knop en door elkaar

![dowload_stylesheet_tabsfout_info_ontbreekt](https://cloud.githubusercontent.com/assets/9005444/14782431/9e810f9a-0ae9-11e6-8418-a1596aeca1c3.jpg)

**Comment by gerardnienhuis** [comment]
is bijzonder effect: bij testen thuis (met IE en andere browsers) is bovenstaand effect niet te zien. Waar het wel afhankelijk van is, weet ik niet: firewall instellingen?

**Comment by HermanAssink** [comment]
Hoe kunnen we dit reproduceren?

**Comment by gerardnienhuis** [comment]
![ie](https://cloud.githubusercontent.com/assets/9005444/14816906/dd00dea6-0bb3-11e6-9df9-9a356cdc5de9.jpg)

**Comment by SandroNeumann** [comment]
**@gerardnienhuis**: heb je dit nog een keer kunnen reproduceren? In mijn geval doet de stylesheet het bij die dataset in zowel IE(11) en Firefox.

**Comment by gerardnienhuis** [comment]
Er is op zijn minst iets vreemds met dit bestand: als ik vanuit het externe portaal vertrek, dan zie ik hier in Overijssel niet eens een download link: mogelijk dat ik moet vertrekken vanuit het interne portaal. verwarring kan veroorzaakt zijn door #5 

wordt verder uitgezocht, hieronder de info die ik nu aantref, bij het onderdeel DETAILS:

Bestandsnaam: 6-cijferig postcodebestand
Alternatieve titel: B0.pcc6_polygon (b0/b05)
Status: Compleet
Versie: peildatum 1 januari 2013
Algemene beschrijving herkomst: Bridgis BV
Potentieel gebruik: Basisdata 
Onderwerp: Grenzen
Onderwerp: Ruimtelijke ordening en kadaster
Trefwoord: postcodegebieden
Trefwoord: postcodes
Thesaurus trefwoorden: Interprovinciale thesaurus
Publicatie datum thesaurus: 2013-09-11
Gebruiksbeperkingen:  Geoportaal extern 
(Juridische) toegangsrestricties: Licentie
Metadata unieke identifier: e91220d6-86e8-4f77-b744-45ac36f58902
Metadata karakterset: utf8
Metadata hiërarchieniveau: Dataset
Metadata standaard naam: ISO 19115
Metadata standaard versie: Nederlandse metadata profiel op ISO 19115 voor geografie 1.2
Karakterset van de bron: utf8
Unieke identifier: cd3e6601-cc53-4896-87a9-6748c83f8684
Niveau kwaliteitbeschrijving: Dataset
Deze informatie wordt beschikbaar gesteld door het Geoportaal van de Provincie Overijssel.
De gegevens zijn gemaakt voor eigen (intern) gebruik door de provincie Overijssel.
Zijn er suggesties of vragen, neem dan contact op met beleidsinformatie@overijssel.nl

**Comment by SandroNeumann** [comment]
De download link wordt alleen getoond wanneer er staat dat de dataset downloadable is. Dat is bij deze dataset niet het geval. Zie #137.

**Comment by gerardnienhuis** [comment]
Het blijft vreemd: als ik een service bekijk, waar deze kaartlaag in zit, dan opent ook deze correct. (hier in Overijssel). Maar als ik probeer het 2e bestand uit deze service te bekijken, dan krijg ik de melding dat de pagina niet te openen is: ik had dus verwacht de stylesheet van het bestand te zien.
dus: b0_6_cijferig_postcodebestand kan ik hier intern Overijssel zonder problemen zien in een stylesheet, en daar is geen download. Maar b0_6_cijferig_postcodebestand_centroides geeft foutmelding als ik de betreffende laag aanklik: zie plaatje

![6_cijferig_postcode](https://cloud.githubusercontent.com/assets/9005444/15706989/b92203e8-27f6-11e6-9929-a9606a474109.jpg)

**Comment by gerardnienhuis** [comment]
Overigens: 

"De download link wordt alleen getoond wanneer er staat dat de dataset downloadable is. Dat is bij deze dataset niet het geval." 

Dat wil dus zeggen dat ik nooit bij die downloadlink kan komen, toch? Dat ik die wel eens heb gezien, lijkt een niet reproduceerbare fout. Ik ga er nu meer testen, zowel intern als extern Overijssel.

**Comment by gerardnienhuis** [comment]
dit klopt nog steeds niet: als ik bij postcodes een download link zie, dan neem ik als gebruiker aan dat ik download kan uitvoeren, maar ik krijg melding:

404 Niet gevonden
Het gevraagde dataset (met id 'e4379b51-e4f0-427a-8300-26b1fc0a83c9') bestaat niet.

Dat is dus niet logisch en lijkt ook niet juist dat ik dan wel download link zie bij dit bestand, zie:

![postcode_download_fout](https://cloud.githubusercontent.com/assets/9005444/16710417/935dc476-462d-11e6-8f25-88fcb605cc24.jpg)

**Comment by gerardnienhuis** [comment]
probleem blijkt opgelost, issue kan gesloten
