### ISSUE TITLE
bij download een naam.xls of  leesmij.xls meeleveren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#143]
nu wordt de metainfo ontsloten via een xls die het id in zich heeft, beter is het om hiervoor de naam van het gedownloade bestand te gebruiken.

In het onderstaande voorbeeld: 

U kunt bestand B0_6_cijferig_postcodebestand.zip downloaden via de volgende link: 
https://acc.geoportaaloverijssel.nl/download-result/614572a0-34de-4a43-83a4-6fd2227c15fd.

wordt de xls dus: B0_6_cijferig_postcodebestand.xls

als het makkelijker is, dan is een leesmij.xls ook een goed alternatief

dan begrijpen mensen duidelijker, dat hier meer info te vinden is

nb: de xls staat wel op de juiste plek in de zip bji het betreffende bestand, wat is gedownload.
locatie is ok, naam kan beter

**Comment by HermanAssink** [comment]
Gaan we doen als het niet teveel werk is.

**Comment by gerardnienhuis** [comment]
is prima. zou mooi zijn als het meteen te regelen is nu. Bij testen merk ik dat het extreem lastig is om data op basis van uuid uit elkaar te houden.

**Comment by gerardnienhuis** [comment]
werkt goed met FF en IE. Toelichten in help en tzt oplossen door leesmij.txt toe te voegen met instructies en downloadgeschiedenis. kan vooralsnog gesloten worden

**Comment by HermanAssink** [comment]
Graag deze wens scherper formuleren. Wat moet het resultaat precies zijn?

**Comment by gerardnienhuis** [comment]
Overleg is nodig: nu komen verschillende bestanden mee met de download. Hier moet een manier beschikbaar komen die voor gebruikers eenvoudiger te gebruiken is. Een leesmij.txt met uitleg over de meegeleverde bestanden zou een eerste (misschien meest eenvoudige) oplossing kunnen zijn. Als in dit bestand ook al wat andere relevante informatie kan worden opgeslagen, dan is dat mooi meegenomen. Ik denk aan de informatie die ook in de mail staat die je bij een download ontvangt.

Dus eerst wat feiten over de download, dit is voor iedere download anders.
En daaronder een standaard een stukje instructie (steeds dezelfde tekst).

Als dat samen in een bestand met de naam leesmij.txt kan worden gezet, dan is het voor de meeste gebruikers veel duidelijker waar ze moeten beginnen met uitzoeken.
