### ISSUE TITLE
extra_informatie.html in de zip met de download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#146]
Kan er bij de xml en de xls ook een bestand worden gezet met de naam extra_informatie.html?
in dit bestand hoeft alleen maar een verwijzing opgenomen te worden naar de betreffende xml, zodat 
je door op de html te klikken direct de metainformatie in een browser kunt zien: nu zullen veel mensen nog moeten zoeken (en xml is niet altijd standaard in een browser geopend, soms is notepad of kladblok hiervoor het standaardprogramma)

**Comment by HermanAssink** [comment]
Bijvoorbeeld een readme.html zodat gebruikers eerder op het idee komen om de xml in de browser te openen.

**Comment by gerardnienhuis** [comment]
Logischer is het om een leesmij.txt neer te zetten, met daarin wat instructies en overige info.
Tzt. verder oppakken. Issue kan nu gesloten worden
