### ISSUE TITLE
Bij downloaden stylesheet externe metadata gebruiken, is nu interne stylesheet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#147]
Bij downloaden (is bijna altijd voor extern gebruik) moet de stylesheet voor geodata voor externe bestanden worden gebruikt. Nu wordt alle metainfo getoond. Bij externe bestanden hoort alleen de eerstgenoemde contactpersoon te worden vermeld. Nu is foutief ook de naam van de interne contactpersoon vermeld, zoals bijvoorbeeld hieronder. Dat is kenmerkend voor de interne metainfo, die moet nu extern in een stylesheet getoond worden.

Beheerder van het bestand
Naam: Provincie Overijssel
Website: www.overijssel.nl
Naam: team Beleidsinformatie
Rol: Beheerder
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands

Eigenaar van het bestand
Naam: Provincie Overijssel: eenheid Publieke Dienstverlening
Website: http://www.overijssel.nl
Naam: Brouwer, Dhr. Michiel
Rol: beheerder
E-mail: MW.Brouwer@overijssel.nl
Adres: Postbus 10051
Postcode: 8000GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands

Auteur bestandsbeschrijving
Naam: Provincie Overijssel: team Beleidsinformatie
Website: www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Distributeur van het bestand
Naam: Provincie Overijssel: team Beleidsinformatie
Website: www.overijssel.nl
Naam: Team Beleidsinformatie
E-mil: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

**Comment by HermanAssink** [comment]
Is nog niet gebouwd. Gaan we toevoegen

**Comment by gerardnienhuis** [comment]
kleurstelling is nu conform externe stylesheet, dat is opgelost.  

nb: het teveel aan contactpersonen (issue #181 ) is nog niet opgelost overigens.

Dit issue kan gesloten.
