### ISSUE TITLE
Metadata uit download niet te bekijken met Chrome en Opera

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#150]
De xml die is meegeleverd bij de download, die is wel te gebruiken om de metadata te bekijken, als je IE of Firefox gebruikt. Dan zie je, als je er op klikt, de metainfo met de juiste vormgeving en stylesheet. Gebruik je Opera of Chrome, dan krijg je een wit scherm.

**Comment by HermanAssink** [comment]
Waarschijnlijk is de beveiliging in die browsers zodanig ingesteld dat de xsl niet wordt uitgevoerd. Het zipje moet eerst sowieso uitgepakt zijn. Klikken op de xml in de zip werkt niet.

**Comment by HermanAssink** [comment]
Zie bijv: http://stackoverflow.com/questions/2981524/how-can-i-make-xslt-work-in-chrome

**Comment by gerardnienhuis** [comment]
idee: html van maken en alleen html in zip meeleveren: is luxe voor beheerfase. 
wordt nu extra tekst in helpscherm

**Comment by HermanAssink** [comment]
@copierrj Kunnen we dit verklaren/reproduceren? Wat is de oplossing?

**Comment by HermanAssink** [comment]
Actie voor deze versie:  Toelichting opnemen in HELP

**Comment by gerardnienhuis** [comment]
ik heb  http://stackoverflow.com/questions/2981524/how-can-i-make-xslt-work-in-chrome en andere suggesties bekeken: dat is niet iets, wat ik in help voor gemiddelde gebruiker ga zetten. Veel te complex. Beter is het, om op termijn hier een pdf met metainfo van te maken, en die pdf altijd mee te leveren bij een download. 

Wat nu wel eventueel in de help kan, is de suggestie om IE of FF te gebruiken (maar is wel tegen voornemen om alles browseronafhankelijk te laten zijn, zoals in FO staat)

**Comment by gerardnienhuis** [comment]
Helptekst moet nog wat verder aangepast, maar dit is inderdaad wel een logische plaats om het (ook) neer te zetten.

**Comment by gerardnienhuis** [comment]
Dit nu niet verder oplossen, tzt ook in de download een .txt bestand plaatsen: leesmij.txt,
hierin zowel de geschiedenis van de download en ook de instructies voor openen in IE of FF van 
leesmij.xml voor meer info.

kan vooralsnog gesloten worden
