### ISSUE TITLE
Controle op emaladres uitleggen in helptekst

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#151]
ik heb zojuist een typfout gemaakt bij het opgeven van mijn emailadres in het download scherm. Ik krijg geen foutmelding. Ik dacht dat controle op juistheid van emailadres wel heeft gewerkt.
Zie invoer hieronder: nl ontbreekt bij mijn mailadres.
Maar download geeft aan dat alles goed is verwerkt. Hoe kan dat?

nb: ik heb meerdere downloads gedaan, en ga met de knop BACK terug naar het vorige scherm, als ik melding krijg dat download verzoek is ontvangen. 

Je download verzoek is in goede orde ontvangen. De download wordt nu voor je klaargezet.

Het bestand is: Gebieden voor waterberging en primaire watergebieden
Het formaat is: GML 3.2
E-mail adres is: g.nienhuis@overijssel 

Je krijgt zo snel mogelijk een e-mail met een download-link.
 Via deze link kun je de download van het bestand uitvoeren.

**Comment by HermanAssink** [comment]
Het gebruikte mailadres is technisch gezien geldig. In het FO staat hierover "Er wordt tevens gecontroleerd of het om een geldig e-mailadres gaat. Er moet in ieder geval een '@' in het e-mailadres staan. ". In de huidige versie wordt hiervoor de in de ontwikkeltool beschikbare controle gebruikt.

**Comment by gerardnienhuis** [comment]
ok, zetten we in de helptekst, is geen bug

**Comment by gerardnienhuis** [comment]
Helptekst moet worden aangepast. Issue zelf kan gesloten worden.
