### ISSUE TITLE
Bij rapportage ook rapportage gebruik van download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#154]
Wens: inzicht in soort gebruik van download.

Naam bestand, naam gebruiker, email gebruiker, type bestand en datum en tijd
Als rapport via de rapporten pagina beschikbaar stellen, zodat beheerder op ieder moment een overzicht kan maken van het gebruik van het download onderdeel

**Comment by HermanAssink** [comment]
In het FO staat hierover: "Op verzoek van Overijssel wordt op adhoc basis (4x per jaar) rapportage geleverd van de bestanden, namen, emailadressen en tijdstippen van download."

**Comment by gerardnienhuis** [comment]
ik wil graag alle informatie die beschikbaar is, dus ook type bestand. Graag net als andere rapportages als .csv file. T.z.t. lijkt het me makkelijk om als beheerder zelf die rapportages op ieder moment te kunnen aanmaken en downloaden.

nb: is zelfde als #165 

per ongeluk dubbel opgevoerd, kan samengevoegd.

**Comment by gerardnienhuis** [comment]
werkt goed, kan gesloten
