### ISSUE TITLE
Type bestand in rapportage

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#155]
Verzoek om naast de bestaande informatie ook in de rapportage van datasets op te nemen welk type het betreft:
- raster
- geodataset
- tabel

**Comment by gerardnienhuis** [comment]
is onderdeel van issue #235

**Comment by copierrj** [comment]
Wat is hier het verschil tussen 'geodataset' en 'tabel'?

**Comment by gerardnienhuis** [comment]
Tabel is iets wat geen geodata is dus bv alleen unfo per gemeente zonder dat dit is gekoppeld een geodataset van gemeenten

**Comment by copierrj** [comment]
Dus een Oracle tabel zonder geometrie kolom?

**Comment by gerardnienhuis** [comment]
Ja

**Comment by gerardnienhuis** [comment]
Kijk voor voorbeelden in geoportaal en zoek nAar tabel
Zijn stuk of 30

**Comment by robstek** [comment]
wordt afgeleid uit het ruimtelijk schema in de metadata

**Comment by gerardnienhuis** [comment]
Dit blijkt goed te werken: issue kan gesloten
