### ISSUE TITLE
Datumnotatie in stylesheets DD-MM-JJJJ

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#162]
Nu staan bijna alle datumvermeldingen in stylesheets niet in de volgorde dag-maand-jaar.
er staat bijvoorbeeld: Datum creatie: 2002-09-16

Alle stylesheets (statische kaarten, geodata en services) aanpassen, zodat er wel de gebruikelijke dag-maand-jaar vermelding komt te staan, dus in bovenstaand voorbeeld 16-09-2002

**Comment by NicoEilers** [comment]
vergelijkbaar met #190

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
