### ISSUE TITLE
Openen bijlage statische kaart gaat naar beheer statische kaart

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#168]
Als je in het Geoportaal een statische kaart wilt bekijken, dan kan je daarvan de metainformatie bekijken. Als er een bijlage aanwezig is, dan zie je ook de link daarnaar toe. Maar als je op die link klikt, dan kan je niet die bijlage zien. Je wordt doorverwezen naar het beheerdeel van statische kaarten. Dat is niet de bedoeling. Als je op de link van de bijlage klikt, dan moet je direct de bijlage openen in de daarbij behorende applicatie.

**Comment by SandroNeumann** [comment]
Het is nu mogelijk zonder inlog gegevens de bijlage te openen.

**Comment by gerardnienhuis** [comment]
is getest: 5 steekproeven mbt extern geoportaal.  lijkt nu wel goed te werken. Issue kan gesloten worden.
