### ISSUE TITLE
In Geoportaal zijn nu ook bestanden uit de prullenbak zichtbaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#170]
Bestanden die status "in prullenbak" of "in concept" hebben, die zijn nu zichtbaar in het externe of interne Geoportaal. Dat is niet de bedoeling: alleen als status "gepubliceerd" is, dan moet het in de Geoportalen zichtbaar zijn.

**Comment by SandroNeumann** [comment]
Alleen gepubliceerde bestanden worden nu getoond.

**Comment by gerardnienhuis** [comment]
probleem is opgelost, kan gesloten worden
