### ISSUE TITLE
Help tekst zoeken Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#172]
Op de home pagina van het Geoportaal zit een knop ZOEK maar niet de knop HELP die volgens het FO er wel had moeten zitten. Graag ook knop HELP er bij zetten. Ook bij Uitgebreid zoeken en Bladeren deze knop HELP toevoegen, zie plaatje

![help_tekst_zoeken](https://cloud.githubusercontent.com/assets/9005444/15608050/86a8a7ec-2417-11e6-93d1-36217dacb83b.jpg)

**Comment by SandroNeumann** [comment]
Moet die knop nog steeds naar dezelfde url gaan als in de mock-up?

**Comment by gerardnienhuis** [comment]
zie #246 en  #248

**Comment by gerardnienhuis** [comment]
kan is aanwezig, maar werkt nog niet goed in de meest gangbare browsers. Tekst waar knop heen linkt is ook verkeerd.

**Comment by gerardnienhuis** [comment]
voor tekst bij help knop: #262

**Comment by gerardnienhuis** [comment]
tijdelijke koppeling met html werkt wel, maar is nog niet zichtbaar zoals bedoeling is. In apart venster, vergelijkbaar met "over deze site" of "contact"

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
