### ISSUE TITLE
Geoportaal zoekscherm 4 aanpassingen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#174]
Bij langdurig gebruik van het Geoportaal blijkt dat de knoppen niet allemaal op een handige plek zitten. 
Aanpassingen zijn nodig op 4 punten:

1) selecties boven de zoekknop en achter elkaar
2) uitklappen selectie bovenaan, op zelfde regel als (1)
3) resultaten en vermelding pagina VET en groter (valt te weinig op)
4) knoppen van maken, als je gaat navigeren naar volgende pagina, knoppen default kleuren geven
tekst knoppen: 
Eerste pagina
Vorige pagina
Volgende pagina
Laatste pagina

![zoekscherm_4_verbeteringen](https://cloud.githubusercontent.com/assets/9005444/15608923/2dcf634e-241d-11e6-8507-38e00f20f74c.jpg)

**Comment by gerardnienhuis** [comment]
Scherm op vergelijkbare manier van onderdeel "Bladeren" aanpassen, bij (2) dan Optie resultaten uitklappen direct links vooraan neerzetten.

**Comment by gerardnienhuis** [comment]
Resultaat van deze aanpassingen valt niet goed uit. Het totaalbeeld is te druk en te compact. Het zorgt voor onrustiger in plaats van rustiger beeld. Voorstel is om bestaande indeling (van versie 110)  te laten bestaan.

**Comment by gerardnienhuis** [comment]
![opmaak_zoekresultaten_voorstel](https://cloud.githubusercontent.com/assets/9005444/19812344/6f638e20-9d35-11e6-817e-9c0d6d47476a.jpg)

**Comment by SandroNeumann** [comment]
Moeten alle vier punten teruggedraaid worden? Dus ook de opmaak van de knoppen?

**Comment by gerardnienhuis** [comment]
wordt zsm bekend, .. nb heb je al gezien dat in IE de tekst van de knoppen van wit naar blauw verandert, als ze inactief zijn en als je met muis er overheen gaat? Dat kan toch niet de bedoeling zijn?

**Comment by gerardnienhuis** [comment]
graag herstellen in vormgeving van versie 1.1.0

**Comment by gerardnienhuis** [comment]
hersteld naar vormgeving 1.1.0, issue kan gesloten
