### ISSUE TITLE
Waarom lukken sommige downloads niet?

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#176]
Ik krijg soms een foutmelding als ik een download wil uitvoeren:

Je download aanvraag 'B3_Oppervlaktewateren' van Geoportaal Overijssel is niet gelukt
noreply@geoportaaloverijssel.nl [noreply@geoportaaloverijssel.nl]
Verzonden:  zondag 29 mei 2016 6:14
Aan:  
Nienhuis, G (Gerard)
Geachte Gerard test 29-5-16 oppervlaktewateren vlak SHP, 

Je download B3_Oppervlaktewateren van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  Unexpected http status code: 404
Neem voor meer informatie contact op met Geoportaal Overijssel.

Getest voor alle beschikbare formaten, zoals shape en kml

Wat is hier aan de hand?

**Comment by SandroNeumann** [comment]
Dat komt wanneer onder aanvullende informatie een link staat die het niet meer doet.

Om de dataset uit het voorbeeld te gebruiken: http://acc-metadata.geodataoverijssel.nl/metadata/dataset/fea85218-3a74-4f37-8e61-ac0ff52b46e1.xml Hier staat een url van het kadaster die niet meer bestaat. Daar komt de 404 (not found) vandaan.

**Comment by gerardnienhuis** [comment]
Maar als url niet meer werkt dan kan download toch gewoon doorgaan? Betreft externe url die kan wel vaker stuk gaan

Verstuurd vanaf mijn iPhone

Op 31 mei 2016 om 17:18 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Dat komt wanneer onder aanvullende informatie een link staat die het niet meer doet.

Om de dataset uit het voorbeeld te gebruiken: http://acc-metadata.geodataoverijssel.nl/metadata/dataset/fea85218-3a74-4f37-8e61-ac0ff52b46e1.xml Hier staat een url van het kadaster die niet meer bestaat. Daar komt de 404 (not found) vandaan.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/176#issuecomment-222722047, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphJ4GofOm1qQa54Zm5Sd_eGXVLnKIks5qHFFNgaJpZM4IpOYX.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
kan het zijn dat dit ook speelt bij onderstaande foutmelding?

Je download B1_Gemeentegrenzen_Overijssel_vlak van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  duplicate entry: gemgrens.jpg
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by HermanAssink** [comment]
De download faalt nu niet meer als een bijlage een kapotte url heeft. Er wordt bij een fout een bestandje in de zip toegevoegd. Bijv: Download_technische_aspecten.html_mislukt.txt

**Comment by gerardnienhuis** [comment]
Werkt nog niet goed: 

download test uitgevoerd van bestand met url die niet goed meer is:
Oppervlaktewateren (vlak) (17-03-2015, Kadaster Geo-Informatie)
metainfo: https://acc-www.geoportaaloverijssel.nl/metadata/dataset/fea85218-3a74-4f37-8e61-ac0ff52b46e1
download: https://acc-download.geoportaaloverijssel.nl/download/fea85218-3a74-4f37-8e61-ac0ff52b46e1

geeft mail met voor gebruiker weinig extra info en geen geslaagde download:

Je download B3_Oppervlaktewateren van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  HTTP/1.1 404 Not Found : http://acc-services.geodataoverijssel.nl:80/geoserver/B35_waterlopen/wfs?REQUEST=GetFeature&service=WFS&version=2.0.0&TYPENAME=B3_Oppervlaktewateren&CRS=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&SRSNAME=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&OUTPUTFORMAT=SHAPE-ZIP
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by gerardnienhuis** [comment]
lijkt op #179 ?

**Comment by gerardnienhuis** [comment]
probleem is gedeeltelijk opgelost: gemeentegrenzen download gaat nu wel goed, daar was de situatie dat de bijlage exact hetzelfde was als het voorbeeldplaatje. Daarvan komt nu inderdaad fout in download erbij. De download B1_Gemeentegrenzen_Overijssel_vlak van Geoportaal Overijssel is dus gelukt.

De download van Oppervlaktewateren (vlak) gaat dus nog fout

**Comment by gerardnienhuis** [comment]
nog 1 download die niet blijkt te werken,

bestand: Gebiedstypering fysiek (28-04-2014, Provincie Overijssel)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/4984016f-0fe2-471c-a492-0fb6dca31bc5

 je krijgt wel melding op scherm dat download wordt uitgevoerd, maar in mail staat:

Je download B8_Gebiedstypering_fysiek van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  HTTP/1.1 404 Not Found : http://acc-services.geodataoverijssel.nl:80/geoserver/B82_volkshuisvesting/wfs?REQUEST=GetFeature&service=WFS&version=2.0.0&TYPENAME=B8_Gebiedstypering_fysiek&CRS=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&SRSNAME=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&OUTPUTFORMAT=SHAPE-ZIP
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by gerardnienhuis** [comment]
Server die niet meer werkt? 

test uitgevoerd tussen 23.40 en 23.55 uur, misschien te laat op de avond?

op scherm komt melding:

Levensloopbestendigheid

Je download verzoek is in goede orde ontvangen. De download wordt nu voor je klaargezet.

Het bestand is: Levensloopbestendigheid
Het formaat is: SHP
E-mail adres is: g.nienhuis@overijssel.nl
Je krijgt zo snel mogelijk een e-mail met een download-link.
Via deze link kun je de download van het bestand uitvoeren. 

maar weer download die niet werkt:
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/45511b12-0128-4c0e-9b40-81faad64f377

Je download B8_Levensloopbestendigheid van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  HTTP/1.1 404 Not Found : http://acc-services.geodataoverijssel.nl:80/geoserver/B82_volkshuisvesting/wfs?REQUEST=GetFeature&service=WFS&version=2.0.0&TYPENAME=B8_Levensloopbestendigheid&CRS=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&SRSNAME=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&OUTPUTFORMAT=SHAPE-ZIP
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by robstek** [comment]
Het lijkt eerder een probleem van bepaalde services dan van de downloadtool.

**Comment by copierrj** [comment]
Ik kan bevestigen dat het probleem in de services zit.

Twee problemen: 
1. De 404 wordt veroorzaakt door het geheel ontbreken van de service (= GeoServer workspace) in de GeoServer configuratie. Oorzaak onduidelijk. Na het opnieuw publiceren van de service werkt het correct.
2. Sommige lagen doen het niet en resulteren in een foutmelding. Ook het opvragen van GetCapabilities geeft problemen.

**Comment by copierrj** [comment]
De 'defecte' lagen bleken in de GeoServer admin te herkennen door het ontbreken van een waarde voor 'Projectie'. Na deze lagen met de hand in de admin te verwijderen en de relevante services opnieuw te publiceren werden de lagen weer aangemaakt en zijn we nu wel correct.

Als het goed is zijn in de acceptatieomgeving alle dataset nu weer te downloaden.

**Comment by copierrj** [comment]
issue mbt defecte lagen: IDgis/geo-publisher#798

**Comment by gerardnienhuis** [comment]
gemeentegrenzen download lijkt goed te werken, bijna goed dan, wat dat betreft kan het tzt opgelost, zie 
https://github.com/IDgis/geoportaal-test/issues/241

**Comment by gerardnienhuis** [comment]
Overige fouten getest: 

levenloopbestendigheid: gaat goed
gebiedstypering: gaat goed
oppervlaktewateren gaat goed, wel fout in link (extra info) maar juist afgehandeld, foutmelding in zip

enkele andere downloads random getest, gaan ook goed, issue kan gesloten
