### ISSUE TITLE
Tekst download veld verplicht

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#178]
Je krijgt nu, als je bij de downloadtool, geen formaat hebt gekregen, de melding:

This field is required

zie plaatje

Deze melding moet worden:

Je moet een keuze maken uit één van de 5 verschillende formaten.

Als je je naam niet invult, dan komt ook dezelfde melding: This field is required

Die melding moet worden: Vul je eigen naam in

Als je een geen email adres invult, dan komt ook de melding: this field is required

Die melding moet worden. Vul hier het email adres in, waarheen de downloadlink moet worden gestuurd.

Als een emailadres zonder @ wordt opgegeven, dan krijg je een melding. Maar deze melding is niet goed zichtbaar en in andere lettertype. Deze melding moet op dezelfde manier, met rode achtergrond en zelfde lettergrootte en op zelfde plaats als andere meldingen komen te staan

![foutmelding_download_veld_verplicht](https://cloud.githubusercontent.com/assets/9005444/15631731/3fb02b78-2578-11e6-9c02-59e40ad65e6a.jpg)

**Comment by HermanAssink** [comment]
Uitzoeken  door IDgis hoe je deze meldingen kunt "customizen".

**Comment by SandroNeumann** [comment]
Een melding kan op deze manier customized worden:
https://stackoverflow.com/questions/20471578/playframework-setting-custom-message-for-required-field-globally

**Comment by gerardnienhuis** [comment]
getest:
2 steekproeven:

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/244cf42a-9d6a-4c58-ad7c-1f5b47eef666
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/f0ddb741-eb1d-43cb-98f5-101f1d566ea0

blijkt goed te werken, issue kan gesloten
