### ISSUE TITLE
Download lukt niet altijd

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#179]
Sommige downloads mislukken: niet helder is waarom dat zo is, 
zie bijvoorbeeld #177 

Is dit een bug in de download-tool? Of fout in data?

Een andere voorbeeld staat hieronder, getest met alle beschikbare downloadformaten zoals shape, kml enz. Geeft allemaal zelfde foutmelding.

Geachte Gerard test 29-5-2016 Strooiroutes preventief SHP, 

Je download B2_Strooiroutes_preventief_Provincie van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  Illegal character in path at index 67: http://gisopenbaar.overijssel.nl/GeoPortal/MIS4GIS/lyr/strooiroutes provincie_arc.lyr
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by SandroNeumann** [comment]
De url onder de foutmelding (de layerfile) is kapot. Er staat een spatie in.

**Comment by gerardnienhuis** [comment]
geen idee hoe dat kan, in huidige geoportaal ziet het er wel goed uit. Kan er wat anders aan de hand zijn?

zie:

Strooiroutes preventief Provincie Overijssel
http://gisopenbaar.overijssel.nl/geoportal_extern/rest/document?id=%7B91B7ED4D-2D10-4691-AC17-04856412FD98%7D

**Comment by SandroNeumann** [comment]
Het huidige geoportaal vervangt spaties in url's blijkbaar voor de spatie teken vertegenwoordiging %20. Wanneer je deze url probeert wordt het layer bestand gedownload: http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\lyr\strooiroutes%20provincie_arc.lyr

**Comment by HermanAssink** [comment]
@SandroNeumann : Is het dus oplosbaar door de download component url encoding te laten toepassen op de link?

**Comment by gerardnienhuis** [comment]
lijkt conversieprobleem: is spatie bij inlezen om te zetten in _
of is een rapportage mogelijk, waarbij aangegeven wordt welke datasets die probleem hebben (zodat wij heel direct dit probleem kunnen oplossen?
hoe nu verder?

---

Van: SandroNeumann [notifications@github.com]
Verzonden: dinsdag 31 mei 2016 13:52
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard); Author
Onderwerp: Re: [IDgis/geoportaal-test] Download lukt niet altijd (#179)

Het huidige geoportaal vervangt spaties in url's blijkbaar voor de spatie teken vertegenwoordiging %20. Wanneer je deze url probeert wordt het layer bestand gedownload: http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\lyr\strooiroutes%20provincie_arc.lyr

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/179#issuecomment-222666430, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphHVsRuqhBupVuGadMquX2oywFOkzks5qHCDmgaJpZM4IpOmK.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
Dit wordt opgelost in de download-tool.

**Comment by gerardnienhuis** [comment]
download is gelukt, foute url wordt blijkbaar in dit geval genegeerd.
probleem met verkeerde urls lijkt nog niet opgelost altijd opgelost, maar blijkbaar in dit geval werkt oplossing wel: download van strooiroutes gaat nu wel goed

https://acc-download.geoportaaloverijssel.nl/download/cd349c2f-b2fe-4ed6-b2b9-a00639ebcebb

dit issue kan gesloten
