### ISSUE TITLE
In stylesheet extern zijn teveel contactpersonen zichtbaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#181]
De bedoeling is, dat bij WIE in een stylesheet voor externe geodata alleen de eerst geleverde naam van een betrokken organisatie wordt opgenomen. Dit om te voorkomen dat interne contactpersonen direct vindbaar zijn via de stylesheet. Nu is alle contactinformatie zichtbaar,  en dat is wel goed bij de stylesheet voor interne metadata, maar niet voor die van extern.

nb: zou ook te maken kunnen hebben met #147

voorbeeld: nu is beschikbaar via een stylesheet, via Geoportaal Extern:

Bestandsnaam: Landgoederen

Beheerder van het bestand
Naam: Provincie Overijssel
Website: http:\www.overijssel.nl
Naam: team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Auteur bestandsbeschrijving
Naam: Provincie Overijssel: team Beleidsinformatie
Website: http:\www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Distributeur van het bestand
Naam: Provincie Overijssel: team Beleidsinformatie
Website: http:\www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Voor het externe geoportaal moet dat worden: alleen de eerste set gegevens, dus:

Beheerder van het bestand
Naam: Provincie Overijssel
Website: http:\www.overijssel.nl
Naam: team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

**Comment by SandroNeumann** [comment]
Er is onderscheid tussen intern en extern.

In het geval van de dataset landgoederen is in geoportaal intern dit zichtbaar:

Beheerder van het bestand
Naam: Provincie Overijssel
Website: http:\www.overijssel.nl
Naam: team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Eigenaar van het bestand
Naam: Provincie Overijssel: eenheid Economie en Cultuur
Website: http://www.overijssel.nl
Naam: Cusveller, Dhr. Sjoerd
E-mail: S.Cusveller@overijssel.nl

Eigenaar van het bestand
Naam: Provincie Overijssel: eenheid Economie en Cultuur
Website: http://www.overijssel.nl
Naam: Wever, Mw. Marieke
E-mail: M.Wever@overijssel.nl

Auteur bestandsbeschrijving
Naam: Provincie Overijssel: team Beleidsinformatie
Website: http:\www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Distributeur van het bestand
Naam: Provincie Overijssel: team Beleidsinformatie
Website: http:\www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

In geoportaal extern dit:

Beheerder van het bestand
Naam: Provincie Overijssel
Website: http:\www.overijssel.nl
Naam: team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Auteur bestandsbeschrijving
Naam: Provincie Overijssel: team Beleidsinformatie
Website: http:\www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

Distributeur van het bestand
Naam: Provincie Overijssel: team Beleidsinformatie
Website: http:\www.overijssel.nl
Naam: Team Beleidsinformatie
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands
Telefoonnummer: -

**Comment by gerardnienhuis** [comment]
Gaat dus goed, zo lijkt het. Wordt gecontroleerd of het ook bij andere bestanden goed gaat

**Comment by gerardnienhuis** [comment]
Alle steekproeven laten zien dat er geen persoonsinformatie extern te zien is. De vraag alleen is nu, hoe het precies werkt. Vragen zijn:

Wat wordt intern wel  en extern niet meegenomen?
Komt het wel in de xml en niet in de stylesheet?

**Comment by gerardnienhuis** [comment]
heeft te maken met #5

**Comment by NicoEilers** [comment]
is getest, blijkt goed te werken, issue kan gesloten
