### ISSUE TITLE
Geoportaal Optie uitklappen bewaren bij vorige/volgende pagina

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#182]
Als je een keuze maakt, om bijvoorbeeld inklappen aan te zetten, dan moet die keuze ook bewaard blijven bij de volgende pagina's. Nu is het zo, dat als je naar volgende of vorige pagina gaat, deze keuze wordt teruggezet naar de default. Dat is voor een gebruiker erg onhandig. Wens is dat eenmaal gemaakte keuze blijft werken, totdat de gebruiker weer iets anders kiest.

Geldt bij uitgebreid zoeken en ook bij bladeren, zowel intern als extern geoportaal

zie plaatje:

![uitklappen_selectie_vasthouden](https://cloud.githubusercontent.com/assets/9005444/15632035/b062378c-2585-11e6-9eb1-21baaf278708.jpg)

**Comment by SandroNeumann** [comment]
Begrijp ik dit punt goed dat de waarde van alles uitklappen/inklappen en de vinkjes voor de type data bij elke pagina bewaard moet blijven?

**Comment by gerardnienhuis** [comment]
bedoeling is dat een keuze, als die eenmaal is gemaakt, ook bij navigeren naar volgende/vorige pagina bewaard blijft. Net zolang totdat een gebruiker weer een andere keuze maakt.

Is de default ingeklapt, dan moet een gebruiker dus uitklappen aanvinken. Als je dat doet, dan moet die keuze bewaard blijven, ook als je weer verder gaat naar andere pagina's. 

merk op: bij de home pagina is de optie: uitgeklapt toegepast, dan moet zo blijven. Maar voor uitgebreid zoeken en bladeren moet inklappen en uitklappen zoals hierboven beschreven.

**Comment by gerardnienhuis** [comment]
Merk op: als je als gebruiker op een pagina bent, met dichtgeklapte namen, dan is het wel ook de bedoeling dat 1 of meerdere namen uit te klappen zijn door op de betreffende naam te klikken. 

Het is de bedoeling dat dit andersom ook werkt, zie je lijst met uitgeklapte namen, dan kan je er van die pagina 1 of meerdere inklappen.

**Comment by gerardnienhuis** [comment]
werkt goed, issue gesloten
