### ISSUE TITLE
Download tekst bestand niet gevonden

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#184]
Als er iets verandert in de url van de download string, dan volgt een foutmelding. Dat is begrijpelijk, maar die tekst is te technisch.

Nu is de tekst:

Nu krijg ik een scherm met de melding:

404 Niet gevonden

Het gevraagde dataset (met id '8fe02f21-92af-4c32-a04a-970ae3ca3e48.xml') bestaat niet.

Melding moet worden:

Je bent bezig met het dowloaden van de dataset met id: 8fe02f21-92af-4c32-a04a-970ae3ca3e48.xml

Deze dataset kan echter nu niet worden gedownload.

Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem. Of misschien heb je onvoldoende rechten om de download uit te voeren. 

Neem voor vragen contact op met beleidsinformatie@overijssel.nl

**Comment by copierrj** [comment]
Het is op internet de gewoonte (in de HTTP specificatie staat dit als suggestie opgenomen) om de melding altijd te laten beginnen met "404 Not Found" en de rest van de melding te beschouwen als een nadere toelichting hierop. Ik zou daarom willen voorstellen om de tekst "404 Niet gevonden" te handhaven.

**Comment by robstek** [comment]
Gaan wij  voor de tekst wijziging van Gerard, maar inclusief de technische melding?

---

**404 Niet gevonden**

Je bent bezig met het downloaden van de dataset met id: 8fe02f21-92af-4c32-a04a-970ae3ca3e48.xml

Deze dataset kan echter nu niet worden gedownload.

Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem. Of misschien heb je onvoldoende rechten om de download uit te voeren.

Neem voor vragen contact op met beleidsinformatie@overijssel.nl

---

**Comment by copierrj** [comment]
Dat zou inderdaad mijn voorkeur hebben, maar is uiteindelijk aan Overijssel.

**Comment by gerardnienhuis** [comment]
Ik vind onderstaande tekst prima:

**404 Niet gevonden**

Je bent bezig met het downloaden van de dataset met id: 8fe02f21-92af-4c32-a04a-970ae3ca3e48.xml

Deze dataset kan echter nu niet worden gedownload.

Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem. Of misschien heb je onvoldoende rechten om de download uit te voeren.

Neem voor vragen contact op met beleidsinformatie@overijssel.nl

**Comment by gerardnienhuis** [comment]
werkt prima, issue kan gesloten
