### ISSUE TITLE
Tekst kenmerk stylesheet statistisch kaarten wordt nummer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#186]
In de beheermodule voor statische kaarten wordt gevraagd om een nummer in te voeren. Maar in de stylesheet wordt datzelfde nummer "kenmerk" genoemd. Dat is niet consequent

Wens is om ook in de stylesheet voor statische kaarten dit "nummer" te noemen. Alleen tekstaanpassing dus, functioneel hoeft niets te veranderen.

**Comment by NicoEilers** [comment]
Kan het zijn dat dit al werkt in de productieversie?

**Comment by SandroNeumann** [comment]
Nee, label is in productie nog kenmerk:
https://www.geoportaaloverijssel.nl/metadata/dc/CE29634C-7EBB-4CDC-9163-C9E02C3C084D

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
