### ISSUE TITLE
Trefwoorden ISO ook voor services bij bladeren beschikbaar maken

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#191]
Nu zijn alleen bij geodata en statische kaarten bij bladeren de trefwoorden van ISO te gebruiken. Wens is om ook voor services dit te kunnen gebruiken bij bladeren.

**Comment by SandroNeumann** [comment]
Gerelateerd aan #167

**Comment by gerardnienhuis** [comment]
idee is om de picklist, zoals die nu wordt toegepast voor statische kaarten, op vergelijkbare manier ook bij services beschikbaar te laten zijn.

**Comment by gerardnienhuis** [comment]
was al gemeld bij #167 
dit issue kan dus hier gesloten worden, lijkt dubbel.
