### ISSUE TITLE
Zijn er 2 versies metadata bij structuurwijziging van data?

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#192]
Het kan zijn dat we nieuwe metadata maken, horende bij een structuurwijziging (b.v. er is een nieuwe kolom aan toegevoegd): dan wil je die metadata niet zichtbaar hebben zolang de structuurwijziging niet inde service is gepubliceerd. Vraag is of er dan 2 versies metadata beschikbaar zijn, namelijk van voor en na structuurwijziging.

**Comment by HermanAssink** [comment]
Het constateren van een structuurwijziging en het lezen van de metadata zijn als twee onafhankelijke processen gerealiseerd. Bij iedere update/harvestactie van de GIS-Publicatieomgeving wordt gecontroleerd op een structuurwijziging, ook als de metadata niet is gewijzigd. Dit is zo gedaan om de beheerder van de GIS-Publicatieomgeving een "early warning" te kunnen geven. Bovendien is het mogelijk om vanuit de GIS-Publicatieomgeving ad hoc een dataset te verversen met de data zoals die bij Overijssel staat, ook als de metadata niet is gewijzigd. Bij zo'n ad hoc verversactie moet er ook op een structuurwijziging worden gecontroleerd. De metadata in de GIS-Publicatieomgeving wordt in de huidige programatuur bij iedere harvestactie ge-update. Door het onafhankelijke karakter van de update van data en metadata is niet bekend welke versie van de metadata bij een bepaalde versie van de data hoort. Een en ander betekent dat om onderscheid te maken tussen de metadata vóór en na een structuurwijziging het werkproces en de programmatuur moet worden aangepast. Dit lijkt me een punt om eerst binnen Overijssel te bespreken.

**Comment by gerardnienhuis** [comment]
Wordt vooralsnog niet geautomatiseerd opgelost: wens is wel dit verder automatisch te laten verlopen in toekomstige versies
werkwijze wordt nu (alleen bij structuurwijzigingen):
1) data aanpassen, door FAB geoportaal
2) in pub omgeving komt melding hiervan
3) FAB geoportaal neemt contact op met FAB Pub omgeving
4) FAB pub omgeving past service aan waar data in zit
5) FAB geoportaal past, na stap 4 en niet eerder, metadata aan

Dat is omslachtiger dan huidige werkwijze,  mogelijk zal bij evaluatie en verdere zoektocht naar verbetering dit wel meer automatisch op te lossen zijn. Vooralsnog niet: issue wordt gesloten.
