### ISSUE TITLE
Wat is relatie tussen Geoportaal en DCAT

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#193]
DCAT lijkt nieuwe ontwikkeling te zijn, is nieuwe Geoportaal hier al klaar voor?

zie:

http://www.geonovum.nl/nieuws/consultatie-geodcat-ap-specificatie-om-geo-informatie-beter-vindbaar-te-maken

**Comment by HermanAssink** [comment]
DCAT kan als extra koppelvlak aan het Geoportaal worden toegevoegd, gebruik makend van dezelfde metadata.

**Comment by gerardnienhuis** [comment]
wat is de impact hiervan en is het zivnvol om in huidige opdracht mee te laten gaan: even bellen?

---

Van: Herman Assink [notifications@github.com]
Verzonden: dinsdag 31 mei 2016 15:03
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard); Author
Onderwerp: Re: [IDgis/geoportaal-test] Wat is relatie tussen Geoportaal en DCAT (#193)

DCAT kan als extra koppelvlak aan het Geoportaal worden toegevoegd, gebruik makend van dezelfde metadata.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/193#issuecomment-222681400, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphHJqPR4g4qMnX3EXhpenly9VixYvks5qHDGEgaJpZM4Iqend.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by HermanAssink** [comment]
Het lijkt me het beste te wachten tot de Geonovum standaard verder is uitgekristalliseerd. In samenhang daarmee zou er ook gekeken moeten worden naar andere koppelvlakken voor de data uit de GIS-Publicatieomgeving zoals GeoJSON via een REST API.

**Comment by gerardnienhuis** [comment]
prima idee, we wachten tot de geonovum standaard volledig in gebruik is genomen, en kijken daarna hoe en wat andere koppelvlakken zijn. voor huidige versie geoportaal niet relevant, mogelijk wel voor toekomstige versies. .. issue kan dus voor de huidige versie gesloten
