### ISSUE TITLE
trefwoorden verkeerde thesaurus

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#194]
In de stylesheet voor services staat dat de trefwoorden uit gemet zijn gebruikt, dit is nu niet het geval, het is de interprovinciale thesaurus (zelfde vermelding en versie als bij geodata). Dit is mogelijk hard gecodeerd in de metadata van services. Omdat het niet correct is, zou dat moeten worden veranderd in de stylesheets voor interne en externe services.

Er staat nu in stylesheet

Thesaurus trefwoorden: GEMET - Concepts, version 2.4
Publicatie datum thesaurus: 2010-01-13

Dat had moeten zijn:

Thesaurus trefwoorden: Interprovinciale thesaurus
Publicatie datum thesaurus: 2013-09-11

**Comment by SandroNeumann** [comment]
Volgens de geonovum standaard moet er een trefwoord uit de GEMET thesaurus gebruikt worden.

**Comment by gerardnienhuis** [comment]
dat heb ik niet in die standaard terug kunnen vinden. Gemet is alleen verplicht voor inspire services, 

zie:

uit: Nederlands metadata profiel op ISO 19119 voor services, versie 1.2

5.2.12 Keyword value
identificationInfo[1]/_/descriptiveKeywords/_/keyword [ISO 19139]
Het element bevat in het algemeen gebruikte woorden of
geformaliseerde zinnen om een service te beschrijven.

Maar alleen voor inspire services geldt gemet:

Voor INSPIRE services dient er op z’n minst één keyword de categorie of subcategorie te bevatten uit deel D.4 van de commissie regulation 1205/2008, zie bijlage 1. Daarnaast kunnen er
 andere keywords met bijvoorbeeld het thema worden opgenomen. In http://www.eionet.europa.eu/gemet/inspire_themes zijn de thema’s van INSPIRE opgenomen.

5.2.13 Originating controlled vocabulary
identificationInfo[1]/_/descriptiveKeywords/_/thesaurusName/_/title [ISO 19139]
identificationInfo[1]/_/descriptiveKeywords/_/thesaurusName/_/date/_/date [ISO 19139]
identificationInfo[1]/_/descriptiveKeywords/_/thesaurusName/_/date/*/dateType [ISO 19139]
Dit is een conditioneel element. Het is verplicht als een keyword uit een thesaurus afkomstig is. Het bevat de naam en publicatie datum van de thesaurus waar het keyword uit afkomstig is. Ook het type gebeurtenis waar de datum betrekking op heeft wordt vastgelegd. Type gebeurtenis wordt gekozen uit codelijst B.5.2 uit ISO 19115. Mogelijke gebeurtenissen zijn: Datum voltooiing, Datum publicatie en Datum laatste wijziging. Het formaat van de datum is JJJJ-MM-DD (met streepjes).

staat nergens dat niet andere thesaurus gebruikt mag worden

**Comment by gerardnienhuis** [comment]
Het is natuurlijk wel zo, dat wij ook services aanmaken tbv inspire, die moeten dus OOK gemet gebruiken, naast eventuele andere thesauri. Meest logische aanpassing ligt bij pub. omgeving, daar moet je kunnen aangeven welke van de gebruikte thesaurussen (thesauri?) gebruikt is bij de metadata. Snelste oplossing is om voor nu de GEMET overal te gebruiken, maar volgens de standaard hoeft dat echt niet.

**Comment by gerardnienhuis** [comment]
Voorstel handmatig oplossen (dwz GEMET trefwoorden erin, overige trefwoorden eruit) wordt besproken intern Overijssel.

**Comment by gerardnienhuis** [comment]
wordt met de hand opgelost, nog wel controleren of e.e.a. goed werkt. bestaande trefwoorden worden vervangen door gemet trefwoorden, met de hand voor alle services. voor testen eerst in acc. omgeving.
Hiermee is het geen bug meer, wens blijft om meerdere thesaurussen te kunnen ondersteunen.

**Comment by gerardnienhuis** [comment]
bezig met testen in acc. omgeving van publ omgeving: onderstaande trefwoorden worden gebruikt:

Administratieve eenheden
Adressen
Atmosferische omstandigheden
Beschermde gebieden
Biogeografische gebieden
Bodem
Bodemgebruik
Energiebronnen
Faciliteiten voor landbouw en aquacultuur
Faciliteiten voor productie en industrie
Gebieden met natuurrisico's
Gebiedsbeheer, gebieden waar beperkingen gelden, gereguleerde gebieden en rapportage-eenheden
Gebouwen
Geografisch rastersysteem
Geografische namen
Geologie
Habitats en biotopen
Hoogte
Hydrografie
Kadastrale percelen
Landgebruik
Menselijke gezondheid en veiligheid
Meteorologische geografische kenmerken
Milieubewakingsvoorzieningen
Minerale bronnen
Nutsdiensten en overheidsdiensten
Oceanografische geografische kenmerken
Orthobeeldvorming
Spreiding van de bevolking — demografie
Spreiding van soorten
Statistische eenheden
Systemen voor verwijzing door middel van coördinaten
Vervoersnetwerken
Zeegebieden

**Comment by copierrj** [comment]
De thesaurus verwijzing wordt ingevuld door de publicatieomgeving. Hierbij is aangenomen dat deze altijd gelijk is. Klopt dit? De concrete waarde die hier gebruikt wordt is eenvoudig aan te passen. Als de thesaurus per trefwoord anders kan zijn zullen zal de gebruiker dit moeten opgeven in de beheerpagina en moet het opgeslagen worden in de database.

Dit issue lijkt mij gerelateerd aan: #236

**Comment by SandroNeumann** [comment]
prov. Overijssel gaat uitzoeken welke thesaurus voor NGR en PGR bruikbaar is.  Hopelijk is dat voor beide systemen dezelfde. Daarna moet in publicatieomgeving die naam worden overgenomen en met de hand de juiste trefwoorden worden toegevoegd per service.

**Comment by copierrj** [comment]
Moet de thesaurus naam voor ieder trefwoord apart opgegeven kunnen worden?

**Comment by NicoEilers** [comment]
Het lijkt er op dat harvesten door NGR en PGR goed verloopt. Urgentie is hiermee niet erg groot. Kan t.z.t. opgepakt worden.

**Comment by gerardnienhuis** [comment]
Harvesten lijkt niet meer goed te gaan bij NGR. Wordt uitgezocht.

**Comment by gerardnienhuis** [comment]
Verder testen heeft nu geen zin, probleem NGR moet eerst uitgezet worden. Dit issue kan wat mij betreft "on hold" gezet worden.

**Comment by gerardnienhuis** [comment]
in overleg met Sandro besloten om dit issue voorlopig niet verder op te pakken. nb: NGR harvesting blijkt ook goed te werken, automatische harvesting is nu van 12 uur naar 3 uur verplaatst
