### ISSUE TITLE
Weergave naam van WMS en WFS

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#196]
Nu zie je, als je services zoekt, dubbele namen in het Geoportaal. De ene blijkft de WMS, de andere de WFS. Het is voor een gebruiker veel makkelijker, als je kan zien, welke service het is. Kan de naam van de service aangepast worden? Zodat in Geoportaal onderscheid makkelijker is?

**Comment by HermanAssink** [comment]
In de lijst met zoekresultaten moet duidelijk zijn welk type service het is.

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
