### ISSUE TITLE
iso 19115 xml meeleveren bij download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#198]
Om delen van info nog makkelijker te maken, ook de xml conform iso 19115 meeleveren in de zip bij de download. Wil iemand anders de resultaten dan in zijn of haar metadatasysteem opnemen, dan maakt zoiets het nog makkelijker.

**Comment by SandroNeumann** [comment]
Die wordt al meegeleverd. Dat is het leesmij.xml bestand.

**Comment by gerardnienhuis** [comment]
Het is inderdaad een iso 19115 xml, maar deze is niet valide, lijkt het. 

Ik heb de xml gebruikt die bij de download van Toekenning_recreatievaartklasse_vaarwegen
vanuit het externe portaal is gemaakt

pad naar validator: 
http://www.geonovum.nl/validator-nederlands-metadataprofiel-op-iso-19115

Validatie resultaat voor bestand leesmij.xml

Resultaat van Validatie
Details
Bestand leesmij.xml
Datum   02/06/2016 11:23
Validaties
Validatie   Resultaat   Standaard informatie
Totaal  Problemen gevonden
Metadata ISO 19115:2003 Problemen gevonden  component: 1.2, bestand: gmd.xsd, versie: 0.1
Schematron validatie: NL_profiel_op_ISO_19115_v1.3_2014 Problemen gevonden  component: 1.4, bestand: dataset_schematron_rules_v13_2014_NGR.xml
Details van Validatie
Metadata ISO 19115:2003
Tijd    Type    Bericht
11:23:57.654    Opmerking   Validatie gestart: Metadata ISO 19115:2003
11:23:57.656    Fout    cvc-complex-type.2.4.b: The content of element 'MD_Usage' is not complete. One of '{"http://www.isotc211.org/2005/gmd":usageDateTime, "http://www.isotc211.org/2005/gmd":userDeterminedLimitations, "http://www.isotc211.org/2005/gmd":userContactInfo}' is expected. [Regelnr: 240, kolomnr.: 20]
11:23:57.656    Opmerking   Validatie afgerond: Metadata ISO 19115:2003
Schematron validatie: NL_profiel_op_ISO_19115_v1.3_2014
Tijd    Type    Bericht
11:23:57.656    Opmerking   Validatie gestart: Schematron validatie: NL_profiel_op_ISO_19115_v1.3_2014
11:23:57.667    Fout    De metadata taal (ISO nr. 3) ontbreekt of heeft een verkeerde waarde. Dit hoort een waarde en verwijzing naar de codelijst te zijn.
11:23:57.667    Fout    (Juridische) toegangsrestricties (ISO nr. 70)en Overige beperkingen (ISO nr 72) dient ingevuld te zijn
11:23:57.667    Fout    (Juridische) toegangsrestricties (ISO nr. 70) dient de waarde 'anders' te hebben in combinatie met een publiek domein, CC0 of geogedeelt licentie bij overige beperkingen (ISO nr. 72)
11:23:57.668    Opmerking   Validatie afgerond: Schematron validatie: NL_profiel_op_ISO_19115_v1.3_2014

**Comment by gerardnienhuis** [comment]
Als kaart downloadbaar is, dan moet de url met CC-0 zijn opgegeven. Moeten beheerders met geosticker doen, en wordt soms vergeten. Verzoek om in rapportage te zetten (nieuw issue). Language probleem en mogelijk andere problemen met syntax xml moet nog opgelost

**Comment by gerardnienhuis** [comment]
kan gesloten worden, gaat deels verder in #232
