### ISSUE TITLE
Bijlage afwezig foutmelding in rapport geodatasets

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#199]
Bij de rapportage (maken van csv) van metainfo van geodatasets moet een kolom aanwezig zijn, met de status van de links naar de bijlagen bij geodatasets. Als er fouten in die links zitten, bijvoorbeeld spaties, dan werkt die link (en daarmee ook de download eventueel) niet goed: controle op fouten is belangrijk en daarom moet bij iedere dataset ook de status (200 of 404) vermeld worden (dwz de status voor het harvesten).

**Comment by copierrj** [comment]
We hebben de fouten al in de csv staan (kolom: http_errors). Het is dus de bedoeling dat er info over alle bijlagen (bij alle http status codes, incl. 200) in het rapport moeten komen? Hierdoor komt er dus een stuk meer info in deze kolom te staan.

N.B. In issue #345 is aangegeven dat het wenselijk is om urls en statuscodes te splitsen in twee kolommen.

**Comment by NicoEilers** [comment]
nee, wij willen niet alle statussen in het rapport, dat zou veel te veel zijn, alleen de foutsituaties.

**Comment by NicoEilers** [comment]
Dit issue heeft zoveel te maken met #345 dat ik deze in milestone 1.1.3 heb gezet

**Comment by copierrj** [comment]
Als we geen foutsituaties gaan opnemen, wat is dan het wijzigingsvoorstel?
