### ISSUE TITLE
Metadata-aanpassing bij gefilterde bestanden

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#2]
Het is mogelijk voor beheerders van de publicatieomgeving om bestanden te filteren. het voorstel is om dan de metadata te kopieren.

aan te titel van het bestand wordt toegevoegd (gefilterd)
aan de samenvatting wordt toegevoegd, aan de laatste regel"
"Op het originele bestand is een filtering toegepast. Zie bij "details" voor de toelichting op de bewerkingen.
bij "details" komt een extra regel over bewerkingen, onder de al reeds eventuele andere regels over bewerkingen. In deze extra regel komt te staan: Het originele bestand is gefilterd. In dit bestand zijn alleen de volgende attributen opgeslagen: ... .... ... ... .

(dit issue is gebaseerd op overleg met André en is op verzoek van Herman opgenomen als issue/d.d. 7-10-2015, opgevoerd door Gerard)

**Comment by gerardnienhuis** [comment]
Dit issue hoort eigenlijk bij de publicatieomgeving: daar wordt de opdracht tot filteren gegeven, uiteindelijk. Als gefilterd wordt in de publicatieomgeving, dan moet die omgeving ook zorgen voor juiste (in dit geval) nieuwe en verrijkte metainformatie. vraag voor @HermanAssink hoe verder op te pakken.

**Comment by gerardnienhuis** [comment]
Dit is voor Geoportaal zelf geen meerwerk of luxe. Metadata moet gewoon goed zijn, en als publicatieomgeving de data aanpast, dan moet ook metadata aangepast worden. Voor Geoportaal zelf is dit geen issue. Kan dit item verplaatst worden naar github voor publicatieomgeving? Of moet ik daar tekst nog een keer in zetten en hier het issue sluiten daarna?

**Comment by HermanAssink** [comment]
Je kunt bij issues verwijzen naar issues in een andere repository, bijvoorbeeld IDgis/geo-publisher-test#65.
Je zou dus in geo-publisher-test een nieuw issue kunnen maken dat verwijst naar deze en deze dan sluiten.

**Comment by gerardnienhuis** [comment]
issue opgenomen bij https://github.com/IDgis/geo-publisher/issues/753
is bij Geoportaal geen issue, maar bij Geo-publisher wel. Daarom is dit issue hier gesloten.
