### ISSUE TITLE
Rapportage aantal lagen bij services

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#203]
De service Toerisme bevat geen lagen. toch is deze in het externe geoportaal aanwezig. Dat is non-informatie, en ongewenst. Bij de rapportage van metadata van services moet ook het aantal lagen van de betreffende service in een aparte kolom worden opgenomen. Dan is voor een beheerder direct zichtbaar welke services misschien wel intern maar nog niet extern ontsloten moeten worden.

**Comment by copierrj** [comment]
Deze service bevat  in de publicatieomgeving helemaal geen lagen. De meest voor de hand liggende oplossing lijkt mij hier het niet toestaan lege services te publiceren.

**Comment by gerardnienhuis** [comment]
is het voorstel om dat hard vast te leggen in de publicatieomgeving, of om een duidelijke waarschuwing voor de beheerder van die omgeving te laten verschijnen?

**Comment by copierrj** [comment]
Bij het publiceren voert de publicatieomgeving eerst een aantal checks uit om te garanderen dat er geen onvolledig geconfigureerde services (bijvoorbeeld: zonder trefwoorden) gepubliceerd worden. Voorstel houd dus concreet in om de check 'aantal lagen > 0' hieraan toe te voegen.

**Comment by copierrj** [comment]
De gebruiker krijgt hierbij een duidelijke foutmelding.

**Comment by copierrj** [comment]
Hoe pakken we dit op: deze situatie in de publicatieomgeving onmogelijk maken (dmv voorgestelde check), deze situatie opnemen in de rapportage, of beide?

**Comment by copierrj** [comment]
Zoals telefonisch besproken: in de publicatieomgeving kunnen aangemaakte services enkel gepubliceerd worden nadat deze aan een aantal voorwaarden voldoen. 

Hieraan wordt de voorwaarde dat de service ten minste een enkele laag bevat toegevoegd.

Bij het deployen van deze wijziging zal gekeken moeten worden of er op dat moment gepubliceerde services zonder lagen zijn.

**Comment by robstek** [comment]
zie #349 extra kolom met aantal lagen per service
Bovenstaande oplossing (voorgestelde constraint) vervalt hiermee

**Comment by gerardnienhuis** [comment]
aantal lagen staat in het rapport, issue kan gesloten
