### ISSUE TITLE
Bijlage url fout, dan ook niet tonen in stylesheet metadata geodatasets

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#204]
Is dit een fout of nog niet geïmplenteerd, dus luxe in dit stadium?

Als ik in het externe Geoportaal zoek naar bushaltes, dan die ik daar 1 bestand, met 1 bijlage:

Bestandsnaam: Bushaltes in Overijssel
http://acc-metadata.geodataoverijssel.nl/metadata/dataset/fbe74ae9-c66f-481a-b3cf-1c0286e7615f.xml
bijlage is:
https://reisinformatiegroep.nl/ndovloket/documentationfile/4/Beschrijving%20GTFS%20formaat.pdf

Het openen van de bijlage lukt niet, maar dit probleem is niet bij het harvesten opgelost. is het mogelijk om links die niet werken, ook niet in de stylesheet voor geodata te tonen?

Kijk bijvoorbeeld bij:

Bestandsnaam: Strooiroutes preventief Provincie Overijssel
Aanvullende informatie: layerfile:|http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\lyr\strooiroutes provincie_arc.lyr

Daar is de url ook fout (zit spatie in) maar die url is in de stylesheet ook niet aanklikbaar.
Dat is dan beter, dan weet je dat die url waarschijnlijk ook niet gaat werken.

De url van de bijlage van de bushaltes, die is wel aanklikbaar, maar dan krijg je een foutmelding.

**Comment by copierrj** [comment]
Bij het harvesten proberen we bijlagen te downloaden. Hierdoor weten we in de publicatieomgeving of een url succesvol gedownload kan worden. 

Wat we kunnen doen is urls waarvan we weten dat deze 'het niet doen' niet opnemen in de metadata. Hiermee verdwijnen ze echter niet enkel in het geoportaal maar worden ze ook niet langer getoond in NGR en PGR.

Enkel in de geoportaal urls verbergen is lastiger.

@SandroNeumann: wat zou jij hier in het geoportaal voor kunnen doen?

**Comment by SandroNeumann** [comment]
Ik kan in de stylesheet hier alleen iets mee als ik een signaal in de XML kan krijgen dat de bijlage het niet doet.

**Comment by copierrj** [comment]
De urls die het wel doen verwijzen allemaal naar de publicatieomgeving. Je zou de rest kunnen verbergen.

**Comment by SandroNeumann** [comment]
Waar wordt op gecheckt? Je kunt controleren of de url geodataoverijssel of geodata bevat. Bij de eerste gaat het bij andere klanten niet werken. Bij de tweede impliceert het dat elke publisher instantie bereikbaar is met geodata in de URL en URL's die toevallig ook geodata in de URL hebben vallen hier doorheen.

**Comment by copierrj** [comment]
Als je dit in de controller oplost (en dus niet in de stylesheet) dan zou je een te configureren url prefix kunnen gebruiken.

**Comment by gerardnienhuis** [comment]
Verwijderen als niet werkt klinkt beste
Maar ik wil dan wel rapport met naam geodataset en naam url die is verwijderd zodat beheerders het kunnen repareren daarna

Voorstel:

Rapport geodata met 1 kolom uitbreiden
Naam kolom is: bijlage en inhoud kolom kan zijn: fout of goed

**Comment by copierrj** [comment]
Het verwijderen kan op twee plaatsen geïmplementeerd worden:

- in de publicatieomgeving: dit zorgt ervoor dat de urls verdwijnen in het geoportaal  en ook in NGR/PGR.
- in het geoportaal: in NGR/PGR blijven de niet werkende urls zichtbaar.

Wat heeft hier de voorkeur?

**Comment by copierrj** [comment]
Zoals telefonisch besproken: urls die tijdens het harvesten niet bleken te werken worden door de publicatieomgeving verwijderd uit de metadata.

**Comment by gerardnienhuis** [comment]
Dit werkt goed, als url fout is (zie rapport geodata, http error code aanwezig) dan blijkt link naar die url van de bijlage niet in de metadata bij het onderdeel WAT te staan (steeksproefsgewijs getest). 

Dit issue kan gesloten.
