### ISSUE TITLE
Type service in stylesheet services fout

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#205]
Het lijkt er op alsof er iets is verwisseld in de stylesheet van services, bij het type service, daar staat download en view, maar staan die wel op de juiste plek (resp bij WMS en WFS)?

https://acc.geoportaaloverijssel.nl/
Naam van de service: B22_wegen

http://acc-metadata.geodataoverijssel.nl/metadata/service/1f3c4554-8ff4-4ae6-b1a8-3c8ba3dc4dc0.xml
bij de WMS staat er als type:

Type service: download

http://acc-metadata.geodataoverijssel.nl/metadata/service/81852c07-7522-44c4-8bb7-5d65244d8ee5.xml
Bij de WFS staat er:

Type service: view

**Comment by gerardnienhuis** [comment]
werkt nog niet goed... of ik controleer verkeerd?

bij de wfs met adressen staat type service: view, dit had download moeten zijn, zie DETAILS

http://acc-metadata.geodataoverijssel.nl/metadata/service/ceb4568b-3d24-40b4-ad4c-3a6c94dfef00.xml

**Comment by copierrj** [comment]
moet nog gedeployed worden

**Comment by gerardnienhuis** [comment]
ok, begrijp nu dat ik te vroeg aan het testen ben.. 
misschien goed idee om label om te zetten van 'gebruikerstest" naar een ander label?

**Comment by gerardnienhuis** [comment]
werkt nu wel goed, issue gesloten
