### ISSUE TITLE
Verzoek rapportage geodatasets bijlage die geen url is

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#206]
In het verleden is het mogelijk geweest om 2 of meer bijlagen bij een bestand toe te voegen.
Sinds het nieuwe NL profiel kan dat niet meer.

Dat is jammer,  2 bijlagen gaan nu niet goed. Is er daarvan ene waarschuwing in de rapportage van geodatasets terug te vinden? Misschien vermelding van alle bijlagen die geen url zijn? Dan kan een beheerder ze handmatig nazoeken en corrigeren

Zie bijvoorbeeld:

huidige geoportaal

http://gisopenbaar.overijssel.nl/geoportal_extern/rest/document?id=%7BC56F0F0B-A2B7-4F3F-A379-3084D83C06CE%7D
Aanvullende informatie:
layerfile: http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\lyr\Carpoolpleinen_bezettingsgraad_auto.lyr ^layerfile: http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\lyr\Carpoolpleinen_bezettingsgraad_fiets.lyr 

nieuwe geoportaal:

http://acc-metadata.geodataoverijssel.nl/metadata/dataset/d88549b0-e892-49e6-b806-c8bc4dee969d.xml
Aanvullende informatie: 1|een^2|twee

**Comment by robstek** [comment]
url's checken conform standaard (bijv met regex)

RFC standaard : https://tools.ietf.org/html/rfc3986

**Comment by gerardnienhuis** [comment]
in het rapport staan 3 kolommen die met elkaar te maken lijken te hebben:

http_errors_urls
http_errors_codes
invalide_urls

wat is de logische relatie tussen
deze kolommen?

**Comment by SandroNeumann** [comment]
De eerste twee waren eerst één kolom, maar die wilde je splitsen. Zie #345 De eerste is de url die het niet deed, de tweede is de http response code.

Invalide urls zijn urls die ingevoerd zijn die niet met http:// of https:// beginnen.

**Comment by gerardnienhuis** [comment]
Antwoord hierboven is helder.

Weer getest. Bij de invalide urls staan veel voorbeelden die inderdaad niet beginnen met http:// maar er staan er ook een paar die daarmee wel beginnen. bijvoorbeeld:

http://gisopenbaar.overijssel.nl/GeoPortal/MIS4GIS/preview/zoutwin.jpg
http://gisopenbaar.overijssel.nl/GeoPortal/MIS4GIS/preview/uiterw_polygon.jpg

deze urls blijken ook goed te openen te zijn.

wat kan hier aan de hand zijn?

**Comment by SandroNeumann** [comment]
Deze url's beginnen met een spatie.

**Comment by gerardnienhuis** [comment]
prima, is nu duidelijk. Werkt dus goed. issue kan gesloten
