### ISSUE TITLE
Update intern en extern Geoportaal niet gelijk

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#208]
Ik heb een update van de metainfo gedaan van het interne en externe Geoportaal: binnen 10 minuten was de info intern zichtbaar, maar voor extern wacht ik nu al half uur en ik zie nog niets. 

3 vragen: 
1) Kan het zijn dat de updatemomenten intern en extern sterk verschillen? 
2) De bedoeling is toch wel dat ze uiterlijk 35 minuten na verandering de nieuwe info beschikbaar hebben op de betreffende portalen?
3) Ik neem aan dat die 35 minuten wel gelijk is voor beide portalen?

**Comment by SandroNeumann** [comment]
Is de dataset wel extern beschikbaar (onder gebruiksrestricties bepaald)?

M.b.t. je vragen: beide portalen kijken naar dezelfde bron, intern toont alleen meer data.

**Comment by gerardnienhuis** [comment]
ja, zojuist komen ze wel extern beschikbaar.. werkt dus wel, maar intern is veel sneller bij mijn controle

Klopt dat?

---

Van: SandroNeumann [notifications@github.com]
Verzonden: donderdag 2 juni 2016 15:10
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard); Author
Onderwerp: Re: [IDgis/geoportaal-test] Update intern en extern Geoportaal niet gelijk (#208)

Is de dataset wel extern beschikbaar (onder gebruiksrestricties bepaald)?

M.b.t. je vragen: beide portalen kijken naar dezelfde bron, intern toont alleen meer data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/208#issuecomment-223286398, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphElT7fJbB6nuQZSJQXs4nTc5Ll7bks5qHtZQgaJpZM4IsiE2.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
Dat is onmogelijk, want ze kijken naar dezelfde bron. Misschien zat je naar een gecachte variant te kijken.

**Comment by gerardnienhuis** [comment]
probleem is opgelost: vervangen op zelfde moment, was waarschijnlijk F5 vergeten in te typen. naar andere pagina gaan vanaf home en dan naar home weer bezoeken is dus niet volledige verversing van de pagina, F5 is dat wel. issue kan gesloten
