### ISSUE TITLE
Download en CC-0 in rapportage geodatasets metadata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#209]
Verzoek is om 2 kolommen toe te voegen in de rapportage (csv) van geodatasets:

Download: is wel of niet downloadable (waarde ja of nee)
CC-0: is url van Creative Commens Zero wel of niet aanwezig (waarde ja of nee)

nb: als Dowload is ja, en CC-0 is nee, dan moet beheerder bij Overijssel de url van CC-0 nog toevoegen, anders is xml niet valide conform iso19115.

zie ook issue #198

**Comment by copierrj** [comment]
zelfde als #278?

**Comment by copierrj** [comment]
waarin is dit issue anders dan #278?

**Comment by gerardnienhuis** [comment]
issue is hetzelfde als #278 Dit issue is daarom gesloten
