### ISSUE TITLE
Hoe werkt beheer van aanvullende informatie bestanden?

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#210]
Als ik een url naar een bestand heb opgenomen in de metadata van geodatasets, dan is deze aanvullende informatie correct ook in de metainfo terug te vinden.

Maar hoe doe je als beheerder beheer van die aanvullende informatie?

1) verwijderen: als ik met geosticker de url verwijder, wordt dan ook de link naar de aanvullende data verwijderd?
2) veranderen: als ik met geosticker de url verandre, wordt dan ook automatische de nieuwe url toegevoegd?
3) veranderen met fouten: als ik met geosticker een typefout maak, bv. een spatie in de url, blijft dan de  oude (correcte) url bestaan, of verschijnt de nieuwe url
4) als ik geen aanvullende informatie meer wil, is het dan voldoende om de url in geosticker te verwijderen
5) als er bij opslaan en tonen van metadata in geoportaal eerst geen url was, en ik wil er als beheerder 1 toevoegen, kan ik dan gewoon met geosticker de url toevoegen en de xml weer opslaan? Gaat de rest dan vanzelf en verschijnt de nieuwe url dan in het geoportaal?

**Comment by SandroNeumann** [comment]
Er zijn na het aanpassen binnen geosticker geen acties van de beheerders nodig. De geopublisher harvest periodiek geosticker die vervolgens de nieuwe metadata presenteert.

**Comment by gerardnienhuis** [comment]
helder, maar hoe zit het dan met:

3) veranderen met fouten: als ik met geosticker een typefout maak, bv. een spatie in de url, blijft dan de oude (correcte) url bestaan, of verschijnt de nieuwe url?

**Comment by SandroNeumann** [comment]
De nieuwe url. De data wordt opnieuw opgehaald, dus ook url's met fouten.

**Comment by gerardnienhuis** [comment]
Is helder nu, issue kan gesloten
