### ISSUE TITLE
Aantal gelijke nummers in rapportage

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#213]
Het kan, perongeluk, gebeuren dan statische kaarten met hetzelfde nummer zijn aangeboden. Kan ik de rapportage (csv) van statische kaarten een kolom komen, waarin staat, hoe vaak een betreffend nummer voorkomt? 

Dat zal dan meestal 1 zijn, maar juist die 2 of meer zijn nuttig voor beheerders om te kijken of hier correcties nodig zijn

**Comment by robstek** [comment]
Het aantal wordt als kolom _count_ opgenomen tussen de kolommen _number_ en _source_.

**Comment by gerardnienhuis** [comment]
werkt goed, nu veel met 2 of zelfs 3, maar dat is iets voor beheer intern Overijssel. rapport werkt correct en issue kan gesloten
