### ISSUE TITLE
Mutatiedatum afwezig in stylesheet statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#214]
Als ik alle datums bij een statische kaart invul, dan lijkt het alsof de mutatiedatum afwezig is.

Klopt de stylesheet wel?

zie

https://acc-admin.geoportaaloverijssel.nl/metadata/dc/1b5427c9-9d74-4a79-975d-ca33ccba6d8c.xml

Naam statische kaart: AAA Test datum in metadata
Datum creatie: 2016-06-01
Datum publicatie: 2016-06-02
Datum geldig, van: 2016-05-30
Datum geldig, tot: 2016-06-05

**Comment by gerardnienhuis** [comment]
zie ook #212

**Comment by gerardnienhuis** [comment]
misschien te maken met #132 ?

**Comment by SandroNeumann** [comment]
Er is geen specifiek metadata element voor datum wijziging. Er is maar één datum element, die voor creatie gebruikt wordt. In het geval van publicatie is er een element 'issued' en de geldigheidsdata vallen onder het element valid. Een optie zou zijn om het datum element in de stylesheet 'Datum laatste wijziging' te benoemen en daar de meest recente datum van creatie en mutatie te plaatsen.

**Comment by gerardnienhuis** [comment]
Even bellen over impact morgen?

Verstuurd vanaf mijn iPhone

Op 14 jun. 2016 om 14:09 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Er is geen specifiek metadata element voor datum wijziging. Er is maar één datum element, die voor creatie gebruikt wordt. In het geval van publicatie is er een element 'issued' en de geldigheidsdata vallen onder het element valid. Een optie zou zijn om het datum element in de stylesheet 'Datum laatste wijziging' te benoemen en daar de meest recente datum van creatie en mutatie te plaatsen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/214#issuecomment-225861795, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphL85qp348rqanPhv0k7LGgxaO2LTks5qLpoJgaJpZM4IsxPc.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by HermanAssink** [comment]
Hallo Gerard,

Akkoord, graag na 9:00 uur zodat ik van tevoren met Sandro kan 
overleggen. Van 10:00 tot 11:00 uur ben ik niet bereikbaar ivm met 
afspraak bij Rijssen-Holten.

Met vriendelijke groet,

Herman Assink

IDgis http://www.idgis.nl
Tel +31 (0)548 367280

Volg IDgis op LinkedIn! http://www.linkedin.com/company/idgis
Op 14-6-2016 om 18:42 schreef Gerard Nienhuis:

**Comment by gerardnienhuis** [comment]
Voorstel is om de mutatiedatum geheel weg te laten, zowel in stylesheet als in invulscherm. Zoveel verschillende datums is onnodige bron van verwarring en verwachting is dat mutatiedatum niet of nauwelijks zinvol gebruikt wordt... Dit wordt nog wel eerst intern Overijssel uitgezocht.

**Comment by gerardnienhuis** [comment]
In huidige geoportaal lijkt ook geen mutatiedatum voor te komen, zie bijvoorbeeld:

RUD IJsselland, kaart (2016-01-12)

http://gisopenbaar.overijssel.nl/geoportal_extern/catalog/search/resource/details.page?uuid=%7BE08F3E65-6438-47FE-AA62-1A84A1727406%7D

Datum publicatie:  2016-01-12
Datum creatie:  2016-01-12
Datum geldig, Van: 2016-01-12
Tot:  2016-01-12

**Comment by SandroNeumann** [comment]
Het andere punt:

Wanneer een record gepubliceerd wordt moet dat record bovenaan komen te staan? Geldt dat voor alle status overgangen of alleen bij het in publicatie zetten?

**Comment by SandroNeumann** [comment]
@gerardnienhuis: laat je nog weten of mutatiedatum definitief overal verwijderd kan worden?

**Comment by gerardnienhuis** [comment]
Is definitief: mutatiedatum kan weg

Verstuurd vanaf mijn iPhone

Op 15 jun. 2016 om 17:34 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis: laat je nog weten of mutatiedatum definitief overal verwijderd kan worden?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/214#issuecomment-226225757, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphGuj14dVeLAEX2KA1cmxDjinxaGEks5qMBuGgaJpZM4IsxPc.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Ja
Kan overal verwijderd

Verstuurd vanaf mijn iPhone

Op 15 jun. 2016 om 17:34 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis: laat je nog weten of mutatiedatum definitief overal verwijderd kan worden?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/214#issuecomment-226225757, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphGuj14dVeLAEX2KA1cmxDjinxaGEks5qMBuGgaJpZM4IsxPc.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Voor alle statusovergangen
Meer niet
Dus niet verandering naam leverancier

Verstuurd vanaf mijn iPhone

Op 15 jun. 2016 om 12:21 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Het andere punt:

Wanneer een record gepubliceerd wordt moet dat record bovenaan komen te staan? Geldt dat voor alle status overgangen of alleen bij het in publicatie zetten?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/214#issuecomment-226147575, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphNRP-WEgvIUH5NjvupfcGkRRJH41ks5qL9JAgaJpZM4IsxPc.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
Nieuw issue wordt #227

Dit issue kan gesloten worden, net als #212, #132, #211

**Comment by gerardnienhuis** [comment]
mutatiedatum wordt niet meer gebruikt bij statische kaarten: issue kan hier gesloten, wordt vervangen door #227
