### ISSUE TITLE
Url van service korenbloem ontbreekt

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#219]
Van de kaart met wilde planten is een selectie gemaakt, daaruit is b.v. de korenbloem als aparte laag opgenomen. Nu blijkt dat de korenbloem wel bij de WAT zichtbaar is in de stylesheet van de service, maar als je dan de metainfo van de korenbloem zelf bekijkt, staat niet bij de DETAILS de url naar deze service. zie afbeelding.

![service_url ontbreekt](https://cloud.githubusercontent.com/assets/9005444/15925066/e8671f54-2e35-11e6-8fe5-95718294e62f.jpg)

**Comment by gerardnienhuis** [comment]
heeft waarschijnlijk te maken met #202

**Comment by HermanAssink** [comment]
Deze service had niet publiek mogen zijn omdat de data niet downloadable is. Wel staat er de vermelding "Geoportaal extern" bij de dataset. Dus de metadata van de dataset mag publiek opvraagbaar zijn.

**Comment by gerardnienhuis** [comment]
moet opgelost door handwerk in pub omgeving, is geen bug. kan gesloten
