### ISSUE TITLE
Beveiligde rasters in extern geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#221]
Dit is niet goed: beveiligde services zijn zichtbaar in het externe geoportaal, in dit geval 

Raster_beveiligd (20-04-2011, Provincie Overijssel)

Deze service had alleen in het interne geoportaal zichtbaar moeten zijn.

Je ziet daarvan in het externe geoportaal een klein stukje metadata, maar als je op metadata klikt, dan krijg je foutmelding, zie hieronder.

404 Not Found: /metadata/service/55cfca99-442f-4fc0-bd9f-efb314e05f80.xml

Raster_beveiligd (20-04-2011, Provincie Overijssel)

slechts klein stukje metadata leesbaar:
De service bevat datasets die als rasters zijn opgeslagen (grids). De service bevat lagen, waarvan de beschrijving wel getoond mag worden. De data van deze lagen mag echter niet altijd online beschikbaar gemaakt worden. Dit betreft bestanden die nog in bewerking zijn of bestanden die informatie over personen bevatten. Ook kan het bestanden betreffen die van derden zijn gekocht voor eigen gebruik, maar waarbij doorlevering niet is toegestaan. Levering v..

**Comment by SandroNeumann** [comment]
Alle services die alleen in de beveiligde omgeving gepubliceerd zijn, zijn intern. Maakt niet uit of er wel of niet vertrouwelijke lagen in zitten.

**Comment by NicoEilers** [comment]
blijkt nu goed te zijn, issue kan gesloten
