### ISSUE TITLE
Naam raster in alternatieve titel laten staan

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#222]
Rasters zijn herkenbaar aan de code grid bij ruimtelijk schema.
Wens is om de (locatie intern bij Overijssel) ook zichtbaar te houden.
Dat is nu met de hand verwijderd, omdat anders programmatuur van pub. omgeving niet verder kon.

zie: Bestandsnaam: Top 250 raster van Nederland
Alternatieve titel: B0.TOP250_KLEUR (B0)

Deel van alternatieve titel moet dan genegeerd worden door harvester pub. omgeving. tzt uitzoeken welk deel.

**Comment by copierrj** [comment]
Impact van deze wens lijkt beperkt (want: lijkt beperkt tot de provider), mits goed duidelijk is wat er precies gebeuren moet.

**Comment by SandroNeumann** [comment]
staat er ook al voor bij alternatieve titel, issue kan gesloten
