### ISSUE TITLE
Datum gebruik weergave Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#226]
In het Geoportaal (zowel intern als extern) worden datums gebruikt voor weergave van de volgorde: de meest nieuwe staan bovenaan. Hiervoor moeten datums gebruikt worden uit de volgende velden:

1) statische kaarten: publicatiedatum (als deze afwezig is, creatiedatum)
2) geodata: Laatste wijziging bestandsbeschrijving
3) services: Laatste wijziging servicebeschrijving

zie bijgevoegde plaatjes
![datum_zichtbaar_geoportaal](https://cloud.githubusercontent.com/assets/9005444/16080699/57cc7578-330a-11e6-8cfa-236a53adb920.jpg)

**Comment by gerardnienhuis** [comment]
![laatste_wijziging_geodata](https://cloud.githubusercontent.com/assets/9005444/16080715/64f85b5e-330a-11e6-88bc-3a5f1c80ea0e.jpg)

![laatste_wijziging_services](https://cloud.githubusercontent.com/assets/9005444/16080722/6b95681c-330a-11e6-9b44-fb4b3e51054a.jpg)

![pub_datum_stat_kaarten](https://cloud.githubusercontent.com/assets/9005444/16080727/71cc2586-330a-11e6-8881-7eca247d92a8.jpg)

**Comment by SandroNeumann** [comment]
Let wel: wanneer een datum niet bestaat en daarmee leeg is in het geoportaal wordt het record niet getoond, omdat er op datum gesorteerd wordt en dat kan niet met lege velden.

**Comment by gerardnienhuis** [comment]
We willen de rapportage gebruiken om te controleren of er 1 datum is

Verstuurd vanaf mijn iPhone

Op 15 jun. 2016 om 16:11 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Let wel: wanneer een datum niet bestaat en daarmee leeg is in het geoportaal wordt het record niet getoond, omdat er op datum gesorteerd wordt en dat kan niet met lege velden.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/226#issuecomment-226199134, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphEdPKQxC-Wb52CIg6kHmlbwD2gxjks5qMAgVgaJpZM4I2VS2.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Betreft alleen conversie huidige data
Rapportage moet dat probleem zichtbaar maken

Verstuurd vanaf mijn iPhone

Op 15 jun. 2016 om 16:11 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Let wel: wanneer een datum niet bestaat en daarmee leeg is in het geoportaal wordt het record niet getoond, omdat er op datum gesorteerd wordt en dat kan niet met lege velden.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/226#issuecomment-226199134, or mute the threadhttps://github.com/notifications/unsubscribe/AIlphEdPKQxC-Wb52CIg6kHmlbwD2gxjks5qMAgVgaJpZM4I2VS2.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
is nu goed, getest. issue kan gesloten
