### ISSUE TITLE
Aantal bijlagen pe statische kaart minimaal 200

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#228]
Het blijkt dat er in het verleden statische kaarten als serie zijn aangeboden. Aantallen van 70 of meer bijlagen bij 1 kaart komen voor. Wat is de beperking van het aantal bijlagen per kaart? Wens is dat dit in ieder geval minimaal 200 is, om ook een marge te hebben voor gebruik in de toekomst.

**Comment by SandroNeumann** [comment]
Er is geen limiet op het aantal bijlagen, alleen de omvang van het volledige formulier (200 MB).

**Comment by gerardnienhuis** [comment]
Klinkt goed, kan dus getest worden in nieuwe op te leveren versie. Als rapportage dan ook aantal bijlagen per statische kaart laat zien, dan is hier ook gericht op te testen. Gaan we doen wat mij betreft bij volgende acceptatieversie.

**Comment by gerardnienhuis** [comment]
getest: 95 bestanden toegevoegd probleemloos bij:
https://acc-admin.geoportaaloverijssel.nl/metadata/8353dea5-f36d-4b56-993a-9a326b5dc1e3
issue kan gesloten
