### ISSUE TITLE
Enter naar volgende veld bij toevoegen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#23]
Bij onderdeel "toevoegen" werkt drukken op <Enter> niet goed in alle velden.

Na drukken op <Enter> moet worden gegaan naar het volgende invoerveld.
Dus bij Titel ga je naar "Omschrijving". Bij "Omschrijving" ga je naar
"Locatie" en bij locatie ga je naar "Kenmerk". Bij <Enter> in 
het veld "Kenmerk" en bij het veld "Bron"gebeurt er niets: je blijft in dat veld. Nu ga je weer naar beginscherm, is erg onhandig.

opmerking nr 14 n.a.v. testen 3-2-16

![enter_invoerveld](https://cloud.githubusercontent.com/assets/9005444/12780261/284f4c22-ca6d-11e5-8b4e-5f1ab843c640.jpg)

**Comment by SandroNeumann** [comment]
Dit kan werken op alle velden, behalve omschrijving. Dat is een ander soort veld en daar heeft enter al een betekenis.

**Comment by gerardnienhuis** [comment]
Morgen bellen?

Verstuurd vanaf mijn iPhone

Op 3 feb. 2016 om 16:53 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Dit kan werken op alle velden, behalve omschrijving. Dat is een ander soort veld en daar heeft enter al een betekenis.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/23#issuecomment-179305768.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
OK, dat is prima.

**Comment by gerardnienhuis** [comment]
Mijn grootste zorg bij niet utf8 tekens is opname in geoportaal en ook de weergave met nieuwe stylesheet: is nu alleen getest met pure utf8 tekens

Verstuurd vanaf mijn iPhone

Op 3 feb. 2016 om 17:51 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

OK, dat is prima.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/23#issuecomment-179342193.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
Na telefonisch overleg is besloten om de web conventie te hanteren en met de tab toets naar het volgende invoerveld te gaan. De overbodige elementen worden uit de tabindex gehaald. @gerardnienhuis: Zou jij dit issue willen sluiten en een nieuwe willen maken die dat omschrijft?

**Comment by gerardnienhuis** [comment]
Is prima
Doe ik morgen

Verstuurd vanaf mijn iPhone

Op 11 feb. 2016 om 16:48 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Na telefonisch overleg is besloten om de web conventie te hanteren en met de tab toets naar het volgende invoerveld te gaan. De overbodige elementen worden uit de tabindex gehaald. @gerardnienhuishttps://github.com/gerardnienhuis: Zou jij dit issue willen sluiten en een nieuwe willen maken die dat omschrijft?

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/23#issuecomment-182925521.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Issue is vervangen door: https://github.com/IDgis/geoportaal-test/issues/55

Zelfde werking, alleen met tab ipv met enter naar volgende veld.

**Comment by gerardnienhuis** [comment]
issue gesloten op verzoek van Sandro. Let op: nieuw issue https://github.com/IDgis/geoportaal-test/issues/55 geopend en vervangt dit issue.
