### ISSUE TITLE
pdf opent in viewer van browser en niet in adobe acrobat viewer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#234]
De bedoeling is dat iedere bijlage bij een statische kaart geopend wordt in de applicatie die daaraan gekoppeld is. Dus als je een pdf opent in de windows verkenner, dan krijg je adobe acrobat viewer.

Nu blijkt het zo dat bij de provincie Overijssel je bij gebruik van Internet explorer een andere pdf viewer krijgt. Deze viewer heeft minder mogelijkheden. Zo opent het scherm niet beeldvullend wat als heel vervelend wordt ervaren.

Dat is niet de bedoeling: bedoeling is dat je de viewer krijgt, die je ook zou krijgen als je de windows verkenner zou gebruiken.

**Comment by SandroNeumann** [comment]
Deze werking is de implementatie van de browser. Mocht je je eigen programma willen gebruiken dan moet je het bestand eerst opslaan. Dit kan met de rechter muisknop en dan link opslaan als.

**Comment by HermanAssink** [comment]
Bij pdf kan de gebruiker dat zelf in de browser instellen, zie bijv: http://blogs.adobe.com/acrolaw/2007/08/how_do_i_open_a_pdf_in_acrobat_i/

Dit valt echter buiten de controle van de applicatie.

**Comment by gerardnienhuis** [comment]
wel sneu voor de gebruikers intern Overijssel: door wordt IE gebruikt. Zie laatste opmerking in deze link:

What about Download Options for Internet Explorer?

From what I understand, IE does not offer a flexible enough programming interface to allow this kind of customization.
