### ISSUE TITLE
Statische kaart ontbreekt

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#237]
Er zijn 2 statische kaarten gepubliceerd, maar er is er maar 1 zichtbaar in het Geoportaal
Dit lijkt een fout. Hoe kan dit? Ze zijn beide een paar dagen geleden al gepubliceerd, dus had ik ze beide verwacht bij de meest recente bestanden.

zie figuur

![ontbreekt_kaart](https://cloud.githubusercontent.com/assets/9005444/16483973/1989bf7e-3eb7-11e6-8188-de338b89f707.jpg)

**Comment by SandroNeumann** [comment]
Ze zijn allebei zichtbaar, maar bij het harvesten wordt de datum nog bepaald op datum creatie. Om die reden komt deze in dit geval veel verderop te staan.

Zie: https://acc-intern.geoportaaloverijssel.nl/search?text=verkoop (het laatste record)

Dit is al opgelost en zal in de komende versie goed gaan.

**Comment by gerardnienhuis** [comment]
is nu goed, issue gesloten
