### ISSUE TITLE
Verwijzing naar zelfde tabel in rapportage

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#240]
Gevonden bij testen:

In de metadata van Overijssel op RIJN staan bestanden die verwijzen naar dezelfde tabel, bijv.
2f2393b5-bf84-4412-bd76-a830838fb867.xml en be857982-886c-4a40-acdc-be67b8fde36b.xml verwijzen beide naar de tabel B3.water_polygon.
Het is gewenst deze situatie te melden in de rapportage van GeoPublisher.

Wens is dat situaties waarbij xls's naar zelfde tabel verwijzen ook terug te vinden zijn als fout in de rapportage van geodatasets

**Comment by NicoEilers** [comment]
Is ook wenselijk in rapportage Geoportaal bij geodatasets

**Comment by copierrj** [comment]
Is de situatie van het hebben van meerdere metadata documenten bij dezelfde database tabel altijd incorrect?

**Comment by gerardnienhuis** [comment]
ja, dat blijkt inhoudelijk niet te moeten. technisch is het wel mogelijk om dat voor elkaar te krijgen, maar het is een ongewenste situatie: je hebt als het fout is, twee keer metainformatie van 1 bestand. Dat is verwarrend en onnodig. Wens is om in de rapportage op te nemen, hoe vaak een xml naar een betreffende dataset verwijst. is dat getal kleiner dan 1 of groter dan 1 dan is hier iets vreemds aan de hand en kunnen beheerders die verder onderzoeken en mogelijk ook oplossen.

**Comment by copierrj** [comment]
De situatie van het ontbreken van metadata document bij een dataset (= Oracle tabel?) is voor de publicatieomgeving niet zichtbaar op dit moment. Vanuit het perspectief van de publicatieomgeving bestaat een dataset pas als er metadata gevonden wordt die verwijst naar een tabel in Oracle. 

Rapporteren over het ontbreken van metadata kan dus niet zonder de werking van de publicatieomgeving aan te passen op dit punt.

**Comment by SandroNeumann** [comment]
alleen 1 of groter dan 1 in rapportage

**Comment by HermanAssink** [comment]
Kan met Excel worden nagegaan mbv kolom alternate-title, zie http://superuser.com/questions/405555/how-can-i-group-by-and-sum-a-column-in-excel

**Comment by SandroNeumann** [comment]
als dit inderdaad lukt, dan kan issue gesloten worden

**Comment by gerardnienhuis** [comment]
Probleem is opgelost, issue kan gesloten. Kan gewoon met excel, hieronder staan de stappen:

7 stappen:

1) maak rapport geodata in het onderdeel rapportage van http://admin.geoportaaloverijssel.nl

2) sorteer op alternate title (onderdeel Gegevens in excel, dan sorteren)

3) selecteer kolom alternate title

4) ga naar het onderdeel start in excel

5) kies voorwaardelijke opmaak, markeringsregels voor cellen, dubbele waarden.

6) geef de cellen een opvallende kleur, bv rood

7) blader door de excelfile en kijk welke cellen rood zijn
