### ISSUE TITLE
Downloadlink niet aanwezig bij Gemeentegrenzen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#241]
In dit geval wordt wel een downloadlink verwacht:
Zie https://acc-metadata.geodataoverijssel.nl/metadata/dataset/9326766b-3393-477d-a4df-38f6e47cc240.xml

**Comment by gerardnienhuis** [comment]
In meer detail:

bij de vorige versie stond bij de DETAILS bij de links naar WMS en WFS ook de link naar de download-url. Deze is nu niet meer aanwezig, bij geen enkel downloadbaar bestand. Wens is om deze downloadlink weer terug te laten komen in de stylesheet

**Comment by NicoEilers** [comment]
Deze issue geldt voor alle datasets.

**Comment by SandroNeumann** [comment]
In de xml is geen download link aanwezig.

**Comment by gerardnienhuis** [comment]
Werkt nu wel (bijna) goed, kan tzt opgelost worden...

in de bijlage was een bestand op genomen met dezelfde naam als de naam van de preview /thumbnail (plaatje in metadata): download blijkt nu goed te werken, maar er komt in de zip een bestand dat lijkt aan te geven dat download is mislukt. Bestand hoeft in dit geval niet neergezet te worden. 

nb, bestand heet: 
Download_gemgrens.jpg_mislukt.txt

**Comment by gerardnienhuis** [comment]
is goed opgelost: er komt nu tekst dat download van jpg niet is gelukt, dat is logisch, die was tenslotte dubbel: in txt file staan nog een keer: duplicate entry: gemgrens.jpg

issue kan gesloten
