### ISSUE TITLE
Link naar metadata van dataset in service md onbegrijpelijk onder tab Details

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#242]
Deze links laten alleen een uuid zien, terwijl dezelfde links op de tab Wat wel duidelijk zijn. Links op tab Details laten vervallen?

**Comment by gerardnienhuis** [comment]
Nee, werkt prima zo. Is geen probleem mee, om in details meer details te tonen, hoe technisch ook. aub stylesheet van geodata zo laten werken
