### ISSUE TITLE
Rapportage van inhoud services

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#243]
nu is er een rapportage voor geodata en statische kaarten, maar niet van services. Omdat services ook in geoportaal zitten, is het wenselijk ook daar een rapportage van te hebben, met alle beschikbare info
(aantal lagen in service, datum, samenvatting enz)

**Comment by gerardnienhuis** [comment]
hangt samen met #235

**Comment by copierrj** [comment]
Al deze informatie is beschikbaar in de publicatieomgeving. Hiervoor zouden we nieuwe rapportage (dus naast de al bestaande rapportages) kunnen maken. Is dit de bedoeling? Of is het wenselijk om deze gegevens te verwerken in bestaande rapportages?

**Comment by gerardnienhuis** [comment]
ja, het is de bedoeling dat hiervoor een aparte rapportage komt, die vanaf de pagina  te benaderen is, waar beheerders van het geoportaal inmiddels al wel de rapportages voor "download", "geodata" en "statische kaarten" kunnen downloaden.

**Comment by SandroNeumann** [comment]
Zelfde als #349

**Comment by SandroNeumann** [comment]
Er is de mogelijkheid om rapportage van services te downloaden. Dit lijkt me een issue waar men vergeten is deze te sluiten.

**Comment by gerardnienhuis** [comment]
klopt, rapportage is aanwezig en werkt correct: issue kan dus gesloten
