### ISSUE TITLE
Help knop bij inloggen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#244]
Bij inloggen blijken toch soms vragen te zijn. Help knop met link naar pagina met helptekst is nuttig, zie plaatje. Als het eenvoudiger te implementeren is, dan is link naar pdf met de helptekst ook een goed alternatief

![help_tekst_inloggen](https://cloud.githubusercontent.com/assets/9005444/16706493/536c2926-45af-11e6-8cd0-b5e67eeff083.jpg)

**Comment by SandroNeumann** [comment]
@gerardnienhuis: Lever je de tekst die hier moet komen nog aan?

**Comment by gerardnienhuis** [comment]
Tekst is:

Toelichting bij inloggen in het Geoportaal.

Je kan, als je hiervoor de rechten hebt, inloggen in het Geoportaal.
Je kan daarna je eigen (statische) kaarten aanbieden.
Heb je een nieuwe kaart, neem deze dan op in het Geoportaal door hier in te loggen.

Gebruik bij het inloggen je emailadres, zoals gebruikt wordt in Overijssel.
Gebruik hier geen spatie of hoofdlettters. Alleen kleine letters gebruiken.
p.pietersen@overijssel.nl is goed
P.Pietersen@Overijssel.nl is niet goed.

Ben je je wachtwoord vergeten, dan kan je een nieuw wachtwoord aanvragen.
Vul dan je emailadres in bij "WACHTWOORD VERGETEN" en je krijgt in je mailbox
een nieuw wachtwoord.

Bij "WACHTWOORD AANPASSEN" kan je eventueel je huidige wachtwoord aanpassen.
Aangeraden wordt om dat 1x per maand te doen. Gebruik hier eventueel wel hoofdletters
en/of andere bijzondere tekens.

**Comment by gerardnienhuis** [comment]
Help tekst klopt nu niet meer: tekst is wel zichtbaar en werkt goed. Maar omdat ook hoofdletters kunnen worden gebruikt, moet tekst in 1 regel worden aangepast.

er staat nu:

Gebruik bij het inloggen je emailadres, zoals gebruikt wordt in Overijssel. Gebruik hier geen spatie of hoofdlettters. Alleen kleine letters gebruiken. p.pietersen@overijssel.nl is goed P.Pietersen@Overijssel.nl is niet goed.

dat moet worden:

Gebruik bij het inloggen je emailadres, zoals gebruikt wordt in Overijssel. Je mag zowel hoofdletters als kleine letters gebruiken. p.pietersen@overijssel.nl is goed. En ook P.Pietersen@Overijssel.nl is goed.

**Comment by gerardnienhuis** [comment]
Helptekst correct aangepast, issue kan gesloten
