### ISSUE TITLE
Url service volledig weergeven in stylesheet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#249]
De url van de services was in eerdere versies voluit weergegeven (dacht ik). 

In de metadata van de service, direct bij het eerste tabblad "WAT".

Nu zie ik slechts een (voor een buitenstaander) onbegrijpelijke tekst staan. De url moet, zowel van WFS als WMS, voluit weergegeven worden in de stylesheet, zodat gebruikers deze url direct kunnen gebruiken.

voorbeeld:

Naam van de service: B22_wegen
er staat nu:
OGC:WMS: geoserver-publicB22_wegen/wms 

moet worden:
OGC:WMS: http://acc-services.geodataoverijssel.nl:80/geoserver/B22_wegen/wms

**Comment by HermanAssink** [comment]
Zie onder tab "Wat" van https://acc-www.geoportaaloverijssel.nl/metadata/service/1f3c4554-8ff4-4ae6-b1a8-3c8ba3dc4dc0

**Comment by gerardnienhuis** [comment]
url is correct weergegeven en blijkt ook te werken (steekproef wms met qgis en steekproef download url): issue kan gesloten
