### ISSUE TITLE
Lange titel of beschrijving statische kaarten geeft fout in rapportage

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#254]
Als er erg lange titels of erg veel tekst in de beschrijving van statische kaarten wordt gezet, dan levert dat fouten op in de rapportage.

**Comment by gerardnienhuis** [comment]
[fouten_tekst_te_lang.xlsx](https://github.com/IDgis/geoportaal-test/files/355583/fouten_tekst_te_lang.xlsx)

is voorbeeld waarbij het fout gaat met te lange teksten

**Comment by NicoEilers** [comment]
Moet tzt worden opgelost, maar is niet productie-remmend.

**Comment by HermanAssink** [comment]
Kolommen breder maken in Excel en opslaan als xls

**Comment by gerardnienhuis** [comment]
gewoon csv inlezen in excel, daarna kolom die te breed is selecteren, daarna:
celeigenschappen / uitlijning: kies terugloop. 
werkt prima, issue kan gesloten worden
