### ISSUE TITLE
Datum rapportage foutief jaar-maand-dag

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#255]
In de rapportage van dublin core data (statische kaarten) staan alle tijden vermeld als:
dag-maand-jaar, met uitzondering van minstens 1 record. Daar staat jaar vooraan.

Kan het zijn dat sorteringen van jaren beneden 1900 fout gaan? Of is er wat anders aan de hand.
Hier meer info over het foutieve record.

https://acc-admin.geoportaaloverijssel.nl/metadata/6c3cf1e7-1dc3-452c-a626-ba644643af4d

filmpje 
Provincie Overijssel: eenheid Bestuurs- en Concernzaken 
farming 
filmpje 
1810-10-10  
Kaart  
ArcGIS: MXD

6c3cf1e7-1dc3-452c-a626-ba644643af4d  
filmpje 
filmpje  
instructievideo_zit_sta_werkplek_website.mp4  
6.37    6.37    Geen restricties    Alleen voor intern gebruik  
van der Veen    supplier    Ter goedkeuring d.vd.veen@overijssel.nl 
21-4-2016   Provincie Overijssel    Provincie Overijssel  
Nederlands  5.791   7.09    52.115  52.853

**Comment by NicoEilers** [comment]
Moet tzt worden opgelost, maar is niet productie-remmend.

**Comment by SandroNeumann** [comment]
**@gerardnienhuis**: Kun je dit nu nog reproduceren? In mijn geval zijn alle data namelijk in het formaat van yyyy-mm-dd. Ik denk dat dit aan de cellen opmaak ligt van het spreadsheet programma dat je gebruikt.

**Comment by gerardnienhuis** [comment]
Lijkt te zijn veroorzaakt door 1 of meerdere vreemde tekens, zoals ; 

Ik heb 4 records gevonden (bij rapport productie van vandaag0 waarbij dergelijke problemen voorkomen.

In de bijgevoegde excelfile zijn de velden die vreemde info bevatten, geel gekleurd.

Voorbeeld:

https://admin.geoportaaloverijssel.nl/metadata/14061968-93af-4730-8f91-2e27eab19f3c
ziet in in de stylesheet (onderdeel beheer productie) goed uit.

Maar in de excelfile gaat de indeling verkeerd,

beschrijving is te vroeg afgekapt:
Zoneringskaart (concept) - boomteelt in Noordoost-Twente.  Voor de zonering zijn gegevens door de gemeenten Dinkelland, Losser, 
Tubbergen aangeleverd, deze staan in de map 'gegevens_sept_2007'.  De map sept_2007 bevat de bestanden die gebruikt zijn voor het project 
(apr: sept_2007).  In de map -kwekerij_2004- bevindt zich het bestand kwek2004" dat de basis is van het bestand 'boomkwekerij' op de 
zoneringskaart.  Dit bestand "kwek2004" is een selectie uit de top10-vector(vlakken), zoals die in juli 2005 beschikbaar waren. 
(de meeste tiles zijn in 2003 of 2004 geinventariseerd).  Selectiecriteria waren

hierachter had moeten staan: boomgaarden, boomkwekerijen, fruitkwekerijen en kassen (glastuinbouw)."

Dat staat er echter niet. 

Opvallend is dat er een ; teken ontbreekt. Mogelijk is dat de oorzaak ervan

De rest van de tekst, zonder ; is terechtgekomen bij een datumveld.

[4fouten_excelfile.xlsx](https://github.com/IDgis/geoportaal-test/files/524826/4fouten_excelfile.xlsx)

**Comment by SandroNeumann** [comment]
Dat is inderdaad een bug, maar dit is iets anders dan waar dit issue om begon. Namelijk het formaat van datums. In je geleverde xls file zie ik alle datum velden in het formaat van dd-mm-yyyy.

**Comment by HermanAssink** [comment]
Oplossing is tekstvelden tussen aanhalingstekens zetten?

**Comment by gerardnienhuis** [comment]
Datum sortering is opgelost, dit issue kan gesloten, nieuw gevonden bug gaat naar apart issue
