### ISSUE TITLE
Rasters en tabellen niet downloaden als shape, kml enz

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#257]
Je kan geodata opslaan als raster of als tabel, maar het downloaden van dergelijke formaten (b.v. als shape) gaat fout. 

Er is wel een download knop aanwezig, maar je krijgt als je alles in het formulier hebt ingevuld altijd een foutmelding in de mail.

Getest met tabellen en grids, b.v.

https://acc-www.geoportaaloverijssel.nl/metadata/dataset/3c9b9a78-fa88-4646-b281-8a7ce696bf80

geeft melding:

Je download maximale_waterdiepte_dijkring_9_breslocatie_Hasselt van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  ExceptionReport: <ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://acc-services.geodataoverijssel.nl:80/geoserver/schemas/ows/1.1.0/owsAll.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
    ows:ExceptionTextFeature type :maximale_waterdiepte_dijkring_9_breslocatie_Hasselt unknown/ows:ExceptionText
  /ows:Exception
/ows:ExceptionReport
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by NicoEilers** [comment]
voorstel: als het een grid (raster) of tabel is, dan knop download niet tonen geoportaal en ook niet in stylesheet. uitzoeken moet nog: kan je service hiervan downloaden

**Comment by SandroNeumann** [comment]
Wat bedoel je in deze context met tabel? Een dataset is gebaseerd op een Oracle tabel en die is wel downloadbaar, mits dat mag.

**Comment by SandroNeumann** [comment]
Voor 1.0 wordt geregeld dat de download link bij rasterdata niet getoond wordt. Voor tabellen wordt een issue voor 1.1 opgevoerd.

**Comment by gerardnienhuis** [comment]
voor versie 1.0 is hier geen groot probleem: geopublisher verwerkt geen tabeldata vooralsnog.
in versie 1.1. wordt dit aan de kant van het geoportaal opgelost, is het voorstel. 
zie nr #261

**Comment by gerardnienhuis** [comment]
correctie: tabellen worden wel door publicatieomgeving doorgegeven, blijkbaar.

Kijk maar naar: 
https://acc-www.geoportaaloverijssel.nl/search?text=tabel
zoeken  "tabel"  levert onder meer op:
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/60d133a2-fdc7-4f77-9fb5-88689d91590b
Onderzoek naamsbekendheid toeristische regio's (16-03-2015, Provincie Overijssel)

Dat is een tabel, onderscheiden van de rest door:
Ruimtelijk schema: Tekst tabel

Net als Rasters (schema = grid) moet hiervan de downloadknop niet getoond worden
(niet in intern en niet in extern portaal)

**Comment by gerardnienhuis** [comment]
Tabellen en grids lijken nu bijna allemaal goed te gaan. Download is niet zichtbaar, niet in Geoportaal zoekresultaten. Maar soms is de download url nog wel zichtbaar in de metainformatie, bij het onderdeel Details. 

Kijk bijvoorbeeld bij de details van: Topografische kaart 1:25000

https://acc-www.geoportaaloverijssel.nl/metadata/dataset/6673048d-eea8-42f6-a805-35098c562c05

Daar staat: 

Download: https://acc-download.geoportaaloverijssel.nl/download/6673048d-eea8-42f6-a805-35098c562c05
OGC:WFS: http://acc-services.geodataoverijssel.nl:80/geoserver/Raster/wfs
OGC:WMS: http://acc-services.geodataoverijssel.nl:80/geoserver/Raster/wms

Ruimtelijk schema: Grid, dus metainfo is goed ingevuld. Toch is download url zichtbaar.

Fout is ook te zien bij:

Potentiekaart warmte_koude_opslag (WKO)

https://acc-www.geoportaaloverijssel.nl/metadata/dataset/2ecc9556-f529-4103-85c7-6eb195a70a46

nb: bij andere gevallen is het wel correct, zoals:

Landelijke grondgebruikskartering Nederland 2007/2008
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/34e17781-1cac-4c4d-ab59-6a22f76cdad4

daar staat geen download url en ook bij zoekresultaten staat geen "download".

**Comment by gerardnienhuis** [comment]
opmerkelijk: bij tabellen lijkt het wel correct te worden afgehandeld

type tabel, dan geen download bij zoekresultaten en geen download url bij details in metainfo

**Comment by gerardnienhuis** [comment]
Ook tabellen blijken nog niet allemaal goed te gaan, merk ik nu. Ik heb een tabel gevonden, die in de details nog een download link heeft: zie

Bestandsnaam: Wandelroutes in Overijssel tabel
https://www.geoportaaloverijssel.nl/metadata/dataset/00e25a39-58fa-485b-92b1-b93829d7a398
Download: https://download.geoportaaloverijssel.nl/download/00e25a39-58fa-485b-92b1-b93829d7a398

**Comment by SandroNeumann** [comment]
Zelfde oorzaak als #269

**Comment by gerardnienhuis** [comment]
werkt nu goed, issue kan gesloten
