### ISSUE TITLE
Knop (link) download alleen laten zien als dataset echt downloadbaar is.

### ISSUE THREAD

**Issue by NicoEilers** [IDgis/geoportaal-test#260]
Als dataset niet gedownload mag worden, dan moet de link "download" niet zichtbaar zijn. Dat staat in de gebruiksbeperkingen: alleen "downloadable data" mag worden gedownload, de rest niet. Merk op: ook tabellen en grids moeten nu niet downloadbaar zijn, omdat het downloaden hiervan niet goed gaat (je kan alleen nu kiezen uit download van geodatasets, bv. als shape enz).

**Comment by NicoEilers** [comment]
zie #257

**Comment by gerardnienhuis** [comment]
let op: opmerking 1 juni #142 van Sandro geeft aan, hoe het moet werken.
"De download link wordt alleen getoond wanneer er staat dat de dataset downloadable is."

Dit blijkt dus nog niet goed te werken.

**Comment by SandroNeumann** [comment]
Die opmerking had betrekking op de download link in de stylesheet, niet in de lijst in het geoportaal.

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
