### ISSUE TITLE
Tekst geoportaal bij help, over deze site en contact

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#262]
tekst bij de knop "help" in het Geoportaal tussen ===
(tekst is zowel voor Home als voor Uitgebreid zoeken als voor Bladeren)
geschikt voor intern en extern Geoportaal
# 

Zoek naar termen in de beschrijving bij de data. Je kan één of meerdere woorden of delen van woorden gebruiken.
Gebruik je meerdere woorden, dan wordt de optie "and" gebruikt.

Dat wil dus bijvoorbeeld zeggen dat je bij het zoeken naar het woord
"natuur" 200 treffers krijgt. 

Maar zoek je 2 woorden, bijvoorbeeld "natuur" en "bos" dan vind je maar 50 treffers.
Dat wil dus zeggen dat er 200 datasets zijn met het woord "natuur" in de beschrijving.
Maar er zijn er maar 50 met zowel de woorden "natuur" als "bos" in de beschrijving.

nb: je hoeft de woorden niet tussen "haakjes" te zetten overigens.

Vind je niet datgene wat je zoekt? Probeer dan een andere zoekterm of
een deel van een andere zoekterm.

Je kan ook bij de onderdelen "Uitgebreid zoeken" of "Bladeren" kijken of je daar kan vinden
wat je zoekt. Die onderdelen leveren weer meer opties om te vinden waar je naar op zoek bent.

Bij "Uitgebreid zoeken" kan je selecties maken. Zo kan je zoeken naar alle datasets.
Maar je kan ook zoeken naar alleen Gis bestanden (geodatasets).
Of naar Services (zowel WMS als WFS)
Of naar Statische kaarten (plaatjes, meestal in pdf-format)

Bij het onderdeel "Bladeren" kan je daarentegen zoeken naar datasets die horen bij 
bepaalde trefwoorden. Selecteer één of meerdere trefwoorden en je vindt de datasets die daarbij horen.
# 

Tekst bij het onderdeel "Over deze site":
# 

Het Geoportaal van de provincie Overijssel bevat datasets en beschrijvingen van datasets.
Deze worden gebruikt door de provincie om het beleid van de provincie te ondersteunen.
Zo worden ze gebruikt om kaarten van te maken of om analyses mee uit te voeren

Een groot aantal datasets wordt vrij beschikbaar gesteld, zodat ook anderen ervan gebruik kunnen maken.

Voor de geodatasets en de services heb je speciale software nodig. Hiervoor wordt de 
verzamelnaam "GIS" gebruikt (geografisch informatiesysteem). Een veel gebruikt GIS is het
systeem ARCGIS van het bedrijf ESRI. Maar er zijn ook "open source" GIS systemen.
Deze zijn veelal gratis. Een veelgebruikt gratis GIS is bijvoorbeeld QGIS.

De datasets zijn veelal te downloaden, zodat je ze met een GIS verder kan gebruiken.

Voor de andere kaarten (statische kaarten) heb je geen GIS nodig.
Dit zijn plaatjes, meestal in de vorm van een PDF.
Je kan dit soort bestanden bekijken met bijvoorbeeld Adobe reader.

Van een aantal datasets is de provincie Overijssel geen eigenaar. Meestal zijn hierbij dan beperkingen
voordat ze gedeeld mogen worden met anderen. Deze beperkingen staan ook in de beschrijving bij de datasets.

De provincie Overijssel streeft ernaar om de data en ook de omschrijving bij de data juist en actueel te houden.
Mocht je ondanks onze inspanningen toch onvolkomenheden tegenkomen, aarzel dan niet contact op ons op te nemen.

Heb je suggesties, tips of vragen, mail dan naar: beleidsinformatie@overijssel.nl
# 

Tekst bij contact:
# 

De informatie in het Geoportaal wordt beschikbaar gesteld door het team
Beleidsinformatie van de provincie Overijssel.

Heb je vragen, suggesties of tips, aarzel dan niet contact op te nemen.

Stuur je email naar: beleidsinformatie@overijssel.nl
#

**Comment by SandroNeumann** [comment]
De tekst bij de help is een pagina die nog gemaakt moet worden en dat issue staat onder 1.1.

**Comment by HermanAssink** [comment]
Overgezet naar 1.1 ivm de link met #172

**Comment by SandroNeumann** [comment]
De tekst voor help komt te vervallen, de tekst wordt wat op deze pagina staat:
http://gisopenbaar.overijssel.nl/geoportalwaf/help/Gebruikershandleiding%20geoportaal%20Overijssel_evdb.htm

**Comment by NicoEilers** [comment]
heeft ook te maken met #248

**Comment by gerardnienhuis** [comment]
werkt nu goed, issue kan gesloten
