### ISSUE TITLE
Statische kaarten archiveren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#264]
Een aantal statische kaarten is zo oud, dat we overwegen om die in een archief te plaatsen. Dat wordt bij geodatasets al gedaan (daar heet het GISBASIH). De knop om te archiveren moet ongeveer net zo gaan werken als de knop "prullenbak" bij de statische kaarten. De knop moet gaan heten "Archiveren" en moet, net als de prullenbak, alleen voor beheerders bruikbaar en zichtbaar zijn. Het archief moet ook, vergelijkbaar met de prullenbak, alleen voor beheerders zichtbaar en benaderbaar zijn. Beheerders moeten, net zo als nu bij de prullenbak, ook de status van "In archief" weer kunnen terugzetten naar een willekeurige andere status.

**Comment by gerardnienhuis** [comment]
![archiveren](https://cloud.githubusercontent.com/assets/9005444/17766627/5228936e-652c-11e6-85f2-09f3d70d118b.jpg)

**Comment by gerardnienhuis** [comment]
Merk op: als een kaart in het archief is geplaatst, dan moet het niet meer zichtbaar zijn in het interne of externe geoportaal. De werking wordt wat dat betreft vergelijkbaar met de "prullenbak".

Filteren op status "gearchiveerd" moet mogelijk zijn voor beheerders en plaatsen in en halen uit het archief ook alleen voor beheerders, vergelijkbaar met de werking van de prullenbak.

**Comment by gerardnienhuis** [comment]
Gaat dus net zo werken als bij de prullenbak. In gewone overzicht zie je alles wat in prullenbak zit niet. Dat moet ook zo werken voor iets wat in archief zit. Gewone leveranciers zien niet meer wat in het archief zit, ook niet in beheeromgeving geoportaal.

**Comment by gerardnienhuis** [comment]
Let op: in de prullenbak kan je ook dingen verwijderen. Dat is natuurlijk niet de bedoeling bij het archief.

Bij verwijderen naar prullenbak komt de mogelijkheid om iets definitief te verwijderen. Die keuzemogelijkheid moet niet worden geboden bij het verplaatsen naar het archief.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
Je schrijft dat de knop archiveren net als de knop prullenbak alleen voor beheerders zichtbaar en bruikbaar moet zijn. Maar dat is niet het geval bij de knop prullenbak. Die is voor iedereen te bedienen, maar leveranciers kunnen alleen hun eigen records in de prullenbak plaatsen en ze kunnen de records in de prullenbak vervolgens niet zien. Graag hoor ik of dat ook zo met archiveren moet gaan.

**Comment by gerardnienhuis** [comment]
Dat is goed opgemerkt. De bedoeling is  dat alleen de beheerders kunnen archiveren. Dat is dus anders dan bij de prullenbak, waar iedereen de spullen in kan zetten. Bedoeling is dat de knop archiveren alleen voor beheerders zichtbaar is. Bestanden die gearchiveerd zijn, die moeten ook niet meer zichtbaar zijn in het geoportaal. Merk op: ze zijn dus ook niet meer zichtbaar voor de leveranciers. De beheerders kunnen ze wel zien, als ze zoeken op de status "gearchiveerd".

**Comment by gerardnienhuis** [comment]
werkt goed, getest door bestanden van en naar archief te verplaatsen: issue kan gesloten
