### ISSUE TITLE
Datum statische kaarten aanpassen op basis van locatie

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#265]
Nu zijn statische kaarten niet te onderscheiden, wat creatiedatum betreft. Er zijn veel kaarten recentelijk aangepast, en die krijgen allemaal creatiedatum 2016. Dat komt omdat in de huidige software de creatiedatum niet zelf is aan te passen. Alleen in het veld locatie is de creatiedatum terug te vinden.

Voorstel is om op basis van de inhoud van het veld "locatie" de creatiedatum aan te passen. Niet voor alle statische kaarten, maar alleen die van 2015 en ouder. Die va 2016 zijn tenslotte al wel correct.

Let op: het invullen van het veld "locatie"  is handwerk, dus typfouten zijn goed mogelijk. 

Het idee is om alles waarvan nu staat dat de locatie is: k:\bab\archief\2000 de creatiedatum wordt gezet op 31-12-2000. Is de locatie nu: k:\bab\2002\0212344566 dan wordt de creatiedatum 31-12-2002

**Comment by SandroNeumann** [comment]
Je kunt het veld datum creatie gewoon aanpassen.

**Comment by gerardnienhuis** [comment]
blijkt niet meer nodig, issue kan gesloten
nb: alle statische kaarten hebben creatiedatum, alleen publicatiedatum ontbreekt soms
