### ISSUE TITLE
Openklikken Geoportaal zoeklijst niet altijd logisch

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#271]
Als je in het Geoportaal een lijst met zoekresultaten hebt, dan kan je 1 van de zoekresultaten openklappen. Is de hele lijst opengeklapt, dan kan je er 1 dichtklappen. Maar dat mechanisme werd niet altijd logisch en intuitief. Het is overgenomen van het huidige Geoportaal, waar dit soort problemen ook in zaten. Vooral het feit dat je soms iets als link ziet (onderstreept) terwijl er op klikken geen effect geeft, is onnodig verwarrend.

voorstel: situaties doorspreken, benoemen en nog betere keuzes maken voor gedrag van zoeklijst en open of dicht klikken.

![klikken_zoeklijst](https://cloud.githubusercontent.com/assets/9005444/17800855/cae3a34c-65e6-11e6-83c0-8287d2874717.jpg)

**Comment by gerardnienhuis** [comment]
Voorstel: als naam van bestand is onderstreept, zoals in bijgevoegd plaatje, dan bij er op klikken altijd metainfo laten zien

**Comment by SandroNeumann** [comment]
**@gerardnienhuis**: Is je opmerking van 14 september het enige wat hier moet gebeuren?

**Comment by gerardnienhuis** [comment]
@SandroNeumann : in het issue staat:

voorstel: situaties doorspreken, benoemen en nog betere keuzes maken voor gedrag van zoeklijst en open of dicht klikken.

Daarmee probeer ik aan te geven dat we de volledige lijst van gebeurtenissen moeten inventariseren en het wenselijke gedrag moeten bepalen. Dat is nooit goed opgepakt, ook niet bij de vorige versie van het Geoportaal. In de huidige versie komen hierdoor onlogische dingen voor, die een erfenis van het verleden zijn die een keer opgelost moeten worden. Een mockup hiervoor zou een idee kunnen zijn misschien?

**Comment by SandroNeumann** [comment]
Het lijkt me het handigst als jullie een dergelijke lijst maken wat nu niet logisch is en hoe het wel zou moeten zijn.

**Comment by gerardnienhuis** [comment]
Eerste voorstel:

1) uitgebreid zoeken en bladeren: default resultaten uitklappen
2) ondersteepte bestandsnaam in zoekresultaten lijst geeft zelfde effect als "meer informatie", je ziet meteen metainfo van het betreffende bestand
3) thumbnail aanklikken zorgt voor tonen van voorbeeldplaatje in apart scherm

**Comment by SandroNeumann** [comment]
Ik zou punt 2 afraden, want je krijgt dan dubbele functionaliteit bij het klikken. Het zorgt er voor dat het zowel open of dicht klapt als dat de metadata pagina geopend wordt. Dat hebben we eerder gehad en werd als niet prettig ervaren. De bestandsnaam niet laten onderstrepen zou een alternatief zijn.

**Comment by gerardnienhuis** [comment]
is prima, dan wordt het voorstel:

1.uitgebreid zoeken en bladeren: default resultaten uitklappen
2.ondersteepte bestandsnaam in zoekresultaten niet meer onderstreept maken
3.thumbnail aanklikken zorgt voor tonen van voorbeeldplaatje in apart scherm

**Comment by gerardnienhuis** [comment]
2 van de 3 wensen werken nu goed:

goed werkt:

1.uitgebreid zoeken en bladeren: default resultaten uitklappen
2.ondersteepte bestandsnaam in zoekresultaten niet meer onderstreept maken

niet goed werkt:
3.thumbnail aanklikken zorgt voor tonen van voorbeeldplaatje in apart scherm

aanklikken van thumbnail geeft geen effect, muispointer verandert wel, als je op thumbnail gaat staan, maar klikken toont geen voorbeeldplaatje

(getest met IE, FF, Opera en Chrome, allemaal zelfde probleem)

**Comment by gerardnienhuis** [comment]
Merk op: probleem met "niet openklikken" als je op thumbnail klikt, dat speelt alleen op de homepagina.

Bij  "uitgebreid zoeken' en "bladeren" werkt het wel naar tevredenheid.

**Comment by gerardnienhuis** [comment]
werkt nu goed, issue kan gesloten
