### ISSUE TITLE
Wachtwoorden kwijt bij nieuwe versies is onhandig

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#273]
onhandig: steeds als versie wordt geupdate, dan is gebruiker
zijn wachtwoord kwijt. 

Kan er niet van te voren een backup van de
lijst met gebruikers en wachtwoorden worden gemaakt, die
meteen na installatie weer wordt gebruikt om in de nieuwe omgeving.

nu heb ik de testgroep zowel bij de laatste acceptatieversie als
bij de eerste productieversie moeten uitleggen wat ze moeten doen:
- wachtwoord vergeten
- naam email
- wachtwoord wijzingen
- dan pas inloggen

gebruikers wil ik hier niet mee lastig vallen: heeft men een wachtwoord dan moet dat niets
steeds te hoeven worden aangepast.

**Comment by NicoEilers** [comment]
Dit blijkt goed te werken, issue kan gesloten
