### ISSUE TITLE
Controle in rapport metadata geodata mbt CC-0 en download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#278]
Bij een aantal geodatasets is ontbreekt CC-0 en/of downloadable data vermelding.

De juiste info als download mag worden uitgevoerd moet beiden bevatten:

Gebruiksbeperkingen: Downloadable data
Overige beperkingen: http://creativecommons.org/publicdomain/mark/1.0/deed.nl

Wens is om in rapport voor Geodata 2 kolommen op te nemen:
1 met ja/nee als downloadable data er staat
1 met ja/mee als er staat: http://creativecommons.org/publicdomain/mark/1.0/deed.nl

Met filteren kan je dan als beheerder de betreffende geodata opzoeken en zo nodig aanpassen

**Comment by gerardnienhuis** [comment]
zie ook #235

**Comment by gerardnienhuis** [comment]
Wens is om 2 kolommen in de rapportage geodatasets toe te voegen:

De ene extra kolom heet: "Creative commons": 
de waarden in deze kolom zijn "ja"  of "nee"

De situatie "ja" geldt voor de aanwezigheid van 2 verschillende waarden:

http://creativecommons.org/publicdomain/mark/1.0/deed.nl
http://creativecommons.org/publicdomain/zero/1.0/deed.nl

Als dus 1 van beide stukjes tekst voorkomen, dan is "creative commons" de waarde "ja"
Komen geen van beide stukjes tekst voor, dan is de waarde hiervan dus "nee"

De andere extra kolom heet"downloadable data"
De waarden in deze kolom zijn ook weer "ja" of "nee".

Komt de tekst "downloadable data" voor dan is de waarde "ja", en anders "nee"

**Comment by robstek** [comment]
maak twee kolommen CC: CC_mark en CC_zero

**Comment by gerardnienhuis** [comment]
cc mark en zero nu apart in rapportage. Downloadable is niet apart aangegeven maar dat blijkt geen probleem in het gebruik. rapport is nu beter bruikbaar geworden, issue kan gesloten worden.
