### ISSUE TITLE
Voorbeeldplaatje in dataset metadata is niet correct dit blokeert het downloaden

### ISSUE THREAD

**Issue by NicoEilers** [IDgis/geoportaal-test#279]
Het blijkt dat tabellen in services kunnen worden opgenomen. Dat geeft problemen, bv bij de weergave van voorbeeldplaatjes (in stylesheet bij de WAT) en bij de downloadfunctionaliteit. 

Tabellen in services zouden niet moeten worden verwerkt.

nb: de meeste tabellen blijken NIET in services te zitten maar zijn wel zichtbaar in het portaal...

voorbeeld: Wandelroutes in Overijssel tabel

https://intern.geoportaaloverijssel.nl/metadata/dataset/00e25a39-58fa-485b-92b1-b93829d7a398

Deze tabel blijkt in een service opgenomen te zijn. Dat zou niet moeten gebeuren.
Ruimtelijk schema: Tekst tabel

Download werkt dus ook niet, zie foutmelding.

Je download B5_Wandelroutes van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  ExceptionReport: <?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://services.geodataoverijssel.nl:80/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException>
      java.lang.IllegalArgumentException: Requested bounding box contains wrongnumber of coordinates (should have 4): 1 Requested bounding box contains wrongnumber of coordinates (should have 4): 1 </ServiceException></ServiceExceptionReport>
Neem voor meer informatie contact op met Geoportaal Overijssel.

**Comment by copierrj** [comment]
Dit probleem blijkt een andere oorzaak te hebben: de url naar het voorbeeldplaatje is een incorrect WMS GetMap request.

**Comment by copierrj** [comment]
Het betreft hier een dataset waarbij de brondataset metadata geen voorbeeldplaatje bevat.  Bij het ontbreken van een voorbeeldplaatje genereert de publicatieomgeving een  GetMap url als voorbeeldbeeldplaatje. Dit gaat op dit moment mis.

Dit dataset heeft dus wel degelijk een geometrie kolom. De url die (na het fixen van de bug) als voorbeeldplaatje gebruikt zal gaan worden: 

http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wms?request=GetMap&service=WMS&SRS=EPSG:28992&CRS=EPSG:28992&bbox=180000,459000,270000,540000&width=600&height=662&format=image/png&styles=&layers=B5_Wandelroutes

Ter informatie: dit probleem treedt op dit moment op voor in totaal 29 datasets.
