### ISSUE TITLE
Metadata van geodatasets extern beschikbaar als "geoportaal extern" beschikbaar

### ISSUE THREAD

**Issue by NicoEilers** [IDgis/geoportaal-test#280]
conform offerte 19-8-16:

De GIS-Publicatieogeving moet ook metadata aanbieden voor niet gepubliceerde
datasets. Als het element use_limitation de tekst "Geoportaal extern" bevat, dan
moet de metadata van de betreffende dataset zowel via het interne als het externe
Geoportaal beschikbaar zijn. Is de tekst "Geoportaal extern" niet aanwezig, dan moet
de metadata wel in het interne Geoportaal maar niet in het externe Geoportaal
vindbaar zijn;
3. De GIS-Publicatieomgeving moet voor externe gebruikers alleen de metadata
aanbieden waarbij in het element use_limitation de tekst "Geoportaal extern" is
opgenomen.

**Comment by gerardnienhuis** [comment]
# werkt correct, issue kan gesloten

5 steekproeven:

# 

Enschede s-contouren vocl 6-25 m-mv
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/67b60c52-11e5-4f34-b41d-b8edc70dd81e
Data mag niet uitgeleverd worden
is nu correct, wel intern, niet extern metadata zichtbaar

# 

Bevolkingsontwikkeling in leeftijdscategorien tussen 2014 en 2030
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/a6ccff56-0ff0-4440-81bf-3805fcf43fe1
Gebruiksbeperkingen:  Data mag niet uitgeleverd worden 

is correct: geen downloadlink in zoekresultaten en ook niet bij DETAILS in stylesheet
metadata zichtbaar in intern

metadata in extern niet gevonden: zit in service mogelijk wel, tzt bij beheerfase oplossen

# 

Landelijke Fietsroutes tbv Omgevingsvisie
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/59b4a6e2-b3dd-4027-a1fb-37ad6c4244a8
Gebruiksbeperkingen:  Data mag niet uitgeleverd worden 
niet extern te gebruiken:
is nu correct, wel intern, niet extern metadata zichtbaar

# 

Landgoederen
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/ea54038c-4817-4600-8928-71f4a3cda1d3
Data mag alleen met verklaring uitgeleverd worden|Geoportaal extern

is nu correct: zowel intern als extern zichtbaar
geen download

# 

Bedrijven en instellingen
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/d89a3cba-041d-4900-824e-2bfcfc120970
Data mag alleen met verklaring uitgeleverd worden|Data mag niet uitgeleverd worden|Geoportaal extern
is nu correct: zowel intern als extern zichtbaar
geen download

#

**Comment by gerardnienhuis** [comment]
testen uitgevoerd met data die nieuw zijn: metainfo nieuw neergezet, lijkt goed te werken.
extra controle intern / extern: ziet er ook goed uit, issue kan gesloten

getest met statische kaarten: klopt ook

test intern/extern met willekeurige geodatasets:
klopt allemaal

Natura 2000 inrichtingsmaatregelen (lijnen)
Data mag niet uitgeleverd worden
Bestand mag alleen uitgeleverd worden na toestemming van Eenheid Natuur &amp; Milieu (dhr. H. Hams)
intern: correct zichtbaar
extern: niet gevonden
klopt

Leegstand gemeente Oldenzaal (buurten)
geen beperkingen|http://creativecommons.org/publicdomain/mark/1.0/deed.nl
Data mag niet uitgeleverd worden
intern: correct zichtbaar
extern: niet gevonden
klopt

Nationale Streekpaden
Niets uit deze publicatie mag worden verveelvoudigd en/of openbaar gemaakt worden d.m.v. druk, fotokopie, internet of op welke andere wijze ook, 
zonder voorafgaande schriftelijke toestemming van de Stichting Wandelplatform-LAW. De gegevens uit deze publicatie mogen niet worden doorgestuurd naar andere instanties. 
Niet te gebruiken voor navigatie
intern: correct zichtbaar
extern: niet gevonden
klopt

CASCO Noordoost Twente, nieuwe lijnelementen
geen beperking
Data mag alleen met verklaring uitgeleverd worden|Geoportaal extern
intern: correct zichtbaar
extern: correct zichtbaar
klopt

Krayenhoff kaart blad V en VIII - 1829
Data mag niet uitgeleverd worden|Geoportaal extern
intern: correct zichtbaar
extern: correct zichtbaar
klopt

Landelijke grondgebruikskartering Nederland 2003
no limitation on public access
Data mag alleen met verklaring uitgeleverd worden|Geoportaal extern
intern: correct zichtbaar
extern: correct zichtbaar
klopt
