### ISSUE TITLE
Bij metadata geodata onbreekt eigendom bij intellectueel eigendom

### ISSUE THREAD

**Issue by NicoEilers** [IDgis/geoportaal-test#281]
Het kan voorkomen dat datasets beschermd zijn. Dan staat in de metadata dat het intellectueel eigendom betreft (jurisiche) gebruiksrestricties en/of toegangsrestricties. Het woord "intellectueel" staat wel in de metadata bij DETAILS maar het woord "eigendom" ontbreekt.

nb: dat gaat wel goed bij statische kaarten

zie voorbeelden:

Naam statische kaart: Beheertypen in provinciaal bezit Saasveld Gammelke

(Juridische) toegangsrestricties: Intellectueel

Bestandsnaam: Hengelo infrastructuur in hoofdgroenstructuur

https://intern.geoportaaloverijssel.nl/metadata/dataset/574220de-2f37-4a3b-aa45-0181fc8789dd

Overige beperkingen: Alleen bedoeld voor presenatie in applas van Hengelo

(Juridische) gebruiksrestricties: Intellectueel

(Juridische) gebruiksrestricties: Niet toegankelijk

(Juridische) toegangsrestricties: Intellectueel

(Juridische) toegangsrestricties: Niet toegankelijk

(Juridische) toegangsrestricties: Anders
# 

Naam statische kaart: Beheertypen in provinciaal bezit Saasveld Gammelke

https://intern.geoportaaloverijssel.nl/metadata/dc/C246131E-1F5A-41B5-9319-9B29F632DBC1

Identificatie: C246131E-1F5A-41B5-9319-9B29F632DBC1

Locatie: K:\BAB\Geo-informatie\2015\150275

Onderwerp: Grenzen

Eigendomsrechten: Intellectueel eigendom

Gebruiksrestricties: Alleen voor intern gebruik

**Comment by gerardnienhuis** [comment]
lijkt bij statische kaarten goed te gaan, issue kan gesloten

nb: er staat nu bij details: Eigendomsrechten: Intellectueel eigendom
