### ISSUE TITLE
Downloadable data bepaalt intern of extern

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#283]
Zie offerte

**Comment by HermanAssink** [comment]
1. Wijziging van de regel wanneer een dataset vertrouwelijk is: Data mag alleen worden
   gedownload als het element use_limitation de tekst "Downloadable data" bevat. Is de
   tekst "Downloadable data" niet aanwezig, dan moet het niet mogelijk zijn de data te
   downloaden. Dit laatste betekent binnen de GIS-Publicatieomgeving dat de dataset
   vertrouwelijk is en daarom alleen in een beveiligde service mag worden aangeboden.

**Comment by HermanAssink** [comment]
@copierrj Moet de rapportage wat betreft "onterecht publiek" worden aangepast?
Kan André na deze aanpassing de huidige situatie met onterecht pubieke datasets nog steeds corrigeren?

**Comment by copierrj** [comment]
Nee, deze rapportage gebruikt al useLimitation = 'Downloadable data'.

**Comment by copierrj** [comment]
Om onterecht publieke data niet langer publiek te laten zijn is het noodzakelijk om de desbetreffende services opnieuw te publiceren. Hetzij na de vertrouwelijke data eerst (in staging) verwijderd te hebben uit deze services hetzij door de services te publiceren in de beveiligde omgeving.

Vanuit het perspectief van de publicatieomgeving veranderd er weinig met de implementatie van de nieuwe regels. Het is de provider die andere regels gaat hanteren om te bepalen of een dataset vertrouwelijk is of niet. Welke regels dit precies zijn is niet relevant voor de publicatieomgeving. 

De aanpassingen met betrekking tot het vertrouwelijk zijn van de metadata (useLimitation = 'Geoportaal extern') hebben slechts effect op het metadata endpoint wat de metadata aan het geoportaal levert.

**Comment by gerardnienhuis** [comment]
De eerste testen zien er veelbelovend uit: data die niet downloadbaar mag zijn is dat nu ook niet meer. er wordt nu ingezet op extra steekproeven om meer zekerheid hierover te krijgen.

**Comment by gerardnienhuis** [comment]
Na meer dan 25 nieuwe steekproeven blijkt dat e.e.a. nu wel goed werkt: de link naar download in zoekresultaten en ook de vermelding van download link bij DETAILS is alleen zichtbaar als het ook zichtbaar mag zijn: als het in een service zit, en als "downloadable data" aangegeven is.
Issue is goed opgelost en kan daarom gesloten.
