### ISSUE TITLE
voorbeeldplaatje statische kaarten in stylesheets

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#284]
van de bekende fileformaten een voorbeeldplaatje tonen in de stylesheet bij het onderdeel WAT
grootte: 150 dpi ,vergelijkbaar met geodatasets (de grote versie). Bij meerdere bijlagen alle voorbeeldplaatjes laten zien onder en/of naast elkaar. Zijn er meer dan 10 bijlagen, dan alleen de eerste 10 laten zien

**Comment by gerardnienhuis** [comment]
zie #160

**Comment by SandroNeumann** [comment]
is duplicaat van #160

**Comment by gerardnienhuis** [comment]
zelfde als #160 en daarom dit issue gesloten
