### ISSUE TITLE
In rapportage opnemen dat een xml aanwezig is die wijst naar brondataset die afwezig is

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#285]
Het kan voorkomen dat in het beheren van xmls wordt vergeten om de xml weg te halen als de dataset is verwijderd of is verplaatst naar de historie. Wens is dat in een rapport zichtbaar wordt bij welke xml's dit voorkomt. Rapport van geodatasets kan hiervoor worden gebruikt (extra kolom toevoegen, gaat heten: fouten)

**Comment by copierrj** [comment]
Word hier bedoeld: metadata aanwezig met een referentie naar tabel / geotiff die niet gevonden kan worden? 

Zo ja, dit is bij de meeste rasterdata het geval. Maar dit komt in dit geval niet doordat men vergeten is metadata te verwijderen maar dit komt omdat de tiff bestanden slechts tijdelijk beschikbaar zijn ivm benodigde schrijfruimte.

**Comment by copierrj** [comment]
@gerardnienhuis: zou je dit issue willen verduidelijken?

**Comment by gerardnienhuis** [comment]
Wat wij hebben als beheerders is een map met xml's. Als wij een dataset verwijderen willen uit het Geoportaal dan is dat een foutgevoelig proces. Soms wordt vergeten een xml te verwijderen. Dan heb je dus wel in het Geoportaal een datasets, maar de achterliggende xml is afwezig: dat wil ik in een rapport terugzien.

**Comment by gerardnienhuis** [comment]
wens is om in rapport 1 kolom extra te krijgen, bronmetadata aanwezig

kan zijn: ja.. dan niets aan de hand
kan zijn: nee.. dan is de xml wel verwijderd, maar staat data nog in service

**Comment by robstek** [comment]
zie #349

**Comment by robstek** [comment]
er kunnen fout situaties optreden bij rasters, dit is gevolg van de huidige werkwijze

een andere issue (#...) gaat rasters en vectoren scheiden

**Comment by gerardnienhuis** [comment]
bronmetadata aanwezig kolom is aanwezig en blijkt goed te werken: gekeken wordt naar de geoweb xml map, is ook correct. issue kan gesloten
