### ISSUE TITLE
Data in beveiligde service maar toch extern beschikbaar volgens rapport Geodata.

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#286]
In het rapport van Geodata wordt bij 1 dataset aangegeven dat de data onterecht extern beschikbaar is.
Maar de service waarin deze dataset zit, die is beveiligd (volgens dat rapport).

Dit lijkt niet te kloppen

**service = beveiligd, maar toch "onterecht publiek = ja"**

1253  
a8d8d8f0-3495-4d23-a2dc-50231a6bf092  
Kadastrale percelenkaart (tijdelijk)  
B0.KAD_vlak_joined (b0/b02) 
8856f882-3082-4335-a892-246210358c5f  
19cab2fd-b85a-4066-868d-42c08f0ccf7a  
Data mag niet uitgeleverd worden|Geoportaal extern
Ja  
Beveiligd_geen_wms_wfs:Kadastrale_percelenkaart_tijdelijk|B02_topografie:Kadastrale_percelenkaart_tijdelijk

In alle andere gevallen lijkt het wel correct in het rapport te staan:

**service = beveiligd en "onterecht publiek = nee"**

bijvoorbeeld:

410 
c5473ad4-7cb1-4341-be5a-c51a98f7538e  
Ligplaatsen recreatievaart langs provinciale vaarwegen  B2.ligplaatsen_prov_vaarweg_arc (b2\b23)  
{F7FF2540-4985-4563-A691-038B2D593673}  9dc1c9fe-7448-493d-b008-31ce0cde13df  
Data mag niet uitgeleverd worden  
Nee 
Beveiligd_geen_wms_wfs:B2_Ligplaatsen_recreatievaart_langs_provinciale_vaarwegen

**Comment by copierrj** [comment]
In het door mij zojuist opgevraagde rapport (op productie) staat voor dit dataset in de kolom 'feitelijk_incorrect_publiek' de waarde 'Nee'.

Voor de zekerheid heb ik dit alles in de database gechecked en het genoemde dataset zit inderdaad (enkel) in een beveiligde service. Mogen we aannemen dat dit issue niet langer actueel is?

**Comment by gerardnienhuis** [comment]
Mijn voorstel is om dit issue gewoon open te laten staan. Als we dan 1.1.0 in productie hebben, dan controleren we meteen of dit nog voorkomt. Gebruikers gaan hier geen last van hebben, mogelijk alleen beheerders. Ik verwacht zelf ook dat het probleem in 1.1.0 niet meer te vinden is, maar wil graag de laatste controle dan doen.

**Comment by gerardnienhuis** [comment]
Dit probleem lijkt niet meer voor te komen. Getest vandaag met productieversie. Issue kan gesloten worden.
