### ISSUE TITLE
Error bekijken  en download metadata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#289]
Leegstand van kantoren, verkooppunten etc. op basis van buurtindeling (26-04-2016, Provincie Overijssel)

er is wel metainfo aanwezig, samenvatting is bijvoorbeeld:
Leegstand gegevens van kantoren groter dan 500 m2, verkooppunten en prognoses tussen 2012 en 2030 van 
vrijkomende agrarische gebouwen in het buitengebied. De leegstandgegevens zijn verzameld op basis van 
de buurtindeling. Buurten vormen het laagste regionaal niveau en zijn afgebakend vanuit bebouwingsoogpunt
 of sociaal-economische structuur. Meer informatie over attributen in dit bestand staat bij het onderdeel 
“uitgevoerde bewerkingen”.

geeft fout bij metadata bekijken:
 https://acc-www.geoportaaloverijssel.nl/metadata/dataset/776d3686-b66c-4fcc-91a9-f0986e70262e
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

geeft ook fout bij download:
404 Niet gevonden
Het gevraagde dataset (met id '776d3686-b66c-4fcc-91a9-f0986e70262e') bestaat niet.

**Comment by gerardnienhuis** [comment]
opvallend is dat er 3x zelfde soort data en metadata set mbt leegstand aanwezig is, waarvan 2 met zelfde thumbnail en 1 andere thumbnail.

**Comment by gerardnienhuis** [comment]
problemen ook gevonden bij:

Boomregister Overijssel (29-07-2016, NEO, Netherlands Geomatics & Earth Observation B.V.)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/07d7d345-ee2a-9a75-6e6e-68cf867717ad

Topografische kaart 1:25000 (18-07-2016, Kadaster)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/6673048d-eea8-42f6-a805-35098c562c05

Topografische kaart 1:50000 van geheel Nederland (22-04-2016, Kadaster)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/649600bf-0df7-4d99-8bc3-0d40a0cbad88

**Comment by gerardnienhuis** [comment]
nog meer gevonden:

Afgekeurde primaire waterkeringen (HWBP) (07-04-2015, Waterschap Groot Salland)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/6ad70d4a-2a7d-499d-9775-a644459b843f

heeft niks of niet altijd met rasters te maken, wel goed gaat: 

Bestandsnaam: Gemiddeld laagste grondwaterstand t.o.v het locale maaiveld.
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/a04249f7-c7ae-4aa1-91f1-1591c1c5d305.xml

**Comment by copierrj** [comment]
Oorzaak gevonden: deze datasets (in totaal 25 stuks) staan wel in de database van de publicatieomgeving maar zijn niet beschikbaar bij de provider component bij Overijssel. Hierdoor is de upgrade voor deze datasets niet correct uitgevoerd. Dit zullen we met de hand oplossen.

**Comment by copierrj** [comment]
De publicatieomgeving database op acceptatie is met de hand bijgewerkt. Als we deze versie gaan uitrollen naar productie zullen we dezelfde database fix ook hier uitvoeren:

``` sql
update publisher.source_dataset_version sdv
set metadata_confidential = false
where sdv.id = (
    select max(id)
    from publisher.source_dataset_version
    where source_dataset_id = sdv.source_dataset_id)
and metadata_confidential 
and exists (
    select * from publisher.source_dataset_metadata
    where source_dataset_id = sdv.source_dataset_id
    and xpath(
        '//gmd:useLimitation/gco:CharacterString/text()', 
        convert_from(document, 'UTF-8')::xml, 
        ARRAY[
            ARRAY['gmd', 'http://www.isotc211.org/2005/gmd'],
            ARRAY['gco', 'http://www.isotc211.org/2005/gco']])::text[]
        @> ARRAY['Geoportaal extern']
)
```

**Comment by HermanAssink** [comment]
Moet getest worden op acc.

**Comment by gerardnienhuis** [comment]
probleem blijkt bij bovenstaande gevallen opgelost en is ook bij meerdere steekproeven bij andere geodatasets niet meer teruggevonden. Issue kan gesloten
