### ISSUE TITLE
Download fout maar metainfo wel goed

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#290]
Nationale landschappen TEST (19-08-2016, Provincie Overijssel)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/fa93d53b-d3ee-a99f-5691-18179859b120

metainfo bekijken gaat goed, maar download gaat fout

500 Interne server fout

Er ging iets mis bij het verwerken van het verzoek.
Foutcode: @71d8o5ho2

download als SHP gaat fout:
https://acc-download.geoportaaloverijssel.nl/download/fa93d53b-d3ee-a99f-5691-18179859b120

zit ook geen wms wfs urls in metadata bij DETAILS

**Comment by gerardnienhuis** [comment]
Boomregister Overijssel (29-07-2016, NEO, Netherlands Geomatics & Earth Observation B.V.)
metadata bekijken gaat ook fout
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/07d7d345-ee2a-9a75-6e6e-68cf867717ad

Natuurbeheerplan Overijssel 2016 (12-07-2016, Provincie Overijssel)
metadata bekijken en download gaat ook fout
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/5561d503-bd03-4222-b3aa-01563fe6021e
404 Niet gevonden
Het gevraagde dataset (met id '5561d503-bd03-4222-b3aa-01563fe6021e') bestaat niet.

**Comment by gerardnienhuis** [comment]
mogelijk zelfde als #289

**Comment by copierrj** [comment]
Oorzaak: deze datasets zijn volgens de metadata 'downloadable' maar zijn (nog) niet gepubliceerd. De download link in het geoportaal werkt hierdoor niet.

**Comment by copierrj** [comment]
@SandroNeumann, mogelijke oplossingsrichting: de publicatieomgeving levert in het WebDAV metadata endpoint een 'published' attribuut.

**Comment by gerardnienhuis** [comment]
heeft dit er ook mee te maken of is het apart issue:

Rotondes test 6 in provinciale wegen: wel download link bij zoekresultaten maar niet in service

metadatalink:
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/d3fb9e54-4f84-5555-d185-0d5600caba33
download link:
https://acc-download.geoportaaloverijssel.nl/download/d3fb9e54-4f84-5555-d185-0d5600caba33

Bestand heeft in de lijst wel download link, maar download werkt niet
logisch: bestand zit niet in een service

download kan wel gestart worden, maar dan volgt foutmelding

500 Interne server fout

Er ging iets mis bij het verwerken van het verzoek.
Foutcode: @71da532ml

**Comment by SandroNeumann** [comment]
Dat heeft dezelfde oorzaak.

**Comment by gerardnienhuis** [comment]
probleem blijkt opgelost, lijkt op #283 
geen verdere problemen gevonden, issue kan gesloten
