### ISSUE TITLE
Raster bevat download link in metadata bij DETAILS

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#291]
Bestandsnaam: Topografische kaart 1:50000 van geheel Nederland
Ruimtelijk schema: Grid
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/649600bf-0df7-4d99-8bc3-0d40a0cbad88

Er zit wel download link in metainfo, dat hoort niet het geval te zijn.

Download: https://acc-download.geoportaaloverijssel.nl/download/649600bf-0df7-4d99-8bc3-0d40a0cbad88
OGC:WFS: http://acc-services.geodataoverijssel.nl:80/geoserver/Raster/wfs
OGC:WMS: http://acc-services.geodataoverijssel.nl:80/geoserver/Raster/wms

download kan uitgevoerd worden, download scherm geeft melding dat download wordt uitgevoerd

Topografische kaart 1:50000 van geheel Nederland

Je download verzoek is in goede orde ontvangen. De download wordt nu voor je klaargezet.

Het bestand is: Topografische kaart 1:50000 van geheel Nederland
Het formaat is: SHP
E-mail adres is: g.nienhuis@overijssel.nl
Je krijgt zo snel mogelijk een e-mail met een download-link.
Via deze link kun je de download van het bestand uitvoeren. 
Deze link blijft 24 uur bruikbaar.
Je kunt nu dit scherm sluiten.

maar dat kan helemaal niet bij een raster... er komt dan ook geen email met download link

**Comment by SandroNeumann** [comment]
Zelfde issue als #269

**Comment by gerardnienhuis** [comment]
Geldt voor meerdere rasters. Nog 1 gevonden:

Bestandsnaam: maximale waterdiepte dijkring 10 breslocatie IJsselmuiden
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/6182f5ce-4247-43fb-b11d-ed22bf39a025
Ruimtelijk schema: Grid

heeft download link: deze moet niet zichtbaar zijn bij rasters in de stylesheet

Download: https://acc-download.geoportaaloverijssel.nl/download/6182f5ce-4247-43fb-b11d-ed22bf39a025
OGC:WFS: http://acc-services.geodataoverijssel.nl:80/geoserver/Raster/wfs
OGC:WMS: http://acc-services.geodataoverijssel.nl:80/geoserver/Raster/wms

**Comment by gerardnienhuis** [comment]
bij bovenstaande 2 voorbeelden lijkt probleem opgelost. er worden meer steekproeven uitgevoerd om te kijken of dit ook bij andere datasets nu goed werkt.

**Comment by gerardnienhuis** [comment]
meer dan 10 steekproeven laten zien dat issue opgelost is. issue kan gesloten.
