### ISSUE TITLE
Download link aanwezig maar service afwezig

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#292]
In zoekresultaten is "download" zichtbaar, maar geodata zit niet in service. Downloaden geeft dan ook foutmelding:

Electronische meetpunten (23-02-2015, Provincie Overijssel)
metainfo: https://acc-www.geoportaaloverijssel.nl/metadata/dataset/c5b38d81-43c3-5935-382f-a2a0dcd39f26
download: https://acc-download.geoportaaloverijssel.nl/download/c5b38d81-43c3-5935-382f-a2a0dcd39f26

maar download moet onmogelijk gemaakt worden. data zit niet in service

500 Interne server fout
Er ging iets mis bij het verwerken van het verzoek.
Foutcode: @71db8a4dc

**Comment by HermanAssink** [comment]
Download link bij Koop- en huurwoningen per buurt https://test-www.geoportaaloverijssel.nl:4443/metadata/dataset/fc5a245f-abe1-4d4f-8a86-27c1f6d74461
is wel aanwezig maar geeft "Not found"

**Comment by SandroNeumann** [comment]
De link is niet volledig. Ander issue, zie #298.

**Comment by gerardnienhuis** [comment]
probleem met
Electronische meetpunten (23-02-2015, Provincie Overijssel)
 metainfo: https://acc-www.geoportaaloverijssel.nl/metadata/dataset/c5b38d81-43c3-5935-382f-a2a0dcd39f26
is opgelost

**Comment by gerardnienhuis** [comment]
Aantal koop- en huurwoningen per buurt
lijkt ook nu goed te gaan: downloadlink aanwezig en lijkt te werken

Aantal koop- en huurwoningen per buurt (28-04-2014, Provincie Overijssel) 
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/fc5a245f-abe1-4d4f-8a86-27c1f6d74461
https://acc-intern-download.geoportaaloverijssel.nl/download/fc5a245f-abe1-4d4f-8a86-27c1f6d74461

Je download verzoek is in goede orde ontvangen. De download wordt nu voor je klaargezet.
Het bestand is: Aantal koop- en huurwoningen per buurt
Het formaat is: SHP
E-mail adres is: g.nienhuis@overijssel.nl

**Comment by gerardnienhuis** [comment]
download is ook succesvol verlopen, issue kan gesloten
