### ISSUE TITLE
Naam bijlage direct zichtbaar in stylesheet statische kaart

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#293]
Nu worden de urls van de bijlagen getoond in de stylesheet: dat geeft bij meerdere bijlagen een onoverzichtelijk beeld. Dat is bij het eerste scherm van de stylesheet, onderdeel WAT. 

Wens is om de naam van de bijlage, zoals die is geleverd, te laten zien en dan te laten doorlinken naar die lange url zodat hierdoor na klikken op de bijlage de bijlage wel gewoon, zoals nu ook, wordt getoond.

In het plaatje staan de namen met rood omcirkeld, zoals die zijn aangeleverd. 

Nb: in het onderdeel DETAILS van de statische kaarten kunnen dan de urls volledig worden weergegeven, zoals ook in de stylesheet van services nu al is uitgewerkt. Dus ook aanklikbaar, vergelijkbaar bij services.
Bij de services staan bij de WAT ook de logische namen en in de DETAILS de urls volledig uitgeschreven. 
..

![naam_bijlage_in_stylesheet](https://cloud.githubusercontent.com/assets/9005444/18580105/dcbd031e-7bf9-11e6-876b-4b087f7582a8.jpg)

**Comment by NicoEilers** [comment]
kan dit nog meegenomen worden in 1.1.3.?

**Comment by gerardnienhuis** [comment]
werkt goed, getest met meerdere statische kaarten, zoals
https://acc-www.geoportaaloverijssel.nl/metadata/dc/BA7A7D80-2C5D-4C35-B927-769782B29D75
pdf naam staat nu veel beter in de stylesheet, meer overzichtelijk en pdf-naam nu goed te onderscheiden.

issue kan gesloten.
