### ISSUE TITLE
Thumbnail in zoekresultaten opeens afwezig

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#295]
De thumbnail die zichtbaar was bij de zoekresultaten van de dataset gemeentegrenzen, die is opeens afwezig. Deze is altijd wel zichtbaar geweest, zowel in stylesheet bij WAT als bij zoekresultaten.

Het plaatje is:
http://acc-metadata.geodataoverijssel.nl/attachment/2518/gemgrens.jpg

de dataset is: Nieuwe Gemeentegrenzen Overijssel (vlakken) (15-09-2016, Provincie Overijssel)
link naar metadata:
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/9a23e820-5124-44d7-9003-1f701c1014a2

zie plaatje hieronder:

![thumbnail_afwezig](https://cloud.githubusercontent.com/assets/9005444/18580949/aa84ab9a-7bfe-11e6-9733-46534e3dc77f.jpg)

**Comment by gerardnienhuis** [comment]
5 minuten laten blijkt thumbnail er wel weer te zijn.. wat is hier aan de hand?

**Comment by SandroNeumann** [comment]
Dit is niet te reproduceren. Oppakken als het zich weer voordoet.

**Comment by gerardnienhuis** [comment]
blijkt niet meer voor te komen, issue kan gesloten
