### ISSUE TITLE
Urls in stylesheet bij statische kaarten altijd aanklikbaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#296]
Nu kan je bij locatie bij de statische kaarten een url opgeven die aanklikbaar is. Wens is om dat bij alle relevante velden mogelijk te maken:

Bij WAT: Kenmerk: http://www.nu.nl
Bij WIE: Eindverantwoordelijke: http://www.nu.nl
Bij DETAILS: Bron: http://www.nu.nl

Nu werkt alleen de doorlink vanaf:
Locatie: http://www.nu.nl (ook bij DETAILS)

**Comment by NicoEilers** [comment]
zie #123

**Comment by gerardnienhuis** [comment]
werkt goed, alle urls zijn aanklikbaar en gaan naar juiste website, issue kan gesloten
