### ISSUE TITLE
Metadata pagina leeg / wordt niet opgemaakt

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#297]
Doet zich voor bij "Aangewezen Natura 2000-gebieden in Niedersachsen en Nordrhein-Westfalen" : 
https://test-www.geoportaaloverijssel.nl:4443/metadata/data
set/0c0f64af-107f-8d30-3882-f9147865bc50

**Comment by gerardnienhuis** [comment]
Geen probleem zichtbaar op acceptatie:
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/b4d0ffe7-88a1-41d9-af33-36435ec2fe07
is opgemaakt en goed zichtbaar.

Steekproeven van andere datasets (geodata) laten ook geen problemen zien met opmaak. 

Incidenteel probleem?

Wat mij betreft kan issue gesloten.
