### ISSUE TITLE
Genereren download link inclusief poortnummer

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#298]
Het genereren van de download link houdt geen rekening met een niet-standaard poortnummer.

**Comment by gerardnienhuis** [comment]
wat kan ik hier als gebruiker aan testen?

**Comment by copierrj** [comment]
Hooguit constateren dat de download url in de metadata (detail tab) het doet. Dit probleem speelde enkel op onze testomgeving.

**Comment by gerardnienhuis** [comment]
issue #283 is correct opgelost: daarmee kan m.i. ook dit issue gesloten worden.
