### ISSUE TITLE
Dubbele vermelding dataset met en zonder download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#299]
Volgens mij gaat er iets niet goed als een dataset wordt toegevoegd (door kopie neer te zetten) van een dataset die al in een service zit. 

Bijvoorbeeld: 
Test1Gemeentegrenzen Overijssel (lijnen)Test1 (19-09-2016, Provincie Overijssel)
hiervan zijn bij de zoekresultaten 2 records te zien, met 2x metadata:
 https://acc-www.geoportaaloverijssel.nl/metadata/dataset/0918da6c-ffeb-4cec-8668-8b857b5f1cf8
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/44171e3b-9cf8-4ad8-8246-ae66455f1151

een van deze heeft ook een dowloadlink
download:
https://acc-download.geoportaaloverijssel.nl/download/0918da6c-ffeb-4cec-8668-8b857b5f1cf8

Dat is wel heel verwarrend voor gebruikers. Is die een bug en hoe kunnen beheerders dit voorkomen? Is er een work-around?

**Comment by HermanAssink** [comment]
Gerard, Dit lijkt me geen bug. Er staan twee metadata bestanden in de map bij Overijssel met (onbedoeld) dezelfde gegevens. GeoPublisher en Geoportal behandelen beide metadata onafhankelijk van elkaar. Beheerders kunnen hierop controleren door met de rapportage na te gaan of eenzelfde naam en/of UUID vaker voorkomt (kan met Excel).

**Comment by gerardnienhuis** [comment]
klopt: hebben wij ook ontdekt. excuses voor eventuele verwarring. Beheerders hebben in het verleden nooit op deze manier met de alternatieve titel rekening hoeven te houden. Dat moet nu dus wel, anders krijg je dit soort verschijnselen. Raadsel is opgelost en is dus geen bug. Issue kan gesloten.
