### ISSUE TITLE
Metadata met verwijzing naar schijf ipv Oracle

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#3]
Vraag: bij de luchtfoto van Overijssel, 2013, resolutie 25 x 25 cm
Alternatieve titel: 2013_Totaalmozaiek_overijssel_25cm.ecw (N:\luchtfoto2013\

Deze data staat niet in Oracle, maar op schijf (N). Maar de metainfo moet wel beschikbaar zijn.
Omdat datasets door de publicatieomgeving worden gecontroleerd op locatie in Oracle, via alternatieve titel, even voor zekerheid vraag hierbij. Ook data die niet in Oracle staat heeft soms metadata, en die metadata moet wel in het Geoportaal zichtbaar zijn. Zie voorbeeld: http://gisintra.ovr.prv/geoportal/rest/document?id=%7B48CA1A1D-B343-4133-A1BE-D863AA78D0D4%7D

**Comment by HermanAssink** [comment]
Ook bij rasterdata wordt de alternatieve titel gebruikt om de naam van het rasterbestand aan te geven. De metadata van deze rasterdata wordt door de GIS-publicatieomgeving om dezelfde manier via een WebDAV map ontsloten als die van data in Oracle.

**Comment by gerardnienhuis** [comment]
Wij hebben als wens om een deel van de alternatieve titel te gebruiken als verwijzing naar de locatie (intern provincie Overijssel): dat heeft het voordeel voor ons, dat we niet bij rasters hoeven te zoeken: nu is de hele alternatieve titel gebruikt (zodat locaties als B0, B1 enz niet meer toegestaan zijn). Voorstel is om te overwegen om alleen string tot aan ( te gebruiken. Dan kan er tussen haakjes (B0 of nog andere tekst) worden opgenomen. Dit betreft een mogelijke uitbreiding van de werking van de publicatieomgeving maar voorkomt dat belangrijke informatie nu moet worden verwijderd. Bovendien is de alternatieve titel dan veel meer uniform. nb: alleen als in metadata type "raster" is opgenomen natuurlijk.

**Comment by gerardnienhuis** [comment]
Dit gaat over de werking van de publicatieomgeving. Daarom opgenomen bij issues van publicatieomgeving. 

https://github.com/IDgis/geo-publisher/issues/754

Kan op deze plaats worden gesloten.

**Comment by gerardnienhuis** [comment]
Dit is nu nog niet opgelost. Eerste voorstel was om te zorgen dat ook alternatieve titel kan worden gebruikt bij rasters (zie tekst hiervoor bij dit issue).

**Comment by HermanAssink** [comment]
GIS-Publicatieomgeving gebruikt inderdaad voor metadata in de gegevensbron "Overijssel rasterdata" de alternatieve titel als naam van het rasterbestand. Daarmee is het toch opgelost? Trouwens, i.v.m. beperkte schijfruimte heeft Overijssel ervoor gekozen om rasterdata niet op schijf te laten staan. Dit geeft meldingen in de GIS-Publicatieomgeving.

**Comment by gerardnienhuis** [comment]
Betreft wens voor werking publicatieomgeving. Wordt hier gesloten en op lijst van wensen mbt publicatieomgeving gezet
