### ISSUE TITLE
Doorlink vanaf extern geoportaal laat bij services interne stylesheet zien

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#300]
Als je in het externe geoportaal bij het onderdeel WAT doorklikt naar een laag die in de service zit, dan wordt de metainfo van die laag correct getoond. Correcte metainfo. Maar de stylesheet is verkeerd.

Als je vanaf het externe geoportaal doorlinkt, dan moet je van de laag de externe stylesheet zien
Als je vanaf het interne geoportaal doorlinkt, dan moet je van de laag de interne stylesheet zien

Bij doorlinken vanaf extern gaat dit nu fout. Niet productie-belemmerend, dus in versie 1.2. oppakken.

**Comment by copierrj** [comment]
@SandroNeumann: hoe zet het geoportaal dit request door naar de publicatieomgeving?

**Comment by SandroNeumann** [comment]
De laag van een service linkt direct door naar de metadata van de publicatieomgeving.

Voorbeeld: https://www.geoportaaloverijssel.nl/metadata/service/aa894124-65c0-4891-9f95-b08a7fb0bd2e
Laag: B4_Afzetmogelijkheden_warmte_in_stads-_en_blokverwarming
Url: http://metadata.geodataoverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50.xml

**Comment by copierrj** [comment]
@SandroNeumann:

Als we voor een request afkomstig van het netwerk van Overijssel hier toch de externe stylesheet willen tonen zijn denk ik twee oplossingsrichtingen mogelijk:

- het request in het geoportaal proxy-en.
- in het metadata endpoint van de publicatieomgeving een request parameter toevoegen waarmee aangegeven kan worden dat de externe stylesheet gewenst is.

De eerste optie zou mijn voorkeur hebben. Want: raakt slechts een enkel component.

**Comment by SandroNeumann** [comment]
Je zou i.p.v:
https://metadata.geodataoverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50.xml

Deze twee url's (afhankelijk van intern of extern) in de XML kunnen schrijven:
https://www.geoportaaloverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50
https://intern.geoportaaloverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50

Daar wordt de publisher metadata al geproxied.

**Comment by copierrj** [comment]
Is het te doen om aan de kant van het geoportaal de service metadata xml te herschrijven zodat een van deze twee urls gebruikt worden ipv de directe link naar de publicatieomgeving?

**Comment by SandroNeumann** [comment]
Dat kan ook inderdaad.

**Comment by gerardnienhuis** [comment]
Dit werkt nu wel goed. getest vanaf extern geoportaal: service bekeken en daarna laag bekeken, door te klikken bij de WAT op de url van die laag: geeft beide nu stylesheet voor extern portaal. Issue kan gesloten
