### ISSUE TITLE
Help tekst tijdelijk vervangen voor pdf

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#302]
De huidige helptekst van het geoportaal komt uit bij de helptekst over het oude geoportaal. Dat is niet logisch. Voor de opening van versie 1.1.0 wordt voorgesteld om hiervoor een pdf in de plaats te stellen, totdat een aparte pagina met (dezelfde) helptekst kan worden neergezet.

De helptekst kan hetzelfde zijn voor de onderdelen "home", "uitgebreid zoeken" en "bladeren". zie plaatje en pdf

![help_tekst](https://cloud.githubusercontent.com/assets/9005444/18701827/0079afda-7fdf-11e6-8f36-29d0fa5a6253.jpg)

[Handleiding_Geoportaal_Overijssel.pdf](https://github.com/IDgis/geoportaal-test/files/484399/Handleiding_Geoportaal_Overijssel.pdf)

**Comment by HermanAssink** [comment]
HELP wordt voorlopig door Gerard als html met de huidige url ontsloten

**Comment by gerardnienhuis** [comment]
wordt neergezet als html onder exact zelfde huidige naam (dus inclusief spaties ipv %20)

**Comment by gerardnienhuis** [comment]
is gelukt, en blijkt goed te werken, issue kan gesloten
