### ISSUE TITLE
Metadata raster met veel te veel bonnebladen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#303]
In de service raster is de laag bonnebladen opgenomen. Op zich correct. Alleen duurt het opvragen van de metainfo van deze service ongewoon lang: 20 seconden of meer

https://acc-www.geoportaaloverijssel.nl/metadata/service/8c7f69e0-c823-4c69-a0e1-7caacea1c950

Het blijkt dat die laag bonnebladen er meer dan 50 (?) keer in staat, onder elkaar. Dat kan niet juist zijn.
Wat is hier aan de hand?

![teveel bonnebladen in raster metadata](https://cloud.githubusercontent.com/assets/9005444/18702809/ac7d6cf0-7fe3-11e6-92ab-41ff536a56cc.jpg)

**Comment by copierrj** [comment]
Ook het dataset id is bij iedere vermelding hetzelfde. Lijkt erop dat er iets fout gaat bij het genereren van de service metadata in de publicatieomgeving.

**Comment by gerardnienhuis** [comment]
dus niet de stylesheet die deze interpretatie doet, maar al eerder niet helemaal goed bij de publicatieomgeving? teveel lagen in de service?

**Comment by copierrj** [comment]
De fout zit in de xml zoals die door het portaal geleverd word en niet in de stylesheet. In de door de publicatieomgeving aangeleverde xml blijkt het probleem niet voor te komen: https://acc-metadata.geodataoverijssel.nl/metadata/service/8c7f69e0-c823-4c69-a0e1-7caacea1c950.xml

**Comment by gerardnienhuis** [comment]
wat is dan de oplossing en hoe kan ik dat als gebruiker testen?

**Comment by copierrj** [comment]
Het probleem moet nog verder uitgezocht worden. We hebben op dit moment enkel uitgesloten dat de oorzaak zit in de publicatieomgeving of in de stylesheet.

**Comment by SandroNeumann** [comment]
Het probleem doet zich alleen voor wanneer de GeoPublisher-trusted header niet op 1 staat.

**Comment by SandroNeumann** [comment]
Ook het geval bij de service B22_wegen:
https://www.geoportaaloverijssel.nl/metadata/service/81852c07-7522-44c4-8bb7-5d65244d8ee5

Bij de lagen:
- n34_kunstwerk_vlakken
- n34_tunnels_punten

**Comment by gerardnienhuis** [comment]
lijkt ook voor te komen in de metadata mbt strooiroutes:

service: wegen
https://www.geoportaaloverijssel.nl/metadata/service/1f3c4554-8ff4-4ae6-b1a8-3c8ba3dc4dc0

daarin komt voor:
•B2_Strooiroutes_preventief_ProvincieB2_Strooiroutes_preventief_Provincie
•B2_Strooiroutes_preventief_ProvincieB2_Strooiroutes_preventief_Provincie

in publicatieomgeving gecontroleerd, daarin staat alleen:
•B2_Strooiroutes_preventief_Provincie

**Comment by gerardnienhuis** [comment]
het opmerkelijke is, dat het verschijnsel WEL optreedt bij het externe Geoportaal, maar NIET bij het intern Geoportaal. Dezelfde services zijn onderzocht, en bij het interne Geoportaal lijkt alles normaal te zijn.

**Comment by copierrj** [comment]
@SandroNeumann: ik kan je analyse wat betreft de GeoPublisher-trusted header bevestingen

**Comment by copierrj** [comment]
@gerardnienhuis: het betreft hier een bug in de publicatieomgeving die enkel optreedt bij 'niet vertrouwde' requests: van buiten provinciehuis Overijssel of requests die via het externe Geoportaal binnenkomen.

**Comment by gerardnienhuis** [comment]
https://www.geoportaaloverijssel.nl/metadata/service/81852c07-7522-44c4-8bb7-5d65244d8ee5 laat nog steeds een verdubbeling van een aantal lagen zien, zie plaatje:

![dubbele_lagen_in_metainfo_service_wegen](https://cloud.githubusercontent.com/assets/9005444/19829489/61a49046-9de3-11e6-87e6-ce09be14b58d.jpg)

**Comment by HermanAssink** [comment]
Betreffende FT komt maar 1 keer voor in WFS. Ligt dus blijkbaar aan de generatie van metadata van deze service.

**Comment by copierrj** [comment]
Link verwijst naar productie. In acceptatie gaat het wel goed:

https://acc-www.geoportaaloverijssel.nl/metadata/service/81852c07-7522-44c4-8bb7-5d65244d8ee5

**Comment by HermanAssink** [comment]
@gerardnienhuis , wil je even opnieuw testen? Het lijkt erop dat je dit getest hebt met de productie en niet met acceptatie.

**Comment by gerardnienhuis** [comment]
https://acc-www.geoportaaloverijssel.nl/search?text=bonnebladen&types=service getest: is OK

https://acc-www.geoportaaloverijssel.nl/search?text=wegen&types=service getest, is ook OK

getest intern Overijssel en ook (via iphone met 4G) als extern bekeken: geen problemen te zien, issue kan gesloten
