### ISSUE TITLE
wens leveranciers kleine letters 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#304]
Hierbij de lijst van leveranciers. Dit zijn de mensen die statische kaarten moeten kunnen aanbieden aan het nieuwe geoportaal. De lijst zit er al wel in, maar er ontbreken er nog 3 waarschijnlijk: met geel aangegeven. Ook is de wens om de emailadressen volledig in kleine letters op te nemen: gebruikers weten nu, zo blijkt, niet of je hoofdletters of kleine letters moeten gebruiken met veel verwarring tot gevolg bij inloggen. Als iedereen kleine letters gebruikt dan is dat probleem opgelost. De wens om hoofdletter-onafhankelijke invoer mogelijk te maken staat ook al in github maar die is voor 1.1.0 versie niet gerealiseerd. Kleine letters gebruiken is dan een werkbare oplossing voorlopig.

[geoportaal_leveranciers_kleine_letters.xlsx](https://github.com/IDgis/geoportaal-test/files/484495/geoportaal_leveranciers_kleine_letters.xlsx)

**Comment by HermanAssink** [comment]
Deze wijziging wordt uitgevoerd bij de productiegang.
Is het erg bezwaarlijk dat de gebruikers na de productiegang moeten inloggen met het standaard wachtwoord?

**Comment by gerardnienhuis** [comment]
Als dat wachtwoord zoiets is als "welkom2016" dan vind ik dat prima (alles kleine letters, niet teveel vreemde tekens)... Ik zal dat dan wel de gebruikers moeten uitleggen natuurlijk. Daar voorzie ik geen problemen, dat blijkt namelijk ook de oplossing voor de helpdesk van Overijssel te zijn en is men dus gewend.

Veel belangrijker is, dat ik kan vertellen dat ze met hun email adres met kleine letters moeten inloggen en niet met hoofdletters.

**Comment by gerardnienhuis** [comment]
kleine letters en ook wachtwoord "welkom2016" wordt gebruikt: testen voor de opening van 4 oktober. Dan pas dit issue sluiten.

**Comment by gerardnienhuis** [comment]
werkt goed, welkom2016 als wachtwoord werkt ook goed, issue kan gesloten

nb: detail: ik heb wachtwoord aangepast van mijn eigen inlog account (g.nienhuis@overijssel.nl). Maar omdat email in Overijssel niet werkt, kan ik nu zelf niet meer inloggen. Wordt hopelijk snel opgelost in Overijssel.
