### ISSUE TITLE
Nieuwe geodatasets sneller zichtbaar in geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#307]
Het duurt nu soms anderhalf uur voordat een nieuwe aangeboden geodataset (die nog niet in een service zit) zichtbaar wordt op het Geoportaal: dus tijd tussen aanbieden (plaatsen xml in de juiste map) tot vindbaar in Geoportaal. Dat is erg lang en lastig voor beheerders. Kan dat sneller?

**Comment by HermanAssink** [comment]
Er zijn drie export/import stappen die op elkaar volgen: 
1.Export van metadata uit GeoSticker naar naar de map met xml data 
2.Ophalen van metadata door Publicatieomgeving uit de map van stap 1
3.Ophalen van metadata door Geoportaal uit de Publicatieomgeving.
De laatste twee stappen hebben een frequentie van 15 minuten. Wat dat betreft zou het maximaal een half uur mogen duren. Reinder Hoekstra weet de frequentie van de eerste stap. Misschien is daar de meeste winst te boeken door de frequentie te verhogen.

**Comment by reinderhoekstra** [comment]
Stap 1 staat nu op 1x per uur, uit te voeren op het halve uur. Dit kan ik wijzigen naar bijv. periodiek 5 minuten (deze stap duurt max. 1 minuut). Kunnen jullie aangeven of dit inbreuk maakt op de algehele verwerkingscyclus?

**Comment by HermanAssink** [comment]
Frequenter verversen van de map met metadata kan misschien conflicteren met het periodiek ophalen van die data door de publicatieomgeving. Is de procedure bij Overijssel transactioneel? M.a.w. bestaat er nog het risico dat de map tijdelijk leeg is?

**Comment by reinderhoekstra** [comment]
Ja, de verversing gaat gepaard met het **eerst leeghalen** van de map voor vectorbestanden en de map voor rasterbestanden. De vulling vindt daarna plaats welke met de huidige aantallen (685 x vector; 170 x raster) niet langer duurt dan een minuut.

**Comment by HermanAssink** [comment]
Kun je procedure misschien aanpassen door eerst naar een tijdelijke map te schrijven, vervolgens de oude te verwijderen en daarna de nieuwe te hernoemen naar de oude naam?

**Comment by reinderhoekstra** [comment]
Dat kan programmeer technisch vast wel, maar de directories voor vector en raster zijn geshared; dat maakt het wat lastiger. Bovendien: hoe zal de Provider op een dergelijke actie reageren, immers dit lijkt me ook een transactionele actie?

Voorstel om dit tijdens de meeting donderdagmiddag 13-10 verder te bespreken.

**Comment by HermanAssink** [comment]
Akkoord. Dat wordt dan een "onderonsje" tussen jou en Reijer.

**Comment by gerardnienhuis** [comment]
Oplossing lijkt te zijn: put uit de Geosticker-WAF (met raster en geodata xml's).
Laat de Provider aan IDGIS kant het splitsen naar vector en raster uitvoeren.

**Comment by reinderhoekstra** [comment]
Het veld waarop ik check of een XML een raster vertegenwoordigd staat in sectie spatialRepresentationType ==> codeListValue = "grid"; al het andere is "vector":

```
  <spatialRepresentationType>
    <MD_SpatialRepresentationTypeCode codeList="./resources/codeList.xml#MD_SpatialRepresentationTypeCode" codeListValue="grid" />
  </spatialRepresentationType>
```

**Comment by HermanAssink** [comment]
@copierrj Wil jij de globale impact (laag/middel/hoog) aangeven?

**Comment by copierrj** [comment]
Oplossingsrichting: bij het itereren over metadata bestanden dmv een (xpath) filter bepalen of een record meegenomen moet worden. De vector provider slaat bestanden met 'grid' over en de raster provider slaat bestanden met 'vector' over.

**Comment by gerardnienhuis** [comment]
Geodata sets komen correct in portaal terecht. Daadwerkelijke snelheid (verschil aanbieden en zichtbaar in portaal) moet nog beter getest worden.

**Comment by gerardnienhuis** [comment]
werkt goed, nu blijkt dat info na ongeveer uur (mogelijk nog sneller) beschikbaar komt ni het Geoportaal. Was eerst 1.5 uur of langer. Issue kan gesloten.
