### ISSUE TITLE
UUID originele XML duidelijker in metainfo

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#309]
Als een xml wordt aangeboden, dan heeft dat de vorm van uuidxyz.xml

maar die naam (het uuid zelf) komt nergens meer terug in de metainfo, ook niet bij de details

wens is om de uuid van het oorspronkelijke bestand ook bij de details zichtbaar te maken.

**Comment by gerardnienhuis** [comment]
voorstel: deze opnemen in uitgevoerde bewerkingen bij tabblad details

tekst wordt: Originele XML was: ... en dan hierbij naam met UUID.xml erachter.

**Comment by gerardnienhuis** [comment]
let op: uuid staat in xml, niet in bestandsnaam:

voorbeeld:

Alternatieve titel: B2.avondspits2020ov_arc (b2\b22)
Versie: febr. 2015
Unieke Identifier: 6d0c8c26-c5f2-4c8f-89a2-a8a6406c4fe6

**Comment by SandroNeumann** [comment]
In jouw voorbeeld (https://metadata.geodataoverijssel.nl/metadata/dataset/fcd2411d-d4b5-4c13-9c31-4d9740f8cec4.xml) staat bij het label unieke identifier 554e3e5a-e92d-40e8-a750-a79eee556ee2. De uuid 6d0c8c26-c5f2-4c8f-89a2-a8a6406c4fe6 komt nergens voor in de XML.

**Comment by gerardnienhuis** [comment]
dat is precies het probleem: die moet wel in de xml worden opgenomen: dat is de originele naam van de xml namelijk. Die wordt ergens in het proces vervangen door een andere naam waardoor het beheer van de xml's erg lastig wordt..

**Comment by copierrj** [comment]
Is het mogelijk om een voorbeeldbestand te leveren met daarin wenselijke  situatie ?

**Comment by gerardnienhuis** [comment]
aantal voorbeelden staan in de zip
[GeoWeb.zip](https://github.com/IDgis/geoportaal-test/files/639672/GeoWeb.zip)

**Comment by gerardnienhuis** [comment]
Is dit niet zelfde als #350 lijkt het. Als ze hetzelfde zijn, dan kan 1 van beide issues gesloten worden.

**Comment by copierrj** [comment]
@gerardnienhuis: lijkt mij idd een duplicaat issue.
