### ISSUE TITLE
Tekst email en download aanpassen met verwijzing Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#311]
Extra tekst toevoegen, onder aan de mail die wordt verzonden.

1 extra witregel

Het Geoportaal van Overijssel bevat honderden datasets die kunnen worden gedownload.
Ze zijn vrij beschikbaar, voor iedereen om te gebruiken.
Wil je deze datasets bekijken of downloaden, kijk dan bij: http://www.geoportaaloverijssel.nl .

(waarbij die http... link dan aanklikbaar moet zijn)

**Comment by NicoEilers** [comment]
Ook bij bericht van download: niet alleen in mail maar ook in zip die geleverd wordt.

**Comment by robstek** [comment]
Moet deze tekst ook worden toegevoegd aan de mail die wordt verstuurd als de download niet is gelukt?
Waar zou je deze tekst in de zip willen hebben, in een apart bestand ?

**Comment by gerardnienhuis** [comment]
ik wil deze tekst in alle mails hebben die verzonden wordt, dus ook als de download om 1 of andere reden niet is gelukt. De tekst wil ik dus in de mail die je ontvangt bij downloaden, niet in de zip of een apart bestand.

**Comment by gerardnienhuis** [comment]
Het ziet er goed uit, zowel email als download tekst.
Werkt ook goed: issue kan gesloten
