### ISSUE TITLE
Download ook als 3 sterren open data (GML?)

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#313]
Als het Geoportaal ook "3 sterren" open data downloads zou moeten ondersteunen, is het dan een logische keuze om ook GML als download optie te laten kiezen? Of zijn er nog andere formaten zinvol. De beschrijving op wikipedia lijkt aan te geven dat wij nu met de standaarden KML, GML enz wel 2 sterren leveren als open data. Of is er meer nodig voor 3 sterren?

zie ook: https://nl.wikipedia.org/wiki/Open_data

**Comment by HermanAssink** [comment]
Gerard, De download van het Geoportaal bied al GML aan (versie 2.1 en 3.2). Wat dat betreft voldoet het Geoportaal aan de drie sterren (De informatie is online beschikbaar in een open bestandsformaat (zoals CSV in plaats van Excel).). Naast de downloadformaten bieden de WFS services van de publicatieomgeving csv en json als outputformat aan. Vooral json wordt gezien als een handig format voor web-ontwikkelaars, niet-GISsers zijnde. Voor "gewone" web-ontwikkelaars is vooral de complexiteit van de WFS standaard een drempel om dit type service te gebruiken. Dat zou op te lossen zijn door het maken van een REST-API en/of een heel leesbare. toegankelijke documentatie van de WFS interface zodat een ontwikkelaar snel resultaat kan boeken.

**Comment by HermanAssink** [comment]
laat aanleiding nog maar even geheim.. straks doen er meer concurrenten mee :-)

**Comment by NicoEilers** [comment]
zie ook #314

**Comment by NicoEilers** [comment]
Issue kan gesloten worden.
GML worden al geleverd.
