### ISSUE TITLE
Services lijken niet goed te werken maar download werkt wel

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#318]
Getest tbv opening 4 oktober 2016:

Eerst metainfo van kaart bekeken, daarna download getest, alle formaten en kaartbeeld gecontroleerd in Qgis. Daarna wilde ik wms en wfs er bij tekenen voor de controle (heeft eerder wel gewerkt) maar werkt nu niet meer. Melding in Qgis is dat er geen lagen zijn (bij wfs). WMS laat ook geen selecteerbare lagen zien. Terwijl download wel gewoon werkt en ook juist kaartbeeld oplevert (mbt KML, is known issue). 

Zijn wms en wfs services wel goed geconfigureerd?

Hieronder 2 testvoorbeelden:

download van willekeurige kaart in 5 fileformaten:
kaart url is:

https://www.geoportaaloverijssel.nl/metadata/dataset/b410f7c4-fbc0-48b9-877d-fa0a32130a4d
Bestandsnaam: Grenzen van alle Nederlandse gemeenten
Download: https://download.geoportaaloverijssel.nl:443/download/b410f7c4-fbc0-48b9-877d-fa0a32130a4d
OGC:WFS: http://services.geodataoverijssel.nl:80/geoserver/B14_bestuurlijke_grenzen/wfs
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B14_bestuurlijke_grenzen/wms

downloads aanwezig. controle bestanden met Qgis: 

shape ligt op juiste plek
gml ook
dxf ook
maar kml niet, bekend probleem
# 

download resultaat vergeleken met wms en wfs van zelfde kaart in Qgis

OGC:WFS: http://services.geodataoverijssel.nl:80/geoserver/B14_bestuurlijke_grenzen/wfs
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B14_bestuurlijke_grenzen/wms

wms is: werkt niet goed, geen lagen te selecteren
wfs is: werkt niet goed, capabilities document bevat geen lagen? melding Qgis

andere wms services getest:

Naam van de service: B22_wegen
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B22_wegen/wms
zelfde probleem

**Comment by gerardnienhuis** [comment]
Voor de zekerheid alle tests met resultaten hierbij gevoegd. Alleen test 16 lijkt problemen te geven, zoals hiervoor beschreven.

[controle_geoportaal_prod_110.txt](https://github.com/IDgis/geoportaal-test/files/504147/controle_geoportaal_prod_110.txt)

**Comment by gerardnienhuis** [comment]
voorlopige testrapport: 16 testen, alleen bij laatste test blijken problemen (zoals hiervoor beschreven).

[controle_geoportaal_prod_110.txt](https://github.com/IDgis/geoportaal-test/files/504148/controle_geoportaal_prod_110.txt)

**Comment by gerardnienhuis** [comment]
laatste test wat dit betreft: willekeurige andere dataset bekeken, en vergelijken met acceptatieomgeving.
resultaat: op productie werken WMS en WFS niet, op acceptatie echter wel.

details, hieronder

# 

Bestandsnaam: Gebiedskenmerken - Stedelijke laag

https://www.geoportaaloverijssel.nl/metadata/dataset/c9bad93e-d8b9-42b6-b328-c17b7950bbe2
Alternatieve titel: B0.stedelijke_laag_polygon (b0/b04)
Download: https://download.geoportaaloverijssel.nl:443/download/c9bad93e-d8b9-42b6-b328-c17b7950bbe2
OGC:WFS: http://services.geodataoverijssel.nl:80/geoserver/B04_stedelijk_gebied/wfs
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B04_stedelijk_gebied/wms

download werkt wel
WMS en WFS niet bruikbaar in Qgis

# 

Acceptatie: geen problemen gevonden, voorbeeld:

Alternatieve titel: B8.pp_winkelgebieden_polygon (b8\b82)
Status: Compleet
Download: https://acc-download.geoportaaloverijssel.nl:443/download/c24e1ad6-8cac-426a-9445-85c500a612b7
OGC:WFS: http://acc-services.geodataoverijssel.nl:80/geoserver/B82_volkshuisvesting/wfs
OGC:WMS: http://acc-services.geodataoverijssel.nl:80/geoserver/B82_volkshuisvesting/wms

WMS en WFS werken wel normaal, lagen zichtbaar in Qgis en kaartbeeld betrouwbaar.

#

**Comment by HermanAssink** [comment]
In de browser geeft deze request geen response: http://services.geodataoverijssel.nl/geoserver/B04_stedelijk_gebied/wms?SERVICE=WMS&REQUEST=GetCapabilities

**Comment by copierrj** [comment]
Er bleek is mis gegaan te zijn bij het starten van GeoServer waardoor een groot aantal lagen niet beschikbaar waren. Na herstart van GeoServer is het probleem verholpen.

Voorbeeld foutmelding:

featureType: B14_bestuurlijke_grenzen:B1_Gemeentegrenzen_Overijssel_vlak does not have a properly configured datastore

Deze melding kwam terug als ServiceException. Is ook terug te vinden in de GeoServer log.

**Comment by HermanAssink** [comment]
Hoe kunnen we dit in de toekomst voorkomen?

**Comment by copierrj** [comment]
Door in de monitoring de inhoud van de capabilities te vergelijken met de configuratie. Lagen met een haperende datastore ontbreken in de capabilities.

**Comment by gerardnienhuis** [comment]
probleem is naar tevredenheid opgelost, issue kan gesloten
