### ISSUE TITLE
Van - tot datum verwijderen als gelijk aan creatiedatum

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#320]
Naam statische kaart: Buurten bevolkingsdichtheid

Het blijkt dat bij de statische kaarten de publicatiedatum vaak ook is gebruik voor het invullen van de datum geldig van en datum geldig tot.

Dat is onwenselijk. Liever in deze situaties de van en tot datum niet meer laten zien, dus leeg maken.

Voorbeeld hieronder

Naam statische kaart: Buurten bevolkingsdichtheid
https://www.geoportaaloverijssel.nl/metadata/dc/CCF40B8C-F8F8-4F1E-B0C7-E0BA46F8A7CB

datums zijn nu:

Datum creatie: 2015-11-03
 Datum publicatie: 2016-09-27
 Datum geldig, van: 2015-11-03
 Datum geldig, tot: 2015-11-03

datums worden straks:

Datum creatie: 2015-11-03
 Datum publicatie: 2016-09-27
 Datum geldig, van: 
 Datum geldig, tot:

**Comment by gerardnienhuis** [comment]
moet ook gelden voor publicatiedatum, dus als publicatiedatum gelijk is aan van en tot datum, dan ook van en tot datum leegmaken, voorbeeld:

Datum creatie: 2015-11-03
 Datum publicatie: 2016-09-27
 Datum geldig, van: 2016-09-27
 Datum geldig, tot: 2016-09-27

datums worden straks:

Datum creatie: 2015-11-03
 Datum publicatie: 2016-09-27
 Datum geldig, van: 
 Datum geldig, tot:

**Comment by SandroNeumann** [comment]
Aantal records waar dit op van toepassing is: 1225

**Comment by gerardnienhuis** [comment]
graag aanpassen conform beschrijving

**Comment by SandroNeumann** [comment]
Query is uitgevoerd.

**Comment by gerardnienhuis** [comment]
werkt nu goed
