### ISSUE TITLE
Access logging (AWStats) opnemen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#323]

**Comment by gerardnienhuis** [comment]
kan ik niet controleren: heb geen rapport ontvangen

**Comment by SandroNeumann** [comment]
Is te bekijken op: https://acc-awstats.geoportaaloverijssel.nl/cgi-bin/awstats.pl?

**Comment by HermanAssink** [comment]
Plaatjes/icons in awstats pagina worden niet getoond.

**Comment by gerardnienhuis** [comment]
is erg complex overzicht, maar mogelijk wel bruikbaar naast de bestaande teller van Nedstat. Omdat ik niet weet hoe de ontbrekende plaatjes/icons er uit zien, weet ik niet of dit issue nu gesloten kan worden

**Comment by HermanAssink** [comment]
Het probleem met de ontbrekende plaatjes lossen we nog op. AWstats kan uitgebreid geconfigueerd worden om specifieke statistieken te rapporteren. Dat pakken we eventueel later op.

**Comment by gerardnienhuis** [comment]
is prima, ik zie een eerste versie nu. lijkt goed te werken. Ik sluit nu dit issue daarom.

**Comment by gerardnienhuis** [comment]
ik kan de awstats teller niet gebruiken, maar mogelijk omdat het IP adres niet bekend is?
Op verzoek van @SandroNeumann hierbij mijn ip adres:

Your IPv6 Address Is:  2a00:7940:0:327:1:982b:d0cb:c3c0

**Comment by SandroNeumann** [comment]
En je IP4 adres?

**Comment by HermanAssink** [comment]
Hiervoor kunnen we toch dezelfde IP-adressen gebruiken als de beveiligde services van de publicatieomgeving?

**Comment by gerardnienhuis** [comment]
ja, zijn de zelfde als in #36

**Comment by SandroNeumann** [comment]
Die worden gebruikt, vandaar mijn vraag van welk ip4 adres de awstats pagina is geprobeerd te bereiken.

**Comment by gerardnienhuis** [comment]
Is hier van mijn kant nog extra input nodig?

**Comment by HermanAssink** [comment]
@gerardnienhuis : Vraag aan jou is vanaf welke locatie jij het probleem hebt geconstateerd. Je zou namelijk vanuit het provinciehuis erbij moeten kunnen. Net zoals je vanuit het provinciehuis bij het interne geoprtaal kunt.

**Comment by gerardnienhuis** [comment]
Ik kon vanuit het provinciehuis niet bij de teller. Ik kan wel altijd vanuit het proviciehuis het interne Geoportaal benaderen.

**Comment by gerardnienhuis** [comment]
issue kan gesloten, blijkt nu wel te werken
https://acc-awstats.geoportaaloverijssel.nl/cgi-bin/awstats.pl
 levert zinvol beeld op
