### ISSUE TITLE
Verwijderen XML zorgt niet voor verwijderen uit Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#324]
Aanbieden van nieuwe Geodatasets en statische kaarten lijkt op de productieomgeving goed te werken. Na een tijdje worden die ook zichtbaar in het Geoportaal. Maar het verwijderen van geodata lijkt niet goed te werken. De xml is uit de map verwijderd, en toch blijkt de metadata uren later nog in het interne Geoportaal zichtbaar te zijn. Lijkt een bug. Details:

https://intern.geoportaaloverijssel.nl/metadata/dataset/8427befe-a4f9-4cfb-8b7f-e27d055e8e2d
Bestandsnaam: B2.n34_polyline
Samenvatting: Ondergrondkaart Trace N34 (lijnen)
Alternatieve titel: B2.n34_polyline (B2\B22)

**Comment by gerardnienhuis** [comment]
Het zal er mee te maken hebben, dat laag al in service is opgenomen. vraag is, hoe nu verder. xml is al verwijderd, en nieuwe versie van metadata met deze laag is al aangeboden. Hoe verwijder je nu als beheerder die verkeerde metainformatie?

**Comment by HermanAssink** [comment]
Bijbehorende dataset die volgens oorspronkelijke metadata alleen voor intern gebruik (vertrouwelijk) is zit in de service B22-wegen die op de publieke omgeving gepubliceerd is. 
Om de metadata weg te halen uit het Geoportaal moeten de volgende stappen in de Publicatieomgeving worden uitgevoerd:
1. Laag n34_lijnen verwijderen uit service B22_wegen
2. Laag n34_lijnen verwijderen
3. Dataset n34_lijnen verwijderen

**Comment by NicoEilers** [comment]
probleem bleek te komen omdat laag al in service zat. is uit service verwijderd en probleem is opgelost, issue kan gesloten daarom
