### ISSUE TITLE
wat doet de DL service bij > 1 urls

### ISSUE THREAD

**Issue by robstek** [IDgis/geoportaal-test#325]
zie #272

**Comment by robstek** [comment]
Ik heb onderzocht wat de downloadtool doet bij het gegeven voorbeeld:
Bebouwde kommen in Overijssel 
Hier staan 2 download links onder tab 'Details'.
Beide leveren een zip op met exact gelijke inhoud. 
De opgeleverde gml bevat niet bijvoorbeeld 2x zoveel features oid.

Dus wat de downloadtool betreft lijken hier geen problemen te zijn.

**Comment by gerardnienhuis** [comment]
blijkt goed te gaan. download bebouwde kommen heeft 2x verwijzing naar WMS en WFS. is correct, staat in 2 services. issue kan gesloten
