### ISSUE TITLE
Namen interne contactpersonen niet via harvest naar PGR

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#327]
Nu is in de stylesheet geregeld dat interne contactpersonen niet zichtbaar zijn als je in het externe Geoportaal kijkt bij het tabblad WIE. Maar ik vermoed dat door het harvesten van PGR deze informatie wel gewoon wordt doorgegeven naar PGR. Is dat te voorkomen? Dus dat je aan het PGR alleen die informatie gaat aanbieden, die je ook nu al ziet als je WIE bekijkt in het externe Geoportaal?

**Comment by copierrj** [comment]
Is opgelost in #355

**Comment by gerardnienhuis** [comment]
is correct, issue kan gesloten omdat #355 goed blijkt te zijn opgelost.
