### ISSUE TITLE
Rapportage statische kaarten fout bij 4 records

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#329]
Ik heb 4 records gevonden (bij rapport productie van gisteren) waarbij problemen voorkomen. De datumvelden worden bijvoorbeeld gevuld met tekst ipv datum informatie.

Lijkt te zijn veroorzaakt door 1 of meerdere vreemde tekens, zoals ; 

In de bijgevoegde excelfile zijn de velden die vreemde info bevatten, geel gekleurd.

Voorbeeld:

https://admin.geoportaaloverijssel.nl/metadata/14061968-93af-4730-8f91-2e27eab19f3c
 ziet in in de stylesheet (onderdeel beheer productie) goed uit.

Maar in de excelfile gaat de indeling verkeerd,

beschrijving is te vroeg afgekapt:
 Zoneringskaart (concept) - boomteelt in Noordoost-Twente. Voor de zonering zijn gegevens door de gemeenten Dinkelland, Losser, 
 Tubbergen aangeleverd, deze staan in de map 'gegevens_sept_2007'. De map sept_2007 bevat de bestanden die gebruikt zijn voor het project 
 (apr: sept_2007). In de map -kwekerij_2004- bevindt zich het bestand kwek2004" dat de basis is van het bestand 'boomkwekerij' op de 
 zoneringskaart. Dit bestand "kwek2004" is een selectie uit de top10-vector(vlakken), zoals die in juli 2005 beschikbaar waren. 
 (de meeste tiles zijn in 2003 of 2004 geinventariseerd). Selectiecriteria waren

hierachter had moeten staan: boomgaarden, boomkwekerijen, fruitkwekerijen en kassen (glastuinbouw)."

Dat staat er echter niet. 

Opvallend is dat er een ; teken ontbreekt. Mogelijk is dat de oorzaak ervan

De rest van de tekst, zonder ; is terechtgekomen bij een datumveld.
[4fouten_excelfile.xlsx](https://github.com/IDgis/geoportaal-test/files/526487/4fouten_excelfile.xlsx)

**Comment by gerardnienhuis** [comment]
betreft dus slechts 4 records van meer dan 7000 in totaal. mogelijk veroorzaakt doordat ; teken in tekst staat. Meest simpele oplossing: ; teken vervangen als beheerder? Of zou het bij meerdere tekens optreden?

**Comment by SandroNeumann** [comment]
Moet onderzocht worden waar het precies fout gaat, maar hier moet de programmatuur mee om kunnen gaan.

**Comment by SandroNeumann** [comment]
Het lag inderdaad aan de ;. Ik heb dit zelf lokaal getest en bij mij zorgt dat teken niet voor verkeerde kolommen. Ik gebruik het spreadsheet programma van Libre Office, jij waarschijnlijk Microsoft Excel. Als je bij de tekstimport onderstaande opties aangeeft - dus scheidingsteken puntkomma en tekstscheidingsteken het aanhalingsteken - gaat het dan nog steeds fout?

![image](https://cloud.githubusercontent.com/assets/10757125/19345514/e302c88a-913e-11e6-86af-3a0f4c95b140.png)

**Comment by gerardnienhuis** [comment]
Extern kan ik dit wel testen, alleen intern Overijssel staat de default zo ingesteld dat je dit soort problemen krijgt. Mijn voorstel is dat we dit zelf oplossen: het betreft slechts 4 records van meer dan 7000 records. We halen gewoon die ; er uit en vervangen dit door : ... niet alleen klopt de tekst dan beter, maar ook het probleem is dan opgelost, verwacht ik. Formeel is het dus ook geen bug maar onhandig gedrag van excel. Ik laat nog even weten het effect is als de ; is verwijderd.

**Comment by gerardnienhuis** [comment]
probleem is opgelost. ; in samenvatting vervangen door , .. was in tekst ook veel logischer. Conclusie: voor makkelijk gebruik intern Overijssel die ; vermijden. Issue kan gesloten
