### ISSUE TITLE
Uitbreiding rapport geodatasets met info mbt brondataset

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#331]
uitbreiding van bestaand rapport, met extra info mbt brondataset (brondataset is originele xml van prov. Overijssel)

1 titel geodataset (bron, origineel die met geosticker is gemaakt)

2 samenvatting van (1) 

3 unieke id is dus bestandsnaam van xml die met geosticker

4 is iets hiervan in services opgenomen?

**Comment by gerardnienhuis** [comment]
Wordt uitgevoerd met beschikbare uren die gereserveerd waren voor de beheerfase. Gaat van fase 1.1.2. naar fase 1.1.1.

**Comment by copierrj** [comment]
Tijdens het ontwikkelen bleek dat de titel al afkomstig was uit de originele metadata xml.

**Comment by gerardnienhuis** [comment]
titel, samenvatting, in service: werken goed
id wordt uitgezocht

**Comment by copierrj** [comment]
@gerardnienhuis: de inhoud van de nieuwe kolom 'filename' zou moeten matchen met de bestandsnamen zoals die in de metadata folder staan.

**Comment by gerardnienhuis** [comment]
ja, dat zou moeten, maar dan moet je toch die datasets terug kunnen vinden als je ze zoekt in het geoportaal? hier lijkt iets vreemds aan de hand

**Comment by copierrj** [comment]
De bestandsnaam (van de metadata documenten in de metadata folder op de jullie server) zul je niet terugvinden in het geoportaal. Deze staan enkel in het rapport en worden alleen gebruikt in de communicatie tussen de publicatieomgeving en het provider component dat bij jullie draait.

**Comment by gerardnienhuis** [comment]
id staat correct in het rapport, test is compleet.
 issue kan gesloten worden.

**Comment by gerardnienhuis** [comment]
nb: nieuw issue van gemaakt om dit nog makkelijker te maken, zie nr. ...
