### ISSUE TITLE
Crash agv time out door problemen netwerk?

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#333]
Als ik een klein bestand (statische kaart) wil aanbieden, dan werkt dat probleemloos. (1 Mb per stuk, soms iets groter). Als ik een veel groter bestand (35 Mb) wil aanbieden, dan duurt het aanbieden erg lang (12 seconden) en daarna volgt een foutmelding. Dit heeft echter wel altijd gewerkt, ook vanuit Overijssel. Er zijn bestanden van 100 Mb of meer getest. Kan het zijn dat intern Overijssel de netwerkinstellingen zijn aangepast, zodat een soort Time-out situatie optreedt? Zie bijgevoegd figuur voor de foutmelding.

![gp_statkrt_error_knipsel](https://cloud.githubusercontent.com/assets/9005444/19436698/0ac44e12-9472-11e6-9a1b-7b53c32eeb9f.PNG)

**Comment by SandroNeumann** [comment]
De oorzaak was een out of memory error. De memory limiet is verhoogd. Wil je het nu nog eens proberen?

**Comment by gerardnienhuis** [comment]
blijkt nu wel te werken, issue kan afgesloten worden
