### ISSUE TITLE
WMS visualiseren via stylesheet en zoekresultaten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#334]
Via aparte viewer WMS zichtbaar maken. Als de WMS aanwezig is, dan is tekst "metadata' en "download" bij zoekresultaten zichtbaar. Daar ook tekst "bekijk in viewer" toevoegen. Als je dan "bekijk in viewer" aanklikt, dan WMS visualiseren op apart tabblad in een externe viewer.

View-link ook zichtbaar maken bij DETAILS in stylesheet:

Nu is download, WMS en WFS link zichtbaar, daaronder ook tekst:
Link naar vierwer opnemen, met de daarbij behorende aanklikbare url

**Comment by HermanAssink** [comment]
Gerard, is het OK om daarvoor [deze viewer](http://services.geodataoverijssel.nl/viewer) te gebruiken, maar dan met betreffende service geopend / zichtbaar gemaakt?

**Comment by gerardnienhuis** [comment]
ja, precies zoiets bedoelde ik. Alleen dan met als enige laag de betreffende service geopend

**Comment by gerardnienhuis** [comment]
Het valt me wel op dat de achtergrondlaag erg traag is ten opzichte van de WMS-sen die ik uit heb geprobeerd. Wat voor een laag of service wordt hiervoor gebruikt? Iets van PDOK? Of zelf geserveerde top-10nl-variant? Inzoomen op die achtergrondlaag laat ook weinig detail zien. De meeste versies van PDOK laten wel meer detail zien, als je verder bent ingezoomd, dacht ik.

**Comment by HermanAssink** [comment]
Dit is de BRT achtergrondkaart van PDOK in pastel kleuren. PDOK is de laatste weken zo nu en dan traag. Eventueel kunnen we een achtergrondkaart van Overijssel zelf (uit de Pub-omgeving) gebruiken.

**Comment by gerardnienhuis** [comment]
Als het niet teveel inspanning vraagt, dan lijkt me een achtergrondkaart uit de pub omgeving meer stabiel en ook logischer en makkelijker te onderhouden: werkt er iets niet dan werken zowel achtergrondkaart als WMS waarschijnlijk niet en is oplossingsrichting ook logischer. Als je PDOK (niet stabiel en traag) en eigen WMS samenvoegt in de viewer dan moet je altijd eerst uitzoeken welke van de 2 bronnen problemen geeft.

**Comment by gerardnienhuis** [comment]
zelfde als #93, is dubbel, dit issue gesloten worden.

**Comment by gerardnienhuis** [comment]
Het opnemen van de link naar de viewer is wel gerealiseerd (conform #93) maar in de zoekresultaten is dit niet opgenomen. De link naar de viewer moet ook zichtbaar zijn in de zoekresultaten. 

Er staat nu: Meer informatie Download

Er moet komen te staan: Meer informatie Bekijk in viewer Download

**Comment by gerardnienhuis** [comment]
kan hier gesloten worden, blijkt exact hetzelfde als #93
