### ISSUE TITLE
Tekst aanpassen in stylesheet en downloadscherm

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#336]
In de stylesheet (bij details) en onderin bij het downloadscherm staan nu standaard 3 regels tekst.
Verzoek is om deze tekst aan te passen.

 Tekst is nu:

 Deze informatie wordt beschikbaar gesteld door het Geoportaal van de Provincie Overijssel.
 De gegevens zijn gemaakt voor eigen (intern) gebruik door de provincie Overijssel.
 Zijn er suggesties of vragen, neem dan contact op met beleidsinformatie@overijssel.nl

Voorstel betere tekst:

Deze gegevens worden beschikbaar gesteld door het Geoportaal van Overijssel: http://www.geoportaaloverijssel.nl
In het Geoportaal staan actuele kaarten en beschrijvingen van die kaarten.
Ter referentie zijn vaak ook nog oudere kaarten beschikbaar gesteld.
De provincie Overijssel stelt zoveel mogelijk kaarten als "open data" voor iedereen beschikbaar.
Heeft u suggesties of vragen? Stuur dan een email naar beleidsinformatie@overijssel.nl
Zie proclaimer: http://www.overijssel.nl/algemene-onderdelen/proclaimer

**Comment by gerardnienhuis** [comment]
merk op: in bij de download wordt een leesmij.xml bestand geleverd. Ook in dit bestand moeten de 3 regels tekst aangepast zijn.

**Comment by SandroNeumann** [comment]
Moeten de links in de tekst in een nieuwe tab openen?

**Comment by gerardnienhuis** [comment]
ja, graag

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
