### ISSUE TITLE
André Weijmer beheerrechten geven

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#338]
Net als Nico Eilers moet ook André Weijmer beheerrechten hebben, zodat hij rapporten van het Geoportaal kan raadplegen (hij moet dus bij inloggen op http://admin.geoportaaloverijssel.nl ook beheerrechten krijgen, anders ziet hij de knop Rapportage niet)

**Comment by SandroNeumann** [comment]
Dit valt onder milestone beheer.

**Comment by SandroNeumann** [comment]
André is nu beheerder.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
