### ISSUE TITLE
Verwijzing naar XML bij details

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#340]
Nu staat de verwijzing naar de XML bij de zoekresultaten, logischer is het, om deze op te nemen bij de DETAILS in de stylesheet.

Boven de zin "Deze gegevens worden beschikbaar gesteld ..."
komt dan een witregel, en daarboven komt bijvoorbeeld te staan:

XML:  https://acc-www.geoportaaloverijssel.nl/metadata/dc/CCF40B8C-F8F8-4F1E-B0C7-E0BA46F8A7CB?noStyle=true

(de url is dan aanklikbaar)

en daarboven weer een witregel om het onderdeel logisch te scheiden van datgene wat daarvoor staat.

**Comment by SandroNeumann** [comment]
**@copierrj**: Je zou in de publisher in de methode van het renderen van de metadata ook een noStyle parameter op moet geven, waarmee je de kale XML kunt zien. Zodat deze wens ook in de publisher gaat werken.

**Comment by copierrj** [comment]
@SandroNeumann: duidelijk. Vraag me echter af hoe dit gaat werken voor gedownloade metadata documenten?

**Comment by gerardnienhuis** [comment]
werkt goed, 
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/62dfd05f-d53d-4f29-8154-f63eadad9301 getest met IE, FF, Opera en Chrome.

Tevens veel andere kaarten getest met Chrome

Kaarten worden goed op scherm zichtbaar,
 issue kan gesloten worden
