### ISSUE TITLE
Intellectueel niet gevonden

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#342]
in de metainfo komt de beperking "intellectueel eigendom" voor. Maar als wordt gezocht naar "intellectueel" dan wordt niks gevonden. Het lijkt er op dat de gebruikersbeperkingen niet doorzoekbaar zijn gemaakt.

Lijkt op probleem met vectoren, wat wel is opgelost.

**Comment by gerardnienhuis** [comment]
zie #268

Bedoeling is, dat alles wat in metainfo wordt aangeboden ook doorzoekbaar is, dus ook gebruikersbeperkingen, overige beperkingen en juridische gebruikersrestricties of toegangsrestricties.

**Comment by gerardnienhuis** [comment]
voorbeeld waarin "intellectueel" als woord wel aanwezig is:

Bestandsnaam: Natura 2000-gebieden in nederland
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/2101e166-89d7-433c-ace3-2c67ff63b62f

Gebruiksbeperkingen:  Geoportaal extern 
Gebruiksbeperkingen:  Downloadable data 
Gebruiksbeperkingen:  Overige beperkingen 
Overige beperkingen: Copyrighthouder: Programmadirectie Natura 2000, Ministerie van Economische Zaken
(Juridische) gebruiksrestricties: Copyright
(Juridische) toegangsrestricties: Intellectueel eigendom
(Juridische) toegangsrestricties: Anders

**Comment by SandroNeumann** [comment]
De juridische restricties moesten nog toegevoegd worden. Het betreft hier wel de originele engelse termen, dus intellectueel eigendom is vindbaar met intellectualPropertyRights. De vertaalslag wordt pas met de stylesheet gedaan.

**Comment by gerardnienhuis** [comment]
tzt controleren of het met die engelse term dan wel goed werkt

**Comment by gerardnienhuis** [comment]
intellectualPropertyRights wordt nu wel gevonden. issue kan gesloten
