### ISSUE TITLE
Rapportage Geodata fouten bijlage code en fout zelf in aparte kolom

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#345]
Wens is om de foutcode (404, 501 enz) in de rapportage te scheiden van de foute link zelf. Zo is er makkelijker op te zoeken in excel

nav #256

**Comment by copierrj** [comment]
Wijzigingsverzoek is duidelijk. 

Echter, het is mogelijk dat voor hetzelfde dataset meerdere downloadfouten zijn opgetreden. De kolom 'http_errors' (zoals die op dit moment bestaat) bevat dan meerdere waarden, gescheiden door komma's. Als we deze kolommen splitsen (in bijvoorbeeld 'http_error_urls' en 'http_error_codes') dan is het dus aan de lezer om te bepalen welke urls en codes bij elkaar horen.

**Comment by gerardnienhuis** [comment]
Wij merkten dat zoeken door die foutcodes lastig is.

 Ik verwacht dat 2 kolommen (dus url en code apart) makkkelijker zoekt. In praktijk is een beheerder meer geinteresseerd in een snel leesbaar overzicht dat de exacte foutcode zelf: die fout moet gewoon opgelost worden. En je kan ze altijd nog achterhalen, indien nodig door de 2 kolommen naast elkaar te bekijken.

**Comment by gerardnienhuis** [comment]
code en fouten nu in 2 kolommen: werkt correct, issue kan gesloten
