### ISSUE TITLE
In rapport Geodata vermelden  intern of extern

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#347]
In het huidige rapport Geodata kan je niet makkelijk zien of een geodataset alleen intern of ook extern zichtbaar is. Wens is dat als aparte kolom toe te voegen in het rapport.

**Comment by copierrj** [comment]
Zelfde als #359?

**Comment by gerardnienhuis** [comment]
ja, deze is daarom gesloten
