### ISSUE TITLE
Rapport services

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#349]
Wens is om bij de rapportages 1 rapport toe te voegen:

items onder meer:

naam geodataset, 
naam van de service, 
samenvatting service
type service, wms of wfs
url van de service
datum voltooiing service
datum laatste wijziging
naam van de laag, status (b.v. bij problemen verwerking in service).
type service: wel of niet beveiligde service

aantal lagen per service (zie #203 )

**Comment by SandroNeumann** [comment]
**@copierrj**: je moet hier de sql voor de service rapportage maken

**Comment by copierrj** [comment]
Een aantal van de gevraagde gegevens (met name die de technische status van de service betreffen) zijn niet (of erg lastig) te leveren.

**Comment by robstek** [comment]
nieuwe rapportage

status van de laag == status van de dataset
elke laag in service krijgt csv rij.
alleen gepubliceerde services.
status waarden: "brondataset afwezig (=deleted vlag bd set)", "structuurwijziging (=import job met notificatie)", "brondataset stuk (=type bd set is unavailable)"

**Comment by gerardnienhuis** [comment]
Naam van de service: Adressen
https://acc-www.geoportaaloverijssel.nl/metadata/service/2f1dddea-bd73-4177-bd32-153fdaeb6eed

Bij WAT staat in de metainformatie, dus geen lagen aanwezig?
volgens rapportage over services zijn er wel 2 lagen aanwezig.

Wat klopt er niet? Stylesheet of rapport services

Samenvatting: De service bevat informatie over adressen. Dit betreft zowel de locaties van de adressen als de functies en populaties die aan de adressen zijn toegekend.
Lagen:
https://acc-www.geoportaaloverijssel.nl/metadata/service/2f1dddea-bd73-4177-bd32-153fdaeb6eed

**Comment by SandroNeumann** [comment]
Komt omdat de twee lagen in die service beide vertrouwelijk zijn. Intern zijn ze wel aanwezig:
https://acc-intern.geoportaaloverijssel.nl/metadata/service/2f1dddea-bd73-4177-bd32-153fdaeb6eed

**Comment by HermanAssink** [comment]
Deze service met vertrouwelijke lagen blijkt in de publieke omgeving gepubliceerd te zijn, waarschijnlijk nog een overblijfsel van de wijziging van het criterium voor vertrouwelijke data. Het is oplosbaar door de service in de publicatieomgeving te verwijderen en vervolgens opnieuw aan te maken en te publiceren in de beveiligde omgeving.

**Comment by gerardnienhuis** [comment]
Bijna alle kolommen zijn aanwezig, alleen kolom "datum laatste wijziging" blijkt afwezig.

**Comment by SandroNeumann** [comment]
Welke acties van André moeten leiden tot het nieuw invullen van de datum?

**Comment by gerardnienhuis** [comment]
De veranderingen van metadata, de service (opnieuw uploaden) en laatste wijziging van 1 of meerdere lagen in de service.

**Comment by copierrj** [comment]
Veranderingen in de metadata worden op dit moment nog niet bijgehouden (heeft relatie met #288). We kennen nu enkel de huidige toestand. We weten niet wanneer deze toestand ontstaan is.

Van services weten we wanneer deze is gepubliceerd (= wanneer er een diepe kopie van de service is gemaakt vanuit de staging omgeving) en wanneer de datasets waarop de lagen gebaseerd zijn voor het laatst zijn geïmporteerd.

Het is niet mogelijk om een service na publicatie nog te wijzigen. Het is enkel mogelijk om een service op een later tijdstip opnieuw te publiceren.

**Comment by gerardnienhuis** [comment]
In de metadata van de services staan nu 2 datumvermeldingen, bij het onderdeel WANNEER.

voorbeeld: Adressen
https://acc-intern.geoportaaloverijssel.nl/metadata/service/2f1dddea-bd73-4177-bd32-153fdaeb6eed
Voltooiing service: 20-04-2011
Laatste wijziging servicebeschrijving: 03-12-2013

De voltooiing service lijkt me het tijdstip van publicatie, de laatste wijziging van beschrijving de aanpassing van de metadata. Zijn deze 2 tijdstippen dan in het rapport op te nemen?

**Comment by gerardnienhuis** [comment]
nee, geen van beide tijdstippen zijn nu op te nemen. De stylesheet moet eerst aangepast worden. Blijkbaar zijn de huidige tijdstippen steeds hetzelfde en niet zinvol. Dit issue kan dus gesloten worden, omdat de overige wensen wel verwerkt al zijn
