### ISSUE TITLE
filenaam xml van geosticker zichtbaar in metadata stylesheet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#350]
Wens is om de volledige naam van de xml terug te laten komen in de metadata van de stylesheet. 

Blijkt nu al wel in rapportage te staan, zie 

#331

**Comment by SandroNeumann** [comment]
Welk metadata element is dat? Kun je een voorbeeld geven van een metadata document en wat daar de filenaam van geosticker is?

**Comment by gerardnienhuis** [comment]
We hebben nu geen metadata element hiervoor. je kan echter wel de "uitgevoerde bewerkingen" hiervoor gebruiken. Mijn suggestie is om bij het inlezen van de xml 1 nieuw element aan de uitgevoerde bewerkingen toe te voegen, waarin de naam van de originele xml staat.

De tekst kan dan zijn: 

Originele bestandsnaam: .... .xml

**Comment by copierrj** [comment]
Is het mogelijk hiervoor een voorbeeldbestand te leveren?

**Comment by gerardnienhuis** [comment]
zie #309

**Comment by SandroNeumann** [comment]
Het herhalende element voor dit onderdeel is processStep onder dataQualityInfo/DQ_DataQuality/lineage/LI_Lineage

**Comment by gerardnienhuis** [comment]
Dit onderdeel blijkt niet meer nodig, omdat de xml wordt gebruikt die in de geoweb map aanwezig is. Hierdoor is de noodzaak er niet meer om de naam van de originele xml te weten. Enige nadeel is dat voor beheer de map van "gewone" iso19115 xmls die wel die uuid hebben, het beheer lastig blijft. Je moet die als beheerder dus (eventueel) verwijderen... procesmatig oplossen t.z.t. Moeten xmls wel verwijderd, of kunnen ze gewoon blijven staan? Waarvoor gebruiken we die map met iso19115 xml's nog? Niet in de software vooralsnog. Issue kan dus gesloten
