### ISSUE TITLE
Lettertype in geoportaal

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#351]
Door een foutje in de html is het lettertype op het geoportaal (dus de voorkant, niet het beheer) tot nu toe niet verdana, maar helvetica geweest. Tot dus de recente versie die nu op acceptatie staat. Ik vermoed dat dit bijgedragen heeft aan het meer onrustige karakter, want bij verdana liggen de tekens wat meer uit elkaar. Je kunt dit vergelijken tussen acceptatie en productie. Op acceptatie is het verdana, productie is helvetica. De titel van de pagina in de balk is goed in het oog springen vergelijkingsmateriaal.

https://acc-www.geoportaaloverijssel.nl/
https://www.geoportaaloverijssel.nl/

**Comment by gerardnienhuis** [comment]
Dat scheelt inderdaad veel, die verschillende lettertypes. Het is goed dat het is ontdekt. Bedoeling is om het lettertype van de huidige versie 1.1.0 te blijven gebruiken, ook voor versie 1.1.1.

**Comment by gerardnienhuis** [comment]
ziet er weer gewoon normaal uit, voor zover ik kan zien. Issue kan gesloten
