### ISSUE TITLE
help tekst download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#352]
De helptekst bij het download scherm veranderen, tekst staat hieronder.

De tekst was:

## **Gebruikershandleiding (vette tekst)**

Een geldig e-mailadres is in het formaat gebruikersnaam@voorbeeld. Er wordt gecontroleerd of er een @ in staat en of daar voor en achter tekst staat. Alle overige typefouten worden niet gecontroleerd.
Bij de e-mail wordt een metadata-info bestand meegeleverd. Deze kan alleen in Internet Explorer en Firefox bekeken worden.
De bestanden worden via het Geoportaal van Overijssel beschikbaar gesteld.
De gegevens zijn gemaakt voor eigen (intern) gebruik door de provincie Overijssel.
Zijn er suggesties of vragen, neem dan contact op met beleidsinformatie@overijssel.nl

De tekst moet worden:

## **Toelichting bij downloaden van bestanden.**

Deze gegevens worden beschikbaar gesteld vanuit het Geoportaal van Overijssel: http://www.geoportaaloverijssel.nl
Veel bestanden uit het Geoportaal kan je downloaden.
Je kan deze informatie daarna zelf verder bewerken, analyseren of weergeven.
Precies zoals jij dat wilt, voor je eigen doeleinden.

Voor gebruik van dit soort bestanden is speciale software nodig.
Dat wordt een GIS genoemd (Geografisch Informatie Systeem). Veel gebruikte systemen zijn Arcgis en QGis.
Voor meer informatie over dit soort systemen, zie: https://nl.wikipedia.org/wiki/Geografisch_informatiesysteem.

Bij de download kan je kiezen uit verschillend formaten:

**SHP** (shape, veel gebruikt open formaat, ontwikkeld door Esri)
**GML** (Geography Markup Language, een open standaard voor GIS data)
**KML** (Keyhole Markup Language, te gebruiken in Google Earth)
**DXF** (Drawing exchange format, veel gebruikt formaat voor AutoCad)

Je kunt zelf kiezen welk bestandsformaat het beste past bij de software die jij gebruikt.

Heb je niet de beschikking over dergelijke GIS-software, maar wil je toch kaarten zien die gemaakt zijn door de provincie Overijssel?
Dat kan, omdat er ook veel pdf-bestanden beschikbaar gesteld worden.
Kijk daarvoor verder in het Geoportaal van Overijssel en selecteer daar alleen “statische kaarten”.

Bij de download wordt de beschrijving van het bestand meegeleverd. Dit staat in het bestand leesmij.xml.
Open je dit bestand in Internet Explorer of Firefox dan wordt de beschrijving het beste weergeven (met opmaak).
Een aantal andere browsers laten alleen de technische versie (xml) zien als je dit bestand opent.

In het Geoportaal van Overijssel staan actuele kaarten en beschrijvingen van die kaarten.
Ter referentie zijn vaak ook nog oudere kaarten beschikbaar gesteld.
De provincie Overijssel stelt zoveel mogelijk kaarten als "open data" voor iedereen beschikbaar.
Heeft u suggesties of vragen? Stuur dan een email naar beleidsinformatie@overijssel.nl
Zie proclaimer: http://www.overijssel.nl/algemene-onderdelen/proclaimer

**Comment by NicoEilers** [comment]
werkt goed, Issue kan gesloten worden.
