### ISSUE TITLE
Raster WFS service niet bruikbaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#353]
In het externe Geoportaal wordt de service met rasters beschikbaar gesteld. De WFS versie van deze service lijkt geen of onjuiste informatie mbt de lagen te bevatten. Mogelijk omdat deze lagen helemaal niet als data beschikbaar gesteld mogen worden (lagen bevatten niet allemaal de term downloadable data). 

Downloaden via NGR en data.overheid.nl gaan dus ook fout en zijn als fout terugvindbaar in de rapportage van de downloads (zowel 2-11-16 als 3-11-16 te zien, bij downloadpogingen van AHN5).

Ook inlezen van deze WFS in Qgis (versie 2.14) levert foutmeldingen op.

Hoe moet dit opgelost worden? De WMS werkt wel correct van deze service en mag wel beschikbaar gesteld worden. Aanpassing in publicatieomgeving, zodat WMS wel en WFS niet aangemaakt wordt als openbare service. En dan de WFS alleen voor de beschermde omgevingen? En hoe werkt dat dan in relatie tot het Geoportaal?

**Comment by copierrj** [comment]
Voorstel aanpassing in publicatieomgeving: WFS url niet opnemen in dataset metadata voor raster dataset.

**Comment by gerardnienhuis** [comment]
Stel je dan wel de download en WMS url beschikbaar via de stylesheet?

Ik denk dat alleen WMS beschikbaar stellen wel zou kunnen werken, maar dan moet zowel WFS als download url niet zichtbaar zijn 

merk op: ook in Geoportaal bij zoekresultaten moet "download" niet zichtbaar zijn in dat geval.

**Comment by copierrj** [comment]
@SandroNeumann: kun jij nagaan wat er moet gebeuren om de "download" optie in het Geoportaal niet te tonen voor bepaalde datasets?

**Comment by SandroNeumann** [comment]
De download links in het geoportaal en de stylesheets worden alleen getoond wanneer het ruimtelijk schema "vector" is. Dus de download links zijn bij raster datasets en tabellen niet zichtbaar.

**Comment by HermanAssink** [comment]
@gerardnienhuis Voor de duidelijkheid: download van rasterdata is nu niet mogelijk o.a. omdat de downloadfunctie een WFS nodig heeft en rasterdata niet via een WFS aangeboden kan worden. Daarvoor is issue #282 . Dus voor nu: geen WFS url opnemen in de metadata XML.

**Comment by gerardnienhuis** [comment]
Werkt voor een deel goed: WFS en downloadlink is inderdaad niet zichtbaar bij de details van een laag in een bepaalde service, als het om rasters gaat. Maar de WMS url had wel zichtbaar mogen zijn. Die staat nu ook niet in de metadata bij DETAILS. Wel kan je de WMS zien bij de services zelf, en het bekijken via de viewer kan ook. Merk op: ook de url naar de viewer ontbreekt bij DETAILS) bij rasters. Is dat oplosbaar?

**Comment by SandroNeumann** [comment]
Dat is een overblijfsel van de eerdere oplossing. Dit zou in de stylesheet opgelost moeten worden. In de XML is de WMS en de link naar de viewer wel beschikbaar.

**Comment by gerardnienhuis** [comment]
OK, helder. Ik wacht dan de nieuwe versie van de stylesheet af, om dit daarna nog verder te testen.

**Comment by gerardnienhuis** [comment]
Wat nog niet werkt is weergave van de url naar de viewer en de wms zelf bij DETAILS in de stylesheet van een laag, getest bij service "raster"

voorbeeld:

Bestandsnaam: Bathymetrische kaart IJsseldelta
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/6460f2f8-103e-4bca-aee6-c272ad866ab0.xml

nb: viewer werkt correct, als je bijvoorbeeld link gebruikt bij het onderdeel WAT van deze kaart:
http://acc-services.geodataoverijssel.nl/viewer/layer/Raster/B7_Bathymetrische_kaart_IJsseldelta

**Comment by SandroNeumann** [comment]
De links worden alleen getoond als er downloadable data in de xml staat. Die conditie kan nu weggehaald worden?

**Comment by gerardnienhuis** [comment]
ja, de wms moet getoond worden als die er is. Dus als de viewer werkt, dan moet je ook link naar wms hebben. Merk op: de url van de  wfs moet alleen getoond worden als deze downloadbaar is.

**Comment by SandroNeumann** [comment]
De download link moet neem ik aan ook alleen getoond worden als de data downloadbaar is.

**Comment by gerardnienhuis** [comment]
klopt helemaal: download link zonder dat er iets te downloaden is, is voor gebruikers erg verwarrend. Dus downloadlink is alleen aanwezig als de WFS er is.
Vergelijkbaar met de viewer: de link naar de viewer wordt alleen getoond als de WMS er is.

**Comment by SandroNeumann** [comment]
De stylesheet is aangepast.

**Comment by gerardnienhuis** [comment]
Het werkt nu goed. Dit is gecontroleerd bij meerdere lagen die in de service "raster" zijn opgenomen.
Link naar wms en viewer bestaan wel, link naar download of wfs staat er niet in. 
Issue kan gesloten
