### ISSUE TITLE
Persoonsgegevens niet doorgeven voor harvesten PGR, NGR enz

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#355]
De bedoeling is, dat interne contactpersonen niet zichtbaar zijn in het externe Geoportaal. Maar ze moeten ook niet door andere systemen geharvest worden. Mogelijk moet er dus een folder gemaakt worden, waarvan uit de harvest kan plaatsvinden. In die folder moet dan alleen de informatie van de datasets staan, die wel extern beschikbaar mogen komen. 

Nu is dat niet het geval en kunnen interne contactpersonen in NGR en data.overheid.nl teruggevonden worden. Dat is niet de bedoeling.

**Comment by HermanAssink** [comment]
Oplossing is om interne contactpersonen alleen op te nemen in de xml als die xml wordt opgevraagd door een "intern" IP-adres,

**Comment by gerardnienhuis** [comment]
alleen oppakken in 1.1.2 als er nog tijd over is, anders pas in latere versie, bijvoorbeeld 1.2 oppakken

**Comment by gerardnienhuis** [comment]
Omdat xml wordt gemaakt door publicatieomgeving is hier label "publicatieomgeving" toegevoegd.

**Comment by copierrj** [comment]
Klopt het dat onder 'interne contactpersonen' de aanvullende (= alle behalve de eerste) point of contacts bedoeld worden?

**Comment by gerardnienhuis** [comment]
@copierrj : je vraagt of alles behalve de eerste point of contacts interne contactpersonen zijn. Volgens mij is dat het geval, maar controleer aub even bij @SandroNeumann : in de stylesheet heeft hij die selectie op de correcte manier uitgevoerd. Ik wil graag dat op dezelfde manier het nu ook doorgegeven wordt naar de sites die de metainformatie harvesten.

**Comment by NicoEilers** [comment]
In het NGR onderstaande link aangetroffen; Rioolwaterzuiveringsinstallaties in Overijssel
Hier in zijn nog wel de persoonsgegevens te vinden.
http://www.nationaalgeoregister.nl/geonetwork/srv/dut/search#|554c02a4-3c12-4197-b4dd-98ccf00fdc1c
eigenaar:
Naam Contactpersoon
Beek, Mw. Astrid van 

Verantwoordelijke organisatie bron *
Provincie Overijssel: eenheid Publieke Dienstverlening 

Adres
Postbus 10078 
Plaats
Zwolle 
Provincie
Overijssel 
Postcode
8000 GB 
Land
The Netherlands 
E-mail *
AM.v.Beek@overijssel.nl 
Hyperlink

**Comment by NicoEilers** [comment]
In het PGR aangetroffen:
Verantwoordelijke organisatie bron [2] 



Naam organisatie: 

Provincie Overijssel: eenheid Publieke Dienstverlening


Naam contactpersoon: 

Beek, Mw. Astrid van


Adres: 

Postbus 10078


Plaats: 

Zwolle


Provincie: 

Overijssel


Postcode: 

8000 GB


Land: 

The Netherlands


E-mail: 

AM.v.Beek@overijssel.nl


URL: 

http://www.overijssel.nl
Klik hier om de link te volgen

Rol organisatie: 

eigenaar

**Comment by NicoEilers** [comment]
xml controleren, kan niet via PGR of NGR getest worden, betreft ACC omgeving, en alleen PROD wordt geharvest.

**Comment by HermanAssink** [comment]
N.B. Om dit te kunnen controleren moet van een extern IP-adres gebruik gemaakt worden.

**Comment by gerardnienhuis** [comment]
ik kan niet in het huidige Geoportaal makkelijk bij de xml. Maar de leesmij.xml die geleverd wordt bij de download, die is wel bruikbaar, denk ik.

**Comment by gerardnienhuis** [comment]
probleem met xml is opgelost: BRON bekijken kan wel in FF, Chrome en Opera, niet in IE: ziet er nu goed uit, Rioolwaterzuiveringsinstallaties nu zonder intern contactpersoon. 

issue kan gesloten
