### ISSUE TITLE
metadata niet zichtbaar 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#356]
https://www.geoportaaloverijssel.nl/metadata/dataset/e7aea0ac-20dd-4cdc-a694-bd5e2d33bf5e

Bestand Bodemgebruik In Overijssel 2000; BBG2000 (27-01-2016, Provincie Overijssel) 

metadata geeft wit scherm

in externe portal is geen metainfo van  beveiligde service te zien
dat had wel gemoeten

**Comment by SandroNeumann** [comment]
De 404 komt omdat de service waar de dataset in zit vertrouwelijk is. Voor extern bestaat die dataset feitelijk niet. Dat je dat record vervolgens wel kunt vinden in het geoportaal komt omdat in de XML 'geoportaal extern' aangegeven is.

**Comment by gerardnienhuis** [comment]
maar als je in het geoportaal een dataset hebt, dan wil je altijd metainfo laten zien. Wat nu komt is een wit scherm, en erg verwarrend voor gebruikers.

**Comment by gerardnienhuis** [comment]
hieronder een voorbeeld, je ziet zelfs voorbeeldplaatje en stukje samenvatting, alleen klikken op meer informatie geeft fout (wit scherm bij IE)

![meer_informatie_wit_scherm](https://cloud.githubusercontent.com/assets/9005444/20177412/e8c26ee6-a74c-11e6-97b8-22f892d61235.jpg)

**Comment by HermanAssink** [comment]
Het betreft metadata van een dataset die vertrouwelijk is (niet downloadable data), maar waarvan de metadata wel geraadpleegd mag worden door externen (Geoportaal extern). De metadata kan wel in het Geoportaal worden gevonden, maar bij klikken op "Meer informatie" komt er een leeg scherm, terwijl de volledige metadata werd verwacht. Vraag die hierbij opkomt is of de links naar de beveiligde services in deze metadata getoond mogen worden.

**Comment by gerardnienhuis** [comment]
wens is dat bij de dataset niet downloadable is, maar wel gepubliceerd is  in beveiligde services:

niet in stylesheet zichtbaar
service urls niet zichtbaar in metainformatie
service urls niet aanwezig in xml's die geharvest kunnen worden

wel is wens dat je alle metainformatie voor de rest ziet, als je op "meer informatie" klikt.

**Comment by gerardnienhuis** [comment]
Onderstaande oplossing is overwogen maar levert teveel praktische problemen op. 

Onderstaande oplossing wordt dus NIET uitgevoerd:

Dit probleem zou zijn op te lossen door de datasets die in beveiligde lagen komen, alleen intern te tonen. Het is te overwegen om dit eerst te proberen.

Suggestie van André:

De oplossing is volgens mij vrij simpel. De huidige atlassen draaien op een versie van geoserver die in huis draait. Deze is nu openbaar. Alles wordt getoond. Op het moment dat wij deze omgeving over gaan zetten naar de nieuwe publicatieomgeving (extern) kunnen wij deze geoserver zo configureren dat alles alleen intern gezien kan en mag worden. Wij kunnen dan een viewer maken die gebruik maakt van de services op deze geoserver zijn geplaatst.

Voorwaarde is dan dat de metadata, van deze beveiligde (niet extern te tonen) datasets, alleen op de interne portal getoond mag worden.

Het gaat volgens mij alleen om de volgende constraints:
-       Alleen voor intern gebruik
-       Niets uit deze publicatie mag worden verveelvoudigd en/of openbaar gemaakt worden d.m.v. druk, fotokopie, internet of op welke andere wijze ook, zonder voorafgaande schriftelijke toestemming van de Stichting Landelijk Fietsplatform. De gegevens uit deze publicatie mogen niet worden doorgestuurd naar andere instanties.
-       Alleen bedoeld voor intern gebruik (team Grondzaken)
-       uitsluitend voor intern WK gebruik
-       betreft vertrouwelijke informatie

Klein nadeel is natuurlijk wel dat je dubbel beheer krijgt, en nog verdere complexe zaken voor geoportaalbeheerders. ook download is nu dan niet mogelijk natuurlijk. Als noodoplossing zou het wel kunnen werken, denk ik.

**Comment by gerardnienhuis** [comment]
Klein nadeel is natuurlijk wel dat je dubbel beheer krijgt, en nog verdere complexe zaken voor geoportaalbeheerders. ook download is nu dan niet mogelijk natuurlijk. Als noodoplossing zou het wel kunnen werken, denk ik.

**Comment by gerardnienhuis** [comment]
conclusie: aan de kant van Geoportaal moet oplossing komen, met als eisen:

1) wens is  dat je alle metainformatie voor de rest ziet, als je op "meer informatie" klikt.
zowel intern als extern.

2) extern alleen metainfo zichtbaar als "geoportaal extern" is ingevuld, alle andere situaties metainfo alleen intern zichtbaar.

3) wens is dat bij de dataset niet downloadable is, maar wel gepubliceerd is in beveiligde services, dan moet gelden dat:
- download url niet zichtbaar in stylesheet
- service urls niet in stylesheet zichtbaar
- service urls niet zichtbaar in metainformatie
- service urls niet aanwezig in xml's die geharvest kunnen worden

**Comment by gerardnienhuis** [comment]
nb: de xml moet dus minder informatie bevatten, en dat kan door aanpassing binnen de publicatieomgeving

**Comment by gerardnienhuis** [comment]
intern wel alle info beschikbaar, geldt alleen voor extern geoportaal

**Comment by gerardnienhuis** [comment]
testsituaties in acceptatieomgeving, die nu (in versie 1.1.1.) nog fout gaan:

Perceelsregistratie (BRP) peildatum 15-05-2015 
(26-10-2016, Ministerie van EZ - Rijksdienst voor Ondernemend Nederland (Dienst Regelingen))
https://www.geoportaaloverijssel.nl/metadata/dataset/80bbe645-1b52-48b3-9d08-b3883167e0a4

Landelijke grondgebruikskartering Nederland 2003 (29-08-2016, Provincie Overijssel)
https://www.geoportaaloverijssel.nl/metadata/dataset/ea2705b2-40e7-476e-9513-39755dcc50d3

Landelijk Grondgebruik Nederland - LGN7 (29-08-2016, Alterra, Wageningen UR)
https://www.geoportaaloverijssel.nl/metadata/dataset/a684342a-98db-45b4-adab-2147d5939412

**Comment by copierrj** [comment]
Doordat de acceptatieomgeving wat betreft databaseinhoud achterloopt op productie trad het probleem daar niet op bij het genoemde dataset (Bodemgebruik In Overijssel 2000). 

Hierbij een aantal datasets waar op productie het probleem bestaat wat nu op acceptatie verholpen is:

https://www.geoportaaloverijssel.nl/metadata/dataset/3a7479e7-2a72-479f-bd97-bd66ffd98338
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/3a7479e7-2a72-479f-bd97-bd66ffd98338

https://www.geoportaaloverijssel.nl/metadata/dataset/67e1bf90-ac93-4b55-9479-bbb9c1e6e2a2
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/67e1bf90-ac93-4b55-9479-bbb9c1e6e2a2

https://www.geoportaaloverijssel.nl/metadata/dataset/c4842560-8e77-41f5-b9f9-26d90a64b26b
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/c4842560-8e77-41f5-b9f9-26d90a64b26b

**Comment by gerardnienhuis** [comment]
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/34e17781-1cac-4c4d-ab59-6a22f76cdad4 

werkt nu ook weer goed, andere bovenstaande links ook getest, werkt goed, issue kan gesloten
