### ISSUE TITLE
Url metadata in downloadscherm

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#357]
Het downloadscherm is zichtbaar als je data wilt downloaden vanaf NGR of http://www.data.overheid.nl 

Maar je ziet daar niet wat de oorspronkelijke metadata is. Voor een deel wordt dat slechts weergegeven. 
Om bezoekers vanaf NGR of data.overheid.nl meer info te geven, zou een link naar de url van de metadata in het Geoportaal een goed idee zijn.

Extra tekst wordt dan:
Metadata: https://www.geoportaaloverijssel.nl/metadata/dataset/dbdfb72b-ec33-4025-b599-969efbd50e11

Die tekst kan geplaatst worden boven de nu al bestaande extra tekst, waarbij het aantal witregels daarboven wel gelijk blijven om afstand te laten bestaan, zie X in plaatje

![url_in_downloadscherm](https://cloud.githubusercontent.com/assets/9005444/20207333/cb92644e-a7e6-11e6-9970-8eaecdacdc7c.jpg)

**Comment by gerardnienhuis** [comment]
Nog mooier is het als er staat:

De volledige metainformatie van dit bestand kunt u hier vinden.

(en dan "metainformatie van dit bestand kunt u hier" aanklikbaar maken en naar de link gaan in nieuw scherm)

**Comment by SandroNeumann** [comment]
@gerardnienhuis Moet het alleen in het formulier terugkomen of ook in de feedback (de pagina die verschijnt wanneer je op download klikt)?

**Comment by gerardnienhuis** [comment]
Goede vraag: in dat feedbackformulier staat bijna dezelfde tekst. Ik denk dat het voor een gebruiker wel zo makkelijk is, als dus ook die extra regel wordt toegevoegd, dus op zelfde plaats en zelfde manier als in downloadscherm.

**Comment by NicoEilers** [comment]
werkt goed Issue kan gesloten worden.
