### ISSUE TITLE
Rapportage Geodata kolom intern of externe portaal zichtbaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#359]
Graag in rapportage geodata 1 kolom toevoegen: intern of extern, dus staat metadata zichtbaar alleen in intern geoportaal of ook in extern geoportaal

nb: als het extern aanwezig is, dan is het automatisch ook intern aanwezig

**Comment by robstek** [comment]
Kolom "geoportaal_extern" toevvoegen: ja / nee.
ja indien vlag "geoportaal extern" (technisch: metadata_confidentional==true)

**Comment by gerardnienhuis** [comment]
metadata_publiek is aanwezig. werkt goed, issue kan gesloten
