### ISSUE TITLE
Uitleg over geoJSON laten verwijzen naar zelf te maken pagina ipv PDOK + Brentjes

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#361]

**Comment by gerardnienhuis** [comment]
nb: tekst op idgis website dus in help alleen link aanpassen

**Comment by HermanAssink** [comment]
Dit is de  link naar de [betreffende wiki pagina](https://github.com/IDgis/geo-publisher/wiki/WFS---JSON-als-output-format) .

**Comment by gerardnienhuis** [comment]
Deze versie bevat nog niet heel veel praktische info, b.v. hoe je e.e.a dan in open layers kan verwerken,
een wat meer  uitgewerkt voorbeeld op basis van de info die al wel is gegeven zou een goed idee zijn,
b.v.
 "http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wfs?service=WFS&version=2.0.0&
request=GetFeature&typename=B51_recreatie:B5_Fietsroutes_in_Overijssel&count=100&
startindex=1&outputformat=json"
en dan voorbeeld met integratie tot eindproduct (dus b.v. kaartje)

**Comment by NicoEilers** [comment]
Tekst is nog te verwarrend:

Er staat nu:

WFS JSON als output format:

GML is voor veel webontwikkelaars niet de eerste keus. JSON en GeoJSON zijn laagdrempeliger waardoor veel webontwikkelaars daar de voorkeur aan geven. Gelukkig is het GeoJSON formaat ook beschikbaar bij de WFSen die GeoPublisher aanbiedt. Gebruik daarvoor de parameter outputformat=json bij een GetFeature request en je krijgt GeoJSON terug. Voorbeeld:

Fietsroutes in GeoJSON


De link naar Fietsroutes in GeoJSON werkt niet

WFS JSON als output format: is overbodige tekst

**Comment by NicoEilers** [comment]
nb: klik op Fietsroutes in GeoJSON levert fout op, met als details:

INFO PLATFORMVERSIE
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.34209
	System.Deployment.dll 		: 4.0.30319.34244 built by: FX452RTMGDR
	clr.dll 			: 4.0.30319.34209 built by: FX452RTMGDR
	dfdll.dll 			: 4.0.30319.34244 built by: FX452RTMGDR
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

BRONNEN
	Implementatie-url			: http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wfs?service=WFS&version=2.0.0&request=GetFeature&typename=B51_recreatie:B5_Fietsroutes_in_Overijssel&count=100&startindex=1&outputformat=json

FOUTSAMENVATTING
	Hieronder ziet u een overzicht van de fouten. Verderop in het logboek vindt u nadere details over deze fouten.
	* Activering van http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wfs?service=WFS&version=2.0.0&request=GetFeature&typename=B51_recreatie:B5_Fietsroutes_in_Overijssel&count=100&startindex=1&outputformat=json heeft tot een uitzondering geleid. De volgende berichten voor mislukte acties zijn aangetroffen:
		+ Er is een uitzondering opgetreden bij het lezen van het manifest van http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wfs?service=WFS&version=2.0.0&request=GetFeature&typename=B51_recreatie:B5_Fietsroutes_in_Overijssel&count=100&startindex=1&outputformat=json: mogelijk is het manifest ongeldig of kan het bestand niet worden geopend.
		+ Gegevens op hoofdniveau zijn ongeldig. Regel 1, positie 1.

SAMENVATTING MISLUKTE TRANSACTIES ONDERDELENARCHIEF
	Er zijn geen transactiefouten aangetroffen.

WAARSCHUWINGEN
	Er werden geen waarschuwingen weergegeven bij deze bewerking.

VOORTGANGSSTATUS BEWERKING
	* [5-12-2016 13:42:51] : De activering van http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wfs?service=WFS&version=2.0.0&request=GetFeature&typename=B51_recreatie:B5_Fietsroutes_in_Overijssel&count=100&startindex=1&outputformat=json is gestart.

FOUTDETAILS
	De volgende fouten zijn aangetroffen bij deze bewerking.
	* [5-12-2016 13:42:52] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Er is een uitzondering opgetreden bij het lezen van het manifest van http://services.geodataoverijssel.nl/geoserver/B51_recreatie/wfs?service=WFS&version=2.0.0&request=GetFeature&typename=B51_recreatie:B5_Fietsroutes_in_Overijssel&count=100&startindex=1&outputformat=json: mogelijk is het manifest ongeldig of kan het bestand niet worden geopend.
		- Bron: System.Deployment
		- Stack-tracering:
			bij System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			bij System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			bij System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			bij System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			bij System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Ingesloten uitzondering ---
		System.Xml.XmlException
		- Gegevens op hoofdniveau zijn ongeldig. Regel 1, positie 1.
		- Bron: System.Xml
		- Stack-tracering:
			bij System.Xml.XmlTextReaderImpl.Throw(Exception e)
			bij System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
			bij System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
			bij System.Xml.XmlTextReaderImpl.ParseDocumentContent()
			bij System.Xml.XmlTextReaderImpl.Read()
			bij System.Xml.XmlTextReader.Read()
			bij System.Deployment.Application.ManifestValidatingReader.XmlFilteredReader.Read()
			bij System.Xml.XmlCharCheckingReader.Read()
			bij System.Xml.XsdValidatingReader.Read()
			bij System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)

TRANSACTIEDETAILS ONDERDELENARCHIEF
	Er is geen transactie-informatie beschikbaar.

**Comment by HermanAssink** [comment]
In Chrome en Firefox werken de links door erop te klikken. In IE moet je voor "opslaan als" kiezen, waarna de GeoJSON output in een bestand wordt bewaard.
N.B. Deze helptekst is bedoeld voor web-ontwikkelaars en lijkt me daarom voorlopig duidelijk genoeg. Inhoudelijk staat er hetzelfde in als in de pagina's van pdok en Thijs. Waarschijnlijk dat Provincie Utrecht opdracht geeft dit punt, de bruikbaarheid voor web-ontwikkelaars, verder uit te werken.

**Comment by gerardnienhuis** [comment]
Getest, werkt inderdaad goed. De verwarring die wordt veroorzaakt komt grotendeels door de opmaak. Er zijn 2 regels die vet (bold) moeten worden gemaakt. In de help bij het zoeken staat dit al wel goed, maar bij het onderdeel "over deze site" nog niet.

Er staat nu:

Tips voor specialisten:

Er worden ook WMS en WFS services via het Geoportaal ontsloten. Deze kun je direct in je eigen GIS applicatie gebruiken. Maak je je eigen app en wil je Geojson gebruiken, dan kan dat ook. Gebruik hiervoor outputformat=json als je een Getfeature request doet op een WFS. Meer tips over Geojson zijn te vinden via onderstaande links:

WFS JSON als output format:


Dat moet worden:


**Tips voor specialisten:**

Er worden ook WMS en WFS services via het Geoportaal ontsloten. Deze kun je direct in je eigen GIS applicatie gebruiken. Maak je je eigen app en wil je Geojson gebruiken, dan kan dat ook. Gebruik hiervoor outputformat=json als je een Getfeature request doet op een WFS. Meer tips over Geojson zijn te vinden via onderstaande links:

**WFS JSON als output format:**

**Comment by gerardnienhuis** [comment]
Merk op: de fout in IE is nog niet opgelost, zie onderstaand plaatje, als ik op Fietsroutes klik, dan kan ik wel openen, maar krijg vervolgens altijd een foutmelding, ik kan dan niets meer doen, behalve op details klikken...

nb: getest intern Overijssel en ook extern (thuis, niet IP adres van provincie maar eigen provider).

![fout_ie_klik_fietsroutes](https://cloud.githubusercontent.com/assets/9005444/20961290/a26ee492-bc64-11e6-9688-1a0dcbaaffcf.jpg)

**Comment by HermanAssink** [comment]
Inderdaad, het was ook niet mijn bedoeling om dit op te lossen. Voor een ontwikkelaar lijkt me dit geen probleem.

**Comment by HermanAssink** [comment]
Ik hoop dat Utrecht opdracht geeft om de bruikbaarheid (in brede zin) voor web-ontwikkelaars te verbeteren.

**Comment by gerardnienhuis** [comment]
naast de (hiervoor genoemde) aanpassing van tekst (**bold** maken 2 regels) hier het voorstel voor aanpassing tekst ivm fout IE:

er staat nu:

outputformat=json bij een GetFeature request en je krijgt GeoJSON terug. Voorbeeld:

Fietsroutes in GeoJSON

er komt te staan:

outputformat=json bij een GetFeature request en je krijgt GeoJSON terug.
Voorbeeld (voor Firefox, Chrome, Safari en Opera, niet geschikt voor IE):

Fietsroutes in GeoJSON

**Comment by gerardnienhuis** [comment]
tekst ziet er nu goed uit, issue kan gesloten
