### ISSUE TITLE
Productieomgeving publicatieomgeving naar acceptatie kopieren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#362]
Bij het testen van versie 112 is het belangrijk dat we geen last hebben van fouten uit het verleden. De huidige acceptatieomgeving is niet meer geschikt om goede testen uit te voeren. Je zou dan problemen gaan vinden, die achterhaald zijn en in de huidige productieomgeving nooit meer zullen voorkomen. 

Daarom is het de wens om de data van de huidige productieomgeving van de publicatieomgeving te kopieren naar de acceptatieomgeving. Hierdoor kunnen de testen met het Geoportaal gebaseerd worden op de echte goede situatie.

**Comment by copierrj** [comment]
We kunnen eenvoudig de inhoud van de publicatieomgeving overzetten naar acceptatie. Bedenk hier echter wel dat jullie acceptatieomgeving (database + metadata) achter kan (zal?) lopen op jullie productieomgeving. Dit kan voor ruis (in de vorm van veel onverwachte structuurwijzigingen) zorgen. Aanbevolen is hierom om ook aan jullie kant acceptatie bij te werken.

**Comment by HermanAssink** [comment]
@gerardnienhuis , @andreweijmer : Zojuist heb ik telefonisch contact gehad met Reinder Hoekstra. Hij vertelde dat het kopiëren van de data van productie naar acceptatie momenteel aan jullie kant niet mogelijk is, ivm onacceptabele systeembelasting. Daarom lijkt het mij verstandig dat wij aan onze kant deze kopieeractie ook niet uitvoeren om inconsistenties tussen de data bij jullie en ons te voorkomen. Dit zou namelijk veel ruis geven.

**Comment by gerardnienhuis** [comment]
Jammer, wordt wel lastiger testen, vermoed ik. Vooral https://github.com/IDgis/geoportaal-test/issues/356 kan ik nu niet goed testen, omdat ik vrees dat in acceptatie geen lagen in beveiligde services staan. 

Dat blijkt gelukkig mee te vallen, ik heb minstens 3 lagen gevonden waarbij de metadata nu niet goed wordt weergegeven. Testen kan dus doorgaan wat dit betreft.

**Comment by gerardnienhuis** [comment]
Lijkt wel zinvol om voor milestone 1.2. uit te voeren. Niet zinvol voor huidige milestone 1.1.2. i.v.m. problemen aan kant van Overijssel op dit moment. 

Milestone op 1.2. gezet.

**Comment by SandroNeumann** [comment]
Dit hebben we een tijd terug gedaan.

**Comment by gerardnienhuis** [comment]
correct, blijkt goed te werken, issue kan gesloten (met excuses dat het niet eerder is gedaan).
