### ISSUE TITLE
Generieke teksten in Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#363]
Als meer organisaties van het Geoportaal gebruik gaan maken, is het niet logisch dat op allerlei plekken naar de provincie Overijssel wordt verwezen. Helemaal anoniem maken kan niet, maar er kan wel op een aantal plekken iets worden veranderd. Hieronder eerst wat moet blijven, om de herkenbaarheid van de provincie intact te houden. Daaronder de plaatsen waar aanpassingen mogelijk zijn.

De tekst "provincie Overijsel" of verwijzing naar email blijft op 4 plaatsen voorkomen:

===================================
### Niet veranderen. Dus laten zoals het nu is
===================================

pagina 1) https://www.geoportaaloverijssel.nl/about

Het Geoportaal van de provincie Overijssel bevat datasets en beschrijvingen van datasets. Deze worden gebruikt door de provincie om het beleid van de provincie te ondersteunen. Zo worden ze gebruikt om kaarten van te maken of om analyses mee uit te voeren.
De provincie Overijssel streeft ernaar om de data en ook de omschrijving bij de data juist en actueel te houden. Mocht je ondanks onze inspanningen toch onvolkomenheden tegenkomen, aarzel dan niet contact met ons op te nemen.

pagina 2) https://www.geoportaaloverijssel.nl/contact

De informatie in het Geoportaal wordt beschikbaar gesteld door het team Beleidsinformatie van de provincie Overijssel.
Heb je vragen, suggesties of tips, aarzel dan niet contact op te nemen.
Stuur je email naar: beleidsinformatie@overijssel.nl

pagina 3) https://www.geoportaaloverijssel.nl/

Zoek en download actuele kaarten en de beschrijving van de kaarten van de provincie Overijssel.

pagina 4) download scherm, b.v.: https://download.geoportaaloverijssel.nl/download/b96d4c68-74ca-47bc-a9af-6b9ac5720f7a

Deze gegevens worden beschikbaar gesteld door het Geoportaal van Overijssel: http://www.geoportaaloverijssel.nl
In het Geoportaal staan actuele kaarten en beschrijvingen van die kaarten.
Ter referentie zijn vaak ook nog oudere kaarten beschikbaar gesteld.
De provincie Overijssel stelt zoveel mogelijk kaarten als "open data" voor iedereen beschikbaar.
Heeft u suggesties of vragen? Stuur dan een email naar beleidsinformatie@overijssel.nl
Zie proclaimer: http://www.overijssel.nl/algemene-onderdelen/proclaimer

===================================
### Aanpassingen:
===================================

https://admin.geoportaaloverijssel.nl/loginhelp

Bestaande tekst:
Gebruik bij het inloggen je emailadres, zoals gebruikt wordt in Overijssel. Je mag zowel hoofdletters als kleine letters gebruiken. p.pietersen@overijssel.nl is goed. En ook P.Pietersen@Overijssel.nl is goed.

Nieuwe tekst:
Gebruik bij het inloggen je werk emailadres. Je mag zowel hoofdletters als kleine letters gebruiken. p.pietersen@werk.nl is goed. En ook P.Pietersen@Werk.nl is goed.

---

https://www.geoportaaloverijssel.nl/about

Bestaande tekst:
Van een aantal datasets is de provincie Overijssel geen eigenaar. Meestal zijn hierbij dan beperkingen voordat ze gedeeld mogen worden met anderen. Deze beperkingen staan ook in de beschrijving bij de datasets.

Nieuwe tekst:
Van een aantal datasets zijn wij geen eigenaar. Meestal zijn hierbij dan beperkingen voordat ze gedeeld mogen worden met anderen. Deze beperkingen staan ook in de beschrijving bij de datasets.

---

https://www.geoportaaloverijssel.nl/help

Bestaande tekst:
Handleiding voor het gebruik van het Geoportaal van Overijssel.

Nieuwe tekst:
Handleiding voor het gebruik van het Geoportaal

---
https://www.geoportaaloverijssel.nl/help

Bestaande tekst:
Het Geoportaal is bedoeld voor het beheer en het beschikbaar stellen van kaarten die de provincie Overijssel gebruikt.

Nieuwe tekst:
Het Geoportaal is bedoeld voor het beheer en het beschikbaar stellen van kaarten.

---

https://www.geoportaaloverijssel.nl/help

Bestaande tekst:
Heb je niet de beschikking over dergelijke GIS-software, maar wil je toch kaarten zien die gemaakt zijn door de provincie Overijssel? Dat kan, omdat er ook veel pdf-bestanden beschikbaar gesteld worden. Zie hiervoor verder bij de toelichting over de “statische kaarten”.

Nieuwe tekst:
Heb je niet de beschikking over dergelijke GIS-software, maar wil je toch kaarten zien? Dat kan, omdat er ook veel pdf-bestanden beschikbaar gesteld worden. Zie hiervoor verder bij de toelichting over de “statische kaarten”.

---

https://www.geoportaaloverijssel.nl/help

Bestaande tekst:
In dit Geoportaal worden niet alleen de datasets maar ook de bijbehorende services getoond. Dat zijn links naar websites, die op een moderne manier dit soort kaarten beschikbaar stellen. In het Geoportaal van Overijssel worden de datasets en ook de bijbehorende services ontsloten. Ook voor het gebruik van services het je een GIS nodig.

Nieuwe tekst:
In dit Geoportaal worden niet alleen de datasets maar ook de bijbehorende services getoond. Dat zijn links naar websites, die op een moderne manier dit soort kaarten beschikbaar stellen. In het Geoportaal worden de datasets en ook de bijbehorende services ontsloten. Ook voor het gebruik van services heb je een GIS nodig.

---

https://www.geoportaaloverijssel.nl/help

Bestaande tekst:
De provincie Overijssel streeft ernaar om de informatie zo goed mogelijk beschikbaar te stellen. We streven naar actualiteit en juistheid bij al onze beschikbare bestanden. En we horen ook graag hoe het nog beter zou kunnen.

Nieuwe tekst:
Wij streven ernaar om de informatie zo goed mogelijk beschikbaar te stellen. We streven naar actualiteit en juistheid bij al onze beschikbare bestanden. En we horen ook graag hoe het nog beter zou kunnen.

---

https://www.geoportaaloverijssel.nl/help

Bestaande tekst:
Heb je vragen over het Geoportaal van Overijssel? Of heb je tips of suggesties? Of wil je op de hoogte blijven van de laatste ontwikkelingen, bijvoorbeeld via de nieuwsbrief?

Nieuwe tekst:
Heb je vragen over het Geoportaal? Of heb je tips of suggesties? Of wil je op de hoogte blijven van de laatste ontwikkelingen?
---

**Comment by gerardnienhuis** [comment]
Hieronder nog een stukje niet generieke tekst, die krijg je als een download om een of andere reden niet is gelukt. Er staat een emailadres is. Ook deze tekst aub niet aanpassen, wat dat betreft.

verbeteren tekst download fout:
Download bestand
404 Niet gevonden

Je bent bezig met het downloaden van de dataset met id: 280e6b1e-730d-4c59-ac0e-cff25f4f4320.xml
Deze dataset kan echter nu niet worden gedownload.
Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem. Of misschien heb je onvoldoende rechten om de download uit te voeren.
Neem voor vragen contact op met **beleidsinformatie@overijssel.nl**

**Comment by gerardnienhuis** [comment]
Merk op dat de helptekst bij het downloaden ook niet generiek is. Dat moet zo blijven omdat dit scherm ook via andere registers zichtbaar is (www.data.overheid.nl bijvoorbeeld). Dan moet je weten wie deze info beschikbaar stelt, dat kan niet anoniem. 

zie ook:

https://github.com/IDgis/geoportaal-test/issues/352

**Comment by HermanAssink** [comment]
Alle teksten waar een verwijzing naar (een contactgegeven van) de bronhouder moet komen, zal dat contactgegeven variabel gemaakt moeten worden zodat we verschil kunnen maken tussen de installaties voor de verschillende bronhouders.

**Comment by gerardnienhuis** [comment]
klinkt ook prima, maar dan hoeven dus geen van de teksten aangepast te worden? Dus ook bovenstaande teksten niet?

**Comment by SandroNeumann** [comment]
Wat in het eerste commentaar onder de kopjes niets veranderen en aanpassingen staat is verwerkt.

Wat niet verwerkt is:
- download email
- download 404
- download help
- download notatie van naam applicatie en versie

Deze punten zijn nu nog steeds zoals ze waren. Hardcoded verwijzingen naar Overijssel. Hier wordt een nieuw issue voor gemaakt.

**Comment by NicoEilers** [comment]
werkt goed: Issue kan gesloten worden.
