### ISSUE TITLE
Tekst als download niet is gelukt duidelijker maken

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#364]
Als een download onverwacht niet is gelukt, dan komt er een tekst op het scherm. Graag deze tekst aanpassen. Voorbeeld:

https://download.geoportaaloverijssel.nl:443/download/280e6b1e-730d-4c59-ac0e-cff25f4f4320

De tekst is nu:

Download bestand
404 Niet gevonden

Je bent bezig met het downloaden van de dataset met id: 280e6b1e-730d-4c59-ac0e-cff25f4f4320.xml
Deze dataset kan echter nu niet worden gedownload.
Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem. Of misschien heb je onvoldoende rechten om de download uit te voeren.
Neem voor vragen contact op met beleidsinformatie@overijssel.nl

De tekst moet worden:

Download bestand is gestopt
Foutmelding: 404 Niet gevonden

Je bent bezig met het downloaden van de dataset: <<< hier bestandnaam neerzetten >>>
Metainformatie:  https://www.geoportaaloverijssel.nl/metadata/dataset/fea85218-3a74-4f37-8e61-ac0ff52b46e1

Deze dataset kan echter nu niet worden gedownload.
Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem.
Of misschien heb je onvoldoende rechten om de download uit te voeren.

Neem voor vragen contact op met beleidsinformatie@overijssel.nl

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Je vraagt om de naam van de dataset en de link naar de metadata te tonen. Maar de reden dat er een 404 foutmelding getoond wordt is omdat de dataset en de metadata niet gevonden kan worden. Dus die informatie is dan niet aanwezig.

**Comment by gerardnienhuis** [comment]
Begrijp ik. Als iets niet kan worden gevonden, dan kan je bij de melding hier niet van gebruik maken.

Voorstel tekst:

De tekst moet worden:

Er is een fout opgetreden.
De download van het bestand is gestopt.

Je was bezig met het downloaden van de dataset: <<< hier id neerzetten >>>
Starttijd van de download: <<<< jaar, maand, dag, uur en seconde neerzetten >>>
Deze actie kan niet succesvol worden afgerond. 

Hiervoor kunnen meerdere redenen zijn:

- Een niet voorzien technisch probleem.
- Onvoldoende rechten om de download uit te voeren.
- Een verouderde downloadlink.

Zoek en download een vergelijkbaar bestand eventueel opnieuw via http://www.geoportaaloverijssel.nl 
Neem voor vragen contact op met de beheerders van het Geoportaal via beleidsinformatie@overijssel.nl

**Comment by SandroNeumann** [comment]
Er is op dat moment geen start tijd van de download. De dataset kan niet worden gevonden, dus de download is nooit gestart. Dus die regel dat begint met "Starttijd van de download" kan niet geïmplementeerd worden.

**Comment by gerardnienhuis** [comment]
jammer, maar als tijd niet beschikbaar is, dan kan je die ook niet vermelden. Dus weglaten. Tekst wordt;


De tekst moet worden:

Er is een fout opgetreden.
De download van het bestand is gestopt.

Je was bezig met het downloaden van de dataset: <<< hier id neerzetten >>>
Deze actie kan niet succesvol worden afgerond.

Hiervoor kunnen meerdere redenen zijn:

- Een niet voorzien technisch probleem.
- Onvoldoende rechten om de download uit te voeren.
- Een verouderde downloadlink.

Zoek en download een vergelijkbaar bestand eventueel opnieuw via http://www.geoportaaloverijssel.nl
Neem voor vragen contact op met de beheerders van het Geoportaal via beleidsinformatie@overijssel.nl

**Comment by gerardnienhuis** [comment]
Hoe zou ik dat moeten testen?

**Comment by SandroNeumann** [comment]
- Service met dataset maken
- Wachten tot het door geoportaal is geharvest, waardoor in het geoportaal een download link bij de dataset te zien is (of de metadata openen, waar het direct te zien is)
- De service uit publicatie halen
- De download zou nu moeten falen

**Comment by gerardnienhuis** [comment]
werkt goed, service uit de lucht gehaald, download lukt ook niet meer
melding wordt:


Download bestand is gestopt

500 Interne server fout


Er ging iets mis bij het verwerken van het verzoek.

Foutcode: @79310doda


Hieronder zou eigenlijk nog een regel tekst moeten staan:


Neem voor vragen contact op met beleidsinformatie@overijssel.nl.
Geef bij uw email ook de foutcode door.

**Comment by gerardnienhuis** [comment]
getest met: https://acc-intern.geoportaaloverijssel.nl/metadata/service/412b6a6e-1d67-45f9-921c-fcb3dd2a645f

B45_ontgrondingen (05-07-2017, Provincie Overijssel) - WFS  
De service bevat informatie over ontgrondingen. Het betreft locaties en zoneringen voor zandwinning en zoutwinning.

**Comment by gerardnienhuis** [comment]
impact is laag, maar doorlooptijd is hoog. We moeten kijken of dit in versie 1.5.5. te realiseren is op een pragmatische manier. Is de inschatting van de impact mogelijk toch anders dan "laag"?

**Comment by SandroNeumann** [comment]
Ik zie dat dit al een keer is opgepakt (label is al een keer op gebruikerstest gezet en er is werk verricht) maar blijkbaar niet volledig naar wens?

Wat is op dit moment de aanpassing die gedaan moet worden?

Impact label pas daarna toekennen.

**Comment by SandroNeumann** [comment]
Dit is de melding bij mislukken van een download:

```
Geachte ${username},

Je download ${featuretype} van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  ${responsecode}
Neem voor meer informatie contact op met kennishub@overijssel.nl.

Het Geoportaal van Overijssel bevat honderden datasets die kunnen worden gedownload.
Ze zijn vrij beschikbaar, voor iedereen om te gebruiken.
Wil je deze datasets bekijken of downloaden, kijk dan bij:
https://www.geoportaaloverijssel.nl .
```

**Comment by gerardnienhuis** [comment]
Deze melding is voorlopig goed genoeg. Dit is al bij een vorige versie geïmplementeerd en hoeft verder nu niet aangepast te worden. Dit issue kan daarom gesloten worden.
