### ISSUE TITLE
Shape met SBN en SBX bestand nodig

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#365]
De download vanuit het Geoportaal levert wel een SHAPE die geschikt is voor het pakket ArcGIS maar een ander pakket (GWSDAT) kan met deze bestanden niet uit de voeten omdat er blijkbaar andere extensie worden verwacht (.shx en .sbn). Hieronder de details.

Is SBN en SBX een bestandstype wat ook kan worden aangeleverd als een shape wordt gedownload?

Van de site: https://www.geoportaaloverijssel.nl/metadata/dataset/bbb2655e-19a6-45ce-a846-0d5bdcf38032 heb ik de benodigde shapefiles kunnen downloaden.

Ik kreeg hiermee de nodige files:
- B3_GrondwaterlichaamPolygon.cst CST-bestand
- B3_GrondwaterlichaamPolygon.prj PRJ-bestand
- B3_GrondwaterlichaamPolygon.dbf DBF-bestand
- B3_GrondwaterlichaamPolygon AutoCAD Shape Source 
- B3_GrondwaterlichaamPolygon AutoCAD Compiled Shape

Echter voor ons programma (GWSDAT) moeten sommige bestanden worden geconverteerd naar de volgende bestanden:
- B3_GrondwaterlichaamPolygon.sbn SBN-bestand
- B3_GrondwaterlichaamPolygon.sbx SBX-bestand
- B3_GrondwaterlichaamPolygon.dbf DBF-bestand
- B3_GrondwaterlichaamPolygon AutoCAD Shape Source 
- B3_GrondwaterlichaamPolygon AutoCAD Compiled Shape

**Comment by gerardnienhuis** [comment]
Dit probleem blijkt alleen betrekking te hebben op GWSDAT. Vooralsnog niet verder oppakken. Issue gesloten

**Comment by HermanAssink** [comment]
ESRI heeft het format van .SBN en .SBX (index bestanden) niet openbaar gemaakt. Daardoor kan het niet door open-source software zoals GeoServer worden aangemaakt.
