### ISSUE TITLE
Updata Geoportaal werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#366]
Vrijdag is er een nieuwe geodata in GISBASIP (intern) geplaatst en gepubliceerd.

B4.lekkages_leidingen_point (b4\b41) 
 ffe44df5-ceb4-4ea3-bd91-b68614d87914.xml
 
Deze xml staat op de juiste plaats, gereed om te harvesten.
Echter, ook na dit weekend is de metainformatie nog steeds niet zichtbaar in het Geoportaal

Reinder heeft gecontroleerd of de harvester aan staat, dat blijkt het geval te zijn
In de publicatieomgeving is de metainformatie ook gewoon te zien.

Wat is hier aan de hand? Hoe zorgen we ervoor dat de metainformatie nu wel goed zichtbaar wordt in het Geoportaal?

**Comment by gerardnienhuis** [comment]
Bestanden zijn nu wel weer zichtbaar. Heeft mogelijk te maken met niet goed werkende verbinding publicatieomgeving. Schijnt week of 2 ook voor te zijn gekomen. Lijkt nuttig om oorzaak hiervan te achterhalen.

**Comment by copierrj** [comment]
We zijn op de hoogte van de zo nu en dan haperende connectie. Wat het probleem triggered is echter nog niet bekend. Zodra we een manier hebben gevonden waarmee we dit issue kunnen reproduceren zullen we dit repareren.

CC: @HermanAssink

**Comment by gerardnienhuis** [comment]
Lijkt me prima. Milestone veranderd van 1.1.2 naar "beheer".

**Comment by gerardnienhuis** [comment]
Probleem blijkt niet meer te bestaan. Issue gesloten
