### ISSUE TITLE
Bij download vanaf intern andere xml als vanaf extern

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#369]
Interne contactpersonen alleen meenemen in leesmij.xml als download is gestart vanaf intern Overijssel. Als download is gestart vanaf extern, dan niet interne contactpersonen in xml zetten

**Comment by copierrj** [comment]
gerelateerd aan: #370

**Comment by gerardnienhuis** [comment]
Test bezig: boomkikkers en gemeentegrenzen lijnen download vanaf extern, daarna vergelijken met download actie vanaf intern.

**Comment by gerardnienhuis** [comment]
is dit niet zelfde issue als #370 ?

**Comment by gerardnienhuis** [comment]
Lijkt nog niet goed te werken: download uitgevoerd van bestand zowel intern als extern geoportaal

Bestandsnaam: Afzetmogelijkheden warmte in stads- en blokverwarming
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50

In de metainfo staat (intern) als contactpersoon: 
Eigenaar van het bestand 
Naam: Provincie Overijssel: eenheid Publieke Dienstverlening
Website:   http://www.overijssel.nl
Naam: Willigenburg, drs. ing. A.K.
Rol: beheerder
E-mail: AK.Willigenburg@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands

Als ik de xml doorzoek, dan vind ik Willigenburg niet terug.
In de xml die via extern geoportaal is gedownload, daar klopt dat
in de xml die via intern geoportaal is gedownload, daar klopt dat niet
in de xml die je krijgt als je intern download, daarin zou Willigenburg aanwezig moeten zijn.

**Comment by gerardnienhuis** [comment]
Zie ook #307 

Op termijn onderzoeken of bij download vanaf intern ook interne contactpersoon moet worden meegeleverd. Nadeel is, dat zo'n bestand "kan gaan zwerven" en dus extern beschikbaar kan komen. Als je intern Overijssel werkt dan heb je ook beschikking over interne portaal. Geen blokkerend probleem meer.

Issue kan gesloten worden.
