### ISSUE TITLE
Zoeken alle inhoud

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#37]
Zoeken moet uitgevoerd worden op alle inhoud, dus zeker ook op "unieke id". Niet alleen samenvatting doorzoeken, maar echt alle "tekst"

Opmerking nr 25 bij testresultaten 3-2-2016

**Comment by gerardnienhuis** [comment]
zoeken geeft nog problemen, zie ook https://github.com/IDgis/geoportaal-test/issues/75

**Comment by gerardnienhuis** [comment]
nogmaals uitgetest, poging werking te begrijpen, lijkt fout te gaan. Tekst met woord "konijn" in 1 van de records opgenomen, zoeken op het woord "konijn" levert alle records (terwijl er slechts 1 is, met dat unieke woord "konijn". nb: ik heb nog meer woorden gezocht, het lijkt wel alsof eerdere zoekresultaten nog bewaard blijven (ook als filter opheffen is ingedrukt tussendoor)

![konijn_gevonden](https://cloud.githubusercontent.com/assets/9005444/13283761/0d016a16-daf0-11e5-9092-4bc1937f043e.jpg)

**Comment by SandroNeumann** [comment]
Je hebt niet goed op de zoekknop geklikt. In de url staat niks achter .nl en de knop filter opheffen is ook niet zichtbaar, wat altijd het geval is bij het uitvoeren van een zoekopdracht. Ik denk dat je bij het klikken op de zoekknop even met de muis versleept en daarmee die knop alleen selecteert en er niet op klikt.

Zie: https://test-admin.geoportaaloverijssel.nl/?text=konijnen

**Comment by gerardnienhuis** [comment]
klopt: is ander probleem: zoektekst invoeren en op enter drukken werkt in ene browser wel en in andere niet

overwegen om deze optie met enter te verwjideren en gewoon met tab naar ander veld en op zoek drukken voor uitvoeren zoekactie

---

Van: SandroNeumann [notifications@github.com]
Verzonden: woensdag 24 februari 2016 12:20
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard)
Onderwerp: Re: [geoportaal-test] Zoeken alle inhoud (#37)

Je hebt niet goed op de zoekknop geklikt. In de url staat niks achter .nl en de knop filter opheffen is ook niet zichtbaar, wat altijd het geval is bij het uitvoeren van een zoekopdracht. Ik denk dat je bij het klikken op de zoekknop even met de muis versleept en daarmee die knop alleen selecteert en er niet op klikt.

Zie: https://test-admin.geoportaaloverijssel.nl/?text=konijnen

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/37#issuecomment-188203399.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
zoeken probleem blijkt niet browserafhankelijk, maar rol-afhankelijk, zie #80 
of zoeken nu echt goed werkt, wordt nader onderzocht.

**Comment by gerardnienhuis** [comment]
is te algemeen issue geworden, daarom hier gesloten
details te zien bij
 #80 
#68 
#71
