### ISSUE TITLE
Bij download vanaf intern ook interne stylesheet meeleveren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#370]
Nu wordt bij downloaden de externe stylesheet meegeleverd in de download, het maakt niet uit of deze vanaf intern of extern wordt uitgevoerd. Vraag is om bij download vanaf intern in de download bestanden ook de stylesheet voor intern mee te leveren, en bij extern de stylesheet voor extern.

**Comment by copierrj** [comment]
Is het OK om bij download vanaf intern de interne metadata (inclusief persoonsgegevens) + interne stylesheet te leveren? Of is het de bedoeling de externe metadata (exclusief persoonsgegevens) te blijven gebruiken in combinatie met de interne stylesheet?

**Comment by copierrj** [comment]
Vraag niet langer relevant, zie nu pas #369

**Comment by robstek** [comment]
Getest met "Aanwijzing foerageergebieden voor ganzen en smienten"

extern:
https://acc-download.geoportaaloverijssel.nl/download/cc887358-bd56-4f5d-a39c-b5c4bf28ab6a

Intern:
https://acc-intern-download.geoportaaloverijssel.nl/download/cc887358-bd56-4f5d-a39c-b5c4bf28ab6a

Bevindingen:

Zowel leesmij.xml extern als intern bevat de tekst :
  ```
    <resourceConstraints>
        <MD_Constraints>
          <useLimitation>
            <gco:CharacterString>Geoportaal extern</gco:CharacterString>
          </useLimitation>
        </MD_Constraints>
      </resourceConstraints>
    <resourceConstraints>
```
intern leesmij.xml bevat niet de string 'intern'.

Verschillen
- Intern heeft een andere leesmij.xml en metadata.xsl in de gedownloade zip.
- Intern leesmij.xml bevat een extra pointOfContact

**Comment by gerardnienhuis** [comment]
Metadata is nu correct vormgegeven: kleuren van leesmij.xml is inderdaad bij interne download zelfde als interne stylesheet. Alleen lijkt interne contactpersoon verdwenen in de xml

Heb getest met
Afzetmogelijkheden warmte in stads- en blokverwarming (08-01-2015, Provincie Overijssel) 
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50
intern contactpersoon is hier Willigenburg
Die naam is wel terug te vinden in de metainfo als je het interne portaal bekijkt, maar die naam is niet meer aanwezig als je de leesmij.xml bekijkt die gemaakt wordt bij de download.

**Comment by SandroNeumann** [comment]
De download link in de metadata linkt door naar de externe download. Als je vanaf hier downloadt krijg je de correcte XML:
https://acc-intern-download.geoportaaloverijssel.nl/download/b2c5f593-de4c-4f7c-9b72-4c0909731a50

**Comment by gerardnienhuis** [comment]
OK, dat is dan nu even niet anders, denk ik. Er is dus ruimte voor verbetering maar het verstoort de werking van het portaal niet. Voor  de werking van het portaal is het belangrijkste, dat de interne contactpersonen niet extern vindbaar zijn. Dat is nu niet het geval en daarom kan dit issue worden gesloten.
