### ISSUE TITLE
Welkom tekst aanpassen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#371]
Tekst in homepagina is nu:

Welkom bij het Geoportaal

Tekst wordt:

Welkom bij het Geoportaal van Overijssel

**Comment by gerardnienhuis** [comment]
Merk op: bij intern geoportaal moet hier nog het woord Intern voor staan. Tekst intern Geoportaal wordt dan: 

Intern: Welkom bij het Geoportaal van Overijssel.

**Comment by gerardnienhuis** [comment]
er ontbreekt, in ieder geval bij het externe geoportaal 1 woord: van

er staat:
Welkom bij het Geoportaal Overijssel

er moet staan: 
Welkom bij het Geoportaal van Overijssel

**Comment by SandroNeumann** [comment]
Het woordje "van" staat er nu tussen.

**Comment by gerardnienhuis** [comment]
is opgelost, issue kan gesloten
