### ISSUE TITLE
Verwijderen bijlage statische kaart geef error

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#372]
Bij een statische kaart zijn meerdere bijlagen toegevoegd. Verwijderen van de laatste 2 geeft een foutmelding.

![oops](https://cloud.githubusercontent.com/assets/9005444/21010041/4069b876-bd4a-11e6-9447-e0adf0909fa0.PNG)

**Comment by gerardnienhuis** [comment]
betreft nummer: 150246

**Comment by SandroNeumann** [comment]
Het komt door een gebrek aan geheugen. Is het enige wat je doet het verwijderen van bijlages? Hoeveel MB's zijn die in totaal?

**Comment by gerardnienhuis** [comment]
Probleem bleek ook al op te treden als je bestand wilde toevoegen. We hebben getest met veel grotere bestanden en dat ging wel goed: wat is hier aan de hand dan?

**Comment by SandroNeumann** [comment]
Meerdere mensen hebben tegelijkertijd iets opgeslagen die de memory heeft overschreden.

**Comment by gerardnienhuis** [comment]
https://admin.geoportaaloverijssel.nl/edit/0afc34da-dd6a-48d1-812e-73ae586794f5

**Comment by gerardnienhuis** [comment]
deze moeten weg: 

legenda150246_3.pdf 0.12 MB  
legenda150246_Achter_de_Voort_3.pdf 0.08 MB

**Comment by SandroNeumann** [comment]
Bij het opslaan worden alle velden van de bijlages in de database opgehaald. Dit is dus ook de inhoud van de bijlage. Dit levert het memory probleem op. Ik begrijp dat dit tot milestone 1.1.3 kan wachten?

**Comment by gerardnienhuis** [comment]
Heeft eigenlijk wel wat haast. Is er niets aan te doen nu? We hebben 1.1.0 getest met veel en grote bestanden en toen was er geen memory probleem. Is er iets veranderd dan? Of is het de grote hoeveelheid kleine bestanden die het probleem oplevert?

**Comment by HermanAssink** [comment]
@gerardnienhuis Voor de duidelijkheid: wil je dat dit tegelijkertijd met 1.1.2 in productie komt?

**Comment by gerardnienhuis** [comment]
Als dat praktisch uitvoerbaar is, dan graag. Mocht dat grote vertragingen opleveren, dan gaan wij werken aan een workaround (speelt slechts bij 1 statische kaart vooralsnog) en kan het in 1.1.3. Ik hoor graag of het vanmiddag bij de oplevering van 1.1.2. meekan, of dat het beter is dit uit te stellen tot oplevering 1.1.3.

**Comment by HermanAssink** [comment]
Het fixen kost niet veel tijd. Willen jullie hetzelfde geval invoeren op de acc.omgeving zodat het daar getest kan worden? Na de lunch staat de nieuwe versie op acc.

**Comment by gerardnienhuis** [comment]
vreemd dat dit nu ook lijkt op te treden bij toevoegen van grote datasets: ik heb er 5 van 22 Mb toegevoegd: bij eerdere testen ging dat goed, als ik deze opsla, dan werkt dat ook, maar als ik er 1 bij wil zetten, dan werkt dat niet meer. Bij eerdere testen (1.1.0) leek dat wel goed te gaan. 

testbestand:
https://acc-admin.geoportaaloverijssel.nl/metadata/0534a67f-667a-4be3-a370-0e5e5b6aa62a

**Comment by gerardnienhuis** [comment]
Probleem is opgelost: 15 bijlagen bij 1 statische kaart toegevoegd, 22 mb per stuk. Niet alleen toevoegen maar ook verwijderen gaat nu weer goed. Issue kan gesloten
