### ISSUE TITLE
Script maken om metadata met attribuutinfo bij Overijssel te kunnen aanvullen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#373]
Overijssel heeft twee zips gestuurd:

-          GeoWeb.zip  (xml-files van metadata met attribuutinformatie)
-          Portal.zip (xml-files van metadata zonder attribuutinformatie)

Portal.zip bevat de metadata zoals die nu door de provider wordt gelezen. GeoWeb.zip bevat de zip met de metadata in het format (met attribuutinfo) zoals deze na realisatie van #4 gelezen moet worden. Vraag is om een script te maken dat een lijst oplevert met alle Oracle tabellen die wel in Portal.zip staan, maar niet in GeoWeb.zip

**Comment by gerardnienhuis** [comment]
Ik denk dat de oplossing, zoals gekozen voor statische kaarten bij oplevering 1.1.0 hier ook kan werken. Wij krijgen een script, wat Reinder hier intern kan installeren. Dat script levert vervolgens een CSV waarin wij als beheerders kunnen zien welke oracle tabellen nog moeten worden bijgewerkt. Niet alles staat nu al in de Geoweb.zip en dat is voor beheerders een klus om zelf uit te voeren. Zo'n CSV met namen van tabellen waarvan de metainfo nog naar de Geowebfolder geschreven moet worden, dat is hiervoor essentieel.

**Comment by NicoEilers** [comment]
merk op: er zitten ook "extra" bestanden in de folder van de geoweb bestanden. Deze hebben dus geen verwijzing meer naar de bestanden in de portal.zip. Het zou heel handig zijn als in de CSV deze "extra" bestandsnamen te vinden zijn.

**Comment by gerardnienhuis** [comment]
Ik heb de eerste voorbeelden gezien vandaag en heb nu 2 vragen:

1) wat stellen de excelfiles voor? Ik heb 2 voorbeelden van excelfiles gezien, met schijnbaar wisselende inhoud, maar kan niet goed beoordelen wat nu waarin staat.

2) kan de formatering (veldscheiding) van de excel iets makkelijker worden gemaakt voor gebruikers?
De csv files die output zijn van het onderdeel Rapportage, die zijn erg makkelijk te gebruiken in excel.
Iedere kolom bevat unieke waarden, en de kolomnamen staan er ook in aparte kolommen boven.
In de csv files die ik nu gezien heb, staat alles op 1 regel. Ik vermoed door de andere veldscheider die gebruikt is, zie voorbeeld van eerste regels hieronder.

Dit gaat niet goed in excel (alles achter elkaar en onoverzichtelijk)
Dit zijn de eerste 2 regels van script, als output:

fileIdentifier,metadataIdentifier,table
'{99bc3b7e-9ac7-4006-96bc-7820ceb7b047}','ea99d10b-cdc4-455c-94d8-7cb923f90ee2','b4.agrcult_polygon'


Maar kan wel goed gaan.
Onderstaande gaat wel goed in excel: alles in gescheiden kolommen
(voorbeeld van rapportage download):

"request_id";"request_time";"crs";"title";"serice_url";"wfs_mimetype";"service_version";"uuid";"user_name";"user_emailaddress";"user_format";"response_time";"response_code";

"edd981e9-dc61-4add-8fb0-82f52d13628b";"2016-08-25 14:00:01.207993";"urn:x-ogc:def:crs:EPSG:28992";"B0_Bebouwde_kommen_in_Overijssel";"http://services.geodataoverijssel.nl:80/geoserver/B04_stedelijk_gebied/wfs";"SHAPE-ZIP";"2.0.0";"f8c9f8c6-1f34-4951-a91f-32ab436a927e";"Reijer Copier";"reijer.copier@idgis.nl";"SHAPE-ZIP";"2016-08-25 14:00:06.997736";"OK";

**Comment by gerardnienhuis** [comment]
merk op: de daadwerkelijke aanvulling met attribuutinformatie dat moet voor iedere nieuw aangeboden set metadata voor een geodataset worden uitgevoerd. Het is dus geen eenmalige actie. De eenmalige actie betreft het voorbereiden voor voor de beheerders van Overijssel voor  het gebruik van de folder met andere type xml's.

Merk op: In de geoweb folder staan de xml's met attribuutinformatie, in de gewone webdav folder staan de xml's zoals die tot nu toe zijn gebruikt.

**Comment by gerardnienhuis** [comment]
De csv's blijken nu goed bruikbaar. De veldscheidingstekens tussen de kolommen zorgen ervoor dat in excel e.e.a. makkelijker te open is. Op de productieomgeving wordt nu gewerkt aan verbetering van de fouten zichtbaar worden bij gebruik van de scripts. Omdat e.e.a. goed werkt kan dit issue gesloten worden.
