### ISSUE TITLE
Kwekkeboom toevoegen als leverancier

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#374]
Graag Geraldine Kwekkeboom toevoegen als leverancier van statische kaarten.

email adres is: g.kwekkeboom@overijssel.nl

**Comment by SandroNeumann** [comment]
Ze is toegevoegd.

**Comment by gerardnienhuis** [comment]
inloggen is goed gegaan, issue kan gesloten
