### ISSUE TITLE
Aangeven dat WMS beschikbaar mag komen

### ISSUE THREAD

**Issue by NicoEilers** [IDgis/geoportaal-test#376]
Het is nodig voor de publicatieomgeving dat er naast WMS en WFS tegelijk, er ook de mogelijkheid komt om alleen een WMS beschikbaar te stellen.

Dat wil zeggen: er staat niet "downloadable data" maar er staat wel "WMS extern beschikbaar" in de metainformatie. Dat moet voor de publicatieomgeving helder maken wat de rechten zijn hiervoor.

Er zijn dan 3 soorten:

1) downloadable data (WMS en WFS beschikbaar in openbare service)
2) WMS beschikbaar (wel WMS maar niet WFS beschikbaar in operbare service)
3) downloadable data is afwezig: geen WMS en ook geen WFS beschikbaar stellen, tenzij via beveiligde service

syntax voorbeeld: 

</gco:CharacterString>
          </useLimitation>
        </MD_Constraints>
      </resourceConstraints>
      <resourceConstraints>
        <MD_Constraints>
          <useLimitation>
            <gco:CharacterString>WMS extern beschikbaar

**Comment by gerardnienhuis** [comment]
zelfde als #388, daarom dit issue gesloten
