### ISSUE TITLE
Helpteksten naar elkaar laten verwijzen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#377]
De helptekst en de "over deze site" bevat voor een deel dezelfde informatie. Op termijn te overwegen om niet dubbele tekst op te nemen, maar om door te linken.

Bij de Over deze site kan dan minder tekst komen. De tekst " Wil je meer weten over zoeken in deze site, kijk dan hier verder" En dan wordt je doorverwezen naar de helptekst die nu al aanwezig is bij het zoeken.

**Comment by SandroNeumann** [comment]
@gerardnienhuis:
Kun je specificeren welke tekst weg mag en waar dus een verwijzing voor in de plaats komt?

**Comment by gerardnienhuis** [comment]
De onderstaande tekst staat nu bij de help bij het zoeken. Maar het is eigenlijk extra informatie, die ook bij "over deze site" kan staan.  Voorstel is om die tekst daarom bij de help van het zoeken weg te halen en op te nemen in het onderdeel "over deze site". In de help kan dan onderaan een link daarheen opgenomen worden. 

De tekst is: meer informatie over het Geoportaal, downloaden, bestanden, services en metadata vind u bij het onderdeel "Over deze site". 

Waarbij dan "Over deze site" een link is naar het tabblad "Over deze site". 


============
Over metadata:

“Metadata” is de term die bij kaarten vaak wordt gebruikt voor de beschrijving van kaarten. Om het delen van gegevens makkelijker te maken, zijn standaarden gemaakt voor de beschrijving van kaarten. In technische termen: ISO19115 en ISO19119. Deze standaarden worden beheerd door een onafhankelijke organisatie (Geonovum: http://www.geonovum.nl).

Over downloaden:

De bestanden kan je in veel gevallen op je eigen pc opslaan. Dat is handig, omdat je dan zelf de data verder kan bewerken, analyseren of weergeven. Precies zoals jij dat wilt, voor je eigen doeleinden.

Gebruik hiervoor de knop “download”. Voor gebruik van dit soort gegevens is speciale software nodig. Dat wordt vaak een GIS genoemd (Geografisch Informatie Systeem). Veel gebruikte systemen zijn Arcgis en QGis. Voor meer informatie over dit soort systemen, zie: https://nl.wikipedia.org/wiki/Geografisch_informatiesysteem.

Bij de download kan je kiezen uit verschillend formaten:
•SHP (shape, veel gebruikt open formaat, ontwikkeld door Esri)
•GML (Geography Markup Language, een open standaard voor GIS data)
•KML (Keyhole Markup Language, te gebruiken in Google Earth)
•DXF (Drawing exchange format, veel gebruikt formaat voor AutoCad)

Door meerdere formaten beschikbaar te stellen, kan je zelf kiezen welk bestandsformaat het beste past bij de software die jij zelf wilt gebruiken.

Heb je niet de beschikking over dergelijke GIS-software, maar wil je toch kaarten zien? Dat kan, omdat er ook veel pdf-bestanden beschikbaar gesteld worden. Zie hiervoor verder bij de toelichting over de “statische kaarten”.

Over services:

In dit Geoportaal worden niet alleen de datasets maar ook de bijbehorende services getoond. Dat zijn links naar websites, die op een moderne manier dit soort kaarten beschikbaar stellen. In het Geoportaal worden de datasets en ook de bijbehorende services ontsloten. Ook voor het gebruik van services heb je een GIS nodig.

Er worden WMS en WFS services via het Geoportaal ontsloten. Deze kun je direct in je eigen GIS applicatie gebruiken. Maak je je eigen app en wil je Geojson gebruiken, dan kan dat ook. Gebruik hiervoor outputformat=json als je een Getfeature request doet op een WFS. Meer tips over Geojson zijn te vinden via onderstaande links:

WFS JSON als output format:

GML is voor veel webontwikkelaars niet de eerste keus. JSON en GeoJSON zijn laagdrempeliger waardoor veel webontwikkelaars daar de voorkeur aan geven. Gelukkig is het GeoJSON formaat ook beschikbaar bij de WFSen die GeoPublisher aanbiedt. Gebruik daarvoor de parameter outputformat=json bij een GetFeature request en je krijgt GeoJSON terug.

Voorbeeld (voor Firefox, Chrome, Safari en Opera, niet geschikt voor IE):

Fietsroutes in GeoJSON

Een GeoPublisher WFS steunt nog meer formaten, zoals gmp, shp, dxf, kml en csv. Zie voor een volledige opsomming het element ows:AllowedValues onder ows:Parameter name="outputFormat" in de Capabilities van de WFS voor bijv. Recreatie

Over statische kaarten:

Naast bestanden en services kan je ook “statische kaarten” vinden in het Geoportaal. Dat zijn kaarten (meestal pdf’s) die gemaakt zijn op basis van de bestanden en services. Deze kaarten worden speciaal gemaakt voor diverse communicatie-doeleinden.

Je kan dit soort kaarten eenvoudig bekijken. Je hebt daarvoor geen geavanceerd GIS systeem voor nodig. Een pdf kan je openen met een PDF reader. Deze readers worden gratis beschikbaar gesteld, bijvoorbeeld door het bedrijf Adobe (http://www.adobe.nl). De metadata van deze statische kaarten wordt ontsloten via de Dublin-core standaard.

**Comment by gerardnienhuis** [comment]
nb: het stukje tekst "Over services" kan volledig weggelaten worden, dat is volledig dubbel


===

Over services:

In dit Geoportaal worden niet alleen de datasets maar ook de bijbehorende services getoond. Dat zijn links naar websites, die op een moderne manier dit soort kaarten beschikbaar stellen. In het Geoportaal worden de datasets en ook de bijbehorende services ontsloten. Ook voor het gebruik van services heb je een GIS nodig.

Er worden WMS en WFS services via het Geoportaal ontsloten. Deze kun je direct in je eigen GIS applicatie gebruiken. Maak je je eigen app en wil je Geojson gebruiken, dan kan dat ook. Gebruik hiervoor outputformat=json als je een Getfeature request doet op een WFS. Meer tips over Geojson zijn te vinden via onderstaande links:

WFS JSON als output format:

GML is voor veel webontwikkelaars niet de eerste keus. JSON en GeoJSON zijn laagdrempeliger waardoor veel webontwikkelaars daar de voorkeur aan geven. Gelukkig is het GeoJSON formaat ook beschikbaar bij de WFSen die GeoPublisher aanbiedt. Gebruik daarvoor de parameter outputformat=json bij een GetFeature request en je krijgt GeoJSON terug.

Voorbeeld (voor Firefox, Chrome, Safari en Opera, niet geschikt voor IE):

Fietsroutes in GeoJSON

Een GeoPublisher WFS steunt nog meer formaten, zoals gmp, shp, dxf, kml en csv. Zie voor een volledige opsomming het element ows:AllowedValues onder ows:Parameter name="outputFormat" in de Capabilities van de WFS voor bijv. Recreatie

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
