### ISSUE TITLE
Rapportage geodata: (mime)type van de bijlage in een kolom toevoegen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoportaal-test#380]

**Comment by gerardnienhuis** [comment]
De bedoeling is, dat in het rapport Geodata, zichtbaar is, welk soort bijlage is gekoppeld bij de extra informatie. Mimetype is mogelijk vrij technisch maar lijkt wel goed zichtbaar. Dan is ook direct voor beheerders te zien, welke html verwijzingen naar externe websites nog aanwezig zijn.

**Comment by gerardnienhuis** [comment]
werkt goed, wel erg technisch. tzt overwergen om een aantal zelfde vermeldingen in een groep onder te brengen, nu zijn er 10 of meer schrijfwijzen voor vermelding dat een jpg is gekoppeld. Issue opgenomen in een volgende versie, voor 1.1.4 succesvol afgerond.

**Comment by SandroNeumann** [comment]
Wat is de wens hier precies nog? Een meer gebruikersvriendelijke formulering? Er is bij mijn weten maar één vermelding van een jpg (namelijk image/jpeg).

**Comment by SandroNeumann** [comment]
Dit issue wordt gesloten. Nieuw issue geopend: #542
