### ISSUE TITLE
Rapportage Geodata: aantal kolommen bij datasets

### ISSUE THREAD

**Issue by robstek** [IDgis/geoportaal-test#382]
aantal kolommen totaal
aantal kolommen met niet-lege beschrijving

Het gaat hier om de attribuut informatie

**Comment by gerardnienhuis** [comment]
Wens is om het aantal verschillende attributen bij een dataset in de rapportage van Geodata op te nemen. Ook in dat rapport moet komen: aantal kolommen (attributen) waarvan de omschrijving van de attributen niet leeg is. Je kan dan als beheerder dat rapport kunnen gebruiken om te kijken of er veel geodatasets zijn, waar nog erg weinig (of juist heel veel) info over attributen is ingevuld.

**Comment by SandroNeumann** [comment]
Zelfde als #527

**Comment by gerardnienhuis** [comment]
#527  is uitbreiding van dit issue. Dit betreffende issue kan daarom gesloten
