### ISSUE TITLE
In rapportage geodata opnemen welke/hoeveel kolommen en rijen zijn gefilterd

### ISSUE THREAD

**Issue by robstek** [IDgis/geoportaal-test#384]

**Comment by gerardnienhuis** [comment]
Je kan in de publicatieomgeving filtering toepassen. Maar je weet niet, op welke datasets dat is toegepast, als je nu de rapportage van Geodata bekijkt. Wens is om in rapportage van Geodata dit zichtbaar te maken.

**Comment by gerardnienhuis** [comment]
vergelijkbaar met issue https://github.com/IDgis/geoportaal-test/issues/740  (is selectie van kolommen)

wens is om in rapportage ook op te nemen of een selectie van rijen is toegepast
extra kolom in rapportage gaat heten: selectie_rijen en de waarde hiervan is "ja" of "nee"

**Comment by SandroNeumann** [comment]
Ik zou de kolom "heeft_filter" noemen, ter verduidelijking.

**Comment by SandroNeumann** [comment]
De naam van de kolom gaat heten: rijen_gefilterd

**Comment by SandroNeumann** [comment]
Dit is al gedaan. Duplicaat van #757

**Comment by gerardnienhuis** [comment]
Dit is inderdaad een duplicaat, dit issue kan daarom gesloten worden.
