### ISSUE TITLE
Toegepaste filtering op rijen van brondata, in metadata opnemen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoportaal-test#385]
voorbeeld:

wilde planten, gefilterd op soort = "pinksterbloem"

**Comment by gerardnienhuis** [comment]
Je kan in de publicatieomgeving filteren op de inhoud van datasets

Dat dit is gedaan, dat zou opgenomen kunnen worden In rapportage van Geodata (zie #384)

Maar of en hoe het in metadata terecht moet komen, dat weet ik nog niet zeker. Uitzoeken t.z.t.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
Heb je hier inmiddels een idee bij?

**Comment by gerardnienhuis** [comment]
in atlas opgelost, vooralsnog niet meer urgent, daarom gesloten
