### ISSUE TITLE
WMS extern zichtbaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#388]
Wens is om een WMS wel via de publicatieomgeving voor externen zichtbaar te laten zijn, terwijl de WFS niet zichtbaar is. Hiervoor is in Geosticker een nieuwe omschrijving gemaakt: WMS extern zichtbaar.
Als "WMS extern zichtbaar"  in de metadata staat, maar niet "downloadable data" dat moet wel de WMS en niet de WFS beschikbaar zijn. 

Publicatieomgeving moet hiervoor ook worden aangepast. 
Mogelijk ook de rapportages over geodatasets, zie #389

Een voorbeeld van een xml waarin deze omschrijving is opgenomen, staat hier als zip:

**Comment by gerardnienhuis** [comment]
zelfde als #376

**Comment by HermanAssink** [comment]
@gerardnienhuis Bij sommige viewers, zoals Flamingo, kun je geen FeatureInfo doen als er geen WFS bij de WMS beschikbaar is. Is dit geen bezwaar?

**Comment by gerardnienhuis** [comment]
Nee
Wij koppelen dan direct met onze interne database

**Comment by HermanAssink** [comment]
Met @andreweijmer en @gerardnienhuis is deze oplossing besproken: Naast de publieke (=externe) en beveiligde (=interne) publicatieomgeving wordt er een derde omgeving "Alleen WMS extern" toegevoegd. In deze omgeving, die publiek/extern toegankelijk is, worden services gepubliceerd met datasets die wel via WMS, maar niet via WFS extern gepubliceerd mogen worden. Deze datasets worden door de beheerders gelabeld met "Alleen WMS extern", maar hebben niet het label "Downloadable data". Deze services met deze datasets mogen ook in de beveiligde omgeving gepubliceerd worden. Datasets met het label "Alleen WMS extern" kunnen dus links in de details bij de metadata naar meerdere services hebben, namelijk zowel de "Alleen WMS extern"-omgeving als de beveiligde omgeving. In onderstaande matrix is de betekenis van de combinatie van "Alleen WMS extern" en "Downloadable data" weergegeven:

![image](https://cloud.githubusercontent.com/assets/2979044/22068045/017de29e-dd94-11e6-9157-87670765ddc1.png)

**Comment by gerardnienhuis** [comment]
Bedoeling is dat beheerders dus aangeven of een WMS wel of niet beschikbaar mag zijn. Maar omdat je als beheerder in Geosticker zowel Alleen WMS beschikbaar en Downloadable data kan aangeven bij 1 geodataset, is ervoor gekozen om in dat geval bij extern Geoportaal "Alleen WMS beschikbaar" te laten gelden. In de rapportage moet dan te vinden zijn, welke combinaties voorkomen zodat de fouten vindbaar zijn.

**Comment by copierrj** [comment]
Deze wijziging raakt de volgende onderdelen:

- database: attribuut 'downloadable' toevoegen aan omgeving en brondataset.
- provider: afleiden van 'downloadable' attribuut brondataset uit metadata.
- domain: toevoegen (= afgeleid van brondataset) 'downloadable' attribuut aan service en laag.
- admin: lagen en services zonder het 'downloadable' attribuut van een label voorzien.
- service: 
  - harvester: van provider ontvangen 'downloadable' attribuut opslaan.
  - service manager: bij publiceren controleren dat voor alle lagen in de het attribuut 'downloadable' gezet is indien dit attribuut bij de omgeving aanwezig is.
  - geoserver: deactiveren WFS indien omgeving niet het 'downloadable' attribuut heeft.
- compositie: 
  - toevoegen nieuwe omgeving.
  - bestaande omgevingen voorzien van het 'downloadable' attribuut.

**Comment by gerardnienhuis** [comment]
let op: als WFS beschikbaar mag zijn, dan kan je ook downloaden

**Comment by gerardnienhuis** [comment]
voorbeeld:
Nu bestaat in het interne Geoportaal:

 Waterprojecten (beveiligd) (03-12-2013, Provincie Overijssel) - WMS  
 Waterprojecten (beveiligd) (03-12-2013, Provincie Overijssel) - WFS 

En extern zie je niets, is tenslotte beveiligd.

en straks komt er een "alleen WMS variant" bij, en dan zie je intern:

Waterprojecten (alleen WMS) (03-12-2013, Provincie Overijssel) - WMS  
 
en dat zie je ook in het externe Geoportaal op de zelfde manier

**Comment by gerardnienhuis** [comment]
let op:

Er staat nu bij de DETAILS:

Download: https://download.geoportaaloverijssel.nl:443/download/5196ac30-7768-46f2-9e5d-1ffe223f3151
OGC:WFS: http://services.geodataoverijssel.nl:80/geoserver/B41_bodem/wfs
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B41_bodem/wms

en als dit bestand "alleen WMS" is, dan moet hier komen te staan:
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B41_bodem/wms

**Comment by SandroNeumann** [comment]
Er worden hierboven meerdere verschillende waardes gegeven om aan te geven dat de data alleen via WMS beschikbaar mag zijn. Ik implementeer nu "Alleen WMS extern".

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
