### ISSUE TITLE
Zoeken start na Enter in Zoek en wijzigen scherm

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#39]
Staat de cursor in het invoerveld "tekst" dan moet je met <Enter> de zoekopdracht kunnen starten
(is er niets ingevoerd, dan krijg je alles, staan er al meer dingen ingevuld, dan wordt daar ook rekening mee gehouden.

Opmerking nr 31 bij testresultaten 3-2-2016

**Comment by gerardnienhuis** [comment]
werkt wel goed in Chrome en Opera, niet in IE (11) en Firefox. Browserafhankelijk?

**Comment by SandroNeumann** [comment]
Kun je je stappen aangeven? In welk invoerveld druk je op enter? Want bij mij doen IE11 en Firefox het ook gewoon.

**Comment by gerardnienhuis** [comment]
ik kan zoekopdracht niet starten, als er niets in invoervak staat, lijkt het. Bij geen van de 4 browsers die ik gebruik (FF, IE11, Chrome, Opera). Maar als ik een spatie er neer zet, en dan op Enter druk, dan wordt zoeken gestart en alles gevonden.

nb: verschil tussen browsers kan ik niet reproduceren, maar ik vermoed dat toevallig na veel handelingen er spaties bij 2 van de 4 browsers stonden. 2 deden het dus wel goed, en 2 niet.

Verwarrend. Mijn vraag is, of zoeken ook gestart kan worden als er niks in zoekveld staat (en dan wordt dus alles gevonden, tenzij er andere filters zoals datum ook zijn aangegeven). 

nb: is dus waarschijnlijk geen bug. Heb het niet kunnen reproduceren (behalve dan door spatie neer te zetten). label "bug" kan verwijderd worden.

**Comment by gerardnienhuis** [comment]
kan gesloten worden: gedrag met of zonder spatie blijkt goed te werken: met spatie, dan komt er vraag filter op te heffen, zonder spatie niet
