### ISSUE TITLE
http://geoportaaloverijssel.nl komt uit op site IDGis

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#397]
als ik http://geoportaaloverijssel.nl opstart
dan wil ik uitkomen op: https://www.geoportaaloverijssel.nl

als ik op dit moment http://geoportaaloverijssel.nl opstart
dan kom ik uit op: http://geoportaaloverijssel.nl/nl/

**Comment by HermanAssink** [comment]
http://geoportaaloverijssel.nl  komt uit op de site van IDgis

**Comment by gerardnienhuis** [comment]
de bedoeling is dat http://geoportaaloverijssel.nl en https://geoportaaloverijssel.nl beiden uitkomen op:
http://www.geoportaaloverijssel.nl

**Comment by HermanAssink** [comment]
De DNS registratieis aangepast zodat geoportaaloverijssel.nl op dezelfde server uitkomt als www.geoportaaloverijssel.nl.
@SandroNeumann : Moet hiervoor nog iets worden aangepast in de webserver configuratie?

**Comment by SandroNeumann** [comment]
Dat denk ik niet, die url wordt nu (straks) gewoon redirect naar www.geoportaaloverijssel.nl. Daar hoeft niks in de proxy voor aangepast te worden.

**Comment by gerardnienhuis** [comment]
Zojuist getest. Het klopt nog steeds niet.

Als ik nu http://geoportaaloverijssel.nl volg, dan kom ik uit op: https://admin.geodataoverijssel.nl/user/login?r=%2F.

De bedoeling is, dat ik in dat geval uitkom op http://www.geoportaaloverijssel.nl

**Comment by SandroNeumann** [comment]
Er moet nog een kleine aanpassing in de proxy plaatsvinden, zodat de verwijzingen ook daar gebeuren.

**Comment by gerardnienhuis** [comment]
Alleen in productie te testen?

**Comment by SandroNeumann** [comment]
Ja, klopt.

**Comment by gerardnienhuis** [comment]
werkt goed, zojuist getest in productieomgeving, issue kan gesloten
