### ISSUE TITLE
Metadata terug te vinden in GeoSticker mbv UUID?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#398]
Zoals besproken gaat de UUID in het metadatabestand gebruikt worden om de metadata te identificeren. Kunnen we er vanuit gaan dat beheerders betreffende metadata in GeoSticker terug kunnen  vinden met betreffende UUID uit een rapportage?

**Comment by gerardnienhuis** [comment]
We hebben de rapportage van geodatasets gecontroleerd: blijkt dat de uuid goed terug te vinden is. Kolom heet: md_identifier Verdere acties zijn wat dit betreft niet nodig, issue kan gesloten
