### ISSUE TITLE
metadata met behoud van attribuutinformatie

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#4]
Het voorstel is om de extra attribuutinformatie op te nemen in de metainformatie, op het moment dat het inleesproces van de xmls's vanuit Overijssel naar IDGis plaatsvind. De eerste tests laten zien, dat die informatie wel te produceren is voor Overijssel door in Geosticker een extra optie te kiezen voordat wordt opgeslagen. Wens is om dit in versie 1.0 van het nieuwe Geoportaal mee te nemen (als het kan). En anders zo snel mogelijk bij versie 1.1.

**Comment by SandroNeumann** [comment]
Wat moet het geoportaal hiervoor doen of wordt dit door geosticker gedaan?

**Comment by gerardnienhuis** [comment]
geosticker kan attribuutinfo opslaan, alleen wordt het dan geen valide xml meer. zou door geoportaal moeten worden omgezet bij inlezen. voorbeelden van dergelijke xml's zijn aanwezig en al eens geleverd, als voorbeeld. idee is om ze te leveren, en dan in de stylesheet bij het onderdeel "bewerkingen" bij de details terug te laten komen. Nu wordt dat door applicatiebeheerders met de hand uitgevoerd.

**Comment by HermanAssink** [comment]
Gerard, wil je voor de volledigheid zo'n xml met attribuutinfo bij deze issue voegen? Gaan die xml's met attribuutinfo de huidige metadata xml's (in de map op jullie server) vervangen?

**Comment by gerardnienhuis** [comment]
als bijlage alle files die gemaakt zijn met als optie "geoweb".
Dit zijn niet alle xml's: we zijn pas verleden jaar gestart met het dubbel opslaan.
we hebben dus xmls met en zonder attribuutinfo,
als bestanden niet in de geoweb-map staan, dan moeten dus de andere xmls worden gebruikt.
De structuur is sterk vergelijkbaar met de standaard xmls, alleen is hier wel attribuutinfo opgeslagen.

ter toelichting zijn alle xml bestanden uit de map geoweb (van vandaag) opgestuurd.

voorbeeld uit bestand: b2.betonning_point.xml

Als er een omschrijving van het attribuut aanwezig is, dan
deze opnemen bij uitgevoerde bewerkingen, die zijn opgenomen bij details
(staat er geen omschrijving, dan ook vermelding van attribuut niet opnemen).

In dit voorbeeld komt er dan te staan:

Uitgevoerde bewerkingen:
Beschrijving van attributen:
PUNT = naam van de betonning, 
X = x-coordinaat in rd ingemeten met gps (06-gps)
Y = y-coordinaat in rd ingemeten met gps (06-gps)</definition>

info in xml in dit voorbeeld is:

  <FC_FeatureCatalogue>
    <featureType>
      <name>B2.betonning_point</name>
      <featureAttribute>
        <name>OBJECTID_12</name>
      </featureAttribute>
      <featureAttribute>
        <name>OBJECTID</name>
      </featureAttribute>
      <featureAttribute>
        <name>PUNT</name>
        <definition>naam van de betonning</definition>
      </featureAttribute>
      <featureAttribute>
        <name>X</name>
        <definition>x-coordinaat in rd ingemeten met gps (06-gps)</definition>
      </featureAttribute>
      <featureAttribute>
        <name>Y</name>
        <definition>y-coordinaat in rd ingemeten met gps (06-gps)</definition>

[attributen_geoweb.txt](https://github.com/IDgis/geoportaal-test/files/263282/attributen_geoweb.txt)

**Comment by gerardnienhuis** [comment]
hallo

hierbij de zip, opslaan in github ging vandaag meerdere keren fout. txt of jpg wil wel, zip niet, vandaar ook Herman.Assink@IDgis.nl bij de cc gezet

zie verdere toelichting bij https://github.com/IDgis/geoportaal-test/issues/4

vrgr
Gerard

---

Van: Herman Assink [notifications@github.com]
Verzonden: woensdag 11 mei 2016 16:27
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard); Author
Onderwerp: Re: [IDgis/geoportaal-test] metadata met behoud van attribuutinformatie (#4)

Gerard, wil je voor de volledigheid zo'n xml met attribuutinfo bij deze issue voegen? Gaan die xml's met attribuutinfo de huidige metadata xml's (in de map op jullie server) vervangen?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/4#issuecomment-218476243

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by SandroNeumann** [comment]
voorbeeld: 

Uitgevoerde bewerkingen

Beschrijving: Attribuut tabel: NAAM_LEIDING: Naam van de leiding, CODE: A = hoofdgastransportleiding (HGS); N = regionale gastransportleiding (RGS), VERKLAAR: Verklaring van de code, GASBEDRIJF: Naam gasbedrijf 

dus uit esri metadata xlm deze info halen en opslaan bij onderdeel uitgevoerde bewerkingen

**Comment by gerardnienhuis** [comment]
hulp nodig bij selectie: er zijn nu 2 mappen, 1 met en 1 zonder extra attribuutinfo conform GEOWEB: harvester moet dus ook kijken naar die 2 mappen, als als xml met extra attribuutinfo aanwezig is, dan deze gebruiken, zo niet , dan bestaande (normale) xml gebruiken.

**Comment by gerardnienhuis** [comment]
let op: de map met xml's gebruikt niet uuid.xml maar heeft als syntax: bestandnaam.xml
(nb: de uuid staat er wel in, maar dan in de metainformatie, 

voorbeeld:

Alternatieve titel: B2.avondspits2020ov_arc (b2\b22)
Versie: febr. 2015
Unieke Identifier: 6d0c8c26-c5f2-4c8f-89a2-a8a6406c4fe6

**Comment by HermanAssink** [comment]
@gerardnienhuis de schatting "impact middel" heeft betrekking op de impactanalyse. We gaan die impactanalyse nu doen zodat we o.a. de schatting van de realisatie duidelijk krijgen.

**Comment by robstek** [comment]
extra element "uitgevoerde bewerkingen" toevoegen.
kolom zonder beschrijving niet opnemen.
overbodige kolommen wegfilteren .
bij geen kolommen na wegfilteren: element "uitgevoerde bewerkingen"  geheel weglaten.

voorbeeld (zie bij Details):
https://www.geoportaaloverijssel.nl/metadata/dataset/f512e2cd-026b-4196-8ec1-f510ac337975

**Comment by gerardnienhuis** [comment]
dit blijkt goed te werken, issue kan gesloten (geweldig mooie toevoeging)
