### ISSUE TITLE
Acceptatieversie meer zichtbaar in beeld

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#404]
Bij het testen van het Geoportaal kom je soms in de war tussen huidige versie en acceptatieversie. Wens is om op alle schermen duidelijke de tekst "acceptatieversie" in beeld te laten komen. Bij alle schermen die een gebruiker ziet, dus niet alleen bij de homepagina, maar ook bij alle andere pagina's, zoals download, helptekst enz. Voorbeeld van homepagine, zie onderstaand plaatje

![acceptatieversie](https://cloud.githubusercontent.com/assets/9005444/21944708/e874f7e8-d9d7-11e6-97f5-c57f46d1e14a.jpg)

**Comment by SandroNeumann** [comment]
Alle schermen? Dus ook de metadata pagina's, geoportaal-beheer en de publisher?

**Comment by gerardnienhuis** [comment]
Publisher moet @andreweijmer  beantwoorden. Alle schermen die je als tester ziet, wil ik graag van herkenbare info voorzien conform voorbeeld.

**Comment by gerardnienhuis** [comment]
Net afgestemd met @andreweijmer : voor publicatieomgeving heeft dit voorstel geen prioriteit. Dat wil dus zeggen dat het voor de publicatieomgeving dit voorstel niet hoeft te worden meegenomen. Voor alle andere schermen van het Geoportaal dus wel.

**Comment by gerardnienhuis** [comment]
Te overwegen valt om niet de tekst ACCEPTATIE OMGEVING neer te zetten, maar alleen een afwijkende achtergrondkleur te gebruiken. Lichtgeel bijvoorbeeld. Dan zie je bijna altijd direct in welke omgeving je zit. Twee voorbeelden hoe dat er dan uitziet, hieronder

![acceptatieomgeving_home](https://cloud.githubusercontent.com/assets/9005444/22105778/eee2b364-de45-11e6-9204-edce2d578136.jpg)

![acceptatieomgeving_beheer](https://cloud.githubusercontent.com/assets/9005444/22105781/f31d3828-de45-11e6-99d5-48b0f0e6c7a2.jpg)

**Comment by HermanAssink** [comment]
Mogelijke andere oplossing: Een balk onder- of bovenaan die altijd in beeld blijft

**Comment by SandroNeumann** [comment]
Nog beslissen welk visueel onderscheid het precies gaat worden.

**Comment by gerardnienhuis** [comment]
Het verzoek is om het dezelfde kleur geel te laten zijn, als bovenstaand voorbeeld. Dus de achtergrond lichtgeel maken, en NIET de paarse letters met ACCEPTATIEVERSIE er bij zetten. We denken dat het kleuronderscheid voldoende is

**Comment by SandroNeumann** [comment]
De kleur code voor de achtergrond o.b.v. wel of geen acceptatie versie aanpassen.

**Comment by gerardnienhuis** [comment]
Dit werkt goed, zojuist de meeste pagina's getest.  De gele kleur zorgt ervoor dat het onderscheid tussen productie en acceptatie in 1 oogopslag helder is. Er is alleen 1 scherm nog hetzelfde bij acceptatie en productie, wat kleur betreft: 

https://acc-admin.geoportaaloverijssel.nl/user/login?r=%2F 

Dit scherm heeft nu nog de kleur van de productieversie.

**Comment by gerardnienhuis** [comment]
Het werkt nu goed: inlogscherm heeft ook gele kleur. Issue kan gesloten
