### ISSUE TITLE
Werkelijke aantal records laten zien bij beheer statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#405]
Nu wordt maximaal 200 records getoond op het scherm, terwijl er (als je alles selecteerd) er veel meer zijn.
De lijst van 200 lijkt te werken. Wil je als beheerder er andere records, dan verfijn je je zoekcriteria. Maar het totale aantal records klopt niet. Dat blijft altijd op 200 staan (zie figuur). Wens is om op die plaats altijd werkelijke aantal records te laten zien. 

Er staat nu:
Aantal records: 200 | Aantal geselecteerde records: 0

Er komt dan te staan: 

Aantal records: 6000 | Aantal geselecteerde records: 0

![aantal_records](https://cloud.githubusercontent.com/assets/9005444/21953300/55dd1eea-da33-11e6-8cf5-d93622f46a11.jpg)

**Comment by SandroNeumann** [comment]
Het aantal records heeft betrekking op de records die je op dat moment kunt zien. Dat is maximaal 200. Er zou nog wel een extra label kunnen komen met het aantal records in de database.

**Comment by gerardnienhuis** [comment]
Kan je bij een selectie van een bepaalde term (b.v. bos of natuur) dan niet laten zien, hoeveel records dat betreft, als het getal groter is dan 200? Ik zou graag ten alle tijde het werkelijk aantal geselecteerde records willen zien, en als je niks selecteert, dan dus het maximaal aantal beschikbare records (muv de prullenbak)

**Comment by SandroNeumann** [comment]
Dat kan wel, maar je hebt wel altijd maximaal 200 records tot je beschikking. Om verwarring te voorkomen zou ik het label van maximaal 200 behouden en het totale aantaal ernaast zetten.

**Comment by gerardnienhuis** [comment]
Lijkt een goede oplossing
Hoe ziet dat er dan in praktijk uit bij bv selectie van 3000 ? En hoe bij selectie van 30?

**Comment by SandroNeumann** [comment]
Ik zou dit voorstellen:

Aantal records: .. | Aantal weergegeven records .. | Aantal geselecteerde records ..

Waar de tweede en derde zijn zoals het nu ook is en de eerste het totaal in de database toont.

**Comment by gerardnienhuis** [comment]
werkt goed, getest met filters (gebruiker of met hand aanklikken en selecteren): werkt beide nu goed

bv: Aantal records: 40 | Aantal weergegeven records: 40 | Aantal geselecteerde records: 0
bij filter Nienhuis

issue kan gesloten
