### ISSUE TITLE
Nummer vermelden en tekst aanpassen bij vreemd nummer bij beheer statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#407]
Nu krijg je een melding als je een vreemd nummer hebt ingevoerd, bij het toevoegen van een statische kaart bij het onderdeel beheer statische kaarten. Maar in dat scherm wordt niet verteld, welk nummer je nu echt hebt ingevoerd. Je kan dat vaak ook niet direct zien, omdat dat scherm er voor komt te staan op het scherm (zie bijgevoegde afbeelding). Wens is om 3 regels toe te voegen aan dat scherm met die waarschuwing:

witregel
Nummer is: .... (en dan hier **in vet** het nummer wat is ingevoerd)
witregel

Op de plaats waar de pijl nu wijst, dus onder de liggende streep onder de waarschuwing.

De tekst in dat scherm ook iets aanpassen. Er lijken verschillende waarschuwingsteksten voor te komen. Zie hieronder en de alternatieve tekst in het bijgevoegde plaatje. Bedoeling is dat er 1 tekst komt, bij de waarschuwing.

Tekst is nu bijvoorbeeld:

Let op: het nummer wat je hebt ingevoerd dat bevat letters of andere vreemde tekens. Het is de bedoeling dat een nummer alleen uit cijfers bestaat. Controleer goed welk nummer je hebt ingevoerd, voordat je verder gaat.

Let op: het aantal cijfers van het nummer wat je hebt ingevoerd, dat is mogelijk niet correct. Gewone nummers zijn bijvoorbeeld: 160023 (in 2016), 150101 (in 2015) enz. Controleer of juiste nummer is ingevoerd, voordat je verder gaat.

Tekst wordt:

Het nummer wat je hebt ingevoerd, wijkt af van de gewone nummers. Controleer of je het juiste nummer hebt ingevoerd, voordat je verder gaat.

Het nu ingevoerde nummer bevat meer dan 8 cijfers. Of het bevat letters of andere vreemde tekens. Het is meestal de bedoeling dat een nummer alleen uit cijfers bestaat. Gewone nummers zijn bijvoorbeeld: 160023 (in 2016), 150101 (in 2015) enz. Combinaties van maximaal 8 cijfers komen ook voor. Dat zijn meestal oudere nummers, zoals 00226467 (uit 2002).

![test_vreemd_nummer](https://cloud.githubusercontent.com/assets/9005444/21953369/2cf3bece-da35-11e6-9858-9eb60ff4bbb2.jpg)

**Comment by gerardnienhuis** [comment]
Voor nu werkt het goed. Voorstel voor verdere verbetering hieronder, kan ik volgende versie meegenomen worden.

Voorbeeld uitwerking:

Waarschuwing: het nummer is niet goed ingevuld
Nummer is: 9

Het nummer wat je hebt ingevoerd, wijkt af van de gewone nummers. Controleer of je het juiste nummer hebt ingevoerd, voordat je verder gaat.

Het nu ingevoerde nummer bevat meer dan 8 cijfers. Of het bevat letters of andere vreemde tekens. Het is meestal de bedoeling dat een nummer alleen uit cijfers bestaat. Gewone nummers zijn bijvoorbeeld: 160023 (in 2016), 150101 (in 2015) enz. 
Combinaties van maximaal 8 cijfers komen ook voor. Dat zijn meestal oudere nummers, zoals 00226467 (uit 2002).



Moet worden:

Waarschuwing: het nummer is mogelijk niet goed ingevuld
Nummer is: 9

Het nummer wat je hebt ingevoerd, wijkt af van de gewone nummers. Controleer of je het juiste nummer hebt ingevoerd, voordat je verder gaat.

Het is meestal de bedoeling dat een nummer alleen uit cijfers bestaat. Gewone nummers zijn bijvoorbeeld: 160023 (in 2016), 150101 (in 2015) enz. 
Combinaties van maximaal 8 cijfers komen ook voor. Dat zijn meestal oudere nummers, zoals 00226467 (uit 2002).

Is het toch nodig een afwijkend nummer te gebruiken, voorkom dan vreemde tekens (- of _ zijn wel toegestaan).
%, @, # en dergelijke, dat wordt afgeraden.
Probeer ook de code niet te lang te maken (streef naar minder dan 12 posities).

**Comment by SandroNeumann** [comment]
Kleine tekstuele aanpassingen.

**Comment by gerardnienhuis** [comment]
Het werkt op zich wel goed, maar we waren iets vergeten. Er is ook bij de invoer (bij het opslaan) een controle of het nummer al bestaat. Daardoor moet de tekst zelf toch anders zijn. Hieronder het nieuwe voorstel:


# **Was:**


Waarschuwing: het nummer is mogelijk niet goed ingevuld
Nummer is: 9

Het nummer wat je hebt ingevoerd, wijkt af van de gewone nummers. Controleer of je het juiste nummer hebt ingevoerd, voordat je verder gaat.

Het is meestal de bedoeling dat een nummer alleen uit cijfers bestaat. Gewone nummers zijn bijvoorbeeld: 160023 (in 2016), 150101 (in 2015) enz.
Combinaties van maximaal 8 cijfers komen ook voor. Dat zijn meestal oudere nummers, zoals 00226467 (uit 2002).

Is het toch nodig een afwijkend nummer te gebruiken, voorkom dan vreemde tekens (- of _ zijn wel toegestaan).
%, @, # en dergelijke, dat wordt afgeraden.
Probeer ook de code niet te lang te maken (streef naar minder dan 12 posities).




# **Wordt:**


Waarschuwing: het nummer is mogelijk niet goed ingevuld

Nummer is: 9

Controleer of je het juiste nummer hebt ingevoerd, voordat je verder gaat.

Kan het zijn, dat het nummer wat je hebt ingevoerd, al bestaat? Nummers moeten altijd uniek zijn.

Of is er een fout in het nummer zelf? Het is de bedoeling dat een nummer alleen uit cijfers bestaat. Gewone nummers zijn bijvoorbeeld: 160023 (in 2016), 150101 (in 2015) enzovoorts. Combinaties van maximaal 8 cijfers komen ook voor. Dat zijn meestal oudere nummers, zoals 00226467 (uit 2002).

Is het toch nodig een afwijkend nummer te gebruiken, gebruik dan geen vreemde tekens. Spaties, %, @, # en dergelijke tekens zijn niet toegestaan. Streepjes (- of _) zijn wel toegestaan). Maak de code niet te lang (streef naar minder dan 12 posities).

**Comment by SandroNeumann** [comment]
Is aangepast

**Comment by gerardnienhuis** [comment]
tekst is goed, maar klopt werking nog? ik heb zojuist zonder waarschuwing 112233445566778899 kunnen toevoegen. Had ik hier geen waarschuwing moeten krijgen?

**Comment by gerardnienhuis** [comment]
het vreemde is, dat ik geen melding krijg als ik 112233445566778899 toevoeg, maar juist wel als ik 180235 toevoeg. Dat moet andersom zijn: bij verkeerde nummers de tekst vermelden

**Comment by gerardnienhuis** [comment]
tekst is goed, maar de controle nog niet. dit issue kan gesloten...
. nieuw issue mbt onjuiste controle lange cijfercodes nog maken.
