### ISSUE TITLE
Response code ontbreekt in rapport download

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#408]
Als een download goed gegaan is, dan komt er OK in het rapport van downloads te staan. Gaat het fout, dan staat de foutmelding daar. Maar hoe kan het dat er 1 download is, waar geen foutmelding is gekomen, maar ook geen OK?

Betreffende download is:

be810459-ff4a-4496-b2dc-5206a5d44e42	2016-10-03 14:15:24.859212	urn:x-ogc:def:crs:EPSG:28992	B2_Bushaltes	http://acc-services.geodataoverijssel.nl:80/geoserver/B25_vervoer/wfs	SHAPE-ZIP	2.0.0	fbe74ae9-c66f-481a-b3cf-1c0286e7615f	naam email	SHAPE-ZIP	2016-10-28 15:30:43.767758	

Opvallend is wel dat de naam van iemand is, die niet in het testteam zit. Blijkbaar heeft die persoon de acceptatieomgeving gevonden en ook gebruikt.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
Ik kan dit niet vinden. In welk rapport staat het? Acceptatie of productie? Kun je het opsturen?

**Comment by SandroNeumann** [comment]
Dat bovenstaande onvindbaar was kwam doordat we een keer de database inhoud van productie naar acceptatie hebben gezet. Er zijn wel drie records waar de response code leeg is, maar dit is niet meer gebeurd na oktober 2016. Dit zal dus heel moeilijk reproduceerbaar zijn.

**Comment by gerardnienhuis** [comment]
niet meer voorgekomen, niet langer relevant, dus kan gesloten
