### ISSUE TITLE
Doorklikken vanaf externe service levert interne kleuren metainfo van laag

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#410]
De externe versie van het Geoportaal levert bij doorklikken vanaf service de interne stylesheet (wat kleuren betreft) van de betreffende laag. Dit had de externe stylesheet van de betreffende laag moeten zijn. 

Verwisseling van kleuren is eerder voorgekomen en toen opgelost, zie #5 

Gevonden door alle services te selecteren (uitgebreid zoeken) en dan bij een willekeurig service de metainfo van de laag te bekijken. Je ziet van de service wel juist de externe stylesheet kleuren maar bij bekijken van de laag zie je de interne kleuren. Dat hadden de kleuren van de externe stylesheet moeten zijn.

Details testen hieronder

==================================
gaat intern goed:, resultaten:
intern vanaf home pagina

home: blauwe balk, rode grote knoppen en blauwe kleine knoppen
meer informatie bij een bestand: blauwe balk, rode grote knoppen 
help bij zoeken vanaf home: blauwe balk, rode knoppen
over deze site: blauwe balk, rode knoppen
contact:  blauwe balk, rode knoppen
download bij een bestand: blauwe balk en blauwe kleine knoppen

actie: selecteer services bij uitgebreid zoeken:

meer informatie bij een service: blauwe balk, rode knoppen
daarna: klik op een willekeurige laag bij het onderdeel WAT van de service.
Dit geeft metainfo van een laag met blauwe balk, rode knoppen.

==================================

externe Geoportaal

home: Rode balk, blauwe grote knoppen en rode kleine knoppen
meer informatie bij een bestand: Rode balk, blauwe grote knoppen 
help bij zoeken vanaf home: Rode balk, blauwe grote knoppen 
over deze site: Rode balk, blauwe grote knoppen 
contact:  Rode balk, blauwe grote knoppen 
download bij een bestand: rode balk en rode kleine knoppen

Actie: selecteer services bij uitgebreid zoeken:

meer informatie bij een service: Rode balk, blauwe grote knoppen
daarna: klik op een willekeurige laag bij het onderdeel WAT van de service.
**Niet juist: Dit geeft metainfo van een laag met blauwe balk, rode knoppen.
Had moeten zijn: Rode balk, blauwe grote knoppen**

Dus externe homepagina levert bij doorklikken vanaf service de interne stylesheet (wat kleuren betreft) van de betreffende laag.

Dit had de externe stylesheet van de betreffende laag moeten zijn.

**Comment by SandroNeumann** [comment]
Zelfde als #300 welke onder 1.1.4 staat.

**Comment by gerardnienhuis** [comment]
staat er nu dubbel in , dit issue kan nu gesloten, #300 blijft openstaan voor versie 114
