### ISSUE TITLE
Juiste publicatiedatum bij stylesheet van services

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#414]
Nu staan er 2 vermeldingen van tijdstippen bij de WANNEER bij services, die geen van beide zinvol zijn. Ze moeten vervangen worden door de Datum laatste wijziging (is publicatiedatum) van de service. De bedoeling is dat het zoveel mogelijk vergelijkbaar wordt, met datumvermeldingen van statische kaarten en geodatasets.

Tekst wordt: Datum publicatie service met daarachter datum, bijvoorbeeld

Datum publicatie service: 09-04-2015

**Comment by SandroNeumann** [comment]
De datum laatste wijziging service beschrijving is verplicht. Gelijk maken aan de datum publicatie service?

**Comment by SandroNeumann** [comment]
@gerardnienhuis: Kun je nog op bovenstaande vraag reageren?

**Comment by gerardnienhuis** [comment]
zojuist telefonisch afgestemd: datum publicatie en beschrijving gelijk maken. Wordt beide datum van beschrijving. Voorbeeld hieronder:

Er staat nu:

Naam van de service: B42_energie
Voltooiing service: 20-04-2011
Laatste wijziging servicebeschrijving: 03-12-2013

Er komt te staan:

Naam van de service: B42_energie
Publicatie service: 03-12-2013
Laatste wijziging servicebeschrijving: 03-12-2013

Merk op: alleen laatste wijziging beschrijving is bekend en verplicht in de standaard. Maar omdat dit hetzelfde is als de datum laatste wijziging is deze oplossing wel correct. Datum publicatie service is dus altijd gelijk aan laatste wijziging service beschrijving.

**Comment by gerardnienhuis** [comment]
werkt nu goed, getest met 

https://acc-www.geoportaaloverijssel.nl/metadata/service/36e0e91b-59a9-4dd8-8038-e0435af8144e
en 
https://acc-www.geoportaaloverijssel.nl/metadata/service/c16c8f56-ad2d-4ed2-8950-779cc379b93f

Naam van de service: B7_test_openbaar
Publicatie service: 19-04-2017
Laatste wijziging servicebeschrijving: 19-04-2017

issue kan gesloten
