### ISSUE TITLE
Andere ondergrond dan PDOK wms in viewer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#416]
In verband met onbekende stabiliteit van PDOK services is het te overwegen om een andere ondergrond te gaan gebruiken. Bijvoorbeeld een ondergrond gebaseerd op onze eigen services, of open streetmap of nog anders. Bedoeling is dat alle viewers die nu in het Geoportaal zitten dan niet meer van de PDOK WMS afhankelijk zijn, maar gebruik maken van deze alternatieve WMS. Als wij zelf geen eigen ondergronden gaan maken, dan denk ik bijvoorbeeld aan: http://www.openbasiskaart.nl/mapcache/tms/1.0.0/osm@rd maar mogelijk zijn er ook bij BIJ12 (GBO) ondergronden die stabiel genoeg zijn, b.v. als ondergrond in viewers voor de risicokaart.

**Comment by gerardnienhuis** [comment]
nav email van Herman impact laag toegekend en verplaatst naar versie 1.1.3.
Voorstel is om de OSM ondergrond te gebruiken:
http://www.openbasiskaart.nl/mapcache/tms/1.0.0/osm@rd

**Comment by gerardnienhuis** [comment]
nieuw voorstel: eerst half jaar ervaring opdoen, dan eventueel naar andere ondergrond op zoek. Welke ondergrond gebruikt de risicokaart trouwens? is die mogelijk nog stabieler dan pdok?

**Comment by HermanAssink** [comment]
De Risicokaart gebruikt een ondergrond die tot voor enkele weken door IDgis werd gehost en nu door Atos. Bij mijn weten is deze ondergrond de laatste jaren niet geactualiseerd.

**Comment by gerardnienhuis** [comment]
Dan heb je 2 redenen om vooralsnog niet die ondergrond te gebruiken. We zoeken tzt een alternatief voor PDOK, als het echt nodig blijkt. Issue is nu naar 1.2 verplaatst

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, vooralsnog. Issue niet sluiten maar tzt keer evalueren. Issue naar milestone 1.4 verplaatst.

**Comment by SandroNeumann** [comment]
Deze wens is er niet meer.
