### ISSUE TITLE
Monitoring tools voor Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#417]
Naast beschikbaarheid en gebruik van services wil ik ook monitoring van gebruik van het Geoportaal zelf. Mogelijk is hier Nagios of AWstats voor in te zetten. Idee is om een wekelijks overzicht te ontvangen via email, waarin voor een beheerder begrijpelijke informatie staat mbt uptime, downtime, gebruik van onderdelen en statistieken mbt bezoekers (wanneer, via welk ip adres, welke organisatie). Ook wil ik deze gegevens kunnen raadplegen via een website, waarbij dan ook de tijdreeksen goed in beeld te krijgen zijn.

**Comment by HermanAssink** [comment]
Gerard, Ik stel voor om als we een keer bij elkaar zijn, met de huidige functionaliteit als voorbeeld. de wensen concreter te maken.

**Comment by gerardnienhuis** [comment]
Goed idee Na oplevering 113 lijkt een goed moment

**Comment by gerardnienhuis** [comment]
zie ook #486

**Comment by HermanAssink** [comment]
Wensen te bespreken

**Comment by gerardnienhuis** [comment]
oplossing van monitoring via nagios lijkt beste oplossing. De app moet dan eerst getest worden op de android telefoon zoals die in Overijssel wordt gebruikt. 

Voorgestelde frequentie van meting: om de 4 uur.  eerste meting van de dag, 4 uur en dan om de 4 uur. Dus 8, 12, 16, 20 en 24 uur. Dat heeft het voordeel dat aan het begin van de werkdag (7 a 8 uur) de meting beoordeeld kan worden. Zijn er fouten dan zijn die mogelijk te herstellen voor de volgende meting.  te monitoren services in gezamenlijk overleg bepalen.

**Comment by SandroNeumann** [comment]
Dit issue gaat op in #536 en IDgis/geo-publisher#914
