### ISSUE TITLE
Rapport geodata uitbreiden met kolommen extern, alleen wms en downloadable

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#418]
In het rapport voor Geodata staat nu bij use_limitation alles wat over beperkingen gaat. Maar omdat daar van alles onder kan vallen, is het selecteren heel lastig. Wens is om het rapport met 3 kolommen uit te breiden, in de CSV direct na de kolom use_limitation.

Extra kolommen zijn:
Downloadable  (afhankelijk of downloadable data staat in use_limitation, waarde is ja of nee)
Alleen WMS ((afhankelijk of Alleen WMS staat in use_limitation, waarde is ja of nee)
Geoportaal extern ((afhankelijk of Geoportaal extern staat in use_limitation, waarde is ja of nee)

**Comment by SandroNeumann** [comment]
Downloadable en Geoportaal extern staan er al onder een andere naam in. Die zijn data publiek en metadata publiek genoemd, zodat dat voor andere klanten ook herkenbaar is.

**Comment by gerardnienhuis** [comment]
OK, duidelijk. 

Mijn voorstel zou dan zijn om die 2 kolommen ook echt naast elkaar in de WMS te zetten, er staan nu 2 kolommen tussen die daar niks mee te maken hebben (cc mark en zero). 

Ik wil dus graag ook 1 kolom erbij, met de naam WMS publiek, zodat ik weet dat  Alleen WMS in de metadata is aangegeven. En die kolom zou dan in de CSV ook aanwezig kunnen zijn, gelijk naast data_publiek of metadata_publiek

**Comment by gerardnienhuis** [comment]
Nu niet te testen op acceptatie, zie #458

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
