### ISSUE TITLE
Extra gebruiksrestricties statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#419]
De wens is om, op termijn, 1 of 2 extra gebruiksrestricties op te kunnen nemen bij het invoerscherm van statische kaarten. Je kan nu kiezen uit 2 mogelijkheden (intern of extern) maar de wens is om hier een aantal extra keuzemogelijkheden toe te voegen. Deze mogelijkheden moeten dan ook vindbaar zijn in het beheerscherm voor statische kaarten (dmv zoeken op tekst) en ook in de rapportage van statische kaarten in de kolom use_limitation.

zie afbeelding hieronder

![extra_gebruiksrestricties](https://cloud.githubusercontent.com/assets/9005444/22104651/a58d435a-de40-11e6-9e2a-c915693b0a06.jpg)

**Comment by gerardnienhuis** [comment]
Extra keuzemogelijkheid moet worden:

Alleen voor intern gebruik. Niet uitleveren zonder verklaring. Bevat privacy-gevoelige informatie.

**Comment by SandroNeumann** [comment]
@gerardnienhuis:
Welke opties vallen onder intern en extern, voor de voorkant van het geoportaal?

**Comment by gerardnienhuis** [comment]
De tekst moet worden:

Alleen voor intern gebruik. Niet uitleveren zonder bewerkingsovereenkomst. Bevat privacy-gevoelige informatie.

Deze tekst moet je kunnen kiezen als je een statische kaart bewerkt of toevoegt. 

Er zijn dus dan 3 mogelijkheden:

1) Alleen voor intern gebruik. (die is er al)
2) Alleen voor intern gebruik. Niet uitleveren zonder bewerkingsovereenkomst. Bevat privacy-gevoelige informatie. 
2) Bron mag ook voor interne partijen vindbaar zijn. (die is er ook al)

De statische kaarten waarin één van de eerste 2 mogelijkheden zijn aangegeven, die mogen alleen via het interne Geoportaal zichtbaar zijn.
Betreft dus nummer 1 en 2. 

Nummer 3 mag ook via het externe Geoportaal zichtbaar zijn.

Merk op: je kan maar 1 van de 3 mogelijkheden kiezen. Dat blijft dus net zo werken, als nu het geval is.
Er komt alleen voor de gebruikers een derde mogelijkheid bij.

**Comment by SandroNeumann** [comment]
@gerardnienhuis: De nieuwe optie is qua tekst erg lang voor een selectie menu. Die kunnen namelijk niet meerdere regels hebben. Kun je de tekst inkorten?

**Comment by gerardnienhuis** [comment]
Alleen voor intern gebruik. Extern leveren met bewerkingsovereenkomst (privacy-gevoelige informatie).

**Comment by gerardnienhuis** [comment]
Alleen voor intern gebruik. Extern leveren met bewerkingsovereenkomst (privacy-gevoelige informatie).


dit met het worden: andere versies kunnen genegeerd worden.

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
