### ISSUE TITLE
Temporele dekking niet van toepassing als tijden zelfde zijn

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#424]
Het is voor een gebruiker erg verwarrend als je bij WANNEER in de stylesheet van geodatasets leest, dat bij temporele dekking een "van datum" en een "tot datum" hetzelfde is.

Dit wordt veroorzaakt omdat deze datums nu worden gebruikt om aan te geven dat de temporele dekking "niet in te vullen" of "niet relevant" is..

Maar het zou beter zijn, om in die situatie in de stylesheet aan te geven, dat het "Niet van toepassing" is. Dus alleen toepassen als "van datum" en "tot datum" hetzelfde is.

Er staat nu:
Temporele dekking
Van datum: 02-02-2011
Tot datum: 02-02-2011

Voorstel nieuwe tekst:

Temporele dekking
Datum: Niet van toepassing

nb: in de rapportage van geodatasets moet wel de van en tot datum blijven staan.

**Comment by SandroNeumann** [comment]
De stylesheet aanpassen zodat alleen de data getoond worden wanneer ze verschillen. Anders "Niet van toepassing" invullen.

**Comment by gerardnienhuis** [comment]
Steekproeven uitgevoerd. 

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/fad3457d-da7c-470a-bb10-5ef67c87d708
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/26531285-60e4-4bc1-97b7-a073fabe9692
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/244cf42a-9d6a-4c58-ad7c-1f5b47eef666

blijkt goed te werken, issue kan gesloten
