### ISSUE TITLE
Geen ruis meer in de log van de provider

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#428]
De huidige log bevat (fout)meldingen die genegeerd kunnen worden. Mogelijke oplossing: status wijzigen in DEBUG.

**Comment by SandroNeumann** [comment]
Uitzoeken welke log meldingen dit zijn.

**Comment by gerardnienhuis** [comment]
Zou het te overwegen zijn om een grep-achtige actie uit te voeren en het resultaat daarvan naar een andere file te laten schrijven? Als daar dan de meest belangrijke regels in staan, dan zou het voor een beheerder mogelijk al makkelijker zoeken zijn. Je hoeft dan alleen maar het kleinere bestand te bekijken, en pas bij problemen het grotere bestand.

**Comment by SandroNeumann** [comment]
Een grep-programma maken zoals @gerardnienhuis omschrijft is een goed idee.

Acties:
- overzicht maken welke logregels in het nieuwe bestand moeten komen
- het oorspronkelijke bestand in laten lezen
- de regels door het programma laten beoordelen of ze wel of niet naar het nieuwe bestand geschreven moeten worden

**Comment by gerardnienhuis** [comment]
let op: deze melding is gisteren ook aangemaakt in de github van de publicatieomgeving. In ieder geval daar een link mee opnemen of deze melding volledig sluiten ivm dubbel?

**Comment by gerardnienhuis** [comment]
Dit issue wordt meegenomen bij de publicatieomgeving. Wordt daarom hier gesloten en elders in github geopend.

**Comment by gerardnienhuis** [comment]
zie verder bij:

https://github.com/IDgis/geo-publisher/issues/914 

https://github.com/IDgis/geo-publisher/issues/711
