### ISSUE TITLE
Fout bij aanpassing status na selectie

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#43]
Selecteren van leverancier en daarna actie van meerdere records aanpassen, geeft fout: This exception has been logged with id 6p22ficc1.

Eenvoudig te reproduceren fout: 

stap 1) selecteer Nienhuis (of een willekeurig andere leverancier)
stap 2) aantal records aanvinken
stap 3) knop statusverandering indrukken, bijvoorbeeld "goedkeuren" indrukken, 

Dit geeft popup scherm met de waarschuwing "als u deze informatie wilt opslaan, moet de eerder opgeslagen informatie opnieuw worden verzonden"

Verder gaan geeft soms foutmelding (lijkt browserafhankelijk) en soms krijg je bij "verder gaan" wel juiste resultaat. Dat waarschuwingsscherm is erg onhandig en onwerkbaar.

Opmerking nr 35 bij testresultaten 3-2-2016

![fout_aanpassen_na_selecteren](https://cloud.githubusercontent.com/assets/9005444/12782717/54910ab8-ca7d-11e5-84e4-e3456cebd780.jpg)

**Comment by SandroNeumann** [comment]
Ik kan dit op de testomgeving reproduceren. Op de ontwikkelomgeving echter niet. Het zou kunnen dat dit issue indirect is opgelost. Mijn voorstel is om dit bij de nieuwe versie opnieuw te testen en mocht het probleem zich weer voordoen dan wordt het bij de volgende milestone afgehandeld.

**Comment by gerardnienhuis** [comment]
Prima

Verstuurd vanaf mijn iPhone

Op 11 feb. 2016 om 17:30 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Ik kan dit op de testomgeving reproduceren. Op de ontwikkelomgeving echter niet. Het zou kunnen dat dit issue indirect is opgelost. Mijn voorstel is om dit bij de nieuwe versie opnieuw te testen en mocht het probleem zich weer voordoen dan wordt het bij de volgende milestone afgehandeld.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/43#issuecomment-182944510.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
probleem bestaat nog steeds

**Comment by gerardnienhuis** [comment]
zojuist thuis getest met Firefox, Internet Explorer (11), Opera en Chrome (browsers zeer recent geupdate): hier lijkt dit probleem niet op te treden. Heeft het te maken met oudere IE versie die bij provincie Overijssel gebruikt wordt?

**Comment by SandroNeumann** [comment]
Welke versie wordt bij de provincie gebruikt? Daar krijg je nog altijd de waarschuwing dat de informatie opnieuw verzonden wordt?

**Comment by gerardnienhuis** [comment]
wordt morgen uitgetest

**Comment by gerardnienhuis** [comment]
blijkt niet meer op te treden, niet extern (met 4 meest actuele browsers getest) en ook niet bij het provinciehuis van Overijssel (met IE 11)
