### ISSUE TITLE
Rapport download request time in 3 kolommen ipv 1 kolom

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#435]
De tijd waarop de download is aangevraagd, die staat uiterst nauwkeurig in 1 kolom.
Bij analyse van deze data is dat lastig.

Voorstel: request time in 2 delen splitsen en datumnotatie aanpassen

nu staat er:

2016-08-25 14:00:01.207993

Dat worden 3 kolommen:

2016-08-25 14:00:01.207993 (kolom blijft heten: request time)
25-08-16 (kolom heet datum)
14:00	(kolom heet tijdstip)

Dat kan in excel ook handmatig, maar is lastig om steeds te herhalen.
stap 1: kolom toevoegen achter kolom request time
stap 2: daarna alles selecteren van kolom request time
stap 3: ga dan naar gegevens: 
stap 4: kies tekst naar kolommen, type vast breedte, en datumveld aangeven

Als dit al in de CSV is gezet, dan is verwerking van die data makkelijker.

**Comment by SandroNeumann** [comment]
In de sql de kolommen toevoegen en met een substring functie de juiste tekst eruit filteren.

**Comment by gerardnienhuis** [comment]
aangepaste en verbeterde versie is #545 
hierdoor is dit issue dubbel en kan deze gesloten worden.
