### ISSUE TITLE
Inhoud kolom service_publiek vervangen door Type beveiliging

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#437]
De kolom service_publiek geeft nu aan of een service wel of niet als een beveiligde service wordt aangeboden. Wens is om dit te vervangen door het type beveiliging.

Er zijn 3 smaken:

1) Beveiligd.

In deze situatie zijn de WMS en WFS services niet openbaar. Ze zijn beschikbaar in volledig beveiligde omgeving: alleen voor intern gebruik of achter wachtwoord.

2) Alleen WMS: hiervan is alleen de WMS beschikbaar en openbaar

3) Openbaar. Zowel WMS als WFS is openbaar en beschikbaar.

**Comment by SandroNeumann** [comment]
Sql wijziging zodat de kolom een van de drie beveiligingtypes weergeeft.

**Comment by gerardnienhuis** [comment]
Blijkt correct te werken, issue kan gesloten.
