### ISSUE TITLE
Help naar juiste onderdeel van helppagina

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#439]
Bedoeling is dat de knop help bij HOME, UITGEBREID ZOEKEN en BLADEREN alle 3 meteen op de tekst uitkomen in de helppagina die daar over gaat. 

Dus klik op help bij het onderdeel HOME komt uit bij het begin van de helppagina: Handleiding voor het gebruik van het Geoportaal.

Uitgebreid zoeken komt uit bij het onderdeel over uitgebreid zoeken.
Bladeren komt uit bij het onderdeel over bladeren.

nb: vooraf moet de helptekst aangepast worden (volgorde van tekst) zodat dit makkelijker bruikbaar is.

**Comment by SandroNeumann** [comment]
Er moeten anchors gemaakt worden voor de onderdelen en daar moet naar gelinkt worden.

Er zal op de meeste desktop schermen echter niet veel effect te zien zijn, omdat de tekst beperkt is en het bijna op één scherm past allemaal.

**Comment by gerardnienhuis** [comment]
Dit werkt nog niet goed. Mogelijk staan de anchors nog niet goed ingesteld. Bedoeling is dat als je op HELP drukt bij het zoekscherm je dan meteen naar het juiste onderdeel in de helppagina gaat, zie toelichting in plaatje hieronder.

![image](https://user-images.githubusercontent.com/9005444/130071797-879fdf89-2474-4a40-918b-3a9326d5ab9a.png)

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
Bij mij gaat de help op de uitgebreid zoeken pagina naar de juiste paragraaf:
https://acc-intern.geoportaaloverijssel.nl/search

Wat doet het nu bij jou?

**Comment by gerardnienhuis** [comment]
Als ik eerst Bladeren selecteer, en daarna op Help klik, dan kom ik terecht bij Tips bij het zoeken, en niet bij het onderdeel "over bladeren". Dat geldt ook voor uitgebreid zoeken. Als dit niet makkelijk te implementeren is, dan wil ik het nu gewoon zo laten. Is er tijd, dan kan dat eventueel t.z.t. aangepast worden. Issue voor dit moment daarom gesloten.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Dat komt omdat je al helemaal naar onderen gescrolled bent. Verder kan niet.
