### ISSUE TITLE
Zoeken geoportaal niet altijd zelfde resultaat

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#441]
Vanaf afgelopen maandag viel me op dat het zoeken in het Geoportaal niet altijd dezelfde resultaten lijkt op te leveren. De zelfde zoekopdrachten leveren op verschillende momenten andere resultaten. Je zou bij dezelfde opdrachten altijd dezefde resultaten moeten hebben. Getest met intern en extern Geoportaal.

Hieronder enkele testresultaten van zoeken in extern Geoportaal:

=========================================

zoekterm: BGT
later test: zoekterm: Topografie 

Weet zeker dat aanwezig is:
BGT puntobjecten Overijssel (20-01-2017, Provincie Overijssel: eenheid Publieke Dienstverlening)

Resultaat: 
statische kaarten: niets gevonden
wel aantal gis bestanden gevonden

Er zijn echter beslist 4 statische kaarten met BGT en topografie in metadata
hoe kan dat?

======================================================

Na paar keer bladeren en weer zoeken daarna met BGT,
dan wel de 4 statische kaarten gevonden.

eerst niet, daarna wel? hoe kan dat?

======================================================

De bron mag ook voor externe partijen vindbaar zijn
wel voor extern gepubliceerd, niet gevonden als je BGT zoekt

in beheermodule zie je dat aanwezig moet zijn:

150122 Werkkaarten BGT 2015 en 2016
160093	BGT stand van zaken Landelijke voorziening Nederland
160093	BGT Assendorperplein Zwolle

Bovenstaande statische kaarten worden niet gevonden als je zoekt naar BGT

maar als je zoekt naar 160093 dan zijn er wel 3 statische kaarten
te vinden. Hierin kan je zien dat BGT in metainfo aanwezig is.

hoe kan dat?

=======================

na aantal kaart bladeren in Geoportaal wordt opeens alles gevonden als je zoekt met 
topografie. Nu zijn die 4 statische kaarten wel weer aanwezig.

totaal: 17 bestanden

13 gis bestanden
4 statische kaarten

nu wel complete set aanwezig. Hoe kan dat?

===========================

**Comment by SandroNeumann** [comment]
Ik heb hier geen verklaring nog voor gevonden. Hij harvest goed. Alles staat in de database. Alleen de tabel die gegenereerd wordt voor het zoeken heeft de ene keer wel en de andere keer niet die records van de BGT die je verwacht. Ik heb daar geen verklaring voor.

Ik heb de harvester wel herstart en sindsdien gaat het vooralsnog goed. Dus zou voorstellen om dit in de gaten te houden en wanneer het weer fout gaat dit te melden. Op dit moment kan ik het dus niet meer reproduceren.

**Comment by gerardnienhuis** [comment]
Ik heb afgelopen dagen regelmatig getest: zoeken met BGT of topografie.
Levert normale aantal bestanden op (extern totaal BGT:  19, waarvan 4 statische kaarten)
Probleem is niet teruggekomen tot nu toe.

**Comment by gerardnienhuis** [comment]
lijkt nu nog steeds goed te werken, issue kan gesloten
