### ISSUE TITLE
Inloggen Kets lukt niet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#442]
Inloggen in beheermodule voor het aanbieden van statische kaarten is niet gelukt voor gebruiker

kets-bolkestein

email wat hier bij hoort is: j.kets-bolkestein@overijssel.nl

Als zij "wachtwoord vergeten" gebruikt dan volgt geen mail in mailbox van j.kets-bolkestein@overijssel.nl

Kan het zijn dat het emailadres van deze gebruiker niet juist is?

**Comment by SandroNeumann** [comment]
E-mailadres was fout. Nu zou het moeten kloppen.

**Comment by gerardnienhuis** [comment]
probleem blijkt opgelost, issue kan gesloten
