### ISSUE TITLE
Beheermodule nieuwe statische kaart 2017 ipv 2016

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#443]
Graag default 2017 neerzetten bij de locatie voor de statische kaart.
Daar staat nu nog 2016, maar de meeste kaarten zijn nu nieuw en dus van 2017.

De volledige default waarde wordt dan:

K:\bab\geo-informatie\2017\

zie figuur:

![2017](https://cloud.githubusercontent.com/assets/9005444/23790768/cab56326-0580-11e7-8602-9f345a71084d.jpg)

**Comment by SandroNeumann** [comment]
Is aangepast

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
