### ISSUE TITLE
1.2 is 1.3 en 1.3 is 1.4 geworden, nieuwe 1.2 aangemaakt

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#444]
@gerardnienhuis Omdat het derde cijfer van het versienummer bedoeld is voor bug-releases heb ik milestone 1.3 hernoemd naar 1.4 en 1.2 naar 1.3. En er is een nieuwe milestone 1.2 aangemaakt die gebruikt kan worden voor de issues die anders onder 1.1.5 zouden gaan vallen.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, kan als issue op zich gesloten
