### ISSUE TITLE
Rapportage vreemde tekens voorkomen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#445]
In de rapportages van kunnen vreemde tekens voorkomen. De letters met trema's, accenten en dergelijke, die worden in de csv niet goed weergegeven. Maar alle tekens van de metadata zijn wel utf-8. Wens is dat alle tekens die in de oorspronkelijke metadata staan, ook op dezelfde manier in de csv's van de rapportages terugkomen.

**Comment by SandroNeumann** [comment]
Zou je aan kunnen geven waar je deze vreemde tekens precies hebt waargenomen?

**Comment by gerardnienhuis** [comment]
Na de ijstijden werd het in Nederland warmer en natter, waardoor op sommige plekken dode planten niet afgebroken werden maar zich opstapelden. Na eeuwen van opstapeling ontstond op die manier een dikke veenlaag. Vanaf de late middeleeuwen begon men dit veen te systematisch in gebruik te nemen. Om het veen te kunnen ontginnen werden slootjes voor afwatering gegraven. Meestal gebeurde dit vanaf een riviertje recht het veen in, zodat parallelle stroken ontstonden. Tussen de parallelle slootjes kon dan landbouw worden bedreven. Door de ontwatering zakte het maaiveld, waardoor aan de Zuiderzeekust het gebied kon overstromen. Hier is dan ook een kleilaagje over de â€˜agrarische veenontginningâ€™ afgezet, de zogenaamde â€˜klei-op-veengebiedenâ€™.  Deze natte gebieden hadden een natuurlijke aantrekkingskracht op watervogels. Er werden eendenkooien aangelegd om watervogels gemakkelijker te vangen. Veel eendenkooien zijn reeds verdwenen maar er liggen nog enkele zichtbaar in het landschap, vooral in de Kop van Overijssel.  Na de late middeleeuwen begon men op grotere schaal veen te winnen om als brandstof te gebruiken. Deze â€˜verveningenâ€™ waren in eerste instantie niet grootschalig gecoÃ¶rdineerd. Vanaf de 19e eeuw werd het winnen van turf planmatig en grootschalig aangepakt, waarbij op vaste afstand van elkaar wijken werden gegraven om de turf te kunnen afvoeren. Voor deze â€˜veenkoloniÃ«nâ€™ werden kanalen gegraven zoals de Dedemsvaart. Soms kwam het maaiveld door vervening of agrarisch grondgebruik zo laag te liggen dat met behulp van dijken, molens en/of sluisjes het land kunstmatig droog gehouden moest worden en er â€˜poldersâ€™ ontstonden. ----Bij het onderdeel â€œkwaliteitâ€ is nog meer informatie te vinden over de attributen in dit bestand. ----


dit is een voorbeeld van metadata, gevonden in een rapport. De oorspronkelijke metadata bevat niet woorden zoals â€˜poldersâ€™

**Comment by gerardnienhuis** [comment]
Nog een voorbeeld:

RWZI staat voor Riool Water Zuiverings Installaties. Uit rioolslib kan biogas gewonnen worden door middel van vergisting. Op een aantal RWZIâ€™s gebeurt dit al, en wordt de door verbranding van het biogas opgewekte energie gebruikt voor het zuiveringsproces.   In deze versie van de Kansenkaart worden alleen de locaties van RWZIâ€™s weergegeven.   - - - - - Meer informatie over de inhoud van de attributentabel is te vinden onder tabblad Kwaliteit

**Comment by SandroNeumann** [comment]
Ik bedoel de plek in de rapportage, zodat ik dat ook kan controleren/inlezen met andere spreadsheet programma's.

**Comment by gerardnienhuis** [comment]
betreffende excel is gemaild naar @SandroNeumann

**Comment by SandroNeumann** [comment]
Hetzelfde probleem doet zich bij LibreOffice voor. Is dus geen probleem met Excel.

**Comment by HermanAssink** [comment]
Is oplosbaar door de encoding bij het openen van de csv te kiezen, zie bijv. https://superuser.com/questions/280603/how-to-set-character-encoding-when-opening-excel. Er zit geen fout in de csv.

**Comment by HermanAssink** [comment]
Eventueel HELP/Instructie hiervoor uitbreiden.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
Lever je de instructie hiervoor aan? Ik zal vandaag waarschijnlijk door de resterende issues van 1.2 zijn.

**Comment by gerardnienhuis** [comment]
Bij de rapportage verschijnt altijd een lichtblauw vlak met extra tekst, zie bijgevoegd plaatje. De tekst die er nu staat, die moet worden uitgebreid met onderstaande tekst. Let op: dat geldt voor alle rapportages.

Eerst een witregel. En daarna de tekst: 

Let op: in Excel zijn er soms vreemde tekens zichtbaar nadat je dit rapport hebt ingelezen. Er staat dan in de tekst iets vreemds, terwijl er eigenlijk een ë of é had moeten staan. Dit kan je voorkomen door onderstaande 5 stappen uit te voeren:
1) Sla het rapport op als *.txt (dus niet standaard als *.csv). 
2) Lees daarna het txt-bestand in, in Excel (met "Bestand Openen").
2) Geef aan dat de gegevens zijn "Gescheiden". Standaard staat hier vaak "Vaste breedte".
3) Pas ook  de "codering van het oorspronkelijke bestand" aan. Dit moet worden: 65001: unicode (UTF-8). 
4) Geef aan dat de velden gescheiden zijn door een punt-komma (;) en niets anders.
5) Klik op "Voltooien" en je hebt wel weer gewoon leesbare tekst zonder vreemde tekens erin.

**Comment by gerardnienhuis** [comment]
![extra_tekst](https://user-images.githubusercontent.com/9005444/31006893-f00f9c2c-a4fe-11e7-8073-ab8ab318a181.jpg)

**Comment by gerardnienhuis** [comment]
De instructie blijkt goed te werken. Gecontroleerd door steekproeven te nemen en door ook op die vreemde tekens in het rapport te zoeken (zoals é en ë). De metainformatie blijkt nu goed in het rapport te staan: dezelfde informatie als op het geoportaal zelf, bij de samenvatting, is nu ook in het rapport zichtbaar. Issue kan gesloten.
