### ISSUE TITLE
Tijdelijk extra tekst homepagina geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#449]
Wens is om, in verband met een enquete, extra tekst op de homepagina van het Geoportaal zichtbaar te hebben. Deze tekst moet dan, na de enquete, weer verwijderd worden.

nb: de tekst wordt 1 regel tekst, inclusief een doorlink naar een externe andere site.

zie plaats van extra tekst bijgevoegd plaatje

![extra_tekst_geoportaal](https://cloud.githubusercontent.com/assets/9005444/24507877/043fa48a-1562-11e7-9d4f-949aa32a8b70.jpg)

**Comment by gerardnienhuis** [comment]
Bedoeling is 1 witregel extra, 1 regel extra tekst en 1 witregel daarna.
Die extra tekst bevat waarschijnlijk meestal ook een doorlink naar een extra pagina (maar hoeft niet altijd).

Wens is om het configurabel te maken: de tekst inclusief doorlink kan ik nu niet geven. Dus standaard is de layout zoals die nu al is. Maar als er wel extra tekst nodig is, dan moet die (inclusief de witregel onder en boven) ook zichtbaar zijn en moet de doorlink naar de extra pagina ook werken). 

Doel is dat hiermee niet steeds als er extra tekst moet komen, een nieuwe versie van het geoportaal gemaakt moet worden, maar dat het aan te passen is, als de noodzaak er is (en dan in het kader van beheer ipv in kader van nieuwe versie).

**Comment by SandroNeumann** [comment]
De tekst zelf lever je nog aan?

**Comment by gerardnienhuis** [comment]
De bedoeling is, dat die tekst eenvoudig in kader van beheer aan te passen is. Als test kan je wat mij betreft zoiets nemen als:

" Dit is een test. Link naar nu.nl (en dan nu.nl als link onderstreept en met doorlink naar nu.nl)"
maar de tekst kan ook langer zijn (max 1 regel), bijvoorbeeld:

"Dit is een test. Hier komen extra teksten over het Geoportaal. Zie website provincie Overijssel (waar dan de tekst provincie Overijssel onderstreept is en als link gaat naar "http://www.overijssel.nl"

De bedoeling is, dat het eenvoudig en zonder teveel impact of noodzaak voor nieuwe versie er zo nu en dan extra tekst op het Geoportaal gezet kan worden. Die tekst moet ook verwijderd of aangepast kunnen worden, indien nodig.

**Comment by SandroNeumann** [comment]
Dat snap ik, maar ik heb voor de eerste keer de tekst nodig zoals die in het begin ingesteld moet gaan worden.

**Comment by gerardnienhuis** [comment]
Bedoeling is, dat er standaard geen tekst staat. Dus dan is layout precies zelfde zoals nu het geval is. Die extra tekst is alleen optioneel, voor speciale gevallen. Voor het testen vind ik het prima om de onderstaande tekst te testen. Maar we moeten dan bij de acceptatietest ook testen, hoe e.e.a. er uit ziet, zonder die tekst

voorbeeld tekst:

"Dit is een test. Hier komen extra teksten over het Geoportaal. Zie website provincie Overijssel (waar dan de tekst provincie Overijssel onderstreept is en als link gaat naar "http://www.overijssel.nl"

**Comment by SandroNeumann** [comment]
Maar je wilde dit toch initieel voor een enquete? Die tekst moeten we tzt nog ontvangen dan.

**Comment by gerardnienhuis** [comment]
Dat is correct. Voor een enquête, maar eventueel ook voor iets anders. Bedoeling is dat het flexibel in te zetten is. Voor een enquête, maar ook voor andere doeleinden. Tekst moet dus vrij op te geven zijn.

**Comment by gerardnienhuis** [comment]
De positie van de tekst is niet goed.

De tekst zelf is wel goed en de link blijkt ook goed te werken. Maar de tekst zelf staat te dicht onder de knoppenbalk. Er was gevraagd om 1 witregel extra, en dan pas de tekst.  

Bedoeling is dat de extra tekst goed opvalt, dus ook met extra witruimte er om heen.

Het lijkt er op alsof de tekst juist dichter bij de knoppenbalk staat, in plaats van verder daarvan verwijderd.

zie afbeelding: 1.1.4. is een schermafdruk van de nieuw acceptatieversie. 1.1.3. is huidige productieversie.

![witregel ontbreekt](https://cloud.githubusercontent.com/assets/9005444/25265068/4d26a1c0-266b-11e7-93af-a86ba79abbe0.jpg)

**Comment by gerardnienhuis** [comment]
per ongeluk gesloten, is nog niet opgelost en dus nog open.

**Comment by gerardnienhuis** [comment]
witregel is toegevoegd, werkt nu goed, issue kan gesloten.
