### ISSUE TITLE
IP-adres van IDgis aanpassen voor test, acc en prod

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#451]

**Comment by gerardnienhuis** [comment]
ik neem aan dat dit nu goed werkt voor IDGis? Kan het issue dan gesloten? 
Is niet iets wat prov. Overijssel kan testen.

**Comment by SandroNeumann** [comment]
Klopt, dit moeten wij verifieren nadat we in productie zijn.
