### ISSUE TITLE
Service met wms_only dataset levert altijd alleen maar WMS aan portaal (ook wanneer het in secured-services zit)

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#453]

**Comment by gerardnienhuis** [comment]
Wat is hier het issue en hoe kan ik dit als gebruiker testen?

**Comment by SandroNeumann** [comment]
Je kunt dit testen door te kijken of wanneer een service in een WMS only omgeving zit er ook alleen een WMS service aan de voorkant van het geoportaal getoond wordt. En als een service in een beveiligde omgeving zit deze zowel WMS als WFS toont (dus zelfs wanneer er een WMS only dataset in zit).

**Comment by gerardnienhuis** [comment]
is zelfde als https://github.com/IDgis/geoportaal-test/issues/465 ?

**Comment by SandroNeumann** [comment]
Nee, dat issue gaat over wat in de metadata zichtbaar is (en de download link). Dit issue gaat over welke records te zien zijn aan de voorkant van het geoportaal.

**Comment by gerardnienhuis** [comment]
alleen WMS service gemaakt, met 1 laag: blijkt bij die laag ook slechts 1 service te staat bij details, namelijk alleen de WMS.
Bij openbaar blijken zowel wms als wfs te zien, klopt dus

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
