### ISSUE TITLE
De viewer url van datasets in wms_only services wordt niet geharvest door geoportaal

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#454]

**Comment by SandroNeumann** [comment]
Ook in de html view viewer-urls die beginnen met "wmsonly-services" toestaan.

**Comment by HermanAssink** [comment]
Is dit ook de oorzaak voor het ontbreken "Bekijk in viewer" in de lijst met zoekresultaten in het Geoportaal?

**Comment by SandroNeumann** [comment]
Ja.

**Comment by gerardnienhuis** [comment]
werkt nu wel goed, getest zowel intern als extern portaal. 

issue kan gesloten. 

Hieronder test details

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/594306a7-2f85-42c9-bb64-da13f525303d
Bestandsnaam: Gemeentegrenzen TEST alleen WMS
























































































































































Alternatieve titel: B7.gemgrens_alleen_WMS (B7.B75)

Status: Compleet


Website: http://acc-wmsonly-services.geodataoverijssel.nl:80/viewer/layer/B7_test_alleen_wms/Gem_TEST_alleen_WMS

OGC:WMS: http://acc-wmsonly-services.geodataoverijssel.nl:80/geoserver/B7_test_alleen_wms/wms
XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/594306a7-2f85-42c9-bb64-da13f525303d?noStyle=true
