### ISSUE TITLE
Lagen/laag wordt niet getoond/uitgeklapt in viewer (via RDP)

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#455]
Bij bekijken in viewer wordt de laag aardgastransportleidingen in service wms-only niet getoond/uitgeklapt via RDP in FF 52.0.2

**Comment by SandroNeumann** [comment]
Ik kan dit niet reproduceren. Heb het in IE, FF en Chrome zowel lokaal als in remote desktop getest. Zelfde versie als hierboven staat in FF.

**Comment by HermanAssink** [comment]
Niet goed reproduceerbaar, alleen in RDP geconstateerd
