### ISSUE TITLE
Bekijken lagen in service geeft foutmelding 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#456]
Het bekijken van lagen bij onderdeel WAT levert fouten op. Zie bijgevoegde figuur.

Dit lijkt bij alle services en alle lagen op te treden. Opmerkelijk is dat bekijken van lagen in viewer wel goed lijkt te werken. In de productieversie 1.1.3 is dit probleem niet opgevallen.

3 bijvoorbeelden:

https://acc-www.geoportaaloverijssel.nl/metadata/service/d27f077b-d471-4778-8591-820bbbd1b127
Naam van de service: Beheer grondwater
B3_Meetnet_verdroging
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/d3675443-bbdc-4b25-b756-fcb380dbc60e
Oops, an error occurred
This exception has been logged with id 73lda1ob5.

B3_Grondwaterbeschermingsgebieden
Oops, an error occurred
This exception has been logged with id 73lda6n17.

Dit geldt ook voor een willekeurige andere services:

Naam van de service: B46_natuur_en_landschap
https://acc-www.geoportaaloverijssel.nl/metadata/service/281728b8-18e7-432e-afbb-fb6f0447de18
B4_Begrenzing_EHS_en_Zone_Ondernemen_met_Natuur_en_Water
Oops, an error occurred
This exception has been logged with id 73lda8np6

![fout_doorverwijzing_lagen_in_service](https://cloud.githubusercontent.com/assets/9005444/25140940/3a14720c-2462-11e7-8431-48f88852de61.jpg)

**Comment by gerardnienhuis** [comment]
Kan het zijn dat inlezen van xmls via provider niet goed is gegaan? Er zijn "maar" 45 geodatasets te vinden (zoek bij uitgebreid zoeken, alleen geodata aangeklikt). Er staan er veel meer bij de services genoemd.

**Comment by gerardnienhuis** [comment]
wens: als achterliggende metadata afwezig is, dan wel zichtbaar in lijst, zoals nu het geval is. maar niet aanklikbaar maken, zodat foutmelding niet meer komt.

nb: voor 114 blijkt het wel te werken, getest met Begrenzing EHS en Zone Ondernemen met natuur en Water

**Comment by SandroNeumann** [comment]
Ik zie deze foutmeldingen niet meer. Kan dit gesloten worden?

**Comment by gerardnienhuis** [comment]
Het probleem lijkt niet meer op te treden. Is zojuist getest bij meerdere services. 
Dit issue kan gesloten.
