### ISSUE TITLE
XML link bij details op verkeerde plaats

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#457]
De link naar de xml lijkt op een verkeerder plaats te staan, bij de details van geodatasets.

zie bijvoorbeeld:
Bestandsnaam: Boomregister Overijssel
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/07d7d345-ee2a-9a75-6e6e-68cf867717ad

De link naar xml bij details bijna bovenin: dat is niet de bedoeling en werkt ook niet zo bij 1.1.3..

zie figuur.

zie ook https://github.com/IDgis/geoportaal-test/issues/340

daarin staat dat deze verwijzing bijna onderin moet staan, niet bijna bovenin bij de details.

![xml_vermelding_bovenin](https://cloud.githubusercontent.com/assets/9005444/25143516/0e3e9852-246b-11e7-8c84-3eb6ed06fa17.jpg)

**Comment by SandroNeumann** [comment]
Dat is veranderd vanwege issue #392

**Comment by gerardnienhuis** [comment]
geen bug, is juist goed, moet nog getest als er services zijn.

**Comment by gerardnienhuis** [comment]
is getest, zie er goed uit, issue kan gesloten
