### ISSUE TITLE
Rapportage acceptatieomgeving geeft rapport productieomgeving

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#458]
Als je een rapport van geodata maakt als beheerder, dan komen er heel veel geodatasets in het rapport. Veel meer dan op de acceptatieomgeving staan. Het lijkt er op alsof het rapport wordt gegeven van de data in de productieomgeving. Geldt ook voor rapport van services, download en statische kaarten.

Bedoeling is, dat als je acceptatieversie test, je ook rapport van acceptatieomgeving krijgt.

**Comment by SandroNeumann** [comment]
Het aantal datasets in het rapport is correct. Wat niet correct is zijn het aantal datasets in het geoportaal. Dit komt vanwege hetzelfde probleem als #456.

**Comment by gerardnienhuis** [comment]
Het is dus geen bug. Dit is weer het probleem dat acceptatieomgeving verouderde en foute bestanden bevat. Wens is om t.z.t. de productieomgeving over te kopiëren naar de acceptatieomgeving, zodat die fouten meteen in één keer op te lossen zijn. Op dit moment kan dat aan kant van Overijssel nog niet en daardoor komt soms deze verwarring weer boven. Rapporten zijn dus wat lastiger leesbaar maar wel bruikbaar voor testdoeleinden.

**Comment by gerardnienhuis** [comment]
issue kan gesloten, geen issue voor 1.1.4.
