### ISSUE TITLE
Rapport geodata WMS extern niet begrijpelijk

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#460]
Wij hebben een testservice gemaakt, waarbij zowel de WMS als de WFS extern beschikbaar is. Echter, in het rapport van geodata staat bij de betreffende geodataset, dat er geen WFS aanwezig is.

We hebben ook andere testbestanden gemaakt, en soms ook in services geplaatst (bijvoorbeeld alleen WMS-services). Deze blijken wel de juiste informatie in het rapport te hebben. Alleen bij de datasets met zowel WMS en WFS klopt het niet. Hieronder de details.

De informatie zoals in geoportaal zichtbaar is, bij details
Hier staan dus correct de WMS en WFS beiden in

Bestandsnaam: Gemeentegrenzen TEST openbaar
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/83af4df4-662a-4808-aa0b-f2d21a86d818
Alternatieve titel: B7.gemgrens_openbaar (B7.B75)
Status: Compleet
Download: https://acc-download.geoportaaloverijssel.nl:443/download/83af4df4-662a-4808-aa0b-f2d21a86d818
Website: http://acc-services.geodataoverijssel.nl:80/viewer/layer/B7_test_openbaar/B7_Gem_TEST_openbaar
OGC:WFS: http://acc-services.geodataoverijssel.nl:80/geoserver/B7_test_openbaar/wfs
OGC:WMS: http://acc-services.geodataoverijssel.nl:80/geoserver/B7_test_openbaar/wms
XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/83af4df4-662a-4808-aa0b-f2d21a86d818?noStyle=true

Deel van het rapport:

1547	3bd63601-a5e0-4ee5-b723-9f716e391b99
	Gemeentegrenzen TEST openbaar	
B7.gemgrens_openbaar (B7.B75)
	Betreft een testbestand ivm installatie geoportaal wijziging 1.14 TEST TEST.  De bestuurlijk vastgestelde gemeentegrenzen van de provincie overijssel. 
De gemeentegrenzen zijn afgeleid uit kadastrale grenzen.   De laatste wijziging die in dit bestand 
is opgenomen betreft een grenscorrectie tussen de gemeenten Borne en Hengelo. Deze wijziging is vastgesteld
 bij besluit van Gedeputeerde staten van Overijssel op 9 december 2010 kenmerk 2010/0213330 TEST TEST	46647460-d8cf-4955-bcac-f1c192d57cc4	
a08542db-251b-42c0-882c-9e6340247ba0	geen beperkingen|http://creativecommons.org/publicdomain/mark/1.0/deed.nl	
Geen gebruiksbeperkingen|Geoportaal extern|Downloadable data	Ja	Nee	B7_test_openbaar:B7_Gem_TEST_openbaar	
		vector	Ja	Ja	Nee	Ja

Bij WMS extern kolom staat nu Nee, maar moet Ja zijn, dus had er moeten staan:

|Downloadable data	Ja	Nee	B7_test_openbaar:B7_Gem_TEST_openbaar	
		vector	Ja	Ja	Ja	Ja

**Comment by SandroNeumann** [comment]
Die kolom heeft als betekenis dat het wms alleen extern vlaggetje aan staat voor een dataset. De naamgeving van die kolom kan dus beter, maar de betekenis is of onder gebruiksbeperkingen in de metadata de waarde "Alleen WMS extern" gevonden is.

**Comment by gerardnienhuis** [comment]
DIt blijkt geen bug te zijn, maar is verwarrend voor iemand die snel de controle van het rapport wil doen.

voorstel: kolom naam gaat van
wms_extern naar alleen_wms_extern

nieuwe kolom toevoegen, tussen data_publiek en  alleen_wms_extern
deze kolom gaat heten: wms_extern_aanwezig en bevat waarden Ja of Nee

Bedoeling is dat als er Ja staat, er een WMS beschikbaar is
Staat er Nee, dan is er geen WMS beschikbaar.

Is het Ja, dan komt dat voor als de dataset daarwerkelijk in een WMS service zit

**Comment by gerardnienhuis** [comment]
rapport is nu wel begrijpelijk: 2 versies getest, zowel wms extern aanwezig als afwezig: verschil is goed te zien bij 
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/14de7639-f14d-4308-9912-cbe1070c8758 en 
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/b77e1f16-0e65-4ef2-ac5b-57eceeae41a3

issue kan gesloten
