### ISSUE TITLE
Datumvermelding in rapportage geodatasets

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#462]
Wens is om de datums die in de metadata staan, ook in het rapport te vermelden.

Nu zijn volgens de stylesheet aanwezig (met achter de : een voorbeeld van de vulling)

Voltooiing bestand: 09-06-1996
Publicatie bestand: 19-04-2017
Laatste wijziging bestand: 18-04-2017
Laatste wijziging bestandsbeschrijving: 19-04-2017
Temporele dekking Van datum: 14-01-2011
Temporele dekking Tot datum: 14-01-2011

**Comment by gerardnienhuis** [comment]
Ook in het rapport nieuw opnemen: herzieningsfrequentie.

Voorbeeld van vulling bij een willekeurig bestand:

Bestandsnaam: Ontgrondingen in Overijssel
https://www.geoportaaloverijssel.nl/metadata/dataset/d66cc0d3-9130-44b6-97f0-fd200f37e1a0

Voltooiing bestand: 08-03-1995
Publicatie bestand: 02-06-2017
Laatste wijziging bestand: 01-03-2017
Herzieningsfrequentie bestand: Indien nodig
Laatste wijziging bestandsbeschrijving: 02-06-2017
Temporele dekking
Van datum: 01-02-2011
Tot datum: 01-02-2011

**Comment by SandroNeumann** [comment]
Tonen wat in de xml staat (dus in het Engels) of hoe het door de stylesheet wordt gepresenteerd?

**Comment by gerardnienhuis** [comment]
graag zoals in stylesheet staat:
01-03-2017 als voorbeeld en bij 
Herzieningsfrequentie bestand: Indien nodig en dergelijke

**Comment by gerardnienhuis** [comment]
datum staat verkeerd in kolom laatste wijzing bestandsbeschrijving

ik vermoed dat dag en maand zijn verwisseld:

er staat in het rapport: 1-11-2017

maar in de metadata bij dit bestand staat: 
Laatste wijziging bestandsbeschrijving: 11-01-2017

zie:

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/6ad70d4a-2a7d-499d-9775-a644459b843f

**Comment by gerardnienhuis** [comment]
verwisseling lijkt ook op te treden bij 2 andere kolommen: temportale dekking van en tot

**Comment by gerardnienhuis** [comment]
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/6a4c016f-aade-4547-8522-64f3b3f513a8
Bestandsnaam: Deventer ruimtelijke ontwikkelingen
Volgens metainformatie gevonden bij de WANNEER:

Voltooiing bestand: 31-01-2011
Publicatie bestand: 27-11-2013
Laatste wijziging bestand: 31-01-2011
Herzieningsfrequentie bestand: Onbekend
Laatste wijziging bestandsbeschrijving: 31-08-2016
Temporele dekking
Van datum: 07-03-2011
Tot datum: 07-03-2011

Hierbij is de laatste wijzing bestand beschrijving volgens metainfo: 31-08-2016
dat komt overeen met de datum in het rapport

Maar de temporele datum van en tot is volgens het rapport: 3-7-2011 
Maar bij de WANNEER in de metadata staat echter iets anders: 07-03-2011

Komt het alleen voor bij de dagen onder de 10? Dus bij 01, 02, enz ?

**Comment by gerardnienhuis** [comment]
wat ook opvalt is dat de onjuiste datums in excel als tekst wordt gezien, en niet als echt datum veld.

**Comment by gerardnienhuis** [comment]
nog een voorbeeld:


Bestandsnaam: Nieuwe kaart van Nederland 2010 (lijnen)
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/e54f2336-0fad-4378-baa0-6a567895aab9

Volgens metadata bij het onderdeel WANNEER:

Voltooiing bestand: 01-03-2010
Laatste wijziging bestand: 01-03-2010
Herzieningsfrequentie bestand: Onbekend
Laatste wijziging bestandsbeschrijving: 17-10-2016
Temporele dekking
Van datum: 19-08-2011
Tot datum: 19-08-2011

Volgens rapport:

Fout: >>>>>>>> Voltooiing bestand: 3-1-2010
Fout: >>>>>>>> Laatste wijziging bestand: 3-1-2010
Herzieningsfrequentie bestand: Onbekend
Laatste wijziging bestandsbeschrijving: 17-10-2016
Temporele dekking
Van datum: 19-08-2011
Tot datum: 19-08-2011

**Comment by SandroNeumann** [comment]
In Excel kun je bij het inlezen per kolom aangeven wat het datatype moet zijn. Bij een datumtype kun je aangeven wat het format van het datumveld moet zijn (DMJ in ons geval). Zou je dat willen proberen?

**Comment by gerardnienhuis** [comment]
gedaan, blijkt nu wel goed te gaan:

B4.luchtkwaliteit_2008_point
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/b3c2ebb7-0049-44ad-9d0e-b171ea45d0e1

bij WANNEER in metadata:

Voltooiing bestand: 05-03-2010
Publicatie bestand: 16-05-2017
Laatste wijziging bestand: 05-03-2010
Laatste wijziging bestandsbeschrijving: 16-05-2017
Temporele dekking
Van datum: 17-01-2011
Tot datum: 17-01-2011

In excel rapport staat nu:

Voltooiing bestand: 5-3-2010
Publicatie bestand: 16-5-2017
Laatste wijziging bestand: 5-3-2010
Laatste wijziging bestandsbeschrijving: 16-5-2017
Temporele dekking
Van datum: 17-1-2011
Tot datum: 17-1-2011

**Comment by gerardnienhuis** [comment]
oplossing testen: opslaan zoals ISO, JJJJ-MM-DD

**Comment by SandroNeumann** [comment]
Aangepast naar iso-formaat.

**Comment by gerardnienhuis** [comment]
wordt meteen getest

**Comment by gerardnienhuis** [comment]
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/6a4c016f-aade-4547-8522-64f3b3f513a8
 Bestandsnaam: Deventer ruimtelijke ontwikkelingen
 Volgens metainformatie gevonden bij de WANNEER:

Voltooiing bestand: 31-01-2011
 Publicatie bestand: 27-11-2013
 Laatste wijziging bestand: 31-01-2011
 Herzieningsfrequentie bestand: Onbekend
 Laatste wijziging bestandsbeschrijving: 31-08-2016
 Temporele dekking
 Van datum: 07-03-2011
 Tot datum: 07-03-2011

blijkt nu wel correcte datums in rapport te geven.

**Comment by gerardnienhuis** [comment]
ook getest bij:

B4.luchtkwaliteit_2008_point
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/b3c2ebb7-0049-44ad-9d0e-b171ea45d0e1

bij WANNEER in metadata:

Voltooiing bestand: 05-03-2010
 Publicatie bestand: 16-05-2017
 Laatste wijziging bestand: 05-03-2010
 Laatste wijziging bestandsbeschrijving: 16-05-2017
 Temporele dekking
 Van datum: 17-01-2011
 Tot datum: 17-01-2011

blijkt nu ook correct in rapport weergegeven te worden.

**Comment by gerardnienhuis** [comment]
Meerdere keren nogmaals getest: e.e.a. blijkt goed te werken. De gewenste nieuwe onderdelen zitten correct in het rapport. Getest met meerdere versies van Excel, ook met versie 2013. Blijkt met alle versies goed te werken. Een paar vreemde datums kwamen wel voor (b.v. datums in de toekomst) maar dat bleek een invoerfout in Geosticker te zijn. Datum op zich werk goed weergegeven. Dit issue kan gesloten
