### ISSUE TITLE
Beveiligde service geeft alleen WMS in interne portaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#465]
Als er een beveiligde service is, dan van mag een laag zowel de WMS als de WFS intern beschikbaar zijn. Extern natuurlijk niet, maar wel intern. Nu lijkt het er op alsof alleen de WMS beschikbaar wordt gesteld. De WFS ontbreekt mogelijk volledig. 

De link naar de download ontbreekt bij de zoekresultaten (zie plaatje).
En bij de details staat alleen de WMS vermeld. Dat lijkt niet correct. 

Details voorbeeld hieronder.

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/ae65e05d-28dd-4ddd-a26c-770bf64da9c7
Bestandsnaam: Gemeentegrenzen TEST vertrouwelijk
Alternatieve titel: B7.gemgrens_vertrouwelijk (B7.B75
Status: Compleet
Website: http://acc-secure-services.geodataoverijssel.nl:80/viewer/layer/B7_test_vertrouwelijk/B7_Gem_TEST_vertrouwelijk
OGC:WMS: https://acc-secure-services.geodataoverijssel.nl:443/geoserver/B7_test_vertrouwelijk/wms
XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/ae65e05d-28dd-4ddd-a26c-770bf64da9c7?noStyle=true

![schermafdruk_download_ontbreekt](https://cloud.githubusercontent.com/assets/9005444/25185754/7ba73a94-251e-11e7-877c-c7d60937eb7f.jpg)

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Wat betreft de WFS link heb je gelijk, dat was een bug. De download link ook in intern niet tonen wanneer het niet downloadable is heeft echter altijd zo gewerkt. Ik meen dat jullie dat destijds wilden, zodat jullie wisten hoe gebruikers de data zouden zien. Graag hoor ik hoe je daar tegenover staat nu. Het is een kleine aanpassing.

**Comment by gerardnienhuis** [comment]
Als er beveilgde wfs is dan die url intern tonen zowel bij details in metainfo en als downloadlink bij zoekresultaten

Dat is zowel als in metadata staat dat het downloadable is en ook als dat er niet staat

In  extern geoportaal nooit wfs url of doenloadlink tonen als downloadable afwezig is

**Comment by gerardnienhuis** [comment]
probleem is nu, dat download niet werkt. Er zijn services gemaakt, waarvan alleen bij intern portaal nog een probleem is. Alleen WMS en Openbaar (zowel WMS en WFS) werken goed, zowel intern als extern. Beveiligde service werkt echter niet goed. Als je op download klikt dan krijg je een foutmelding:

gekozen bestand:
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/a579da33-6a76-45ef-9c75-a4c75753aaf0


404 Niet gevonden
Je bent bezig met het downloaden van de dataset met id: a579da33-6a76-45ef-9c75-a4c75753aaf0.xml
Deze dataset kan echter nu niet worden gedownload.
Hiervoor kunnen meerdere redenen zijn. Een niet voorzien technisch probleem. Of misschien heb je onvoldoende rechten om de download uit te voeren.
Neem voor vragen contact op met beleidsinformatie@overijssel.nl 

merk op: betreft alleen intern portaal.
in externe portaal werkt alles nu wel naar tevredenheid, ook bij beveiligde services


testbestand:
Bestandsnaam: Gemeentegrenzen TEST vertrouwelijk
Alternatieve titel: B7.gemgrens2_vertrouwelijk (B7.B75
Sttus: Compleet
Download: https://acc-download.geoportaaloverijssel.nl:443/download/a579da33-6a76-45ef-9c75-a4c75753aaf0
Website: http://acc-secure-services.geodataoverijssel.nl:80/viewer/layer/Beveiligd/b7_Gemeentegrenzen_TEST_vertrouwelijk
OGC:WFS: https://acc-secure-services.geodataoverijssel.nl:443/geoserver/Beveiligd/wfs
OGC:WMS: https://acc-secure-services.geodataoverijssel.nl:443/geoserver/Beveiligd/wms
XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/a579da33-6a76-45ef-9c75-a4c75753aaf0?noStyle=true

opvallend is dat er staat dat er link naar viewer en ook download aanwezig is, .. maar die download is nooit gemaakt in de publicatieomgeving, denk ik.

zie figuur hierna
![download_fout](https://cloud.githubusercontent.com/assets/9005444/25944326/32af181c-3643-11e7-8b81-f1ca86e01134.jpg)

**Comment by gerardnienhuis** [comment]
probleem gevonden, na overleg met Sandro: download tool controleert te streng. Als je intern zit, dan mag je wel download link zien en in metadata staat ook die wms en wfs en download link. Maar de controle werkt hetzelfde bij intern en extern, en daardoor komt blijkbaar dit foutmelding. 

Oplossingsrichting: 

download tool controle laten inbouwen: als intern, dan wel download mogelijk maken van beveiligde service. 

nb: en als extern, dan bij beveiligde services dus geen download (dat werkt nu al goed, moet zo blijven werken).

**Comment by SandroNeumann** [comment]
Aangepast:

https://acc-intern-download.geoportaaloverijssel.nl/download/a579da33-6a76-45ef-9c75-a4c75753aaf0

**Comment by gerardnienhuis** [comment]
getest, zowel intern en extern, zowel zoekresultaten als links laten nu correcte informatie zien.

nb: bij intern zie je dus bij beveiligde service bij de details zowel wms als wfs naam, en ook download en viewer bij zoekresultaten. precies goed dus.

issue kan gesloten.
