### ISSUE TITLE
Plaatjes zoekresultaten ontbreken vanaf 24-4-17

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#466]
Bij de zoekresultaten en ook op de homepagina ontbreken de plaatjes opeens. Dat was voor 24-4-2017 niet het geval, maar bij de geodata die na 204-2017 is gepubliceerd, daar ontbreekt soms het plaatje (zie figuur).

Hieronder 3 voorbeelden. 2 waarbij het nu niet goed is, en 1 waarbij het wel goed is.

Na 24-4-2017 geupdate, gaat fout.

plaatje bij zoekresultaten is afwezig. Dat is vreemd, wat plaatje bij WAT is wel aanwezig

2 voorbeelden, niet goed

https://intern.geoportaaloverijssel.nl/metadata/dataset/d88549b0-e892-49e6-b806-c8bc4dee969d
Bestandsnaam: Carpoolbezetting voor auto en fiets
Publicatie bestand: 01-05-2017
Laatste wijziging bestand: 01-05-2017
Laatste wijziging bestandsbeschrijving: 01-05-2017

https://intern.geoportaaloverijssel.nl/metadata/dataset/7bf1b609-f389-4c5e-a5e7-13b4402879e4
Bestandsnaam: Natuurdatabase RVO
Publicatie bestand: 26-04-2017
Laatste wijziging bestandsbeschrijving: 26-04-2017

Voor 24-4-2017: 

gaat wel goed, zowel plaatje in zoekresultaten als bij WAT is aanwezig

Bestandsnaam: Natura 2000-gebieden in Nederland
https://intern.geoportaaloverijssel.nl/metadata/dataset/2101e166-89d7-433c-ace3-2c67ff63b62f
Publicatie bestand: 24-04-2017
Laatste wijziging bestandsbeschrijving: 24-04-2017

![plaatje_ontbreekt](https://cloud.githubusercontent.com/assets/9005444/25610859/26be84b8-2f25-11e7-9280-ea50ee094fd1.jpg)

**Comment by gerardnienhuis** [comment]
nb: het valt op dat het bestanden betreft die op 25-4-17 of later als nieuw bestand zijn toegevoegd in oracle. De plaatjes van andere bestanden die opnieuw zijn gepubliceerd (ook na 24-4-7) die lijken wel goed zichtbaar te zijn, die bijvoorbeeld: 

Contouren rond kleine kernen zoals opgenomen in het streekplan 2000+ (25-04-2017, Provincie Overijssel) 
https://www.geoportaaloverijssel.nl/metadata/dataset/a242740a-fac5-454d-bc34-2190a2a2994d

**Comment by gerardnienhuis** [comment]
Zojuist getest. Probleem bestaat nog steeds

**Comment by SandroNeumann** [comment]
Beide genoemde datasets hebben structuurwijzigingen die nog geaccepteerd moeten worden:

https://admin.geodataoverijssel.nl/datasets/2338cc4e-a138-4e09-aaa2-a99f4717b037
https://admin.geodataoverijssel.nl/datasets/a82fba19-8457-48b7-a768-1d9f3025d159

Om die reden zal vermoedelijk de oude versie nog altijd gepubliceerd worden.

**Comment by gerardnienhuis** [comment]
Volgens mij werkt e.e.a. nu niet goed.

Een deel van de metainfo wordt wel overgehaald als nieuwe metainfo wordt gepubliceerd, en een andere deel niet? Dat kan niet de bedoeling zijn.

Zie onderstaand voorbeeld.

Begrenzing NNN (voorheen EHS) en Zone Ondernemen met Natuur en Water (25-04-2017, Provincie Overijssel)
https://www.geoportaaloverijssel.nl/metadata/dataset/ee6f220d-ca3e-4222-b690-4a13dd9257e2

heeft bij de WAT het nieuwe plaatje, wat na 24-4-17 is aangeboden en gepubliceerd
metadata.geodataoverijssel.nl:80/attachment/32266/NNN_ONW2.jpg

opvallend is dat bij de zoekresultaten en op de homepagina een verwijzing staat naar een niet meer bestaand plaatje:
metadata.geodataoverijssel.nl:80/attachment/30366/NNN_ONW.jpg

**Comment by SandroNeumann** [comment]
Ik heb de oorzaak gevonden. De harvester loopt al een hele tijd niet meer, omdat de id van een tabel de max van de range van het kolom type is overschreden. Dat is de tabel waar alle termen in komen waar op gezocht moet kunnen worden. Dat zijn er aardig wat per dataset. Alle drie data types (dataset, service, statische kaart) staan in dezelfde database en de harvester loopt per data type elk kwartier. Dus dat loopt hard op.

Ik heb de sequence van het id op 1 gezet, zodat het weer opnieuw begint. En nu slaagt de harvest weer. Voor nu werkt het weer. Dit is wel wat aangepakt moet worden, want anders gaat het over een aantal maanden / jaar weer mis. Ik maak hiervoor een issue aan.

**Comment by gerardnienhuis** [comment]
probleem lijkt niet meer op te treden, kan vooralsnog gesloten worden
