### ISSUE TITLE
Omgaan met snel oplopende id sequence in geoportaal-publiek

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#467]
Id kolommen in geoportaal-publiek database en harvester veranderen van serial naar bigserial.

Zie #466

**Comment by SandroNeumann** [comment]
Tevens status harvest actie naar een file wegschrijven ter behoeve van monitoring.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Hiervoor moet de database van de voorkant van het geoportaal opnieuw gemaakt worden. Dit is de database die gevuld wordt door de harvesters, dus NIET wat jullie aan statische kaarten invoeren.

Het heeft dus als effect dat de voorkant van het geoportaal een paar minuten leeg is, totdat de harvesters een keer gelopen hebben.

**Comment by gerardnienhuis** [comment]
Dat klinkt als een ongewenst bijeffect. Of is het zo, dat dan alleen de homepagina leeg is?
Of niet leeg, maar alleen voorzien van de statische kaarten?

**Comment by SandroNeumann** [comment]
Er zijn een paar minuten geen datasets, services en statische kaarten te zien aan de voorkant van het geoportaal.

**Comment by SandroNeumann** [comment]
Niet te testen voor Overijssel, daarom sluit ik deze.
