### ISSUE TITLE
Viewer en download in Geoportaal Flora streeplijst werkt niet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#471]
Viewer geeft geen kaartbeeld in Geoportaal en download werkt niet
Een mail verschijnt wel. Dat duurt vrij laat en dan staat er een foutcode in. 502 proxy error.

Gaat fout: 

Bestandsnaam: Flora streeplijst
Alternatieve titel: B4.flora_streeplijst_point (B4/B47)
Status: Compleet
Download: https://download.geoportaaloverijssel.nl:443/download/e5f02bb8-59fb-4734-ac05-28b65e10af08
Website: http://services.geodataoverijssel.nl:80/viewer/layer/B47_flora_en_fauna/B4_Flora_streeplijst
OGC:WFS: http://services.geodataoverijssel.nl:80/geoserver/B47_flora_en_fauna/wfs
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B47_flora_en_fauna/wms
XML: https://www.geoportaaloverijssel.nl/metadata/dataset/e5f02bb8-59fb-4734-ac05-28b65e10af08?noStyle=true

Download scherm geeft wel gewoon melding:

Flora streeplijst
Je download verzoek is in goede orde ontvangen. De download wordt nu voor je klaargezet.
Het bestand is: Flora streeplijst
Het formaat is: SHP
E-mail adres is: g.nienhuis@overijssel.nl
Je krijgt zo snel mogelijk een e-mail met een download-link.
Via deze link kun je de download van het bestand uitvoeren. 
Deze link blijft 24 uur bruikbaar.
Je kunt nu dit scherm sluiten.

Foutmelding in email: 

Je download B4_Flora_streeplijst van Geoportaal Overijssel is niet gelukt.
De foutcode is:
  HTTP/1.1 502 Proxy Error : http://services.geodataoverijssel.nl:80/geoserver/B47_flora_en_fauna/wfs?REQUEST=GetFeature&service=WFS&version=2.0.0&TYPENAME=B4_Flora_streeplijst&CRS=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&SRSNAME=urn%3Ax-ogc%3Adef%3Acrs%3AEPSG%3A28992&OUTPUTFORMAT=SHAPE-ZIP
Neem voor meer informatie contact op met beleidsinformatie@overijssel.nl.

Ter controle. Veel werkt wel goed. 
Hieronder de geslaagde download van 2 andere datasets die via deze service worden ontsloten:

Je kunt bestand B4_Weidevogelgebieden.zip downloaden via de volgende link:
https://download.geoportaaloverijssel.nl:443/download-result/100a6464-5f2c-4a71-a58d-7c54a7705cb8

Je kunt bestand B4_Floragebieden.zip downloaden via de volgende link:
https://download.geoportaaloverijssel.nl:443/download-result/0ec2002c-1f09-47ea-96d0-b9f67baa3783

**Comment by SandroNeumann** [comment]
Viewer toont de kaartlaag wel, maar pas na zo'n halve minuut.

**Comment by gerardnienhuis** [comment]
Ja, klopt, viewer zie ik nu ook: is inderdaad lang wachten, maar werkt wel. Wat kan die traagheid veroorzaken? De meeste bestanden (ook de grote) staan binnen maximaal 10 seconden op het scherm.

Is dit zo'n zwaar bestand? En werkt daarom de download niet goed?

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Ik heb in de proxy de timeout voor de services op een kwartier gezet en nu slaagt de bovengenoemde download.

**Comment by gerardnienhuis** [comment]
Klopt, het is getest. Hier intern Overijssel werkt het nu ook. Het tijdstip van verzenden van downloadopdracht is 9.06 uur geweest. Mail met link ontvangen: 9.19 uur. Dat wil dus zeggen dat er 13 minuten tussen zit. Dat is meestal enkele seconden tot maximaal 1 minuut. Het is daarom niet ondenkbaar dat die 15 minuten voor sommige bestanden nog te krap is. Maar dat is niet erg. We weten dan in ieder geval wat er aan de hand kan zijn. 

Dit issue kan gesloten.

nb: mail tekst:

Geachte Test Gerard download flora streeplijst als shape. Start download 9.06, 18-5-17., 
Je kunt bestand B4_Flora_streeplijst.zip downloaden via de volgende link:
https://download.geoportaaloverijssel.nl:443/download-result/46d5caf2-ba4a-4b75-be0b-0d5af403e99e
Deze link is 24 uur bruikbaar.
Deze mail is verzonden omdat iemand dit emailadres heeft opgegeven voor een download van een bestand uit het Geoportaal van Overijssel. Mocht jij niet de persoon zijn, die deze download heeft aangevraagd, dan kan je deze mail verder negeren.
Zijn er vragen over de download, neem dan contact op met beleidsinformatie@overijssel.nl
Het Geoportaal van Overijssel bevat honderden datasets die kunnen worden gedownload.
Ze zijn vrij beschikbaar, voor iedereen om te gebruiken.
Wil je deze datasets bekijken of downloaden, kijk dan bij: 
http://www.geoportaaloverijssel.nl .
