### ISSUE TITLE
2 download formaten toevoegen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#473]
Wens is om 4 extra formaten toe te voegen. Het blijkt dat een deel van de gebruikers deze formaten goed kan gebruiken. Details staan hieronder.

Nu staat in het download scherm:

Kies formaat  

SHP  GML 2.1   GML 3.2    KML    DXF 

verzoek om daar 4 formaten aan te voegen:

JPG, CSV, PDF en GeoJson

Volgorde wordt dan:

SHP DXF GeoJson GML 2.1 GML 3.2 JPG KML PDF

**Comment by HermanAssink** [comment]
Wat is de bedoeling van de downloadformaten JPG en PDF, een plaatje van de kaartlaag zoals de WMS die kan leveren? Deze formaten lenen zich namelijk niet (goed) om de ruwe data in uit te wisselen.
De formaten CSV en GeoJSON worden door GeoServer ondersteund en zijn daardoor relatief eenvoudig toe te voegen.

**Comment by gerardnienhuis** [comment]
Klopt, PDF en Jpg leveren geen referentie, en zijn daarom minder zinvol. Graag wel Geojson en CSV toevoegen. Volgorde in het download scherm wordt dan:

SHP CSV DXF GeoJson GML 2.1 GML 3.2 KML

**Comment by gerardnienhuis** [comment]
Merk op dat ook de tekst "Over deze site" moet worden aangepast. Nu staat er:

Bij de download kan je kiezen uit verschillend formaten:

SHP (shape, veel gebruikt open formaat, ontwikkeld door Esri)
GML (Geography Markup Language, een open standaard voor GIS data)
KML (Keyhole Markup Language, te gebruiken in Google Earth)
DXF (Drawing exchange format, veel gebruikt formaat voor AutoCad)

Dat moet worden:

Bij de download kan je kiezen uit verschillend formaten:

SHP (shape, veel gebruikt open formaat, ontwikkeld door Esri)
CSV (bestand waarbij de gegevens door komma's zijn gescheiden)
DXF (Drawing exchange format, veel gebruikt formaat voor AutoCad)
GeoJson (formaat, eenvoudig geschikt voor ontwikkelaars die Java script hanteren)
GML (Geography Markup Language, een open standaard voor GIS data)
KML (Keyhole Markup Language, te gebruiken in Google Earth)

**Comment by gerardnienhuis** [comment]
zelfde als #438

**Comment by SandroNeumann** [comment]
Lijst outputFormats aanpassen

**Comment by gerardnienhuis** [comment]
De files worden gemaakt: met FME blijkt geojson te benaderen en de csv is leesbaar in notepad. 
let op:  arcgis geeft een foutmelding en qgis vraagt urls ipv files (tzt keer uitzoeken)
 
De tekst Over deze site is aangepast. 

Issue kan gesloten.
