### ISSUE TITLE
Bij statusovergang UNAVAILABLE => VECTOR / RASTER eerder aangemaakte notificaties afvinken

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#474]
Tabellen blijken soms tijdelijk afwezig / niet toegankelijk te zijn en komen later "automatisch" weer terug. De notificatie die is gemaakt bij het verdwijnen van de tabel is daardoor niet meer relevant.

**Comment by SandroNeumann** [comment]
Wanneer een brondataset van unavailable naar vector/raster verandert alle "Brondataset niet beschikbaar" notificaties die bij dat brondataset horen als "gedaan" afvlaggen.

Ter info: deze oplossing betekent wel dat alle notificaties van deze aard vóór deze wijziging nog wel met de hand afgevinkt moeten worden. Dit omdat alleen bij een statusovergang dit automatisch afgevinkt wordt.

**Comment by gerardnienhuis** [comment]
vooral betrekking op publicatieomgeving.

**Comment by SandroNeumann** [comment]
Bij handmatig opschonen deze query gebruiken:

```
update publisher.harvest_notification hn
set done = true
where done is false 
	and exists (
		select *
		from publisher.source_dataset sd
		join publisher.source_dataset_version sdv on sdv.source_dataset_id = sd.id
		where sd.id = hn.source_dataset_id
		and sdv.id = (
			select max(sdv2.id) 
			from publisher.source_dataset_version sdv2 
			where sdv2.source_dataset_id = sd.id)
		and sdv.type != 'UNAVAILABLE'
	)
	and notification_type = 'SOURCE_DATASET_UNAVAILABLE'
;
```

**Comment by HermanAssink** [comment]
@SandroNeumann: Zo te zien zet bovenstaande query alle noificaties van het type SOURCE_DATASET_UNAVAILABLE op done als de laatste source_dataset_version  UNAVAILABLE is. Is de beste oplossing misschien om dit type notificaties sowieso niet aan te maken?

**Comment by gerardnienhuis** [comment]
Een nadeel van verwijderen van notificaties is dat wij als databeheerders niet meer zien wat er met de data aan de hand kan zijn. Soms zien wij problemen via het rapport (en dashboard) op basis van die notificaties. Door ze allemaal weg te laten vrees ik dat we dan als beheerders minder informatie hebben dan daarvoor. Of is het streven om alleen in speciale gevallen de notificatie weg te laten? Bijvoorbeeld bij rasters en in geval van  SOURCE_DATASET_UNAVAILABLE = done ?

**Comment by gerardnienhuis** [comment]
nb: gaat het probleem van André dat hij heel veel moet afvinken inderdaad alleen over rasters en alleen over de situatie  SOURCE_DATASET_UNAVAILABLE = done ?

**Comment by HermanAssink** [comment]
Het plan is om de notificaties van het type SOURCE_DATASET_UNAVAILABLE  alleen te verwijderen als die niet meer actueel is. Dus zo'n notificatie wordt verwijderd als de dataset bij de laatste harvest-actie weer beschikbaar is. Deze verbetering heeft zowel betrekking op vector en raster.

**Comment by gerardnienhuis** [comment]
klinkt goed, maar ik heb nu wel 2 vragen:

1)  als iets niet meer actueel is, dan lijkt me de melding ook volledig niet meer waardevol. Maar het feit dat de SOURCE dataset afwezig is, dat is voor ons als databeheerders natuurlijk wel van belang. Hoe gaat dat straks werken? Als de SOURCE_DATASET is verwijderd en die is nog wel beschikbaar in de publicatieomgeving, dan is dat toch een foutsituatie, waar je als beheerders juist over geïnformeerd wilt worden?

2) of is het juist anders: als een dataset wordt verwijderd, en de koppeling in de publicatieomgeving wordt verwijderd, dan komt die melding niet meer?

Misschien is het goed om de flow uit te schrijven, hierbij. Welke notificaties krijg je nu en straks, bij welke situatie? En wat zien wij in het rapport van geodata?

**Comment by HermanAssink** [comment]
De oorzaak van veel notificaties SOURCE_DATASET_UNAVAILABLE die de laatste tijd optreden is niet dat betreffende tabel afwezig is, maar vermoedelijk treedt een time-out op bij de test of de tabel bestaat. Daardoor lijkt het alsof de tabel de ene keer niet bestaat en een volgende keer wel. Als bij de laatste harvestactie de fout SOURCE_DATASET_UNAVAILABLE optreedt dan wordt die notificatie niet verwijderd. Alleen voorlaatste notificaties van het type SOURCE_DATASET_UNAVAILABLE worden verwijderd.

**Comment by HermanAssink** [comment]
Voor de duidelijkheid:
- De notificatie van de meest recente controle dat een dataset waar de metadata naar verwijst niet gevonden is, wordt niet verwijderd.
- De notificatie dat metadata is vewijderd terwijl de data nog wordt gebruikt in de publicatieomgeving wordt niet verwijderd.
- De notificatie dat voor bepaalde metadata nog geen data in de publicatieomgeving is opgenomen wordt niet verwijderd.
Alleen notificaties uit het verleden van het type SOURCE_DATASET_UNAVAILABLE terwijl de dataset bij de laatste check weer beschikbaar was, worden verwijderd.

**Comment by gerardnienhuis** [comment]
Verwijderen van historische, niet meer relevante meldingen klinkt prima. Ik ben blij dat de overige meldingen nog wel beschikbaar blijven in het rapport van de metadata van geodata.
Anders gezegd: notificaties uit het verleden van het type SOURCE_DATASET_UNAVAILABLE terwijl de dataset bij de laatste check weer beschikbaar was, kunnen worden verwijderd.

**Comment by gerardnienhuis** [comment]
Testen moet worden uitgevoerd in publicatieomgeving voornamelijk. wel moet aan Geoportaal kant controle worden uitgevoerd om te kijken of er nog wel soms notificaties in de rapportage worden geplaatst.

**Comment by SandroNeumann** [comment]
André heeft dit getest en goed bevonden dus het issue kan gesloten worden.
