### ISSUE TITLE
Zomerdijk beheerrechten geven

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#476]
Graag Ineke Zomerdijk ook beheerrechten geven voor het beheeronderdeel van statische kaarten van het Geoportaal.

**Comment by SandroNeumann** [comment]
Aangepast

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten

**Comment by gerardnienhuis** [comment]
Verzoek is om de rechten van Zomerdijk weer aan te passen van leverancier naar beheerder.

**Comment by SandroNeumann** [comment]
Zomerdijk stond al ingesteld als beheerder.

**Comment by gerardnienhuis** [comment]
werkt nu goed
