### ISSUE TITLE
Harvestacties lukken niet altijd tenzij pub.provider wordt herstart

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#479]
Het lijkt er op dat soms harvestacties (bij nieuwe of aangepaste geodata of metadata) niet lukken. De oplossing (aangedragen door IDGis) is dan om de publisherprovider te herstarten. De problemen lijken daarna verholpen.

Echter, dat is onhandig. Niet helder is het, of er nu wel of niet een probleem is, die met de publisherprovider te maken heeft. Dat is niet te vinden omdat het niet uit de huidige logging af te leiden is.

Voorstel: betere logging zodat problemen wel door technisch beheerder te vinden zijn en optioneel ook melding laten sturen naar technisch beheerder. Ook misschien mogelijk: provider zichzelf laten herstarten na problemen.

zie ook https://github.com/IDgis/geoportaal-test/issues/425

**Comment by gerardnienhuis** [comment]
zie ook #425

**Comment by gerardnienhuis** [comment]
zou https://github.com/IDgis/geoportaal-test/issues/417 hier ook bij kunnen helpen?

 Als je betere monitoring hebt, dan weet je ook sneller als er iets aan de hand is, tenslotte.

**Comment by HermanAssink** [comment]
Ja, want dan kun je als medewerker van Overijssel een melding krijgen, via mail of Andoid app, dat de er geen verbinding is.

**Comment by SandroNeumann** [comment]
Account voor Overijssel in Nagios maken en de diverse checks toevoegen. Ook een grep programma maken voor de provider logging. Zodat zij signaal krijgen wanneer de provider herstart zou moeten worden.

**Comment by gerardnienhuis** [comment]
is impact inderdaad hoog, bij deze eenvoudige oplossingen?

**Comment by SandroNeumann** [comment]
Onder impact hoog wordt minimaal een dag werk verstaan. Dat zal hier het geval zijn.

**Comment by gerardnienhuis** [comment]
ivm harvestproblemen 2-3-2020 issue voorzien van grotere urgentie

**Comment by gerardnienhuis** [comment]
Dit lijkt veel minder vaak op te treden dan in het verleden. Bug is opgelost. Issue kan gesloten.
