### ISSUE TITLE
Snelheid services niet altijd even hoog

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#483]
Afgelopen dagen lijkt het alsof de snelheid van services niet altijd even hoog is. Mogelijk door backup processen bij IDGis. Deze processen zijn 14-6-17 (12.30 uur) aangepast.

Daarna lijkt snelheid van de meeste services sterk verbeterd. 

details hieronder:

===============================================

testen stabiliteit services 13-6-17 en 14-6-17

conclusie: bijna alle services lijken bij laatste
testserie sneller dan daarvoor. 

De veranderingen die IDGis heeft doorgevoerd,
die lijken succesvol te zijn.

===============================================

eerste test: middag 13-6-17 (na 14.00 uur)
daarna test: ochtend 14-6-17 (8.00 tot 8.12 uur)
opnieuw test: middag 14-6-17 (13.55 uur tot 14.05 uur)
daarna direct weer test 14-6-17 (14.08 uur tot 14.15 uur)

nb: testen op PC thuis, browser Opera (recentste versie)
tussen iedere testserie met Ccleaner cache geleegd

================================================

2 dingen vallen op: 

1) op de middag 14-6-17 zijn meeste services sneller dan daarvoor

2) enige uitzondering is B46_Geomorfologische_kaart_van_Overijssel
http://wmsonly-services.geodataoverijssel.nl/viewer/layer/B41_bodem_alleen_wms/B46_Geomorfologische_kaart_van_Overijssel
Bij die kaart duurt het op 14-6 meer dan 20 seconden, terwijl
bij metingen daarvoor de kaart in 5 seconden op scherm kwam.

===============================================
Alleen WMS services, 1 service, 2 lagen:
===============================================

nummer: 1

http://wmsonly-services.geodataoverijssel.nl/viewer/layer/B41_bodem_alleen_wms/B4_Bodemkaart
/ B41_bodem_alleen_wms / B4_Bodemkaart
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
kaart op scherm: 21 seconden (ochtend, 14-6-17)
kaart op scherm: 5 seconden (ochtend, 14-6-17, hertest na 10 minuten)
kaart op scherm: 8 seconden (middag, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17, hertest)

nummer: 2

http://wmsonly-services.geodataoverijssel.nl/viewer/layer/B41_bodem_alleen_wms/B46_Geomorfologische_kaart_van_Overijssel
/ B41_bodem_alleen_wms / B46_Geomorfologische_kaart_van_Overijssel
kaart op scherm: 3 seconden (midag, 13-6-17)
kaart op scherm: 31 seconden (ochtend, 14-6-17)
kaart op scherm: 24 seconden (ochtend, 14-6-17, hertest na 10 minuten)
kaart op scherm: 15 seconden (middag, 14-6-17)
kaart op scherm: 4 seconden (middag, 14-6-17, hertest)

===============================================
beveiligde services
===============================================

nummer: 3

https://secure-services.geodataoverijssel.nl/viewer/layer/B46_natuur_en_landschap_beveiligd/B4_Terreinen_van_terreinbeherende_organisaties
/ B46_natuur_en_landschap_beveiligd / B4_Terreinen_van_terreinbeherende_organisaties
kaart op scherm: 3 seconden (midag, 13-6-17)
niet getest 14-6-17

nummer: 4

https://secure-services.geodataoverijssel.nl/viewer/layer/B46_natuur_en_landschap_beveiligd/B46_Concept_Habitattypenkaart_Vecht_Beneden_Regge
/ B46_natuur_en_landschap_beveiligd / B46_Concept_Habitattypenkaart_Vecht_Beneden_Regge
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
niet getest 14-6-17

nummer: 5

https://secure-services.geodataoverijssel.nl/viewer/layer/B02_topografie_beveiligd/B0_Bodemgebruik_Overijssel_1996
/ B02_topografie_beveiligd / B0_Bodemgebruik_Overijssel_1996
kaart op scherm: 6 seconden (midag, 13-6-17)
niet getest 14-6-17

nummer: 6

https://secure-services.geodataoverijssel.nl/viewer/layer/B02_topografie_beveiligd/B0_Bodemgebruik_in_2010
/ B02_topografie_beveiligd / B0_Bodemgebruik_in_2010
kaart op scherm: 8 seconden (midag, 13-6-17)
niet getest 14-6-17

nummer: 7
 
https://secure-services.geodataoverijssel.nl/viewer/layer/B22_wegen_beveiligd/B2_Hectometerpunten_langs_rijks-_en_provinciale_wegen_NWB
/ B22_wegen_beveiligd / B2_Hectometerpunten_langs_rijks-_en_provinciale_wegen_NWB
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
niet getest 14-6-17

===============================================
Openbare services
===============================================

nummer: 8

http://services.geodataoverijssel.nl/viewer/layer/B47_flora_en_fauna/B4_Beschermingsplan_boomkikkers
B47_flora_en_fauna B4_Beschermingsplan_boomkikkers
kaart op scherm: 4 seconden (midag, 13-6-17)
kaart op scherm: 41 seconden (ochtend, 14-6-17)
kaart op scherm: 3 seconden (ochtend, 14-6-17, hertest na 10 minuten)
kaart op scherm: minder dan 2 seconden (middag, 14-6-17)
kaart op scherm: minder dan 2 seconden (middag, 14-6-17, hertest)

nummer: 9

B73_Cultuur B7_Archeologische_verwachtingenkaart
http://services.geodataoverijssel.nl/viewer/layer/B73_Cultuur/B7_Archeologische_verwachtingenkaart
kaart op scherm: 3 seconden (midag, 13-6-17)
kaart op scherm: 5 seconden (ochtend, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17, hertest)

nummer: 10

http://services.geodataoverijssel.nl/viewer/layer/B06_bladindelingen/B0_Indeling_km_hokken_1000x1000m
B06_bladindelingen B0_Indeling_km_hokken_1000x1000m
kaart op scherm: 2 seconden (midag, 13-6-17)
kaart op scherm: 3 seconden (ochtend, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17)
kaart op scherm: 2 seconden (middag, 14-6-17, hertest)

nummer: 11

http://services.geodataoverijssel.nl/viewer/layer/B34_beheer_grondwater/B3_Nitrofiele_indicatiewaarde
B34_beheer_grondwater B3_Nitrofiele_indicatiewaarde
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
kaart op scherm: 4 seconden (ochtend, 14-6-17)
kaart op scherm: 7 seconden (middag, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17, hertest)

nummer: 12

http://wmsonly-services.geodataoverijssel.nl/viewer/layer/B41_bodem_alleen_wms/B46_Geomorfologische_kaart_van_Overijssel
B41_bodem_alleen_wms B46_Geomorfologische_kaart_van_Overijssel
kaart op scherm: 5 seconden (midag, 13-6-17)
kaart op scherm: 5 seconden (ochtend, 14-6-17)
kaart op scherm: 22 seconden (middag, 14-6-17)
kaart op scherm: 23 seconden (middag, 14-6-17, hertest)

nummer: 13

http://services.geodataoverijssel.nl/viewer/layer/B02_topografie/Puntenbestand_met_namen_uit_de_topografische_kaart_1_50000
B02_topografie Puntenbestand_met_namen_uit_de_topografische_kaart_1_50000
kaart op scherm: minder dan 2 seconden(midag, 13-6-17)
kaart op scherm: 3 seconden (ochtend, 14-6-17)
kaart op scherm: 2 seconden (middag, 14-6-17)
kaart op scherm: 2 seconden (middag, 14-6-17, hertest)

nummer: 14

http://services.geodataoverijssel.nl/viewer/layer/B44_geluidshinder/B44_Geluidbelasting_op_adressen
B44_geluidshinder B44_Geluidbelasting_op_adressen
kaart op scherm: 6 seconden (midag, 13-6-17)
kaart op scherm: 25 seconden (ochtend, 14-6-17)
kaart op scherm: 6 seconden (ochtend, 14-6-17, hertest na 10 minuten)
kaart op scherm: 6 seconden (middag, 14-6-17)
kaart op scherm: 5 seconden (middag, 14-6-17, hertest)

nummer: 15

http://services.geodataoverijssel.nl/viewer/layer/B61_economie/B6_Bedrijventerreinen_in_Overijssel
B61_economie B6_Bedrijventerreinen_in_Overijssel
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
kaart op scherm: 26 seconden (ochtend, 14-6-17)
kaart op scherm: minder dan 2 seconden (ochtend, 14-6-17, hertest na 10 minuten)
kaart op scherm: minder dan 2 seconden (middag, 14-6-17)
kaart op scherm: minder dan 2 seconden (middag, 14-6-17, hertest)

nummer: 16

http://services.geodataoverijssel.nl/viewer/layer/B22_wegen/B2_Hectometerpunten_langs_de_provinciale_wegen_en_waterwegen
B22_wegen B2_Hectometerpunten_langs_de_provinciale_wegen_en_waterwegen
kaart op scherm: 6 seconden (midag, 13-6-17)
kaart op scherm: 9 seconden (ochtend, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17)
kaart op scherm: 3 seconden (middag, 14-6-17, hertest)

nummer: 17

http://services.geodataoverijssel.nl/viewer/layer/B22_wegen/B2_Wegbeheer_punten
B22_wegen B2_Wegbeheer_punten
kaart op scherm: 12 seconden (midag, 13-6-17)
kaart op scherm: 7 seconden (ochtend, 14-6-17)
kaart op scherm: 6 seconden (middag, 14-6-17)
kaart op scherm: 7 seconden (middag, 14-6-17, hertest)

nummer: 18

http://services.geodataoverijssel.nl/viewer/layer/B32_waterkeringen/B3_Dijkringgebieden_Omgevingsvisie
B32_waterkeringen B3_Dijkringgebieden_Omgevingsvisie
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
kaart op scherm: 4 seconden (ochtend, 14-6-17)
kaart op scherm: 2 seconden (middag, 14-6-17)
kaart op scherm: 2 seconden (middag, 14-6-17, hertest)

nummer: 19

http://services.geodataoverijssel.nl/viewer/layer/B42_energie/B42_Energielabel_woningen
B42_energie B42_Energielabel_woningen
kaart op scherm: 12 seconden (midag, 13-6-17)
kaart op scherm: 11 seconden (ochtend, 14-6-17)
kaart op scherm: 10 seconden (ochtend, 14-6-17, hertest na 10 minuten)
kaart op scherm: 12 seconden (middag, 14-6-17)
kaart op scherm: 10 seconden (middag, 14-6-17, hertest)

nummer: 20

http://services.geodataoverijssel.nl/viewer/layer/B71_educatie/B7_Onderwijsinstellingen
B71_educatie B7_Onderwijsinstellingen
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
kaart op scherm: minder dan 2 seconden (ochtend, 14-6-17)
kaart op scherm: minder dan 2 seconden (middag, 14-6-17)
kaart op scherm: 5 seconden (middag, 14-6-17, hertest)

nummer: 21

http://services.geodataoverijssel.nl/viewer/layer/B62_innovatie/B6_Aanpak_leegstand_kantoren_en_winkels
B62_innovatie B6_Aanpak_leegstand_kantoren_en_winkels
kaart op scherm: minder dan 2 seconden (midag, 13-6-17)
kaart op scherm: minder dan 2 seconden (ochtend, 14-6-17)
kaart op scherm: minder dan 2 seconden (middag, 14-6-17)
kaart op scherm: 2 seconden (middag, 14-6-17, hertest)

=========================================================

**Comment by gerardnienhuis** [comment]
zelfde als 478, dit issue kan daarom gesloten

**Comment by HermanAssink** [comment]
Backup was 's morgens tot ongeveer 10:00 uur nog bezig. Morgenvroeg, 15-6, zou de backup vóór 7:00 uur klaar moeten zijn, waardoor na zeven uur de services snel zouden moeten reageren.
