### ISSUE TITLE
Uitgevoerde bewerkingen niet aangepast als dataset in service zit

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#489]
De metainformatie zoals publicatiedatum, samenvatting en dergelijke wordt correct aangepast, als er nieuwe metainfo beschikbaar komt. Dat werkt in alle gevallen: onafhankelijk of er een service is waar die geodata in zit als laag. Maar wat er fout lijkt te gaan, is de update van de uitgevoerde bewerkingen. Die lijkt niet vervangen te worden, als de geodataset in een service zit. Dat is wel de bedoeling. Het valt vooral op bij de attributen-informatie die in de metadata bij DETAILS wordt getoond. We hebben meerdere voorbeelden, waarvan nu de metadata van de samenvatting wel is aangepast, maar waarbij de beschrijving van de attributen nog de oude metainformatie bevat. Dat maakt het voor beheerders erg lastig om te weten of de update nu is goed gegaan. En het is foutieve informatie voor gebruikers.

**Comment by HermanAssink** [comment]
Graag enkele concrete voorbeelden.

**Comment by gerardnienhuis** [comment]
Bestandsnaam: Boringsvrije zones
https://intern.geoportaaloverijssel.nl/metadata/dataset/accf5f80-a8e7-49b4-8778-11e55734d953

Bestandsnaam: Grote attracties
https://intern.geoportaaloverijssel.nl/metadata/dataset/730c1040-ea2c-4d53-a2c4-daa7b59742cc

De vraag is, of dit een bug is. De samenvatting kan je wel aanpassen van een dataset die al een een service is opgenomen, maar de attributen niet. Logisch, want als je download dan krijg je de "oude"  data, met dus ook de oude serie attributen. Wat je eigenlijk wilt is een nieuw metadatarecord met de info van de nieuwe geodataset, naast de info van de oude, reeds aanwezige geodataset die in een service zit. Dan zie je meteen het verschil tussen beide datasets. Nu is het zo, dat je alleen een nieuwe set metadata ziet als die geodata nog niet een een service zit. Maar eigenlijk wil je dat altijd.

Probleem blijft de vraag wanneer de omschrijving van de attributen dan gaat veranderen, als je wel een nieuwe dataset aan gaat bieden? Of op een ander moment. Dit verschil tussen geodata in services en niet in services blijft onnodig complex voor beheerders (en nu ook voor gebruikers die 2 soorten metadata zien) en moet op een goede manier worden opgelost.

**Comment by HermanAssink** [comment]
Dit lijkt me vraagstuk wat het beste in een persoonlijk gesprek doordacht kan worden.

**Comment by gerardnienhuis** [comment]
zelfde issue als #495

**Comment by gerardnienhuis** [comment]
Dit issue is een onderdeel van #495 en wordt daarom gesloten om dubbele issues en verwarring hierdoor te voorkomen.
