### ISSUE TITLE
Aanleveren teksten voor tooltips

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#49]
@gerardnienhuis: Graag binnen enkele dagen aanleveren zodat we ze kunnen meenemen in de volgende versie.

**Comment by gerardnienhuis** [comment]
Ok

Verstuurd vanaf mijn iPhone

Op 5 feb. 2016 om 09:32 heeft Herman Assink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis: Graag binnen enkele dagen aanleveren zodat we ze kunnen meenemen in de volgende versie.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/49.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
9-2-2016 via mail geleverd. Ik neem overigens aan dat aanpassingen van deze teksten altijd ook na productiegang (dus in de beheerfase) aan te passen zijn, in overleg met IDGis. Is de tekst goed genoeg voor IDGis om nu verder mee te kunnen werken?
