### ISSUE TITLE
Sortering beschrijving attributen zoals in xml staat

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#490]
Nu lijkt het er op alsof bij de uitgevoerde bewerkingen de metainfo van de attributen omgekeerd gesorteerd is. De laatste in de metainfo van de xml, die zie je het eerste. Dat is heel verwarrend voor beheerders die de metainfo moeten controleren. Verzoek is om de sortering zo te maken, zoals deze ook in de geoweb xml aanwezig is.

Hieronder een voorbeeld:

url: 

https://intern.geoportaaloverijssel.nl/metadata/dataset/5f5f65d5-c29c-4a1e-8e53-92207fcf9830

Uitgevoerde bewerkingen

daar staat nu:

Beschrijving: INHOUD ATTRIBUTENTABEL: CD_VERORD: Uniek nummer, gebruikt bij codering verordening in PRIMA PRIMAID: uniek ID nummer gebruikt bij codering visie en verordening in PRIMA CD_VISIE: Uniek nummer, gebruikt bij codering visie in PRIMA LEGENDA: Gebiedstypen van de dataset, zoals op de kaart wordt getoond OBJECTID: ObjectID

maar in de xml is de volgorde andersom:

<FC_FeatureCatalogue>
    <featureType>
      <name>O2.VRO_agr_cultlandsch_polygon</name>
      <featureAttribute>
        <name>OBJECTID</name>
        <definition>ObjectID</definition>
      </featureAttribute>
      <featureAttribute>
        <name>LEGENDA</name>
        <definition>Gebiedstypen van de dataset, zoals op de kaart wordt getoond</definition>
      </featureAttribute>
      <featureAttribute>
        <name>CD_VISIE</name>
        <definition>Uniek nummer, gebruikt bij codering visie in PRIMA</definition>
      </featureAttribute>
      <featureAttribute>
        <name>PRIMAID</name>
        <definition>uniek ID nummer gebruikt bij codering visie en verordening in PRIMA</definition>
      </featureAttribute>
      <featureAttribute>
        <name>CD_VERORD</name>
        <definition>Uniek nummer, gebruikt bij codering verordening in PRIMA</definition>
      </featureAttribute>
      <featureAttribute>
        <name>SHAPE</name>
        <definition />
      </featureAttribute>
      <featureAttribute>
        <name>SE_ANNO_CAD_DATA</name>
        <definition />
      </featureAttribute>
      <featureAttribute>
        <name>SHAPE.AREA</name>
        <definition />
      </featureAttribute>
      <featureAttribute>
        <name>SHAPE.LEN</name>
        <definition />
      </featureAttribute>
    </featureType>
  </FC_FeatureCatalogue>

Dit is ook de volgorde zoals die in geosticker staat:

Object naam: O2.VRO_agr_cultlandsch_polygon
Attributen 
OBJECTID: ObjectID
LEGENDA: Gebiedstypen van de dataset, zoals op de kaart wordt getoond
CD_VISIE: Uniek nummer, gebruikt bij codering visie in PRIMA
PRIMAID: uniek ID nummer gebruikt bij codering visie en verordening in PRIMA
CD_VERORD: Uniek nummer, gebruikt bij codering verordening in PRIMA
SHAPE
SE_ANNO_CAD_DATA
SHAPE.AREA
SHAPE.LEN

**Comment by SandroNeumann** [comment]
In de dataset metadata generator de tabel kolommen ascending i.p.v. descending sorteren.

**Comment by gerardnienhuis** [comment]
Sortering blijkt nu goed te zijn. Getest door geosticker invoer te vergelijken met details op stylesheet. Issue kan gesloten.
