### ISSUE TITLE
Download link bij details werkt niet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#491]
Er is een bestand waarbij de downloadlink zoals beschikbaar bij de DETAILS in de metadata niet werkt: er komt een 404 melding. Maar het vreemd is, dat de download via de zoekresultaten wel werkt. Dat is vreemd: tot nu toe werken ze beiden, of geen van beiden. Wat is hier aan de hand? Details hieronder:

https://intern.geoportaaloverijssel.nl/metadata/dataset/32f2a479-9e24-4fad-b3b6-e4ca5cec7e3c

Bestandsnaam: Energielabel corporatie woningen

zoekresultaten geeft link naar download die wel werkt, maar als je bij details in metadata bekijkt, dan krijg je daar downloadlink die niet werkt: 404 foutmelding

Dat is vreemd, de download levert wel gewoon goed resultaat op (link in email levert bestand op), maar de url bij de details werkt niet

Hieronder de links:

via zoekresultaten, deze werkt wel:

https://intern-download.geoportaaloverijssel.nl/download/32f2a479-9e24-4fad-b3b6-e4ca5cec7e3c

via details in metadata, levert uiteindelijk 404 fout op.

https://download.geoportaaloverijssel.nl:443/download/32f2a479-9e24-4fad-b3b6-e4ca5cec7e3c

klik op deze link komt uit bij onderstaande url, en de foutmelding 404

https://download.geoportaaloverijssel.nl/download/32f2a479-9e24-4fad-b3b6-e4ca5cec7e3c

**Comment by SandroNeumann** [comment]
De data is niet voor publiek toegankelijk, dus vandaar dat je onder de interne download url de data kunt downloaden en onder de publieke download url een 404 terug krijgt. Dat is in orde. Je krijgt echter in de metadata de verkeerde url te zien. Daar moet in de publieke metadata geen download link verschijnen en in de interne metadata de interne download url. Op dit moment wordt simpelweg altijd de publieke download url gebruikt.

We pakken dit mee met de versie waar de wensen van Utrecht ook bij zitten.

**Comment by gerardnienhuis** [comment]
Zie ook #492

**Comment by gerardnienhuis** [comment]
lijkt nu wel te werken. bij details en via zoekresultaten geeft nu zelfde resultaat. Nog wel opnieuw testen ivm issue #520

**Comment by gerardnienhuis** [comment]
Getest met meerdere services. Alles blijkt te werken. Issue kan gesloten.
