### ISSUE TITLE
Download niet goed bij beveiligde service intern geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#492]
Er lijkt iets fout te gaan, als de metadata wordt aangepast van een laag die in een beveiligde service zit.

voorbeeld:

Actueel Hoogtebestand Nederland 1, grid 25x25 m. (20-07-2017, Rijkswaterstaat) 
https://intern.geoportaaloverijssel.nl/metadata/dataset/027a5b48-1aa5-43d6-9be8-6e04fcd6746e

Van dit bestand is de metadata verbeterd (contactinformatie).

In de zoekresultaten bij het interne geoportaal staat:

Meer informatie Bekijk in viewer 

Hier ontbreekt de download link

Wat ook niet klopt: 

Bij de details staat wel de download url, zie hieronder.

Download link levert ook 404 melding op.

Intern bij details:

Bestandsnaam: Actueel Hoogtebestand Nederland 1, grid 25x25 m.
Alternatieve titel: AHN25
Status: Compleet
Download: https://download.geoportaaloverijssel.nl:443/download/027a5b48-1aa5-43d6-9be8-6e04fcd6746e
Website: http://secure-services.geodataoverijssel.nl:80/viewer/layer/Raster/Actueel_Hoogtebestand_Nederland_AHN25
OGC:WMS: https://secure-services.geodataoverijssel.nl:443/geoserver/Raster/wms
XML: https://intern.geoportaaloverijssel.nl/metadata/dataset/027a5b48-1aa5-43d6-9be8-6e04fcd6746e?noStyle=true

nb: het externe geoportaal geeft deze problemen niet, want daar ontbreekt de download en viewer link (zit tenslotte in beveiligde service en is dus correct).

**Comment by SandroNeumann** [comment]
Zelfde als #491

**Comment by gerardnienhuis** [comment]
Deze issue kan gesloten worden.
Zie nr. #491
