### ISSUE TITLE
Vilsteren beheerdersrechten geven beheer statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#493]
Graag de rechten van Gerrit van Vilsteren zo aanpassen, dat hij als beheerder rechten heeft mbt de statische kaarten in het Geoportaal.

**Comment by SandroNeumann** [comment]
Aangepast

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten,
