### ISSUE TITLE
Vilsteren gebruikersrechten geven ipv beheerdersrechten.

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#499]
Rechten als beheerder zijn nu niet meer nodig voor Vilsteren. Graag weer gewoon rechten van gebruiker geven. Beheer moet dus niet meer mogelijk zijn voor Vilsteren. 

nb: dat beheer was aangevraagd in een eerder issue en heeft goed bewerkt. Betreft: https://github.com/IDgis/geoportaal-test/issues/493

**Comment by SandroNeumann** [comment]
Gedaan

**Comment by gerardnienhuis** [comment]
is goed opgelost, Vilsteren kan niet meer als beheerder werk uitvoeren, issue kan gesloten
