### ISSUE TITLE
weergave intranet en extern

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#5]
Overijssel hanteert 2 soorten weergaven (vooral de kleuren blauw en rood worden hier anders gebruikt). Dat betekend dat er verschillende stylesheets en schermen moeten komen:
1) geoportaal zelf: 2 soorten, intern en extern
2) download scherm: 2 soorten, intern en extern
3) stylesheets bestanden, statische kaarten en services: intern en extern
4) beheer statische kaarten: alleen intern (is niet bedoeld voor extern in de huidige versie)

**Comment by gerardnienhuis** [comment]
Er zijn nog een paar onvolkomenheden in de vormgeving, zie overzicht hieronder. Mogelijk zijn stylesheets verwisseld?

Heeft mogelijk ook te maken met #181 

Overzicht betreft huidige situatie en opmerkingen daarbij:

vormgeving extern:

Geoportaal: rode balk, blauwe knoppen (goed)
download: rode balk (goed)
stylesheet geodata: rode balk, blauwe knoppen (goed)
stylesheet services: rode balk, blauwe knoppen (goed)
stylesheet statische kaarten: blauwe balk, rode knoppen (niet juist, moet rode balk, blauwe knoppen zijn)

vormgeving intern:

Geoportaal: blauwe balk, rode knoppen (goed)
download: rode balk (niet juist, moet blauw zijn)
stylesheet geodata: rode balk, blauwe knoppen (niet juist, met zijn: blauwe balk, rode knoppen) 
stylesheet services: rode balk, blauwe knoppen (niet juist, met zijn: blauwe balk, rode knoppen)
stylesheet statische kaarten: blauwe balk, rode knoppen (goed)
Beheer statische kaarten: rode balk, blauwe knoppen (niet juist, met zijn: blauwe balk, rode knoppen)
Inloggen beheermodule: rode balk (niet juist, moet blauw zijn)

**Comment by gerardnienhuis** [comment]
lijkt niet volledig te reproduceren:
stylesheet geodata: rode balk, blauwe knoppen (niet juist, met zijn: blauwe balk, rode knoppen) 
 stylesheet services: rode balk, blauwe knoppen (niet juist, met zijn: blauwe balk, rode knoppen) lijkt bij Overijssel intern wel goed te zijn, wordt gecontroleerd inclusief klikpad

wel aantoonbaar fout: 

bij intern:

download: rode balk (niet juist, moet blauw zijn)
Beheer statische kaarten: rode balk, blauwe knoppen (niet juist, met zijn: blauwe balk, rode knoppen)
 Inloggen beheermodule: rode balk (niet juist, moet blauw zijn)

**Comment by gerardnienhuis** [comment]
als ik intern overijssel werk, dan wil ik zowel het interne als het externe portaal en de data en metadata kunnen benaderen. als ik extern ben, dan alleen het externe portaal

**Comment by gerardnienhuis** [comment]
extern GP en beheer statische kaarten is al gecontroleerd, ziet er nu goed uit. Intern GP wordt asap getest.

Geoportaal: rode balk, blauwe knoppen (gecontroleerd, is goed)
download: rode balk (gecontroleerd, is goed)
stylesheet geodata: rode balk, blauwe knoppen  (gecontroleerd, is goed)
stylesheet services: rode balk, blauwe knoppen  (gecontroleerd, is goed)
stylesheet statische kaarten:  (gecontroleerd, is goed)

Beheer statische kaarten: gecontroleerd, is nu goed: blauwe balk, rode knoppen)
Inloggen beheermodule: is nu goed, moet blauw zijn

**Comment by NicoEilers** [comment]
klopt nu bijna volledig, alleen download intern kan niet getest worden.
omdat download intern niet zichtbaar hoeft te worden gemaakt, kan dit issue gesloten

nb:

stylesheet geodata: klopt nu wel: blauwe balk, rode knoppen
stylesheet services: , klopt nu wel: blauwe balk, rode knoppen
stylesheet statische kaarten: blauwe balk, rode knoppen (goed)
Beheer statische kaarten: , klopt nu wel: blauwe balk, rode knoppen
Inloggen beheermodule:  juist, is blauw zijn
