### ISSUE TITLE
Id van url naar metadata ook in rapport geodata opnemen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#500]
In het rapport van Geodata staan 3 soorten id's (uuid's) maar geen daarvan wijst naar de id die gebruikt wordt in de url, die wijst naar de metadata. Voorbeeld:

Bestandsnaam: Uitsluitingsgebieden nieuwe landgoederen
Daar hoort als url bij: https://intern.geoportaaloverijssel.nl/metadata/dataset/62bca9ef-3365-4919-a7de-62701d70f7f0

In het rapport van geodata komt de id 62bca9ef-3365-4919-a7de-62701d70f7f0 niet terug.

Wens is dat ook deze id's in het rapport worden opgenomen.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
In het rapport nemen we de brondatasets als basis en alle gegevens in de daaropvolgende kolommen gaan dus ook van die bron uit. De uuid die jij hebt is van de dataset. Het aantal uuid's daarvan kan echter groter zijn dan 1 (als er meerdere datasets zijn gemaakt van dezelfde brondataset) en het kan ook 0 zijn (als er nog geen dataset is gemaakt). We zouden voor die laatste variant dan in de kolom in het rapport (nog niet geïmporteerd) kunnen invullen. Voor de eerste zouden we een reeks van uuid's onderbroken door een separator (zoals elders in de rapportage ook al gebruikt wordt) kunnen invullen.

**Comment by SandroNeumann** [comment]
Er komt naast bovenstaande een kolom bij hoeveel datasets van de brondataset gemaakt zijn.

**Comment by gerardnienhuis** [comment]
Meerdere keren nogmaals getest: e.e.a. blijkt goed te werken. De gewenste nieuwe onderdelen zitten correct in het rapport.  issue kan gesloten
