### ISSUE TITLE
Viewer toont attribuutinformatie niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#501]
Ik merk opeens dat als ik nu in de viewer klik op de kaart, ik dan geen beschrijving van de vulling van de attributen krijg, bij het object waarop ik heb geklikt. Dat was eerder wel het geval en werkte heel erg goed om een indruk van het bestand te krijgen. Graag herstellen, zodat klikken op een gebied, zie voorbeeldplaatje, weer attribuutnamen en vulling voor zo'n gebied laat zien. nb: werkt nu ook niet meer voor puntobjecten en ook niet bij andere services die ik steeksproefsgewijs heb getest.

Voorbeeld bij plaatje:
http://services.geodataoverijssel.nl/viewer?service=B03_projectgrenzen

![attribuutinfo_viewer_ontbreekt](https://user-images.githubusercontent.com/9005444/29812421-c927fdcc-8ca6-11e7-9e90-864df26b29f9.jpg)

**Comment by SandroNeumann** [comment]
Op acceptatie werkt het weer, dus de publisher-viewer versie was inderdaad de oorzaak:

http://acc-services.geodataoverijssel.nl/viewer?service=B02_topografie

**Comment by SandroNeumann** [comment]
Aangepast op productie:

http://services.geodataoverijssel.nl/viewer?service=B03_projectgrenzen

**Comment by gerardnienhuis** [comment]
Op 29-8 intern geoportaal getest en op 30-9 ook extern geoportaal steeksproefsgewijs getest.
Alles blijkt nu weer goed te werken,
Issue is daarom gesloten.
