### ISSUE TITLE
Link naar data vanaf service in stylesheet werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#503]
Als je de metainfo van een service bekijkt, dan kan je doorklikken naar de achterliggende data. Dat blijkt niet meer te werken. In plaats van de url naar de metadata van de data, wordt je nu verwezen naar http:/// En dat levert een blanco pagina op.

zie figuur

![link_data_vanuit_service_fout](https://user-images.githubusercontent.com/9005444/29815409-ce869d14-8cb0-11e7-99c3-3ef258dec0b9.jpg)

**Comment by SandroNeumann** [comment]
Op acceptatie doet ie het weer. Je zult waarschijnlijk wel je cache moeten legen.

https://acc-metadata.geodataoverijssel.nl/metadata/service/608d22a6-2735-4240-8330-34ee5b4ac4a5.xml

**Comment by SandroNeumann** [comment]
Aangepast op productie:

https://intern.geoportaaloverijssel.nl/metadata/service/a767648e-bbe0-45f8-8a70-135f8d7cc9d0

**Comment by gerardnienhuis** [comment]
Op 29-8 intern geoportaal getest en op 30-9 ook extern geoportaal steeksproefsgewijs getest.
Alles blijkt nu weer goed te werken,
Issue is daarom gesloten.
