### ISSUE TITLE
Tekst zoeken statische kaarten werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#508]
Bij iedere zoekopdracht die ik invoer als ik zoek naar statische kaarten, krijg ik 0 gevonden. Het lijkt er sterk op dat zoeken naar statische kaarten in het Geoportaal niet meer werkt (getest intern en extern geoportaal), bij zoeken op de pagina's HOME en Uitgebreid zoeken

 (nb: bij bladeren vind je geen statische kaarten, dat is een ander bekend probleem).

Getest door te zoeken naar statische kaarten met woorden die daarin echt voorkomen, zie plaatje hieronder. Geen van de gezochte woorden geeft zoekresultaten, en dat kan natuurlijk niet. 

nb: dergelijke problemen treden niet op bij services of geodatasets. Daar lijkt zoeken wel goed te werken.

![zoeken_statische_kaarten_bug](https://user-images.githubusercontent.com/9005444/30056488-36179140-9233-11e7-8317-4f407a571919.jpg)

**Comment by SandroNeumann** [comment]
Als het goed is is het probleem opgelost.

**Comment by gerardnienhuis** [comment]
helaas, er gaat toch nog wat fout: ik zie nu inderdaad alle zoekresultaten van statische kaarten weer correct. Maar die van services zie ik dubbel. Er wordt bij een bepaalde zoekterm zowel de WMS als de WFS getoond. Dat was al zo. Maar die krijg ik nu 2 keer: dus dezelfde WMS 2 keer en de WFS 2 keer. Dat was eerder niet het geval. Of er ook bij de geodata nu iets vergelijkbaars speelt, dat wordt nog uitgezocht.

![services_dubbel](https://user-images.githubusercontent.com/9005444/30061820-2c45899a-9249-11e7-9258-7f4c087ca8bd.jpg)

**Comment by SandroNeumann** [comment]
Dat is wel een ander issue. Graag deze sluiten en een nieuwe openen die daarover gaat.

**Comment by gerardnienhuis** [comment]
ok, gaat verder in volgend issue. nb: geodatasets hebben geen last van deze verdubbeling, het is nu alleen te zien bij services.
