### ISSUE TITLE
Zoekresultaten services komen dubbel voor

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#509]
Na een verstoring mbt zoeken van statische kaarten lijkt nu het zoeken van geodatasets verstoord te zijn: als je een bepaalde zoekterm in het Geoportaal gebruikt, dan krijg je twee keer dezelfde WMS en twee keer dezelfde WFS. Dat was eerder niet het geval, zie ook #508 

![services_dubbel](https://user-images.githubusercontent.com/9005444/30062012-f0e67dd6-9249-11e7-9617-e7665cf698bd.jpg)

**Comment by SandroNeumann** [comment]
Dat zijn twee verschillende services. Eentje flora en fauna beveiligd en eentje flora en fauna (publiek). 

In het externe geoportaal zijn er bijv gewoon twee services i.p.v. vier:
https://www.geoportaaloverijssel.nl/search?text=flora&types=service

**Comment by gerardnienhuis** [comment]
helder, moet dus in beheeronderdeel publicatieomgeving worden opgepakt, issue kan hier gesloten
