### ISSUE TITLE
Statusverandering van meer dan 60 items tegelijk niet mogelijk

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#510]
Bij de beheermodule van het Geoportaal kan je honderden statische kaarten tegelijk aanklikken en in theorie zou je die in 1 keer van status kunnen veranderen. Bijvoorbeeld van "gepubliceerd" naar "archief" verplaatsen. Dat hebben we geprobeerd, maar als je dat doet dan krijg je een wit scherm en verder gebeurt er niks. Het lijkt er mee te maken te hebben dat de volledige opdracht in een url wordt gestopt, en die is natuurlijk veel te lang bij honderden statische kaarten tegelijk.

Formeel is dit niet correct, want het systeem geeft een mogelijkheid, die eigenlijk niet bruikbaar is. Dit is vooralsnog pragmatisch opgelost: 60 tegelijk selecteren, dan opdracht geven en dan weer 60 selecteren. 

Maar het zou eigenlijk t.z.t. aangepast moeten worden: of selectie beperken tot 60 of mogelijkheid inbouwen dat selecteren van meer dan 60 mogelijk wordt. Omdat het vooralsnog is opgelost, is dit minder urgent en dus geplaatst in milestone 1.4.

**Comment by SandroNeumann** [comment]
Je aanname is correct. De limiet voor een url is bij de meeste browsers 4096. Die wordt vanaf 60+ records overschreden. Er kan nog wel wat aan die url gedaan worden. Voor elke record staat "recordsChange[]=[uuid]". Dat is hoe dan ook overbodig en raar. Maar dat zou enkel voor verdubbeling van aantal records zorgen die je kunt aanpassen. Het valt te overwegen - ook voor issue #406 - om het hele paginering idee op de schop te nemen. Door alleen dat aan te passen wat je ziet (dus 20 per keer), maar waar je wel door alles heen kunt bladeren i.p.v. maximaal 10 pagina's. Als je dan een filter hebt aanstaan zie je dan direct de volgende 20 die je moet veranderen, dat werkt op zich ook wel snel. Er is hoe dan ook een moment dat de grens van de URL bereikt wordt, gezien aangegeven moet worden welke records veranderd moeten worden. Welke oplossingsrichting ook gekozen wordt.

**Comment by gerardnienhuis** [comment]
label "bug" is verwijderd. kan tzt eens opgepakt worden. is formeel wel een bug, maar er is een eenvoudige workaround dus veel minder urgent nu. workaround is; maximaal 60 tegelijk selecteren.

**Comment by SandroNeumann** [comment]
De records via een post body doorsturen.

**Comment by gerardnienhuis** [comment]
Dit lijkt niet goed te werken: ik heb 100 metadatasets van "overige data" geselecteerd en heb daarna de opdracht gegeven om de status te veranderen (van gepubliceerd naar ter goedkeuring). Ik krijg daarna een wit scherm en meer niet. Getest op IE-11. Is de browser een probleem of is er iets anders aan de hand?

**Comment by SandroNeumann** [comment]
De versie met deze fix was nog niet op acceptatie neergezet.

**Comment by gerardnienhuis** [comment]
Dit blijkt nu goed te werken: 100 metadata sets tegelijk geselecteerd en status veranderd (van gepubliceerd naar concept). Resultaat is nu wel goed. Issue kan gesloten
