### ISSUE TITLE
Geen download link beschikbaar bij metadata by wel downloadable data

### ISSUE THREAD

**Issue by Michiel-2** [IDgis/geoportaal-test#511]
De dataset van "Spoorwegen uit het Nationaal Wegenbestand" bij Overijssel zou je wel mogen downloaden, maar er is geen download link beschikbaar op de metadata pagina.
https://www.geoportaaloverijssel.nl/metadata/dataset/39a142e3-e1eb-4abc-ba90-ef64683f0de0

**Comment by gerardnienhuis** [comment]
lijkt een bug, die download link is er wel geweest, bij de details.

Als je Bestandsnaam: Spoorwegen uit het Nationaal Wegenbestand bekijkt, dan staat er nu bij de details:

Website: http://services.geodataoverijssel.nl:80/viewer/layer/B24_spoorwegen/B2_Spoorwegen_NWB
OGC:WFS: http://services.geodataoverijssel.nl:80/geoserver/B24_spoorwegen/wfs
OGC:WMS: http://services.geodataoverijssel.nl:80/geoserver/B24_spoorwegen/wms
XML: https://www.geoportaaloverijssel.nl/metadata/dataset/39a142e3-e1eb-4abc-ba90-ef64683f0de0?noStyle=true

Hier had ook de download link moeten staan. Die is ook niet onbekend, omdat de id hetzelfde is:

https://download.geoportaaloverijssel.nl/download/39a142e3-e1eb-4abc-ba90-ef64683f0de0

Wens is om bij de details de url naar de downloadlink weer toe te voegen met als tekst:

Download: https://download.geoportaaloverijssel.nl/download/39a142e3-e1eb-4abc-ba90-ef64683f0de0

**Comment by SandroNeumann** [comment]
De configuratie voor download link prefix is veranderd, omdat er een onderscheid is gemaakt tussen intern en extern. De configuratie loopt voor op de versie die bij Overijssel deployed is. Zal bij volgende versie automatisch verholpen zijn.

**Comment by SandroNeumann** [comment]
Zie #491

**Comment by gerardnienhuis** [comment]
lijkt nog niet goed te werken: heb bestand getest: download link nu wel zichtbaar in metadata, maar klikken op link geeft foutmelding,
betreft:

https://acc-download.geodataoverijssel.nl:443/download-result/bbe5f450-7773-48e1-afb4-3c58dea7784b

https://acc-metadata.geodataoverijssel.nl/metadata/dataset/39a142e3-e1eb-4abc-ba90-ef64683f0de0.xml 

Bestandsnaam: Spoorwegen uit het Nationaal Wegenbestand

**Comment by gerardnienhuis** [comment]
wordt nog getest met andere downloads

**Comment by SandroNeumann** [comment]
Verkeerde domein in url. Verband met download beschikbaar maken voor Utrecht. Is nieuw issue.

**Comment by gerardnienhuis** [comment]
is nieuw issue. De link op zichzelf werk wel, dus dit issue kan gesloten.
