### ISSUE TITLE
Oracle locatie mappen gescheiden weergeven in rapport geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#512]
In alternate title staan de namen, van de geodatasets zoals die in oracle zijn opgeslagen.
Maar er staat ook de locatie. Wens is om deze locatie (mappen) in aparte kolommen
te plaatsen, direct na de kolom van alternate title.

Wens is ook om de mappen te splisten in de hoofdmap (map_1) en de submap die daar bij hoort.
Naam van de kolom met de hoofdmap wordt dan map_1 en de submap wordt dan map_2.
De mappen zijn van de naam te onderscheiden doordat ze achter de naam staan, en beginnen
met ( .. let op, ze eindigen niet altijd met ), maar vaak wel. Map_1 en map_2 zijn
gescheiden door een \, een / of een punt. Hieronder een aantal voorbeelden:
 
B1.rayonwk_locatie_point (b1\b14)
map_1 wordt dan B1
map_2 wordt dan B14

GEM.hoofdgroenstructuur_part (GEM.Hengelo)
map_1 wordt dan GEM
map_2 wordt dan HENGELO

B3.plassen_polygon (B3.B33)
map_1 wordt dan B3
map_2 wordt dan B33

B0.kmpunt_point
map_1 wordt dan leeg (geen tekst hier invullen)
map_2 wordt dan leeg (geen tekst hier invullen)

B4.VRN_GebiedVerwerving_polygon (b4/b46)
map_1 wordt dan B4
map_2 wordt dan B46

H2O.Ens_onttrekput_recent_point  (H2O\GGGB0
map_1 wordt dan H2O
map_2 wordt dan GGGB0

2015_Overijssel_o10.ecw (N:\luchtfoto2015\
map_1 wordt dan N:
map_2 wordt dan luchtfoto2015\

O2.natuurlijke_laag_o2_polygon (O2\Vastgesteld_O2_verordening)
map_1 wordt dan O2
map_2 wordt dan VASTGESTELD_O2_VERORDENING

O2.VRO_beekdal_veenweid_polygon (O2/Revisie1617)
map_1 wordt dan O2
map_2 wordt dan REVISIE1617

**Comment by SandroNeumann** [comment]
Dit compliceert het wel voor andere klanten, omdat het mechanisme m.b.t. alternate title niet door iedereen gebruikt wordt. Mochten zij alternate title wel invullen, maar voor iets anders zouden zij rare kolommen in de rapportage kunnen krijgen.

**Comment by gerardnienhuis** [comment]
Ja, dat lijkt logisch: de ene organisatie heeft andere wensen dan de andere, wat rapportages betreft. Zijn er meer geoportaal gebruikers dan zal dat vaker voor gaan komen.

**Comment by SandroNeumann** [comment]
Dit gaat verschillende sql files betekenen. Zal qua onderhoud wat meer werk gaan opleveren.

**Comment by gerardnienhuis** [comment]
Zojuist eerste test uitgevoerd. Veel ziet er al goed uit. Alleen zijn de kleine letters van de mappen niet veranderd in hoofdletters. Dat was wel gevraagd, zie voorbeeld hierboven:

B1.rayonwk_locatie_point (b1\b14)
map_1 wordt dan B1
map_2 wordt dan B14

**Comment by HermanAssink** [comment]
Gerard, de rapportage is toch bedoeld om te laten zien wat er in alternate_title is ingevuld? Dan is het toch niet logisch dat de rapportage iets anders weergeeft dan wat er is ingevuld, namelijk hoofdletters i.p.v. kleine letters?

**Comment by gerardnienhuis** [comment]
Ik wilde graag hoofdletters omdat ik dan in excel de boel in 1 keer kan sorteren. Jouw suggestie heeft ook voordelen. Gaan we uitzoeken.

**Comment by gerardnienhuis** [comment]
Uitgezocht: de excel opdracht =hoofdletters blijkt goed genoeg te werken (in engelse versie: upper). Hoeft dus in deze versie van het rapport niet aangepast te worden.

**Comment by gerardnienhuis** [comment]
Meerdere keren nogmaals getest: e.e.a. blijkt goed te werken. De gewenste nieuwe onderdelen zitten correct in het rapport.  issue kan gesloten
