### ISSUE TITLE
Rapport Geodata Feitelijk onterecht publiek onjuist

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#515]
Sinds de komst van de services van het type "alleen WMS" klopt de waarde in de kolom "feitelijk_onterecht_publiek" niet meer. Als er een service aanwezig is,  van het type "alleen WMS"dan staat in dat rapport bij die kolom nu consequent "ja" maar dat is niet juist. In de meeste gevallen moet daar "nee" staan. Er is in dat rapport geen rekening mee gehouden, dat je soms wel WMS mag hebben, maar toch de data niet mag downloaden. Met de komst van het type "alleen WMS" had dus, achteraf gezien, ook dat rapport moeten worden aangepast.

**Comment by SandroNeumann** [comment]
De sql moet rekening houden met het wms only mechanisme.

**Comment by SandroNeumann** [comment]
Ik heb dit nader bekeken, maar wat je zegt klopt volgens mij niet. Hier wordt 'ja' ingevuld wanneer de data vertrouwelijk is, maar de dataset vervolgens in een publieke service zit. Dat staat buiten het hele wms-only mechanisme.

**Comment by SandroNeumann** [comment]
Ik zie nu waar de fout in zit. In de query of de dataset in een publieke service zit moet nog een where clause bij om de wms only services weg te filteren. Nu worden ook de wmsonly services meegenomen en daar mogen vertrouwelijke datasets in zitten.

**Comment by gerardnienhuis** [comment]
Het rapport lijkt te werken, maar het is onduidelijk welke criteria: er moet beschrijving bij de rapporten beschikbaar komen zodat voor beheerders duidelijk is wat de velden voorstellen.  Wat valt er nu onder "onterecht publiek"?. Als "downloadable data" niet aanwezig is, en de data is wel in een WFS-service opgenomen?

**Comment by gerardnienhuis** [comment]
zie ook: https://github.com/IDgis/geoportaal-test/issues/562

**Comment by gerardnienhuis** [comment]
opnieuw getest: blijkt wel goed te werken. statusveranderingen komen nu wel goed in rapport terecht. Issue kan gesloten
