### ISSUE TITLE
Zoeken geodatasets werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#517]
Verleden week, voor de productiegang, werkte het zoeken naar geodatasets nog goed. Maar sinds vrijdag blijkt het zoeken naar geodata niet meer goed te werken. Verleden week kreeg je bij uitgebreid zoeken nog meerdere treffers als je zocht naar geodata en het woord "water" of "gml". Nu werkt dat niet meer. Kan dit door de productiegang zijn veroorzaakt?

**Comment by SandroNeumann** [comment]
Harvester moest herstart worden. Probleem is opgelost.

**Comment by gerardnienhuis** [comment]
zoeken werkt weer, issue kan gesloten
