### ISSUE TITLE
Rapport harvester en provider

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#518]
In de publicatieomgeving kan de beheerder van die omgeving zien wat de status van de harvester is. Bij de rapportages van het Geoportaal wil ik graag 1 rapport erbij.  Doel hiervan is dat beheerder van Geoportaal zonder veel ingewikkelde acties snel kan zien of er een storing mbt provider of harvester is. Zonder technisch beheer hierover te raadplegen. Is er geen fout, dan kan een eventueel probleem aan de invoerkant gezocht worden.

Rapport naam voorstel: providerhavester. Rapport in vorm van csv, net als andere rapportages, met in de bestandnaam ook datum verwerkt. Inhoud rapport: tijdstippen dat acties van harvester of provider niet succesvol zijn. 

Dus minstens 4 kolommen: 
datum, tijd, provider_fout, harvester_fout. Inhoud van provider_fout en harvester_fout: 0 of 1. 0 wil zeggen geen probleem, 1 wil zeggen wel probleem.  

Mogelijkheden:
provider_fout = 0
harvester_fout = 1

of 

provider_fout = 1
harvester_fout = 1

of 
provider_fout = 1
harvester_fout = 0

Als alles goed is, dan hoeft dat niet in het rapport opgenomen te worden.

Dus onderstaande situatie komt NIET voor in het rapport:

provider_fout = 0
harvester_fout = 0

Dit om te voorkomen dat het rapport onnodig lang wordt. Meestal gaan harvest en provider acties namelijk wel gewoon goed.

**Comment by gerardnienhuis** [comment]
alternatief: subset van monitoring bekijken, eventueel als app en waarschuwingen bij problemen. Link wordt gestuurd om te bekijken.

**Comment by SandroNeumann** [comment]
We kunnen geen onderscheid maken tussen of de provider een fout heeft of de harvester. Hooguit of de connectie verbroken is, maar dat slaan we op dit moment niet op. We kunnen wel een rapport maken of de harvest acties om wat voor reden dan ook falen, maar dat kunnen we niet toeschrijven aan de provider of de harvester. Alleen dat het fout gaat. In die zin kan de provider ook niet echt een fout maken, hij kan alleen informatie opsturen waar de harvester niets mee kan. Alleen de wisselwerking tussen de twee componenten kun je iets over zeggen.

**Comment by HermanAssink** [comment]
Sandro, Gerard, Welke fouten moeten onderscheiden worden? Wat ik zo kan bedenken is:

- geen verbinding tussen provider en harvester
- provider-fout bij lezen metadata
- provider-fout bij lezen geodata
- harvester-fout bij importeren geodata

In het algemeen is het denk ik wenselijk om duidelijk te hebben op welk bestand/tabel/dataset de fout betrekking heeft.
Verder is de vraag of deze wens bedoeld is om fouten die optreden z.s.m. te signaleren of dat het gaat om verzamelen van statische gegevens over opgetreden fouten. In het eerts geval ligt een oplossing mbv monitoring of email voor de hand en is een (csv) rapport minder geschikt omdat een beheerder dan zelf het initiatief moet nemen om te controleren op een fout.

**Comment by gerardnienhuis** [comment]
misschien is een dashboard voor beheerders en een email notificatie naar technisch beheerder eenvoudiger te implementeren en/of beter bruikbaar?

**Comment by SandroNeumann** [comment]
Onderdeel van #536
