### ISSUE TITLE
Geen metadata van tabellen in het geoportaal

### ISSUE THREAD

**Issue by NicoEilers** [IDgis/geoportaal-test#519]
Op dit moment kan ik geen enkele tabel de metadata vinden in het interne geoportaal.
Er zijn wel xml-files van tabellen opgenomen in de geoweb-folder.
Deze tabellen zijn ook niet meer terug te vinden in de rapportage.

Hier enkele voorbeelden van tabellen :

Inwonersaantal gemeente Deventer en Zwolle
Alternatieve titel: B0.cbs_pc6_leeftijd_dev_zwol (b0)
Versie:peildatum: 1 januari 2014
Unieke Identifier: f0e29a04-7ed4-4344-8090-9a631ad6b1d9

Beoordeling waterlichamen (KRW), peiljaar 2015
Alternatieve titel: B3.KRW_beoordeling_2015 (B3)
Unieke Identifier: 0a95f041-f162-44cb-81cf-7ab7a383301b

**Comment by SandroNeumann** [comment]
De brondataset staat ook niet in de GeoPublisher.

@reinderhoekstra 
Kun je iets hierover in de provider log vinden (productie) of tabellen in het algemeen?

**Comment by reinderhoekstra** [comment]
Ik heb gekeken in de logs van de maand oktober, maar vind niets terug over de genoemde tabellen of andere tabellen. Ook zie ik geen andere foutmeldingen dan gewend. Misschien goed om te weten: elke dag om 06:00 uur wordt de provider bij ons herstart.

**Comment by NicoEilers** [comment]
Onderstaande tekst staat wel in de metadata van de xml:
Ruimtelijk schema: TekstTabel

Voor de laatste wijziging was de metadata van tabellen wel zichtbaar in het geoportaal

**Comment by NicoEilers** [comment]
In de acceptatie omgeving wordt de metadata van tabellen nu wel getoond.
Issue kan worden afgesloten

**Comment by gerardnienhuis** [comment]
Getest door het aanbieden van nieuwe tabel. Bestaande tabellen en ook nieuwe tabel blijken nu wel goed zichtbaar.
