### ISSUE TITLE
Url download link klopt niet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#520]
Doordat Utrecht ook gebruik gaat maken van publicatieomgeving is er wat veranderd aan de urls. Dit moet nog gecorrigeerd worden. Nu werkt de download link niet meer goed, zie voorbeeld:

Deze link krijg je in je mail als je download opdracht geeft:

https://acc-download.geodataoverijssel.nl:443/download-result/bbe5f450-7773-48e1-afb4-3c58dea7784b 

Deze url geeft een foutmelding.

Dit is de link naar de metadata:

https://acc-metadata.geodataoverijssel.nl/metadata/dataset/39a142e3-e1eb-4abc-ba90-ef64683f0de0.xml

Bestandsnaam: Spoorwegen uit het Nationaal Wegenbestand

**Comment by SandroNeumann** [comment]
Dit is gefixed.

**Comment by gerardnienhuis** [comment]
Klopt. Getest en download link die via mail wordt doorgegeven, die werkt nu wel goed. Resultaat beoordeeld (shape download spoorwegen NWB) en kaart ziet er goed uit. Issue kan gesloten.
