### ISSUE TITLE
Url voorbeeldplaatje in rapport

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#523]
Wens is om de url van het voorbeeldplaatje uit de metadata van geodata op te nemen in het rapport van geodata. 

Kolom naam wordt: "url_plaatje" 

Url is af te leiden uit de eigenschappen, als geklikt wordt op het plaatje zelf, zie figuur. 

In het geval van dit voorbeeld wordt dus url_plaatje:

http://metadata.geodataoverijssel.nl/attachment/71723/gebouwd_monument.jpg

Mocht het voorbeelplaatje ontbreken, dan moet de betreffende cel leeg blijven.

De bedoeling is dat de volledige url in het rapport wordt opgenomen, direct na de kolom "abstract". 

![url_voorbeeldplaatje](https://user-images.githubusercontent.com/9005444/32595122-dcc290f2-c52e-11e7-95f3-4ef78e8198d5.jpg)

**Comment by HermanAssink** [comment]
@SandroNeumann : Graag vandaag technische impact beschrijven en schatten.

**Comment by SandroNeumann** [comment]
De url moet uit het metadata element BrowseGraphic met xpath gequeried worden.

**Comment by gerardnienhuis** [comment]
Na overleg verplaatst van issue 1.3 naar 1.2.

**Comment by gerardnienhuis** [comment]
de url staat inderdaad op de juiste plaats in het rapport. Maar het is de url, zoals die bij ons staat. En de wens is om de url te hebben van het bestand, zoals dat bij IDGis wordt gehost. Zie ook bijgevoegd plaatje.

**Comment by SandroNeumann** [comment]
Het is aangepast, zodat de url na ophalen door IDgis getoond wordt.

**Comment by gerardnienhuis** [comment]
Zojuist getest: de aanwezige urls zijn correct weergegeven. Meerdere urls in andere browsers uitgeprobeerd en resultaat is correct plaatje. Dat lijkt dus goed te gaan.

Wat opvalt is dat er ook cellen "leeg" zijn. Dat was ook de bedoeling, als de bijlage ontbreekt. Maar dat gaat nog niet altijd goed. Er zijn nu cellen leeg van datasets, die echter wel een plaatje bevatten. Het lijkt er op, alsof het bij de jpg-bestanden goed gaat, maar niet bij de overige bestanden, zoals png's.

voorbeeld:

B7.oude_hoeven_1500_point
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/dc8ecff1-615e-4186-889a-db00c9980a8d

In de metadata in het Geoportaal staat bij dit bestand als plaatje:
http://acc-metadata.geodataoverijssel.nl/attachment/3417/oude_hoeven_1500_point.png

**Comment by SandroNeumann** [comment]
Zijn er nog meer type afbeeldingen, of alleen jpg's en png's?

**Comment by gerardnienhuis** [comment]
nee, er worden alleen jpg en png bestanden aangeboden.

**Comment by SandroNeumann** [comment]
Het is aangepast

**Comment by gerardnienhuis** [comment]
Weer getest: zowel jpg's als png's zijn nu goed zichtbaar. De 21 ontbrekende urls zijn apart ook nog getest en die blijken allemaal inderdaad geen (of geen goede) plaatjes te bevatten. 1 van de 21 blijkt te verwijzen naar intern Overijssel, maar dat is een heel ander issue en wordt mogelijk apart in github opgenomen. Test laat dus zien dat alles nu werkt en issue kan gesloten.
