### ISSUE TITLE
Url aanvullende informatie goed verwerken

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#525]
Nu staan er in de "aanvullende informatie" van een bestand vaak bestanden. Maar het is ook mogelijk dat hier een website wordt ingevuld. De verwerking van die website gaat fout. De url wordt verwerkt als bestand en dat eindigd in een onbruikbare link:

goed gaat bijvoorbeeld:  Aanvullende informatie: layerfile:| http://metadata.geodataoverijssel.nl:80/attachment/5291/betonning_point.lyr
te vinden bij: 
https://www.geoportaaloverijssel.nl/metadata/dataset/b94e6e73-396f-449c-9492-f4a4ac0ae273
Bestandsnaam: Betonning provinciale vaarwegen

**Comment by SandroNeumann** [comment]
Dit lijkt een voorbeeld te zijn waar het fout gaat:
https://www.geoportaaloverijssel.nl/metadata/dataset/b2c5f593-de4c-4f7c-9b72-4c0909731a50

**Comment by SandroNeumann** [comment]
Er moet een check komen of de oorspronkelijke supplementalInformation een bestand of een webpagina is. In het laatste geval moet het metadata element ongewijzigd blijven.

**Comment by SandroNeumann** [comment]
Andere voorbeelden:
https://www.geoportaaloverijssel.nl/metadata/dataset/ee3e4139-75b3-48af-900e-0076185d0c6b
https://www.geoportaaloverijssel.nl/metadata/dataset/61b08aeb-e437-4e33-bdcc-193867241e99

Hier wordt wel een pagina weergegeven. Maar het gaat fout wanneer er relatieve url's gebruikt worden in de paden naar stylesheets en javascript bestanden.

**Comment by gerardnienhuis** [comment]
https://www.geoportaaloverijssel.nl/metadata/dataset/61b08aeb-e437-4e33-bdcc-193867241e99
 lijkt een goed resultaat op te leveren, alleen is de naam van de bijlage wel heel vreemd.

https://metadata.geodataoverijssel.nl/attachment/85345/www.ibis-bedrijventerreinen.nl

terwijl de bedoeling is, dat de url gewoon wordt: 
http://www.ibis-bedrijventerreinen.nl 

kan dan in de stylesheet niet ook gewoon die kortere versie weergegeven worden? 

url op zich lijkt wel goed te werken, maar is heel verwarrend op deze manier

**Comment by gerardnienhuis** [comment]
controle op productie uitgevoerd, per ongeluk. Moet opnieuw op acceptatie getest

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, zie voorbeelden hieronder:

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/eb1861da-3053-47a9-b9a5-720b62fd4226
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/74d9ec7b-aec7-4ecd-a7cc-1595738a6096

**Comment by gerardnienhuis** [comment]
issue kan gesloten
