### ISSUE TITLE
GeoJson als download formaat mogelijk maken

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#526]
Naast de formaten shape, gml enz is de wens dat ook bestanden als GeoJson kunnen worden gedownload.
Nu staat er in de pagina voor de download: 
 SHP    GML 2.1    GML 3.2    KML    DXF
Dat wordt dan:
 SHP    GeoJson   GML 2.1    GML 3.2    KML    DXF

**Comment by SandroNeumann** [comment]
Hier was al een issue voor: #473
