### ISSUE TITLE
Attributeninformatie in rapport geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#527]
Ik wil graag voor de analyse van de vulling van de metadata inzicht hebben in de informatie die opgeslagen is bij de atributen. Die informatie wil ik graag in het rapport bij de geodata beschikbaar hebben. Het betreft:

1) totale tekst van de beschrijving van de attributen, zoals nu ook in de metadata zichtbaar is gemaakt, zie voorbeeld hieronder

2) totaal aantal attributen bij een geodataset

3) aantal attributen bij een geodataset, waar informatie over beschikbaar is.

Voorbeeld:

Bestandsnaam: Langeafstandswandelroutes (LAW's)
https://www.geoportaaloverijssel.nl/metadata/dataset/dbfede1b-9176-422d-ad3c-4087819ee961

1) volledige tekst metainformatie:

PRIMAID: Uniek ID nummer gebruikt bij codering visie en verordening in PRIMA CD_VERORD: Uniek nummer, gebruikt bij codering verordening in PRIMA CD_VISIE: Uniek nummer, gebruikt bij codering visie in PRIMA LAWNUMMER: Nummer van de LAW LAWNAAM: Naam van de LAW zoals deze in LAW-gids verschijnt. OBJECTID: ObjectID

2) aantal verschillende atributen: 8

3) aantal attributen waarvan informatie is ingevuld: 6

**Comment by SandroNeumann** [comment]
Waar haal je "aantal verschillende attributen: 8" vandaan bij deze dataset? Ik zie hier namelijk de 6 attributen + shape:
https://admin.geodataoverijssel.nl/datasets/f7559a4b-48ae-47f2-a2f3-189609e71a74/edit

**Comment by gerardnienhuis** [comment]
aantal is inderdaad 8 ipv 6 attributen, verkeerd geteld.

**Comment by gerardnienhuis** [comment]
volgt nog voorbeeld waarbij metainfo van attributen gedeeltelijk afwezig is, of zelfs afwezig

**Comment by gerardnienhuis** [comment]
Bestand met gedeeltelijk ingevulde metainfo van attributen is geplaatst op de acceptatieomgeving. hieronder de details:

TEST ivm weergave tabelinfo in attributentabel
Alternatieve titel: B7.TEST_PMJP_waterschap (b7/b75)
 
Samenvatting: Betreft een testbestand om te bezien of de inhoud van de attributentabel juist wordt weergegeven in de rapportage. In dit bestand is de helft van velden in de attributentabel wel beschreven en de andere helft niet.
 
De velden in attributentabel zijn voor een deel voorzien van beschrijving, voor een deel leeggelaten;
 
Object naam: B7.TEST_PMJP_waterschap
Attributen
OBJECTID
ID
AREA_
PERIMETER
HECTARES
TYPE
NAAM
ZETEL
INTERNET
CBS_CODE
KAARTNAAM
SE_ANNO_CAD_DATA
KW_CLTLAND: Aantal uitgevoerde projecten t.b.v. de kwaliteit van het cultuurlandschap i.h.k.v. het PMJP.
WATER_BERG: Gerealiseerde waterberg i.h.k.v. het PMJP in m3/jaar.
WATERNOOD: Uitgevoerde Waternood projecten (Watersysteemgericht Normeren, Ontwerpen en Dimensioneren) in hectares.
BK_RV_HERS: Aantal kilometers Beek- en rivierherstel i.h.k.v. het PMJP.
GR_SMWKP: Aantal grootschalige samenwerkingsprojecten i.h.k.v. het PMJP.
AFK_VERH_O: Aantal hectares afgekoppeld verhard oppervlak i.h.k.v. het PMJP.
SHAPE
SHAPE.AREA
SHAPE.LEN

**Comment by SandroNeumann** [comment]
Duidelijk.

Er zijn trouwens in bovenstaand voorbeeld drie attributen die niet als kolommen in de GeoPublisher komen. Dat zijn:

SE_ANNO_CAD_DATA
SHAPE.AREA
SHAPE.LEN

**Comment by gerardnienhuis** [comment]
Dit lijkt nog niet correct
getest met: Bestandsnaam: Beekdal- en veenweidegebieden

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/78398257-2a5d-4a4b-a787-01fd2c264fec 

Hier staat bij de details: Uitgevoerde bewerkingen

Beschrijving: INHOUD ATTRIBUTENTABEL: OMSCHR: omschrijving van het type gebied, veenweide | beekdal


Dus aantal atributen had minimaal 1 moeten zijn (attribuut is: OMSCHR: omschrijving van het type gebied, veenweide | beekdal)
er staat in het rapport echter dat er 0 attributen zijn, en in de kolommen aantal_attributen en aantal_attributen_met_info staat nu 0
dat had dus minimaal 1 moeten zijn in dit geval

**Comment by SandroNeumann** [comment]
Het attributen veld in het rapport is leeg?

**Comment by gerardnienhuis** [comment]
ja, op dit moment is er niets te zien in het rapport bij de kolom attributen. Dat lijkt niet juist.
Er had moeten staan: 
OMSCHR: omschrijving van het type gebied, veenweide | beekdal

**Comment by SandroNeumann** [comment]
Klopt.

Ik zie wat er fout gaat. We pakken de laatste versie, maar we moeten de laatste geïmporteerde versie pakken.

**Comment by gerardnienhuis** [comment]
prima, ik wacht op de nieuwe versie. 
nu gaat het bij veel records nog fout, zie ook onderstaand voorbeeld:

Voertuigverdeling akoestisch onderzoek

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/fd6e1c0c-6941-461f-87f3-e22181398701


Er staat bij Uitgevoerde bewerkingen


JAAR: jaartal 
WEGCODE: wegnummer 
SORT_WEGCODE: uniek nummer 
HM: hectometerpaal meetpunt 
OMSCHRIJVING: omschrijving wegvak 
MEETPUNTNAAM: meetpuntnaam 
LENGTE: lengte wegvak 
BEGIN_HM: hectometerpaal begin wegvak 
EIND_HM: hectometerpaal eind wegvak 
JAARGEMTOTAAL: gemiddelde weekdag intensiteit totaal 
UUR_DAG_LICHT: uurintensiteit lichte voertuigen dag 
UUR_DAG_MIDZWAAR: uurintensiteit middelzware voertuigen dag 
UUR_DAG_ZWAAR: uurintensiteit zware voertuigen dag 
UUR_AVOND_LICHT: uurintensiteit lichte voertuigen avond 
UUR_AVOND_MIDZWAAR: uurintensiteit middelzware voertuigen avond 
UUR_AVOND_ZWAAR: uurintensiteit zware voertuigen avond 
UUR_NACHT_LICHT: uurintensiteit lichte voertuigen nacht 
UUR_NACHT_MIDZWAAR: uurintensiteit middelzware voertuigen nacht 
UUR_NACHT_ZWAAR: uurintensiteit zware voertuigen nacht 
PERC_DAG_TOTAAL: percentage verkeer dag 
PERC_AVOND_TOAAL: percentage verkeer avond 
PERC_NACHT_TOTAAL: percentage verkeer nacht


in het rapport staat echter alleen bij attributen:
LENGTE: lengte wegvak

**Comment by SandroNeumann** [comment]
De rest van de issues kan wel verder getest worden. Ik rol de fix uit wanneer je alles getest hebt.

**Comment by gerardnienhuis** [comment]
ok, wij testen hier verder

**Comment by SandroNeumann** [comment]
Het is aangepast.

**Comment by gerardnienhuis** [comment]
Zojuist getest. 4 willekeurige bestanden. 3 lijken correct, 1 is aantoonbaar fout. Het aantal genoemde attributen zoals vermeld in het rapport is niet juist (item: aantal_attributen_met_info) en ook attributen die zijn opgenomen, daarvan ontbreken er heel veel. Details hieronder:

**goed:Thermische invloedsgebieden bekende energieopslagsystemen**
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/b840d54d-3db9-426d-aa07-a259dd205f3c
rapport: XCOOR: X-coordinaat in meters YCOOR: Y-coordinaat in meters
details: XCOOR: X-coordinaat in meters YCOOR: Y-coordinaat in meters
volgens rapport aantal totaal:   5
volgens rapport aantal met info: 2

**goed: Beschermingsplan boomkikkers**
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/c3ce8efd-74e8-488c-8f32-14651f45c024
rapport: NR: 1 = kerngebied; 2 = potentieel kerngebied; 3 = verbindingsgebied; OMS: omschrijving
details: NR: 1 = kerngebied; 2 = potentieel kerngebied; 3 = verbindingsgebied; OMS: omschrijving
volgens rapport aantal totaal:   5
volgens rapport aantal met info: 2

**goed: Locaties van natuurlijke bronnen in Overijssel - Omgevingsvisie**
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/58083c32-fabf-4f68-a323-5359d817b088
rapport: NR: nummer bronlocatie CODE: code bronlocatie binnen het zelfde brongebied N3: code die het waterschap regge en dinkel hanteert voor haar waterlopen NAAM: naam van de bron BRON_VAN_B: naam van de beek die de bron voedt PLAATS: naam van de dichtst bijzijnde plaats
details: NR: nummer bronlocatie CODE: code bronlocatie binnen het zelfde brongebied N3: code die het waterschap regge en dinkel hanteert voor haar waterlopen NAAM: naam van de bron BRON_VAN_B: naam van de beek die de bron voedt PLAATS: naam van de dichtst bijzijnde plaats
volgens rapport aantal totaal:   10
volgens rapport aantal met info: 6


**niet goed: Voertuigverdeling akoestisch onderzoek**
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/fd6e1c0c-6941-461f-87f3-e22181398701
**rapport, hier ontbreken 21 attributen: LENGTE: lengte wegvak**
details (had moeten zijn): 
JAAR: jaartal 
WEGCODE: wegnummer 
SORT_WEGCODE: uniek nummer 
HM: hectometerpaal meetpunt 
OMSCHRIJVING: omschrijving wegvak 
MEETPUNTNAAM: meetpuntnaam 
LENGTE: lengte wegvak 
BEGIN_HM: hectometerpaal begin wegvak 
EIND_HM: hectometerpaal eind wegvak 
JAARGEMTOTAAL: gemiddelde weekdag intensiteit totaal 
UUR_DAG_LICHT: uurintensiteit lichte voertuigen dag 
UUR_DAG_MIDZWAAR: uurintensiteit middelzware voertuigen dag 
UUR_DAG_ZWAAR: uurintensiteit zware voertuigen dag 
UUR_AVOND_LICHT: uurintensiteit lichte voertuigen avond 
UUR_AVOND_MIDZWAAR: uurintensiteit middelzware voertuigen avond 
UUR_AVOND_ZWAAR: uurintensiteit zware voertuigen avond 
UUR_NACHT_LICHT: uurintensiteit lichte voertuigen nacht 
UUR_NACHT_MIDZWAAR: uurintensiteit middelzware voertuigen nacht 
UUR_NACHT_ZWAAR: uurintensiteit zware voertuigen nacht 
PERC_DAG_TOTAAL: percentage verkeer dag 
PERC_AVOND_TOAAL: percentage verkeer avond 
PERC_NACHT_TOTAAL: percentage verkeer nacht
volgens rapport aantal totaal:   26
**volgens rapport aantal met info: 1 (had 22 moeten zijn)**

**Comment by SandroNeumann** [comment]
We hebben hier te maken met wat vertakkingen op basis van de status in de GeoPublisher:

1) Er is geen dataset
2) Er is een dataset en staging en publicatie zijn verschillend
3) Er is een dataset en staging en publicatie zijn gelijk

Aangezien we het rapport genereren met statische sql kunnen we hier geen beslissingsmoment maken welke van de drie we per brondataset moeten uitvoeren. En ze alledrie naast elkaar plaatsen zal verwarrend zijn. De beste oplossing is om van harde sql over te stappen naar gegenereerde sql, maar dat heeft een hoge impact. Ik hoor graag hoe jij dit ziet.

**Comment by gerardnienhuis** [comment]
voorstel: kolom erbij maken in rapport met als titel: geopublisher
heeft 3 mogelijkheden:
geen dataset
staging en publicatie verschillend
staging en publicatie gelijk

en dan in rapport de querie voor situatie 3 correct uitvoeren.

**Comment by SandroNeumann** [comment]
Ik zie dat we dit niet eenvoudig kunnen uitvoeren omdat het rapport zich baseert op brondatasets en we hier spreken over datasets. We kunnen de id's van datasets wel opvragen, maar dan kunnen we meer dan 1 dataset id hebben en dan moeten we de attribuut gegevens tonen als een lijst (met een separator zoals op andere plekken in het rapport).

**Comment by SandroNeumann** [comment]
Een alternatief is om een rapport er naast te maken die gegevens van datasets toont.

**Comment by SandroNeumann** [comment]
We gaan voor de oplossing dat we alle attributen voor alle gekoppelde datasets tonen (met een separator om ze te onderscheiden).

**Comment by gerardnienhuis** [comment]
in volgende versie verder uitwerken, in de huidige versie laten voor wat het nu is. Issue kan daarom gesloten
