### ISSUE TITLE
Plaatje uit rapport geodata opent niet altijd goed in browser

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#528]
In het rapport van geodata staat de link naar de plaatjes zoals die in het geoportaal worden getoond. Enkele plaatjes blijken niet altijd goed weer te geven te zijn in een browser. De meeste plaatjes kan je bekijken door de url uit het rapport te openen in een browser zoals IE of Chrome. Maar er zijn enkele plaatjes die niet altijd goed te openen zijn. 

In onderstaand voorbeeld het plaatje van het gladheidmeldsysteem. Dat plaatje blijkt slechts 1 keer goed geopend te worden. Probeer je in een zelfde sessie onder een ander tabblad het platje te openen dan verschijnt een fout 404 (niet gevonden). Dit is opgemerkt door te testen vanuit provincie Overijssel (intern). Als het zelfde plaatje op een laptop met verbinding via een extern netwerk wordt geprobeerd, dan verschijnt meteen de 404 fout. 

Wat kan hier aan de hand zijn?

Voorbeeld waarbij dit is gevonden is:

https://www.geoportaaloverijssel.nl/metadata/dataset/ddcf7561-1796-47e2-9338-3d5e3b136a1f
Bestandsnaam: Locatie meetpunten van GladheidsMeldSysteem

url volgens de metainformatie, zoals gevonden bij het onderdeel WAT van de bestandbeschrijving
(rechtermuisknop op plaatje, daarna eigenschappen):
http://metadata.geodataoverijssel.nl/attachment/75975/gladheidsmeldsysteem.jpg 

volgens het rapport:
http://metadata.geodataoverijssel.nl:80/attachment/75970/gladheidsmeldsysteem.jpg

als je de url uit het rapport in een browser opent, dan wordt de url:
https://metadata.geodataoverijssel.nl/attachment/75970/gladheidsmeldsysteem.jpg

zie ook onderstaande schermafdruk

![plaatje_gladheid](https://user-images.githubusercontent.com/9005444/33721510-8837f640-db67-11e7-9dab-76a164885fca.jpg)

**Comment by SandroNeumann** [comment]
Ik kan dit niet reproduceren. Ik kan bovenstaand plaatje altijd correct openen. Ook via een extern ip.

**Comment by SandroNeumann** [comment]
Bovenstaande url doet het nu niet meer, maar dat komt omdat de url veranderd is:
https://metadata.geodataoverijssel.nl/attachment/78715/gladheidsmeldsysteem.jpg

Deze url staat ook in het rapport en doet het bij mij op een intern en extern adres.

**Comment by gerardnienhuis** [comment]
niet reproduceerbare fout?

**Comment by SandroNeumann** [comment]
Niet reproduceerbaar. Nieuwe issue wanneer het weer voorkomt.
