### ISSUE TITLE
Gintare Morkute als leverancier statische kaarten toevoegen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#529]
Nieuwe leverancier van statische kaarten (dus niet beheerder, alleen leverancier). Graag toevoegen aan de lijst, zodat zij kan beginnen met aanbieden van statische kaarten.

naam: Gintare Morkute
email: G.Morkute@overijssel.nl

**Comment by SandroNeumann** [comment]
Account is toegevoegd. Ik heb je een mail gestuurd met het wachtwoord.

**Comment by gerardnienhuis** [comment]
leverancier gevraagd om te testen

**Comment by gerardnienhuis** [comment]
Dit is niet meer relevant doordat geoportaal beheerders nu zelf mogelijkheid hebben om gebruikers toe te voegen. Issue kan gesloten.
