### ISSUE TITLE
Rudy Tuit toevoegen als beheerder

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#532]
Graag Rudy Tuit toevoegen als beheerder van de statische kaarten van het Geoportaal. Hij moet dus als beheerder via het interne geoportaal kunnen inloggen en ook rapportages maken die daar beschikbaar zijn. Email adres is: r.tuit@overijssel.nl

**Comment by SandroNeumann** [comment]
Account is toegevoegd. Ik heb je een mail gestuurd met het wachtwoord.

**Comment by gerardnienhuis** [comment]
inloggen is succesvol getest: het werkt goed. Dit issue kan gesloten
