### ISSUE TITLE
Download tekst ook aanwezig bij knop WAT in stylesheet van geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#534]
Wens is om ook download direct mogelijk te maken bij het onderdeel WAT in de metainformatie van geodata, zie plaatje. Dat moet dan net zo werken als klikken op de downloadlink bij de details. 

De tekst van deze downloadlink wordt: Download de kaart naar je eigen omgeving

zie plaatje als voorbeeld:

![nieuwe_vormgeving_download](https://user-images.githubusercontent.com/9005444/34773672-d0503914-f60c-11e7-8432-402ff7f39e92.jpg)

**Comment by SandroNeumann** [comment]
Hier is enkel een kleine stylesheet aanpassing voor nodig.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, maar helaas heb ik een typfout gemaakt bij de tekst

er staat nu:
Download de kaart naar je eigen omgeving

er moet staan:
Download het bestand naar je eigen omgeving

**Comment by gerardnienhuis** [comment]
nieuwe versie ziet er goed uit, issue kan gesloten.
