### ISSUE TITLE
Dashboard voor beheerders

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#536]
Om een actueel overzicht van de status van de processen te laten zien, lijkt een dashboard zinvol. Vergelijkbaar met het dashboard voor de publicatieomgeving. Denk aan bijvoorbeeld:

1) status provider en harvester
2) bereikbaarheid data in oracle
3) laatste 10 harvestacties: met aantallen veranderingen daarbij
4) enz

Dit om te voorkomen dat fouten optreden die niet of niet eenvoudig door een beheerder te merken zijn, zoals bijvoorbeeld: verstoring in harvestacties, zoeken statische kaarten offline enz.

**Comment by SandroNeumann** [comment]
Gegevens die in het dashboard getoond worden:
- connectie met provider
- aantal datasets, services en kaarten in interne en externe geoportaal (en verschil met een week geleden)
- systeemtaken van geopublisher

**Comment by gerardnienhuis** [comment]
voorstel is om eerst een mockup te maken en dan met de beheerders door te spreken of alle onderdelen inderdaad aan de behoefte voldoet. Pas als alles naar tevredenheid werkt in de mockup uitrollen naar productie.

**Comment by SandroNeumann** [comment]
Voor 1.3 doen we alleen de mock-up of ook direct de implementatie?

**Comment by gerardnienhuis** [comment]
bedoeling is om eerst de mockup te maken, en dan ook meteen de uitwerking naar productie versie

**Comment by SandroNeumann** [comment]
Mijn voorstel is om hier een aparte applicatie voor te maken. Dit omdat het onvermijdelijk is - gezien de wensen - dat het verknoopt wordt met de geo-publisher. Wanneer we een aparte applicatie maken kunnen we dit gewoon uitzetten voor een klant die alleen het geoportaal heeft.

Todo:
- mock-up
- connectie met provider in publisher naar json pagina schrijven
- in geoportaal-publiek database aantallen van datasets, services en kaarten per harvest actie met timestamp bewaren
- connectie met publisher database om systeemtaken te querien
- aparte app voor dashboard maken met requests en database queries voor alle benodigde informatie
- configuratie

**Comment by gerardnienhuis** [comment]
mijn voorstel is om voor het maken van de mockup nog te zetten: plaatje maken met voorbeeld van uiteindelijke scherm, dus zelfs nog voordat je een mockup maakt. Dat geeft ons de gelegenheid om het gesprek te hebben over wat er wel en niet te zien is in de dashboard

**Comment by gerardnienhuis** [comment]
Dashboard lijkt op hoofdlijnen goed te werken: verwijderen van geodata, nieuw aanbieden van geodata en statische kaarten blijkt goed te gaan (gezien naar metingen per uur en per dag). Wat nog niet geheel goed gaat is verwijderen en aanmaken van services. 

2 nu bekende problemen: 

1) In de middelste kolom kan je zien dat een service net is gemaakt. Maar de telling (verandering laatste uur) is nog niet aangepast. Na een tijdje is dit overigens wel weer aangepast.  Er zit blijkbaar een tijdverschil tussen. Maar hoeveel dan?

2) aanmaken van services geeft verdubbeling van aantal, als je de metingen bekijkt. Maar in de totalen staat juist weer het totaal aantal services, zoals ook in het Geoportaal staat. Dat is verwarrend. Als er 1 service bijkomt of afgaat, dan moet er ook slechts 1 bij opgeteld of afgetrokken worden.

zie figuren.

nb: testen afgelopen week en stoppen van harvesters is nog niet getest. Kunnen wij de provider stoppen, of moet bij IDGis de harvester handmatig worden uitgezet om dit effect goed te zien?

![telling_services_fout](https://user-images.githubusercontent.com/9005444/39198514-93080ee2-47e7-11e8-9cb3-9b6d2ebb125f.jpg)

![telling_services_dubbel](https://user-images.githubusercontent.com/9005444/39198528-97fe58e8-47e7-11e8-8cfe-ef16d2d66e3d.jpg)

**Comment by SandroNeumann** [comment]
1) De harvesters lopen elk kwartier, dus na een kwartier zijn de veranderingen zichtbaar.

2) Een service levert een wms en wfs, dus vandaar de verdubbeling. Tenzij het een wms only service is.

**Comment by gerardnienhuis** [comment]
De middelste kolom is het meest actueel. De rechter kolom loopt een kwartier achter maximaal, doordat deze kolom de resultaten van de harvester weergeeft. Tekst wordt hierover toegevoegd voor de "i" bij deze kolom.

**Comment by gerardnienhuis** [comment]
Dashboard werkt goed. Nog getest door 1 geodataset, 2 statische kaarten en 1 wms-only service toe te voegen. Blijkt in dashboard goed weergegeven. Extra tekst is ook correct toegevoegd. Issue kan gesloten.
