### ISSUE TITLE
Verwijzing met link naar geoportaal opnemen bij stylesheets.

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#537]
Nu kan je, als je de metainformatie leest van een geodataset, service of statische kaart, niet de verwijzing naar het Geoportaal zelf zien. Dat is jammer, want hierdoor moeten mensen zoeken naar het Geoportaal zelf, als ze dat nodig hebben. het is mogelijk op te lossen door de tekst en link op te nemen in de stylesheet zelf, bijvoorbeeld in de header daarvan, zie plaatje.

voor extern geoportaal wordt de tekst: www.geoportaaloverijssel.nl : klik je op die tekst dan ga je ook naar het externe geoportaal. Voor het interne geoportaal wordt de tekst: intern.geoportaaloverijssel.nl

**Comment by gerardnienhuis** [comment]
bijbehorende plaatje:

![link_geoportaal_opnemen](https://user-images.githubusercontent.com/9005444/34842130-d744630e-f70a-11e7-893d-ee1b241b0e99.jpg)

**Comment by SandroNeumann** [comment]
Stylesheet transformatie implementeren o.b.v. of deze url getoond moet worden (voor klanten die geen geoportaal hebben).

**Comment by gerardnienhuis** [comment]
bedoeling is, dat als je op die tekst klikt, dat je dan ook naar de betreffende url gaat, dus resp. naar http://www.geoportaaloverijssel.nl en http://intern.geoportaaloverijssel.nl

**Comment by gerardnienhuis** [comment]
lijkt op #600

**Comment by gerardnienhuis** [comment]
lijkt op #554 
T.z.t. dubbele issues verwijderen

**Comment by SandroNeumann** [comment]
is duplicaat van #600

**Comment by gerardnienhuis** [comment]
De opname van de url ziet er goed uit. Alleen valt het op dat bij services een ander (te groot) logo voor provincie Overijssel bovenaan de pagina's staat. Bij statische kaarten, bij geodata en bij de homepagina staat wel het juiste logo.

**Comment by gerardnienhuis** [comment]
De stylesheet verwijzing gaat goed, conform wens. Logo's is apart issue van gemaakt: #709 
dit issue kan dus gesloten
