### ISSUE TITLE
Openen metainformatie na klikken op bestandnaam

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#538]
Nu wordt bij de zoekresultaten na het klikken de metainformatie in of uitgeklapt. De meeste nieuwe gebruikers verwachten echter dan je dan op de metainformatie zelf komt. Wens is daarom om dit zo te veranderen dat je ook echt de metainformatie ziet, en niet dat het open of dicht wordt geklapt. Let op: dit geldt voor eerste scherm geoportaal en ook de zoekresultaten van "uitgebreid zoeken" en "bladeren".

zie plaatje, in dit voorbeeld moet het klikken op de tekst 
"Beperkte versie van de Basisregistratie Kadaster BRK (zonder NAW gegevens). (11-01-2018, Kadaster)" opleveren dat de metainformatie wordt getoond, net alsof je zou klikken op "meer informatie".

![klik_doorlink_wens](https://user-images.githubusercontent.com/9005444/34843799-d64dec72-f70f-11e7-8411-cd6f63b7fe19.jpg)

**Comment by SandroNeumann** [comment]
Moet je dan niet meer individuele records dicht kunnen klappen?

**Comment by gerardnienhuis** [comment]
correct, alles in en uitklappen vink moet wel blijven werken, maar werkt natuurlijk niet meer als je op naam van bestand zelf klikt.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken
getest bij "home", "uitgebreid zoeken" en ook bij "bladeren"
issue kan gesloten
