### ISSUE TITLE
Link aanklikbaar in stylesheet statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#54]
Kan de stylesheet van statische kaarten zo aangepast worden dat een url die wordt ingevuld in het veld "locatie" aanklikbaar is (zie plaatje). Doel is dat meteen naar de betreffende url wordt gegaan als deze url wordt aangeklikt (openen in nieuw venster). Nu wordt alleen de tekst van de locatie weergegeven in de stylesheet, dus mogelijk moet hiervoor de stylesheet worden aangepast. En kan een link die in de omschrijving wordt opgenomen, dan ook in de stylesheet aanklikbaar gemaakt worden? 
![url_in_locatie_aanklikbaar](https://cloud.githubusercontent.com/assets/9005444/13081002/60298ece-d4cb-11e5-9ea1-f455f1d1a6ea.jpg)

**Comment by gerardnienhuis** [comment]
let op: heeft niet alleen gevolgen voor de stylesheet. Mar het heeft ook consequenties voor maximale lengte (aantal tekens) van invoerveld "Locatie". Dit invoerveld mag niet te klein zijn als heel lange url's moeten worden ingevoerd.

**Comment by HermanAssink** [comment]
Het veld Locatie vergroten tot 2000 tekens (=maximum lengte van een url)

**Comment by gerardnienhuis** [comment]
label luxe (nice to have) kan weg: is gewoon een wens geworden, nu opdracht is verleend hiervoor

**Comment by gerardnienhuis** [comment]
werkt goed
