### ISSUE TITLE
Aantal bijlagen vermelden in rapport geodata

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#542]
Kolom gaat heten: aantal_bijlagen

**Comment by gerardnienhuis** [comment]
kolom lijkt "count" te heten, graag aanpassen in attachment_count en in tabel laten terugkomen tussen de kolommen "attachment" en "attachment_size_in_mb"

**Comment by gerardnienhuis** [comment]
aantal bijlagen gevonden, controle loopt nog

**Comment by gerardnienhuis** [comment]
vreemde plek voor kolom, tzt oplossen, zie issue #631 
Niet nu aanpassen

**Comment by gerardnienhuis** [comment]
controle op basis van rapportage: 2 bijlagen lijkt niet altijd correct, b.v.:

Bestandsnaam: Kaart Ten Have - 1648
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/ee3e4139-75b3-48af-900e-0076185d0c6b 
dat blijkt niet een bijlage te zijn, maar een url:

**Comment by gerardnienhuis** [comment]
wel correct met 2 bijlagen:

Paleografische kaart 500 voor Christus (14-08-2013, Provincie Overijssel) 
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/8e3c1d27-f27d-4422-8fed-4ba0504f3bc2
Aanvullende informatie: Informatie|  http://www.wtkg.org/geo_paleomap.html
Aanvullende informatie: Legenda|  https://acc-metadata.geodataoverijssel.nl:443/attachment/2603/PALEOGR_MAP_legend_NL.jpg

Digitaal terrein model kanaal Almelo de Haandrik
blijkt ook correct, met 2 bijlagen

**Comment by gerardnienhuis** [comment]
niet correct, heeft geen bijlagen, zou volgens rapport 1 bijlage hebben

TABEL test nieuw
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/42a1c0a0-96aa-4343-9114-a0d4a4ccf946

**Comment by gerardnienhuis** [comment]
wel weer correct, met 1 bijlage:

Gebieden ter uitvoering van Europese programma's
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/f4b5857c-50db-49ed-9377-23eb2e4ff854

**Comment by SandroNeumann** [comment]
Komt hierdoor:

![image](https://user-images.githubusercontent.com/10757125/44779351-98598500-ab7f-11e8-82c1-2bff33ba176a.png)

Het rapport kijkt hoeveel bijlages er zijn, maar houdt er geen rekening mee wanneer er een element is zonder inhoud (iets wat de stylesheet wel doet). Dat moeten we toevoegen.

**Comment by SandroNeumann** [comment]
De oorzaak was iets anders. Namelijk dat de url van aanvullende informatie weggehaald wordt uit de oorspronkelijke xml, omdat de url een fout oplevert. Er zitten spaties in de url in het geval van de dataset "TABEL test nieuw".

Je wilt in principe geen foute url presenteren.

Zie oorspronkelijke metadata:
https://acc-admin.geodataoverijssel.nl/metadata/source-datasets/13729924-960c-4ae9-8f49-6bc2c52e0fc6

**Comment by gerardnienhuis** [comment]
Dit blijkt op te treden bij verkeerde bijlagen. Dus eerst bijlagen goed maken, voordat test uitgevoerd kan worden. Fouten in urls zijn onder meer \ ipv / en spaties in urls. Merk op: urls met statuscode 404 geeft aan dat url helemaal niet bestaat. Overige controles kloppen, issue kan gesloten.
