### ISSUE TITLE
Rapport download tijden aanpassen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#545]
De tijden in het rapport download staan nu onhandig en tot op de microseconde uitgeschreven. Dat maakt verwerking van het rapport lastig. Bovendien zijn er maar 2 ipv 3 kolommen:
begin- en eindtijd zijn er nu wel, maar niet doorlooptijd.

Wens is deze 2 kolommen met tijd bij elkaar te zetten, nu zitten er meerdere andere kolommen tussen
Deze 2 kolommen graag direct plaatsen na "request-id"

verdere aanpassingen:
request_time: zo laten staan, niet bewerken
respons_time: zo laten staan, niet bewerken

daarna nieuwe kolommen:

request_datum: dit is request_time maar outputformat aanpassen: wordt DD MM JJJJ 
met 2 extra kolommen daarna: 
request_tijd_uur 
 en request_tijd_seconde

voorbeeld request_time is: 2016-08-25 14:00:01.207993

de request_datum wordt dan: 25-08-2016
de request_tijd_uur wordt dan: 14
de request_tijd_seconde wordt dan: 0

vergelijkbare wens met respons_time, dat wordt dus 
respons_datum (in DD MM JJJJ)
respons_tijd_uur  en
respons_tijd_seconde

daarna een extra kolom: 
doorlooptijd: verschil tussen 1 en 2 dus respons-time min request-time
(in seconden)

**Comment by SandroNeumann** [comment]
Is het i.p.v. request_tijd_seconde niet request_tijd_minuut?

**Comment by gerardnienhuis** [comment]
ja, excuses. bedoeld was inderdaad request_tijd_minuut
en ook respons_tijd_minuut

**Comment by gerardnienhuis** [comment]
Het rapport ziet er goed uit: tijden zijn in format, zoals gevraagd en ook doorlooptijd is correct (steekproefsgewijs getest, bij enkele korte en wat langere doorlooptijden). Issue kan gesloten.
