### ISSUE TITLE
Rapport download email namen uitsplitsen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#546]
user_emailadres extra kolommen toevoegen, direct na user_emailadres

email adres is nu naam met @ en organisatie,

bijvoorbeeld pietje.puk@voorbeeld.nl

kolommen na user_emailadres toevoegen:

email_naam toevoegen : 
naam is in dit voorbeeld alles voor de @, dus pietje.puk

organisatie_naam toevoegen: 
dat is alles tussen @ en de . (in hoofdletters), in dit
bij pietje.puk@voorbeeld.nl wordt dit dus VOORBEELD

organisatie_url toevoegen
dat is alles na @, maar dan met http://www ervoor
bij pietje.puk@voorbeeld.nl wordt dit dus http://www.voorbeeld.nl 

email_land toevoegen. In hoofdletters. 
Dat is alles na de ., dus 
bij pietje.puk@voorbeeld.nl wordt dit dus NL

**Comment by SandroNeumann** [comment]
Besef wel dat waardes die in de organisatie_naam ingevuld zouden worden niet altijd een organisatie naam hoeven te zijn. Denk bijv. aan e-mailadressen als hotmail, gmail of me. Wat dat betreft zou een kolomnaam als email domein de inhoud beter beschrijven.

En http://www voor een url plakken heeft als aanname dat www. voor het adres een url is die ergens heen gaat. Dat is tegenwoordig steeds minder het geval, www is namelijk gewoon een subdomein.

**Comment by gerardnienhuis** [comment]
is bekend dat het niet 100 % goed gaat maar is goed genoeg als eerste schatting.

**Comment by gerardnienhuis** [comment]
niet met rapportage oplossen, mogelijk in excel of python. issue kan gesloten
