### ISSUE TITLE
Kats toevoegen als leverancier van statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#548]
Graag Judith Kats toevoegen, zodat zij ook statische kaarten kan leveren

email: 

j.kats@overijssel.nl

**Comment by SandroNeumann** [comment]
Nieuwe gebruiker is toegevoegd.

**Comment by gerardnienhuis** [comment]
gebruiker blijkt te kunnen werken, issue kan gesloten
