### ISSUE TITLE
Url loopt door bij statische kaart stylesheet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#550]
Als je een statische kaart bekijkt, waarin een hele lange url aanwezig is, dan gaat er iets fout. Het bijzondere is, dat je wel een goed resultaat hebt, als je bij het onderdeel ZOEKEN EN WIJZIGEN METADATA  van een statische kaart bent (klik op oogje geeft goed resultaat, zie plaatje 1, hieronder). Maar als je in het geoportaal zelf dezelfde statische kaart bekijkt, dan loopt de url van het scherm af. Dat is niet de bedoeling, zie plaatje 2. Dit komt in ieder geval voor in het interne geoportaal, mogelijk ook extern.

situatie goed, plaatje 1 (vanaf onderdeel zoeken en wijzig metadata):

![urlgoed_looptnietdoor](https://user-images.githubusercontent.com/9005444/35618243-a9f2aae4-067a-11e8-87c8-d080c666045a.jpg)

situatie fout, plaatje 2 (vanaf intern geoportaal):

![urlfout_loopt_door_geoportaal_intern](https://user-images.githubusercontent.com/9005444/35618268-becbd4c2-067a-11e8-8af9-3ecd834148ef.jpg)

**Comment by SandroNeumann** [comment]
Komt door verschil in browsers. De eerste screenshot is Opera, de tweede IE.

**Comment by gerardnienhuis** [comment]
De wens is dat het in alle nu gangbare browsers nu goed werkt. 
Dus IE, Edge, FF, Chrome en Opera. Kan dat?

**Comment by SandroNeumann** [comment]
Ja, gezien dit een bug is hoeven er geen uren geschat te worden. Dit moeten we sowieso oplossen.

**Comment by gerardnienhuis** [comment]
Getest door extra lange url op te nemen:

https://acc-admin.geoportaaloverijssel.nl/metadata/276f2be4-d7ba-4595-9d78-5c55a08996bb

blijkt goed te werken, url is aanklikbaar, ondanks feit dat het over 2 regels wordt verdeeld.

Getest met recente versies van: Opera, Chrome, Firefox en IE-11

 Dit issue kan gesloten.
