### ISSUE TITLE
Wens url opnemen in downloadscherm in titelbalk

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#554]
Vergelijkbaar met vraag #537 een verwijzing naar het Geoportaal opnemen met doorklikbare url in balk van het downloadscherm. zie plaatje:

![wens_download_tekst_geoportaal](https://user-images.githubusercontent.com/9005444/36028252-2f2feb78-0d96-11e8-8166-6840dea0ded0.jpg)

**Comment by SandroNeumann** [comment]
is duplicaat van #600

**Comment by gerardnienhuis** [comment]
is dubbel, staat al in #600. Dit issue kan gesloten
