### ISSUE TITLE
Verwijderen metadata uit geoportaal werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#556]
Het was altijd zo, dat als je metadata verwijderde als beheerder, dat die dan binnen een uur ook niet meer in het Geoportaal te zien is. Nu is dat echter niet meer zo. Voor het eerst is dit gemerkt op zondag 28 januari.

Hieronder de details. Kan het zijn dat er een probleem bij de provider of harvester?

zondag ochtend 28-1: bestand toegevoegd
zondagmiddag xml verwijderd (uit folder geoweb verwijderd)
tevens oracle geodataset verwijderd

, maar staat nu nog steeds in geoportaal

https://www.geoportaaloverijssel.nl/metadata/dataset/ca0e042c-0468-4754-8c36-eece771dd795 

Alternatieve titel: B7.TEST_gemgrens_polygon (b7/b75)

Bestandsnaam: TEST data ivm patches update
Samenvatting: Het SSC-ONS wil in het weekend van 26 en 27 januari alle Windows server patchen en daarmee voorzien van de laatste beveiligingsupdates. Ter controle is deze dataset gemaakt

**Comment by gerardnienhuis** [comment]
merk op: een xml die op vergelijkbare manier in het Geoportaal is gezet afgelopen vrijdag, die is vandaag met succes verwijderd: deze blijkt nu ook niet meer in het Geoportaal zichtbaar te zijn.

**Comment by SandroNeumann** [comment]
Het kwam hierdoor:

![brondata_1](https://user-images.githubusercontent.com/10757125/36101629-292299da-100a-11e8-804f-10be36f4e070.png)

![brondata_2](https://user-images.githubusercontent.com/10757125/36101636-2d156d10-100a-11e8-82de-38d57e93b3e6.png)

Er waren nog notificaties aan de brondata gekoppeld, waardoor deze nog niet definitief verwijderd werd. Pas als die weggeklikt zijn gebeurt dat. Ik heb dat net gedaan, de harvesters met de hand laten draaien en de dataset is nu ook in het Geoportaal verdwenen.

**Comment by gerardnienhuis** [comment]
Correct opgelost, metainfo is nu niet meer zichtbaar in geoportaal, wat inderdaad de bedoeling was. Issue kan gesloten.
