### ISSUE TITLE
Error codes onduidelijk of fout

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#557]
In het rapport van geodata zit de kolom http_errors_urls. Het is onduidelijk waarom die urls er in staan. Sommige urls lijken prima te werken en anderen ontbreken schijnbaar in de metainformatie (bij het onderdeel WAT in de stylesheet). Voorbeelden zijn te vinden door error code 301 te selecteren (ook een kolom in het rapport). Onduidelijkheden zijn onder meer:

productbeschrijving|http://www.kadaster.nl/top10nl/technische_aspecten.html 
(deze url werkt gewoon goed)

http://nl.wikipedia.org/wiki/Christiaan_Sgroten
(deze url werkt gewoon goed)

Natura 2000-gebieden in Nederland
Gebiedendatabase|http://www.synbiosys.alterra.nl/natura2000/gebiedendatabase.aspx?subj=n2k^Regiegroep Natura 2000|http://www.natura2000.nl
logisch dat deze niet werkt, is meerdere urls op 1 regel, maar deze staat ook niet in de metainformatie
zie: https://intern.geoportaaloverijssel.nl/metadata/dataset/2101e166-89d7-433c-ace3-2c67ff63b62f

kan het zijn dat sommige urls worden verwijderd uit de stylesheet, bijvoorbeeld als een error is gevonden?

**Comment by SandroNeumann** [comment]
De statuscode wordt gecheckt en alles wat niet een 200 (= OK) terug geeft wordt als error geschreven. Statuscode 301 is een redirect, je wordt omgeleid naar een andere pagina. Wat feitelijk geen fout is, je komt enkel op een andere url uit uiteindelijk. Dus hier zouden we inderdaad nog een uitzondering voor moeten maken. Dit geldt ook voor 302, wat ook een redirect is.

Overigens is niet het geval bij: https://www.kadaster.nl/top10nl/technische_aspecten.html
Dat is een 404 (= NotFound), maar het Kadaster heeft daar een opgemaakte pagina voor gemaakt.

**Comment by gerardnienhuis** [comment]
Het werkt al een stuk beter. Alle 404 error codes geven aan, dat de url fout is. Dat is mooi, want dan kan je als beheerder kijken wat er aan de hand is.

Maar er zijn nog 3 vragen:

er is 1 melding met error code 301 die mogelijk niet in het rapport had moeten staan.
er is minstens 1 400 melding die mogelijk niet in het rapport moet staan:
wat is ? in dit geval? er zijn meerdere meldingen met ? 


voorbeelden met details staan hieronder:


301 onterecht?

id is: 814
title is: Top 250 raster van Nederland
http error urls, daar staat:
http://www.kadaster.nl/web/artikel/productartikel/TOPraster.htm
dat verwijst door naar de juiste pagina:
https://www.kadaster.nl/-/topraster 


400 onterecht

id is 500:
title is: Essen
url werkt gewoon en document kan worden gedownload:
http:\\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\Docs\Methode van Onderzoek essenkaart.doc

**Comment by SandroNeumann** [comment]
1) De '?' wordt getoond wanneer er geen http_status_code gevonden kan worden. Dat heb je wanneer de url niet meer bestaat / geregistreerd staat.

2) De 301 kwam omdat de brondata metadata niet meer bestaat. Dan komt er geen informatie meer binnen en wordt de http_status_code niet ge-update. Ik heb even alle http_status_codes opgeschoond en nu is de 301 weg. Dat moet ik dan ook even met de hand doen op productie.

3) De 400 komt omdat er spaties in de url staan. De browser past dat aan, in de controle check die wij doen gebeurt dat niet. In principe zou ik dat wel zo willen laten, want de url is wel fout. De browser corrigeert dat alleen al.

In het voorbeeld wordt de url:

http://gisopenbaar.overijssel.nl/GeoPortal/MIS4GIS/Docs/Methode van Onderzoek essenkaart.doc

veranderd naar:

http://gisopenbaar.overijssel.nl/GeoPortal/MIS4GIS/Docs/Methode%20van%20Onderzoek%20essenkaart.doc

**Comment by gerardnienhuis** [comment]
error codes zijn nu wel duidelijk en consequent. getest met meerdere steekproeven. Nu zijn alleen 400, 404 en ? codes aanwezig. Dit  issue kan gesloten
