### ISSUE TITLE
Fouten bij aanvullende informatie in metadata datasets

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#558]
Hier staat geen bestandsnaam in de URL:
https://www.geoportaaloverijssel.nl/metadata/dataset/0c8fdd40-d2e4-4cf3-9da8-139620f73e03

Hier heb je voorgenoemd probleem ook en staan er twee elementen (standaard schrijft voor dat er maximaal 1 element mag bestaan):
https://www.geoportaaloverijssel.nl/metadata/dataset/06543cf0-1c6f-4522-a076-019c1e506375

**Comment by SandroNeumann** [comment]
Het tweede punt ligt aan de invoerkant.

**Comment by gerardnienhuis** [comment]
problemen aan de invoerkant zijn niet technisch op te lossen, maar moeten gevonden worden in het rapport geodata.

**Comment by gerardnienhuis** [comment]
gevonden in rapport geodata

bij http_errors_urls

aanvullende informatie|http://www.kadaster.nl/web/artikel/productartikel/TOPraster.htm 

levert in rapport foutmelding op: 

http_errors_codes is 301

maar als je de website test, dan levert dit gewoon goede leesbare internet site op:
http://www.kadaster.nl/web/artikel/productartikel/TOPraster.htm  
opent normaal in browser

het lijkt er dus op dat er nog steeds errors worden gemeld in het rapport van geodata bij sites die het wel doen

**Comment by SandroNeumann** [comment]
Dat is een ander issue dan waar dit issue om draait. Zie: #557 

Wat mij betreft kun je dat issue nog naar 1.3.3 verplaatsen en de labels vraag en gebruikerstest verwijderen.

**Comment by gerardnienhuis** [comment]
code 301 is niet zinvol om als fout op te nemen, wordt gecorrigeerd, zie #557

**Comment by SandroNeumann** [comment]
Voorbeeld van url aan jullie kant:
Aanvullende informatie: Meer informatie| https://noorderbreedte.nl/2005/10/01/de-kaarten-van-huguenin/

**Comment by gerardnienhuis** [comment]
te testen door http://www.nu.nl als url op te nemen, met daarachter een /
dus: http://www.nu.nl/
het resultaat in het geoportaal moet dan zijn: http://www.nu.nl

**Comment by gerardnienhuis** [comment]
werkt wel maar echt goede url wordt bij #525 opgelost

**Comment by gerardnienhuis** [comment]
Leave a comment
