### ISSUE TITLE
Download link aanwezig op home pagina maar geeft fout

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#559]
Wat kan hier aan de hand zijn? Er is wel een download link aanwezig, maar geen link naar de viewer.

 En als ik de download probeer dan krijg ik een foutmelding als ik probeer de download uit te voeren. Bij de details in de metadata staat ook geen link naar een downloadlink. 

Dan moet die toch ook niet op de homepagina staan?

De foutmelding is:

500 Interne server fout

Er ging iets mis bij het verwerken van het verzoek.

Foutcode: @772c945ao

![downloadfout](https://user-images.githubusercontent.com/9005444/36303518-b225c5a4-130c-11e8-9e98-7b6d44682d30.jpg)

**Comment by SandroNeumann** [comment]
De dataset is vanochtend naar publiek veranderd, maar hij zit in de publisher nog in een beveiligde service. Voor het geoportaal is ie dus publiek en downloadbaar, vandaar dat de download link er is. We zouden daar inderdaad een check op moeten doen voordat we de download link presenteren.

**Comment by gerardnienhuis** [comment]
te testen door dataset die in beveiligde service zit, van status te laten veranderen. 
Bijvoorbeeld 1 van beide datasets:

Lekkages horizontaal leidingwerk (transportleidingen) 
Bodemkundige basisinformatie 

deze zitten in de service: B41_bodem_beveiligd:B4_Bodemkundige_basisinformatie.

**Comment by gerardnienhuis** [comment]
getest, gaat nu wel goed: downloadlink is wel intern te zien, is correct
maar is niet extern te zien: is ook correct
issue kan gesloten
