### ISSUE TITLE
Personen aan rollen koppelen tbv testen Geoportaal beheer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#56]
Ik zou graag bij het testen van de beheermodule van het Geoportaal ook de juiste personen aan de bijbehorende rollen willen koppelen. Dan is het voor de beheerders ook veel duidelijker wat de uiteindelijke werking van het systeem wordt. 

Rol beheerder: Gerrit Jurjens, Nico Eilers, Ria Kalter, Reinder Hoekstra en Gerard Nienhuis
Rol: leverancier: iedereen (de rest)

**Comment by HermanAssink** [comment]
Aanvulling van Gerard: Graag een extra account Test met als rol Leverancier zodat Gerard deze rol kan testen.

**Comment by gerardnienhuis** [comment]
is goed nu / test 24-2-16
