### ISSUE TITLE
Metainformatie als UKST toevoegen bij details

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#560]
Wens is om de url naar de metainformatie ook op te nemen in de xml en in de stylesheet, zodat deze ook zichtbaar wordt bij de "andere bronnen" in het NGR. Als je een Unknown Service type opneemt in de metainformatie, dan wordt deze zichtbaar in het NGR. Dus hierdoor kan je ook de link naar de volledige metainfo in het NGR laten zien.

Voorstel hieronder. 2 plaatjes: origineel bij details, en aangepaste versie

![ukst_wensen_extra](https://user-images.githubusercontent.com/9005444/36304600-7a973f38-1310-11e8-97cf-4551bea20b03.jpg)

![ukst_wensen_extra_bewerkt](https://user-images.githubusercontent.com/9005444/36304605-7fc8f532-1310-11e8-8438-abab65cf9aed.jpg)

**Comment by SandroNeumann** [comment]
Als het protocol UKST wordt moet het label bij de url ook iets in die richting zijn. Zoals "Onbekend" of "Overig" bijvoorbeeld.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Ik bedenk me net dat wat wij met het XML element doen niet mee komt naar NGR. Dit zit puur in onze stylesheet en NGR ontvangt alleen de kale XML. Het beste wat wij kunnen doen is er een protocol website aan hangen en daar de geoportaal metadata link in stoppen. Dan komt ie in NGR onder de tab "Downloads, views en links" onder kopje "Andere bronnen".

**Comment by SandroNeumann** [comment]
Protocol UKST en in onze stylesheet maken we dat aan de voorkant dan op met label "MetadataInfo". NGR krijgt dit echter dan binnen als UKST.

**Comment by gerardnienhuis** [comment]
Ziet er goed uit, url is in xml aanwezig. in productie zal blijken of het ook goed in NGR zichtbaar is. Zou wel moeten, gezien ervaringen met andere urls (b.v. voor download). 

In de stylesheet staat nu:
Metadatainfo. 
Gevraagd was (zie plaatje aan begin van dit issue): Metainfo.
Meer toepasselijk is eigenlijk: Metadata url

nb: in NGR gaat deze url heten: UKST. Daar is niks aan te doen. Maar in stylesheet is de tekst waarschijnlijk wel aan te passen.

**Comment by gerardnienhuis** [comment]
voorbeeld: is nu:
MetadataInfo: https://acc-www.geoportaaloverijssel.nl:443/metadata/dataset/b23366ad-6669-4bae-a1d4-eb85e9de55fc

voorbeeld wordt:
Metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/dataset/b23366ad-6669-4bae-a1d4-eb85e9de55fc

**Comment by SandroNeumann** [comment]
Is aangepast

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
