### ISSUE TITLE
Brondata afwezig dan niet meer tonen in geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#563]
Als een xml met metadata wordt verwijderd, dan kan de metainfo nog steeds in het geoportaal zichtbaar zijn. bijvoorbeeld omdat er een wms van gemaakt is of omdat de laag in de publicatieomgeving zichtbaar is.

Wens is, dat als de brondata afwezig is (conform rapport geodata "brondata aanwezig" is NEE), dan die metainfo ook niet meer zichtbaar laten zijn in het Geoportaal. 

nb: ze mogen nog wel zichtbaar zijn bij de metainfo van de services, maar ze zijn in ieder geval minder goed vindbaar dan nu het geval is. 

Hangt samen met issue #564

**Comment by SandroNeumann** [comment]
Zelfde als #564 in de zin dat met die maatregel dit ook opgelost is.

**Comment by gerardnienhuis** [comment]
Voor een latere versie van het Geoportaal: ook niet meer vindbaar maken in de metadata van de services. nu is het nog steeds zo dat de verwijderde lagen, als die in een service zitten, wel nog bij de details van de metadata van de services zichtbaar zijn in het Geoportaal. Maar als je die metainformatie dan wilt benaderen, dan krijg je straks een foutmelding ipv de metainformatie van de verwijderde dataset cq laag.

**Comment by gerardnienhuis** [comment]
lijkt wel op #564 maar is toch wat anders. Dit issue gaat over de weergave in het Geoportaal. #564 gaat over de harvestmogelijkheden. Technisch zal het misschien wel neerkomen op de aanpassing van slechts 1 component, maar functioneel is het iets heel anders. Daarom het label 'duplicate" verwijderd.

**Comment by gerardnienhuis** [comment]
Wordt getest met:

Bestandsnaam: Amfibieën in Overijssel
 Alternatieve titel: B4.amfibie_RAVON_point (b4.b47)
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/e3d568de-e094-42cc-a6a2-302f312974ea

**Comment by gerardnienhuis** [comment]
Gezocht naar   " Amfibieën in Overijssel" na 2 uur. Dit levert geen resultaten meer op, als alleen gezocht wordt in de geodatasets. Werkt dus goed. Issue kan gesloten worden.
