### ISSUE TITLE
Niet meer harvesten als brondata afwezig is

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#564]
Als een xml met metadata wordt verwijderd, dan kan de metainfo nog steeds in de harvestresultaten van het geoportaal zichtbaar zijn. Hierdoor wordt de metainformatie nog wel aan systemen als NGR doorgegeven. Dat is niet de bedoeling.

Wens is, dat als de brondata afwezig is (conform rapport geodata "brondata aanwezig" is NEE), dan die metainfo ook niet meer zichtbaar laten zijn in de webdav van het Geoportaal. 

Anders gezegd: de wens is dat als de brondata afwezig is, ook de xmls niet meer in de harvester te vinden zijn: ze moeten dus niet extern door NGR of anderen te harvesten zijn als die metainfo ontbreekt.

hangt samen met #563

**Comment by SandroNeumann** [comment]
We moeten de query die de uuid's aan de webdav levert aanpassen.

**Comment by gerardnienhuis** [comment]
Kan niet worden getest omdat wij geen toegang hebben tot acceptatieomgeving van NGR. We moeten aannemen dat als issue #563  is opgelost, dat dan ook de harvesting naar NGR goed gaat. Issue blijft daarom open staan tot na de productiegang van deze versie van het Geoportaal.

**Comment by gerardnienhuis** [comment]
Getest: data in geoportaal gezet: bleek in NGR te zien. Daarna weer xml verwijderd, is niet meer zichtbaar in Geoportaal daarna. En bij nachtelijke harvest van NGR blijkt ook daarna metadata uit NGR te zijn verdwenen: werkt dus.  Issue kan gesloten
