### ISSUE TITLE
Metainfo van laag niet meer zichtbaar als bronmetadata is verwijderd

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#565]
Nu is het zo, dat als de bronmetadata wordt verwijderd, de metadata nog wel zichtbaar is, als deze in de publicatieomgeving is gekoppeld of als er een service van is gemaakt. Dat wordt aangepast bij de nieuwe versie 1.3 van het Geoportaal. Zie ook #563 en #564 .

Maar bij de details van de metadata van een service, daar kunnen nog steeds de betreffende lagen zichtbaar zijn. 

nb: klikken op de link naar de metainfo van zo'n laag zal resulteren in een foutmelding, omdat die metadata in versie 1.3 is verwijderd. Dat werkt goed op de korte termijn. Verkeerde metainfo is niet meer zichtbaar.

Op de langere termijn zou je eigenlijk willen dat de link naar de metadata van zo'n verwijderde dataset ook niet meer zichtbaar is in het Geoportaal.

**Comment by gerardnienhuis** [comment]
Het gaat dus straks zo zijn, dat als brondata wordt verwijderd door beheerders, de metadata daarvan via het geoportaal (onderdeel home, uitgebreid zoeken en bladeren) niet meer vindbaar is.

we weten dat het via de link in de services (metadata) nog wel zichtbaar is, maar dat wordt pas opgelost in een latere versie, zie issue.....

**Comment by SandroNeumann** [comment]
Dit issue is toch juist bedoeld om het bij de service metadata weg te halen? De dataset metadata niet meer tonen was al gerealiseerd met #563.

**Comment by gerardnienhuis** [comment]
correct, mijn excuses. Bedoeling is bij dit issue dat ook de link vanuit de services niet meer zichtbaar is

**Comment by gerardnienhuis** [comment]
Gaan we testen door van een bestaande laag in een service de xml te verwijderen: gevolg moet zijn dat dan ook de laag niet meer vindbaar is bij de metainfo van de betreffende service.

**Comment by gerardnienhuis** [comment]
wordt getest in productie. Issue kan voor nu gesloten
