### ISSUE TITLE
Invulscherm voor beheerder bij nieuwe leverancier

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#566]
Nu moet bij iedere nieuwe leverancier van gegevens (statische kaarten) aan IDGis worden gevraagd of de persoon kan worden toegevoegd. Wens is dat zelf door de beheerders te laten doen. Vooralsnog dus alleen toevoegen van nieuwe leveranciers. Middels een apart invulformulier, alleen voor beheerders benaderbaar, bijvoorbeeld via een knop bij het onderdeel waar ook rapportages kunnen worden opgevraagd. Of via het nieuwe dashboard, als dat logischer is.

**Comment by gerardnienhuis** [comment]
Het blijkt toch vaker voor te komen dan bij de ontwikkeling van het Geoportaal was ingeschat. Issue van milestone 1.6 verplaatst naar 1.4. Moet tzt alsnog worden opgepakt.

**Comment by SandroNeumann** [comment]
Alleen formulier om een nieuwe leverancier/beheerder toe te voegen en **geen** lijst waar je alle leveranciers/beheerders kunt zien/aanpassen?

**Comment by gerardnienhuis** [comment]
goed idee, maar toevoegen is meest urgent. Aanpassen, inzien, verwijderen speelt veel minder vaak. Om kosten te besparen lijkt het zinvol om alleen voor toevoegen een formulier te maken.

**Comment by gerardnienhuis** [comment]
Het toevoegen van leveranciers blijkt goed te werken. Naam, email en wachtwoord worden correct verwerkt en het blijkt ook goed te werken als daarna met die nieuwe naam wordt ingelogged. Issue kan gesloten.
