### ISSUE TITLE
Monitoring van verbinding met provider mbv Nagios

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#569]
Mogelijke oplossing: Dashboard kunnen oproepen met un/pw in de url en vervolgens de response inspecteren zoals het check_wms command.

**Comment by SandroNeumann** [comment]
Er komt een json pagina waarmee je de status van de provider kunt uitlezen.

**Comment by gerardnienhuis** [comment]
Kan die json pagina dan ook toegankelijk gemaakt worden via het dashboard?

**Comment by SandroNeumann** [comment]
De linker kolom in het dashboard (de connectie met de provider databronnen) is waar de informatie uit deze pagina gepresenteerd zal worden.

**Comment by gerardnienhuis** [comment]
Kan pas getest worden als #571   is uitgerold. Kan bij deze versie gesloten.
