### ISSUE TITLE
Metainformatie blijft hangen in Geoportaal 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#570]
Wij hebben afgelopen weekend metadata aan het Geoportaal aangeboden. En op dezelfde dag ook weer verwijderd. Maar de metadata is nog steeds zichtbaar in het Geoportaal. Dat is niet de bedoeling. Het lijkt op een bug die we eerder hebben gezien, maar toen betreft het metadata waarvan al een laag in de publicatieomgeving zat. 

Let op. Dit betreft metadata van een dataset die **# NIET** in een service is opgenomen.

Details:

https://www.geoportaaloverijssel.nl/metadata/dataset/98a1a7cc-fc80-4ac2-a07f-3e702084f32e 

Bestandsnaam: TEST Gemeentegrenzen Overijssel

aangemaakt en ook weer verwijderd op 3 maart (zowel oracle dataset als xml uit geoweb folder verwijderd)

**Comment by gerardnienhuis** [comment]
Voorbeeld van issue waarbij metadata blijft hangen die WEL in een service is opgenomen:
https://github.com/IDgis/geoportaal-test/issues/563

**Comment by SandroNeumann** [comment]
Dit komt omdat er aan de dataset nog notificaties hangen, dat is vergelijkbaar met wanneer de dataset in een service zit. Dan wordt de dataset in de GeoPublisher niet verwijderd. Er worden notificaties aangemaakt op het moment dat er een nieuwe dataset is en wanneer een dataset verwijderd wordt. Dus aan deze dataset hingen twee notificaties.

Dit zal allemaal opgelost worden wanneer #563 is uitgerold.

Ik heb voor bovengenoemde dataset de notificaties weggeklikt, dus deze zal uit het Geoportaal verdwijnen.

**Comment by gerardnienhuis** [comment]
Zojuist gecontroleerd: bestand is niet meer zichtbaar in het externe Geoportaal. Issue kan gesloten.

**Comment by gerardnienhuis** [comment]
Dit moet natuurlijk nog wel op acceptatie getest worden, of het bij de volgende versie wel automatisch gaat. Daarom dit issue voor zekerheid weer geopend, zodat de test niet wordt vergeten.

**Comment by NicoEilers** [comment]
Zojuist één bestand verwijderd uit de geoweb-folder. Na +/- 1 uur was deze ook verwijderd uit het geoportaal.
Issue kan dus worden afgesloten.
