### ISSUE TITLE
Datum xml in webdav zelfde als update datum metadata ipv update datum bestand

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#575]
Er zijn minstens 3 soorten datum betrokken bij metadata en harvesting (door b.v. NGR). Wij stellen xml bestanden via webdav beschikbaar, en die xml's hebben een datum: 

**de xml file datum.**

Nu staan er in die xml's nog 2 andere datumvermeldingen;

1) **bestand update datum** (last revision date dataset)
2) **update datum van metadata** van dat bestand (last revision date metadata

De bedoeling is dat de xml dezelfde datum heeft als 2 (update datum van metadata).  Dus de datum van de xml file met gelijk zijn aan 2. 

Het lijkt er op dat de xml file datum gelijk is aan 1. Dat is niet correct. Dat moet goed uitgezocht worden, zeker omdat NGR ook kijkt naar de filedatum van de xml. Pas als die datum is aangepast, dan wordt de metadata in NGR aangepast (zo lijkt het nu).

Voorbeeld; als er een ander inhoudelijk contactpersoon is, bij een bestand uit 2000, dan blijft de update datum van het bestand gewoon 2000. Zelfs als die andere contactpersoon pas in 2018 in de metadata wordt gezet: beheerders passen die "publicatiedatum" van de metadata dus aan en niet de datum van het bestand zelf. Dat zou ook heel verwarrend zijn, omdat je dan na verloop van tijd niet meer echt weet van welke datum die bestanden zijn. En juist dat is erg belangrijke informatie.

**Comment by SandroNeumann** [comment]
De opmerking van @gerardnienhuis is correct. De datum van de dataset wordt als file datum doorgegeven. Dit moeten we aanpassen.

![webdav-list-ov-prod](https://user-images.githubusercontent.com/10757125/37763533-a5088500-2dbf-11e8-9e26-d73819b71446.png)

![md-datums-ov-prod](https://user-images.githubusercontent.com/10757125/37763538-a8f1aa98-2dbf-11e8-8603-89198877ae97.png)

**Comment by SandroNeumann** [comment]
![md-datums-ov-prod](https://user-images.githubusercontent.com/10757125/37968510-a357ce9c-31ce-11e8-814a-4c24eb5ddba6.png)

![webdav-list-ov-prod](https://user-images.githubusercontent.com/10757125/37968516-a895e4a2-31ce-11e8-9ede-b44434fee86c.png)

**Comment by gerardnienhuis** [comment]
blijkt goed te werken: update naar NGR werkt goed nu. Issue kan gesloten
