### ISSUE TITLE
Zoeken geodata, statische kaarten of services werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#576]
Dit hebben we in het verleden ook wel eens gehad. Je zoekt een term, waarvan je zeker weet dat het in de metainformatie staat (b.v. natuur) maar je vind geen enkel bestand als zoekresultaat. Dit lijkt voornamelijk op te treden bij statische kaarten. 

In het verleden was er sprake van een lijst of database die volliep. Nu kan het mogelijk ook te maken hebben met de updates van eerder deze week.

Het is heel onhandig als het zoeksysteem niet werkt. Wens is dat dit snel opgelost kan worden.

**Comment by SandroNeumann** [comment]
Lijkt inderdaad alleen bij statische kaarten op te treden. Ik heb de harvester van statische kaarten herstart en nu lijkt het weer normaal.

**Comment by gerardnienhuis** [comment]
Komt het vaker voor dat de harvester het niet doet? Moet dan die harvester voor statische kaarten ook niet in het dashboard? zie #568

**Comment by gerardnienhuis** [comment]
Probleem is opgelost, issue kan gesloten.

**Comment by gerardnienhuis** [comment]
probleem kwam zojuist weer voor, maar nu bij het zoeken naar geodatasets.  Zoeken naar trefwoorden gaf geen resultaat. aAntal geodatasets was 0 (bij alleen aanvinken geodatasets bij uitgebreid zoeken). 

Probleem bleek na een paar minuten weer opgelost.

Apart issue van maken? 

Zou het helpen als alle harvesters in het dashboard komen, dus ook die het zoeken regelen binnen het geoportaal?

**Comment by gerardnienhuis** [comment]
nu blijkt zoeken naar geodata wel goed te werken, maar ik heb maar 6 services ipv 147 (zie plaatje)
![services_6_stuks](https://user-images.githubusercontent.com/9005444/40411932-62f8a776-5e61-11e8-8b6b-f7db6ca5135e.jpg)
 en helemaal geen statische kaarten meer.

**Comment by gerardnienhuis** [comment]
en een minuut later (zonder verversen van cache oid): 
weer 147 services, en 2612 statische kaarten. de 1078 geodatasets waren er al. 
totaal aantal: 3837 (lijkt correct)

Tijdelijke verstoring, nu opgelost? (nb: intern geoportaal getest in Zwolle, provinciehuis, met IE-11).

**Comment by SandroNeumann** [comment]
Ik heb de harvesters voor de zekerheid net herstart, dat zou het weer stabiel moeten maken.

Mijn vermoeden is dat dit komt door het hoge aantal database transacties. Met name de harvester van de statische kaarten: elk kwartier zo'n 6000. Wanneer we de harvester slimmer maken en de wijzigingen bepalen i.p.v. alles steeds weer opnieuw invoeren denk ik dat dit probleem niet meer voorkomt.

**Comment by gerardnienhuis** [comment]
kan je niet de status "in archief" van de statische kaarten uitsluiten van harvesten? Of die alleen 1x per dag voor zekerheid. Scheelt 4300 van de 6000 statische kaarten in 1 klap.

**Comment by gerardnienhuis** [comment]
Nu lijkt alles inderdaad te werken weer

**Comment by gerardnienhuis** [comment]
helaas, uurtje later weer getest, werkt weer niet.

totaal is nu: 122
gis bestanden: 116
services: 6
statische kaarten: 0

**Comment by gerardnienhuis** [comment]
na middagpauze getest, lijkt nu wel weer te werken:

totaal: 3837
gisbestanden: 1078
services: 147
statische kaarten: 2612

**Comment by SandroNeumann** [comment]
Ik denk te weten wat hier speelt.

Alle data wordt wel goed opgehaald, maar voor het zoeken maken we gebruik van wat in database termen een "materialized view" heet. Dat is een tabel dat kijkt naar andere tabellen (in deze context kolommen in tabellen die voor het zoeken relevant zijn). Deze tabel is stabiel en wordt op bepaalde momenten vernieuwd. Dit gebeurt wanneer een harvester klaar is. Dat zijn er drie: eentje voor datasets, eentje voor services en eentje voor statische kaarten.

Nu viel me op in de data statistieken (die we sinds kort bijhouden voor het dashboard) dat de drie harvesters bijna op hetzelfde moment klaar zijn. De harvest actie voor jouw opmerking van 9:14 vanochtend:

1716 | dataset |         1078 |          752 | 2018-05-23 09:03:45.087
1715 | dc      |         2612 |          303 | 2018-05-23 09:03:38.544
1714 | service |          147 |           87 | 2018-05-23 09:03:18.427

De twee bovenste lopen enkel seconden uit elkaar.

Nu zou dit eigenlijk wel goed moeten gaan. Wanneer een materialized view bezig is komt er een lock op te staan, wat zou moeten betekenen dat de volgende refresh pas gedaan wordt als de vorige klaar is. Maar het lijkt er op dat hier iets mis gaat.

Ik voorzie een aantal mogelijke oplossingen:

- De drie harvesters niet tegelijkertijd starten, maar een aantal minuten er tussen laten. De meest simpele oplossing, maar niet de meest betrouwbare. Want aangezien de lengte van elke harvest actie niet gelijk is (service is korter dan statische kaarten) kan het op den duur weer een keer voorkomen dat de harvest acties tegelijkertijd eindigen.
- We zouden ook i.p.v. een interval (van een kwartier) met vaste tijden kunnen werken. Bijv. datasets worden elk uur om *:00 opgehaald, services elk uur om *:15 en statische kaarten elk uur om *:30. Dat maakt dat we dan ook van elk kwartier harvesten naar elk uur gaan.
- Niet meer drie verschillende harvesters hanteren, maar alles in eentje doen. Dat zou ik zelf erg onwenselijk vinden, want als er iets mis is met een bron dan wordt niks meer ververst. Nu zouden de andere twee gewoon doorgaan als er iets mis is met een harvester.
- De materialized view verversen uit de drie harvesters halen en daar een aparte service voor maken die ervoor zorgt dat elk kwartier een keer de view ververst wordt. Ik denk dat dit de beste optie is.

**Comment by SandroNeumann** [comment]
We hoeven geen aparte service voor te maken, het is afdoende om het in een crob job te zetten.

We denken hier zo'n 3-5 uur voor nodig te hebben.

**Comment by gerardnienhuis** [comment]
Bij testen geen problemen gevonden. Moet in productie bij langdurend gebruik blijken of probleem echt is opgelost. Issue kan vooralsnog gesloten.
