### ISSUE TITLE
Nedstat teller Overijssel onterecht op meerdere geoportalen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#578]
Ik zie bij de nedstat teller dat ik ook bezoek van Utrecht meegeteld krijg. Ik vermoed dat de nedstat teller ook daar op de homepagina staat. Dat moet natuurlijk niet. Ik zie dat bijvoorbeeld bij download via data.overheid, daar kom ik via nedstat terecht op de data die geleverd is door utrecht ipv Overijssel.

https://data.overheid.nl/data/dataset/vereenvoudige-bodemkaart-01

vervelende bug: nu krijg ik een onbetrouwbaar beeld in de teller: teveel bezoek dus.

wens is dat iedere organisatie zelf kan bepalen welk soort teller er op de pagina's komt te staan. nb: over enkele maanden werkt nedstat niet meer en zal een alternatief moeten worden gezocht.

**Comment by gerardnienhuis** [comment]
nog 1 gevonden: https://data.overheid.nl/data/dataset/rode-contouren

in ieder geval speelt dit bij de download pagina, omdat ik in Nedstat kan zien welke pagina's hiervoor bezocht werden, blijkt download te zijn.

**Comment by SandroNeumann** [comment]
Moet inderdaad de download-tool zijn, aangezien alleen jullie nog het Geoportaal hebben.

**Comment by gerardnienhuis** [comment]
is niet op acceptatie te testen: zal worden gecontroleerd in productiefase. Er is namelijk geen aparte teller op acceptatie aanwezig. Bij de productiefase moet alles goed werken. De teller moet dan zijn verwijderd uit de downloadpagina's van Utrecht en alleen de bezoekers van Overijssel moeten bij downloads geteld worden.

**Comment by SandroNeumann** [comment]
Dezelfde nedstat teller staat ook in acceptatie. Moet ie daar ook uitgezet worden?

**Comment by gerardnienhuis** [comment]
Wel die van Utrecht. 

Als in de acceptatieomgeving van Utrecht ook de nedstatteller van Overijssel staat, dan krijgen we daar mogelijk ook dubbeltellingen van. 

Ik wil graag dat alleen in de productieomgeving en de acceptatieomgeving van Overijssel de nedstatteller aanwezig is. Als deze teller ook staat in pagina's van andere gebruikers van de Geoportaal software, dan krijg ik in Overijssel teveel hits, wat de interpretatie van de resultaten onmogelijk maakt.

**Comment by SandroNeumann** [comment]
Ja, bij Utrecht acceptatie staat hij nu uit.

Hij staat trouwens ook aan in onze testomgeving. Daar zal ik 'm nog uitzetten.

**Comment by gerardnienhuis** [comment]
Wordt op productieomgeving van Utrecht opgelost. Kan dus pas na productiegang getest worden.

**Comment by gerardnienhuis** [comment]
Zojuist gecontroleerd, resultaat roept vragen op.
Productieversie uitgerold op 17 mei
Maar toch 18 mei meerdere downloads via Utrecht geregistreerd in Nedstat.
19 mei en later worden geen verkeerde downloads meer gevonden.

Hoe kan het toch op 18 mei zijn foutgegaan? Loopt er in Utrecht iets achter?
Of is de productieversie in Utrecht een dag later uitgerold?

details, zie hieronder:

metingen via nedstat, 18 mei: 

15:47:07
Weidevogelkerngebied
https://data.overheid.nl/data/dataset/weidevogelkerngebied-01
https://download.geodata-utrecht.nl/download/vector/8b1e13af-0a9e-4627-a746-7feaf48d5872

15:25:19
Natuurnetwerk Nederland 
https://data.overheid.nl/data/dataset/natuurnetwerk-nederland-01
https://download.geodata-utrecht.nl/download/vector/1ddb7003-28d7-4fbf-9d67-09ffe697a660

12:55:44
Signaleringskaart ext. veiligheid transp. en plasbrandaandachtsgebied spoor 
https://data.overheid.nl/data/dataset/signaleringskaart-ext-veiligheid-transp-en-plasbrandaandachtsgebied-spoor-01
https://download.geodata-utrecht.nl/download/vector/0da76eaa-49d9-4efc-a03e-b86ea4b69bde

12:08:41
Werklocaties - kantoren
https://data.overheid.nl/data/dataset/werklocaties-kantoren
https://download.geodata-utrecht.nl/download/vector/56f1f4bd-fd37-4520-831d-f5249d652764

Na 4 foutmetingen controle van 18 mei gestopt.

**Comment by SandroNeumann** [comment]
Bij Utrecht is de laatste versie 3 dagen geleden uitgerold.

**Comment by gerardnienhuis** [comment]
Raadsel is opgelost: productieversie is de 19 mei uitgerold in Utrecht. Vandaar dat de 18e nog fouten voorkwamen. Omdat na de 18e geen problemen meer gevonden zijn, is dit probleem nu opgelost en kan het issue gesloten.
