### ISSUE TITLE
invoer veel tekst in omschrijving kan niet opgeslagen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#58]
Als ik veel tekst in omschrijving probeer te zetten, dan kan ik wel de knop opslaan indrukken, maar er gebeurt verder niets. Opslaan blijkt ook na 3 minuten nog niet afgerond te zijn. Zie document met tekst die ik met Ctrl-A / Ctrl -C uit kladblok heb gekopieerd en met Ctrl-V in omschrijving heb neergezet
[lange_tekst_invoer_napoleon.txt](https://github.com/IDgis/geoportaal-test/files/140490/lange_tekst_invoer_napoleon.txt)

**Comment by SandroNeumann** [comment]
De limiet is rond de 100.000 tekens.

**Comment by gerardnienhuis** [comment]
lijkt me meer dan genoeg. Huidige vulling van statische kaarten is iets meer dan 2000 tekens, mogelijk bij geodatasets nog wat meer, maar zeker geen 10.000 tekens. 100.000 tekens lijkt me dan dus ook een prima bovengrens. Probleem is wel, dat je hier praktisch mee moet omgaan: teveel tekens zorgt wel voor extreme traagheid bij de browser. Waar de grens in de praktijk ligt, dat zal de praktijk wel uitwijzen. Issue kan dus gesloten worden, wat mij betreft.
