### ISSUE TITLE
Locatie naar K:\bab\geo-informatie\2018

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#581]
De locatie in het invoerscherm voor metadata van statische kaarten is nu default ingesteld op:

K:\bab\geo-informatie\2017\

dat moet worden

K:\bab\geo-informatie\2018\

De werking van dat invoerveld moet onveranderd blijven. Je moet het als leverancier of beheerder altijd nog kunnen aanpassen, indien nodig.

**Comment by SandroNeumann** [comment]
Is aangepast

**Comment by gerardnienhuis** [comment]
klopt, werkt nu goed, dank!
issue kan gesloten
