### ISSUE TITLE
Dubbele uuid's opnemen in rapport geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#582]
Soms komen dubbele uuid's voor in de metadata. Dat is ongewenst. In het rapport van geodatasets moeten 2 extra kolommen worden opgenomen:

eerste kolom: deze moet heten: "dubbele uuid": waarde is "nee" of "ja"
tweede kolom: deze moet heten: "aantal uuid": getal, getal van 1 of hoger

aantal situaties hierbij:

0: kan niet voorkomen, er is altijd een uuid
1: dan is er dus maar 1 uuid, correcte situatie, waarde "dubbele uuid" is dan dus  "nee"
2 of hoger; dan zijn er 2 of meer uuid's: niet juiste situatie, waarde "dubbele uuid" is dan dus "ja'

**Comment by SandroNeumann** [comment]
De informatie voor de tweede kolom hebben we op dit moment niet. Dat valt wel te maken, maar heeft meer impact.

**Comment by SandroNeumann** [comment]
We gaan dit in een aparte tabel opslaan, waar de bovengenoemde informatie wordt bewaard. Zie ook #584 

0 keer zou kunnen voorkomen op het moment wanneer de brondata is verwijderd, maar er nog een dataset of notificatie aan de brondataset is gekoppeld. Dan wordt ie als "verwijderd" gekenmerkt, maar het moment van verwijderen wordt uitgesteld tot dat alle koppelingen zijn weggehaald. Er komt dan geen uuid meer binnen, maar de brondataset is nog wel zichtbaar in de rapportage.

**Comment by gerardnienhuis** [comment]
Als er nu dubbele uuid's voorkomen, dan wordt bij de harvester al een actie uitgevoerd, zodat alleen de oudste dataset wordt meegenomen. Nieuwere datasets met dezelfde UUID worden niet geharvest en zullen dus ook niet in het Geoportaal zichtbaar zijn. En dus ook niet in de rapportage. Wel staat in de rapportage bij de oudste (eerste) geodataset dat er meer dan 1 keer een zelfde UUID voorkomt. Als beheerder kan je dan naar de map met xml's gaan en daar uitzoeken welke nu echt de dubbele datasets zijn. Meer elegante oplossing is het opslaan van ook de nieuwere gegevens, zoals naam en alternatieve titel van de datasets waarin dubbele UUID's voorkomen. Dat is uitgewerkt in een ander issue.

**Comment by gerardnienhuis** [comment]
gaat nog niet geheel goed. er is 1 record aangetroffen waarin niet 0, 1, 2 of een ander getal staat, maar een datum. gevonden is de waarde: 9-6-2017

**Comment by gerardnienhuis** [comment]
waarde 0 lijkt bijna correct, hier is ook altijd bronmetadata afwezig (12 records gevonden).
maar als je zoekt (filtert) naar waarde van bronmetadata aanwezig is "nee" dan vind je 13 records. Dat is vreemd, omdat dit altijd gelijke resultaten hadden moeten zijn. Veroorzaakt door de fout die hiervoor gevonden is (datum ipv 0, 1 of ander getal)? 

nb: 
waarde 1 komt meeste voor ; lijkt correct
waarde 2 komt ook 5 keer voor, wordt nog gecontroleerd, zou kunnen kloppen.

**Comment by SandroNeumann** [comment]
Waar zie jij die datum? Ik zie bij gevonden waardes alleen 0, 1 en 2.

![image](https://user-images.githubusercontent.com/10757125/40903650-57cb5c42-67d8-11e8-8595-df84aa48cfb5.png)

**Comment by gerardnienhuis** [comment]
lijkt nu volledig correct, datumveld kwam voor verkeerd ingelezen xls file.
issue kan gesloten.
