### ISSUE TITLE
Omgaan met dubbele uuid's in de GeoPublisher

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#584]
Er is een veld in de metadata van datasets waar een uuid in staat onder het pad:

``/MD_Metadata/identificationInfo/MD_DataIdentification/citation/CI_Citation/identifier/MD_Identifier/code/gco:CharacterString``

Dit veld is in de opgemaakte metadata te zien onder "details" en "Unieke identifier".

Dit veld wordt als identificatie gebruikt bij het doorsturen van de datasets van de provider naar de publisher. Mochten er essentiele eigenschappen zijn gewijzigd (naam, alternate_title, vertrouwelijk, etc) dan wordt een nieuwe versie aangemaakt. Mochten er twee metadata bestanden met hetzelfde uuid in dat veld zijn dan wordt binnen dezelfde harvest actie twee maal een nieuwe versie gemaakt, omdat telkens een wijziging wordt waargenomen (tenzij de bestanden voor de rest ook identiek zijn). 2 versies per harvest actie levert 48 versies per dag op en als er erg veel versies voor één dataset zijn maakt dat de queries traag.

We hebben daar een aanpassing voor gedaan dat als er in dezelfde harvest actie meer dan één keer dezelfde uuid binnenkomt alleen de eerste wordt verwerkt en er dan een notificatie wordt aangemaakt om de beheerder te informeren dat er een verdubbeling is waargenomen voor een dataset. Dit is op dit moment te zien op de acceptatie-omgeving:

![image](https://user-images.githubusercontent.com/10757125/39751894-03fc2f5c-52ba-11e8-9849-314c3648f48f.png)

Nu is dit iets waar niet André, maar de beheerders van het Geoportaal actie op moeten ondernemen. Dus is het zinvol om deze notificatie in de GeoPublisher te tonen of levert dat alleen maar ruis op?

**Comment by andreweijmer** [comment]
Ik wil in de publicatie-omgeving geen melding zien dat er dubbele uuids voorkomen. Het Geoportaal moet een melding aan de beheerder afgeven (eigenlijk niet accepteren dat er dubbele ids voorkomen.

**Comment by SandroNeumann** [comment]
De oplossingsrichting is dan om het niet als notificatie op te slaan, maar in een aparte tabel of kolom (dan kunnen we direct de informatie voor #582 daarin meepakken). Deze informatie wordt dan door het Geoportaal Dashboard opgevraagd.

Het lijkt me goed om dit dan nog in milestone 1.3.2 te doen. Niet het presenteren in het dashboard, maar wel de notificatie weghalen en het op een andere plek bewaren. Anders krijgt André in deze versie alsnog een ongewenste notificatie.

**Comment by gerardnienhuis** [comment]
gevolgen van deze aanpassing moeten in de publicatieomgeving worden getest.

**Comment by gerardnienhuis** [comment]
Blijkt goed te werken. Getest door 2 bestanden aan te bieden, met een andere naam en andere samenvatting, maar wel met zelfde UUID. Het blijkt dat het eerste bestand, wat is gepubliceerd, wel zichtbaar is in het Geoportaal. Maar het tweede bestand niet. Dat is dus nu correct opgelost. Hierdoor kunnen dubbele UUID's niet meer voorkomen. Issue kan gesloten.
