### ISSUE TITLE
In rapportage dubbele UUID's opnemen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#585]
Nu worden geodatasets door de harvester genegeerd, als ze een UUID hebben, wat al voorkomt. 

zie #582 

Maar omdat je als beheerder ook dit soort fouten wilt herstellen, is het handig als je ook naam en alternatieve titel van de geodatasets tot je beschikking hebt. Dat staat nu niet in het rapport van het Geoportaal, omdat geodata met dubbele UUID niet wordt verwerkt in de harvester. Het zou handig kunnen zijn om hier toch een overzicht van te krijgen, liefst in een goed leesbaar rapport (csv).

**Comment by SandroNeumann** [comment]
Dit staat al in het rapport geodata. Kolomnaam: "uuid_count"

**Comment by gerardnienhuis** [comment]
Testen loopt nog. 
uuid-count zit op vreemde plaats in rapport (tussen datum velden), moet tzt verplaatst worden.

waardes aanwezig: 0, 1 en 2. 
0: geen brondata aanwezig, lijkt correct
1: wel brondata, 1 uuid: lijkt correct
2: dubbele id: testen door metadata van willekeurig bestand andere id te geven.

**Comment by gerardnienhuis** [comment]
Gaan we testen door expres een dubbele uuid op te nemen in de metadata: dat moet dan in het rapport terug te vinden zijn.

**Comment by gerardnienhuis** [comment]
wordt getest in productie. issue kan gesloten
