### ISSUE TITLE
In het dashboard van het geoportaal staan bij service systeemtaken de naam van de service twee keer

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#586]

**Comment by gerardnienhuis** [comment]
Probleem lijkt nog niet opgelost: er wordt bij de telling van aantal veranderingen het cijfer 2 gegeven, terwijl er maar 1 service is aangemaakt. 

Deze is dan wel op staging en publicatie gezet, maar als gebruiker van het dashboard zie je het aantal (in plaatje extern 87 en intern 145 en dat zijn alleen de gepubliceerde services. Wens is dus dat bij de verschillen alleen de veranderingen mbt gepubliceerde services worden getoond.

 Staging is meer nodig voor beheerder publicatieomgeving, niet voor beheerder geoportaal.

zie ook plaatje:

![dashboard_zonder_overloop](https://user-images.githubusercontent.com/9005444/40959617-bdd73786-688c-11e8-9c59-660d2ed4aa79.jpg)

**Comment by SandroNeumann** [comment]
Dat is een ander punt.

Het issue hier was dat in de middelste kolom bij een service de naam van de service twee keer achter elkaar stond.

De verdubbeling bij aantallen services in de derde kolom komt omdat er en een WMS en een WFS service bij komt.

**Comment by gerardnienhuis** [comment]
klopt, probleem is opgelost: nu staat nog maar 1 keer de naam. issue kan gesloten
