### ISSUE TITLE
Toepassingsschaal en resolutie in rapport geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#587]
De wens is om ook toepassingschaal en resolutie in het rapport van geodatasets op te nemen. Het blijkt namelijk dat deze wel eens foutief worden ingevuld (moet handmatig). zie voorbeeld. Merk op: er zijn twee toepassingsschalen (van en tot) en ook twee resoluties (van en tot). Wens is deze alle 4 in het rapport op te nemen. 

De kolommen komen tussen de twee al bestaande kolommen temporele_dekking_tot en eigenaar_organisatie_1.

De nieuwe kolommen gaan heten: 

toepassingsschaal_van
toepassingsschaal_tot
resolutie_van
resolutie_tot

![toepassingsschaal_omgedraaid](https://user-images.githubusercontent.com/9005444/40177004-c53302cc-59cc-11e8-9f3c-4fa409143147.jpg)

**Comment by SandroNeumann** [comment]
Wat als er een keer 5 toepassingschalen/resoluties in de metadata staan? Is het niet beter om alle toepassingschalen/resoluties in één kolom weer te geven, afgescheiden door het '|' teken?

Dus dan worden het twee kolommen i.p.v. vier:

- toepassingschalen
- resoluties

**Comment by SandroNeumann** [comment]
Na telefonisch contact met @gerardnienhuis is besloten dat het de volgende kolommen worden:

- toepassingsschaal_van (eerste gevonden toepassingsschaal)
- toepassingsschaal_tot (tweede gevonden toepassingsschaal)
- toepassingsschalen (alle toepassingsschalen afgescheiden door het '|' teken)
- resolutie_van (eerste gevonden resolutie)
- resolutie_tot (tweede gevonden resolutie)
- resoluties (alle resoluties afgescheiden door het '|' teken)

**Comment by gerardnienhuis** [comment]
nb: uitgezocht: schaal mag 2 keer voorkomen, letterlijke tekst bij toelichting 

https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#toepassingsschaal
5.2.21 Toepassingsschaal
identificationInfo[1]/*/spatialResolution/*/equivalentScale/*/denominator[ISO 19139:2007]
Dit element is conditioneel. Het element is verplicht als er een toepassingsschaal gespecificeerd kan worden en het element resolutie niet voorkomt. Het element bevat de schaal die aansluit bij de nauwkeurigheid waarmee de dataset is ingewonnen en vastgelegd. Voor een dataset met afwijkingen van 100 meter is dat 1:100000. Het element kan twee keer voorkomen, hiermee wordt een interval aangegeven. Deze dient vanuit de klasse spatialResolution te worden aangemaakt.

**Comment by SandroNeumann** [comment]
De resolutie kolommen gaan heten:
- resolutie_x (eerste gevonden resolutie)
- resolutie_y (tweede gevonden resolutie)
- resoluties (alle resoluties afgescheiden door het '|' teken)

**Comment by gerardnienhuis** [comment]
info staat op juist plaats in rapport. steekproeven laten zien dat schaal correct is ingevuld (te zien bij home in stylesheet metadata). Ook resolutie klopt, te zien in de xml, b.v.:

<spatialResolution>
<MD_Resolution>
<distance>
<gco:Distance uom="m">100</gco:Distance>
</distance>
</MD_Resolution>
</spatialResolution>

gevonden in:
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/b23366ad-6669-4bae-a1d4-eb85e9de55fc
Bestandsnaam: Schadebeeld Afwateringskanaal Marsweg

issue kan gesloten
