### ISSUE TITLE
selecteren en verwijderen levert 0 records op

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#59]
Dit is een fout, lijkt alleen op te treden bij "verwijderen" knop indrukken. Ik kies leverancier "Nienhuis" en als zoektekst "test". Dat levert een aantal kaarten op, die ik aanvink (alles tegelijk, door box aan te vinken): de selectie werkt: alle kaarten hebben nu vinkje ervoor. Maar als ik "verwijderen" knop indruk, dan krijg ik melding dat ik 0 records ga verwijderen. Fout, ik heb er wel degelijk een paar geselecteerd.

bevinding testen 23-2-16
![bug_selectie_0_records](https://cloud.githubusercontent.com/assets/9005444/13245047/9eee421e-da0a-11e5-8d42-fe9e7cb59dbd.jpg)

**Comment by gerardnienhuis** [comment]
let op: als ik daarna, na die acties, met vinkje de selectie weer ga op heffen, dan zie ik nergens vinkjes meer: dat is correct. Maar druk ik dan knop verwijderen in, dan krijg ik melding dat ik 10 records ga verwijderen. zie plaatje: ook dat is niet correct natuurlijk. Als ik niets geselecteerd heb, dan wil ik niets verwijderen.
![bug_selectie_10_records](https://cloud.githubusercontent.com/assets/9005444/13245107/25e75f80-da0b-11e5-9b10-565bed036ba8.jpg)

**Comment by SandroNeumann** [comment]
Gerelateerd aan: IDgis/geoportaal-test#61
Gerelateerd aan: IDgis/geoportaal-test#64

**Comment by gerardnienhuis** [comment]
getest, werkt nu goed, issue kan gesloten
