### ISSUE TITLE
Dashboard geeft 502 error en start niet op; Probleem met PID file

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#590]
22-5-2018, 8.38 uur: dashboard is niet bereikbaar via productie

locatie: provinciehuis Zwolle, browser: IE 11.0.50

meerdere keren getest, laatste test 9.08 uur (zelfde resultaat)

knop in https://admin.geoportaaloverijssel.nl/
gaat naar https://dashboard.geoportaaloverijssel.nl/

maar dan krijg je foutmelding (502 proxy error):

Proxy Error

The proxy server received an invalid response from an upstream server.
 The proxy server could not handle the request GET /.

Reason: DNS lookup failure for: por.dashboard

Apache/2.4.18 (Ubuntu) Server at dashboard.geoportaaloverijssel.nl Port 443

**Comment by SandroNeumann** [comment]
Normaal wanneer een applicatie even down is wordt deze automatisch weer herstart, maar bij het dashboard lukt dat op dat moment niet vanwege een bestand dat vervolgens al bestaat. We moeten dit configureren zodat dit bestand niet wordt aangemaakt en dan lukt het herstarten vervolgens wel.

Nu werkt het weer, maar dit moeten we in elk geval in 1.3.3 meenemen.

**Comment by gerardnienhuis** [comment]
9.18; opnieuw getest, nu ook met Firefox. Zowel IE als FF blijken weer te werken.

**Comment by gerardnienhuis** [comment]
Probleem kan terugkomen. Als het te vaak gebeurd, dan een bugfix versie overwegen.

**Comment by gerardnienhuis** [comment]
issue lijkt niet voor te komen. Kan gesloten worden.
