### ISSUE TITLE
CC-Mark licentie onterecht NEE

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#591]
Er is in het rapport van geodatasets een vermelding of creative commons MARK aanwezig is in de metadata. In dat rapport lijkt het bij minstens 1 datasets fout te gaan. Bij nazoeken zijn niet heel snel andere fouten gevonden op dit punt. Onduidelijk is, waarom het nu bij dit record wel fout gaat. Kan dit wijzen op meer situaties die nu fout zijn aangegeven in het rapport?

Bij de other_constraints staat "Geen beperking|http://creativecommons.org/publicdomain/mark/1.0/deed.nl"
maar in het rapport staat bij cc_mark "Nee". Dat had "ja" moeten zijn

title: Bladindeling topografische kaart 1 op 50.000
id in rapport: 56

**Comment by SandroNeumann** [comment]
Er wordt gekeken of onder other_constraints **precies** de waarde "http://creativecommons.org/publicdomain/mark/1.0/deed.nl" voor komt. In het voorbeeld hierboven staan twee spaties achter de url, waardoor de conditie in het "Nee" blok terecht komt. We moeten eerst alle spaties om de waarde heen eraf halen.

**Comment by gerardnienhuis** [comment]
-	B7.Gemgrens_CC_mark (b7/b75)
Betreft een nieuw bestand met in de gebruiksbeperking: openbaar bestand zijn niet eigendom van de provincie dus CC-mark
Achter de url zijn 2 spaties toegevoegd.


Deze gaat wel goed, spaties worden nu genegeerd

issue kan gesloten

**Comment by gerardnienhuis** [comment]
het lijkt er op alsof dit issue weer is teruggekomen. Het probleem is dat er 81 datasets zijn op productie die bij de kolommen "cc_by" en ook "cc_mark" en ook "cc_zero" de waarde "Nee" hebben terwijl in de de kolom "other_constraints" wel een licentie staat vermeld (https://creativecommons... enz). 

 Dit is onjuist: als er 1 van de 3 licentiesoorten staat bij "other_constraints" dan moet dat ook in de kolommen cc_by, cc_mark of cc_zero vermeld worden.

**Comment by SandroNeumann** [comment]
Bij welke dataset is het fout?

**Comment by SandroNeumann** [comment]
Ik zie wat het probleem is. De url's zijn naar https gegaan en wij checken nog op http (althans voor mark en zero). Ik zal het protocol onderdeel van de url negeren.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, getest door selecties uit te voeren op kolommen MARK, ZERO en BY: blijkt correcte selecties te leveren (als MARK is ja, dan is rest nee, enz). Ook handmatige steekproeven laten zien dat alles nu correct werkt. Issue kan gesloten.
