### ISSUE TITLE
CC-By in rapport metadata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#594]
Naast de licentiemogelijkheden CC-Mark en CC-Zero komt er ook een CC-By (dat is openbare data met verplichting tot delen van naam bronhouder). 

Ik wil ook graag als dat komt, dit in het rapport van metadata terug laten komen. Voorstel is om een kolom te krijgen in het rapport voor Geodata, voor de kolommen CC-Mark en Zero.

Naam: CC-By

url waar  op moet worden getest is: https://creativecommons.org/licenses/by/4.0/deed.nl

**Comment by gerardnienhuis** [comment]
dit werkt nog niet goed: 

-	B7.Gemgrens_CC_By (b7/b75)   
Betreft een nieuw bestand met in de gebruiksbeperking:  gebruik van bronvermelding dus CC-By

laat wel zien bij other_constraints dat CC-BY wel goed is ingevuld
waarde is:
Verplicht gebruik van bronvermelding|http://creativecommons.org/licenses/by/4.0/deed.nl

maar bij cc_by staat NEE ipv JA

**Comment by SandroNeumann** [comment]
Er wordt gecheckt op de https url en niet op de http url, die werd hier eerder genoemd. Veranderen naar http?

**Comment by gerardnienhuis** [comment]
verstandiger om van https uit te gaan. 
Wij hebben de test niet goed gedaan en proberen het opnieuw.

**Comment by gerardnienhuis** [comment]
getest: werkt nu goed met https
issue kan gesloten
