### ISSUE TITLE
nedstat teller

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#6]
wens is om een nedstat teller te kunnen gaan gebruiken, vanaf het eerste gebruik van het Geoportaal. Als het mogelijk is, dan ook gebruik van download en stylesheets monitoren. Teller komt uiteindelijk zowel op extern als intern Geoportaal: 2 soorten tellers dus. Dit staat los van de overige documentatie en rapportagevormen.

**Comment by HermanAssink** [comment]
Gerard, waarom nedstat? Nedstat is een verouderde oplossing die zo te zien is vervangen door http://www.motigo.com/nl_NL/main#head. 
Welke output verwacht je zoal? Wij gebruiken standaard AWStats om te rapporteren over het gebruik, zie bijv. http://server-a.inspire-provincies.nl/awstats/awstats.pl?config=protectedsites.
Zullen we AWStats implementeren?

**Comment by gerardnienhuis** [comment]
Besproken met Herman, gisteren. Nu eerst Nedstat gebruiken en later heroverwegen of verder tellers optimaliseren (is apart issue aangemaakt hiervoor). 

Let op: nedstat tellers voor stylesheets lijken niet zinvol, maar voor 3 andere plekken wel:
1) interne geoportaal (user interface voor zoeken, alleen intern)
2) externe geoportaal (als 1, maar dan extern)
3) downloadscherm

code voor tellers wordt als zip toegevoegd en verzonden

nb: tellers moeten al in acceptatieversies in gebruik worden genomen heeft voordeel dat getest kan worden of ze ook werken

**Comment by gerardnienhuis** [comment]
Hieronder de 3 stukjes code (tussen --- ) die nodig is voor het tellen van het gebruik van de pagina's met Nedstat. 

nb: vormgeving van dit issue is wat afwijkend, mogelijk doordat de code wordt gebruikt. Code is goed zichtbaar als je dit issue gaat editen. Voor zekerheid ook code als txt bestand toegevoegd.

---

## code voor tellen gebruik openen scherm Geoportaal Extern



<script language="javascript" type="text/javascript">

</script>

<noscript>
<img src="http://m1.nedstatpro.net/nl/nedstatpro.gif?name=provinci18_1" width="1" height="1" align="right" alt="" />
</noscript>



# 

# code voor tellen gebruik openen scherm Geoportaal intern



<script language="javascript" type="text/javascript">

</script>

<noscript>
<img src="http://m1.nedstatpro.net/nl/nedstatpro.gif?name=provinci18_2" width="1" height="1" align="right" alt="" />
</noscript>



# 

# code voor tellen gebruik openen scherm DOWNLOAD



<script language="javascript" type="text/javascript">

</script>

<noscript>
<img src="http://m1.nedstatpro.net/nl/nedstatpro.gif?name=provinci18_3" width="1" height="1" align="right" alt="" />
</noscript>



# 

[nedstat_tellers.txt](https://github.com/IDgis/geoportaal-test/files/262762/nedstat_tellers.txt)

**Comment by SandroNeumann** [comment]
In de download zit nu ook de nedstat implementatie.

**Comment by gerardnienhuis** [comment]
tellers werken naar tevredenheid, issue kan gesloten worden
