### ISSUE TITLE
Dashboard teller op 0

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#601]
Er is iets vreemds met het dashboard. Mogelijk een bug. Alle veranderingen stonden op 0, maar nu ik 1 statische kaart heb toegevoegd, staan de veranderingen van statische kaarten opeens op -8. Wat is hier aan de hand? Zijn de gegevens door een ander proces gereset?

zie plaatje:

![dashboard_alles_0](https://user-images.githubusercontent.com/9005444/41335231-9c187cbc-6ed7-11e8-81c1-8a13f33a6d46.jpg)

**Comment by SandroNeumann** [comment]
Kan het niet zijn dat een andere beheerder een aantal kaarten uit publicatie heeft gehaald?

**Comment by gerardnienhuis** [comment]
zou heel vreemd zijn, als alles op 0 staat. Maar wordt verder getest. De onderste -8 zou kunnen omdat het niet opviel de eerste keer en de info net onder het scherm viel. Testen met geodata en statische kaarten is gestart.

**Comment by gerardnienhuis** [comment]
statische kaarten lijkt weer goed te werken: aantal updates wordt verwerkt

**Comment by gerardnienhuis** [comment]
ook geodata werkt nu goed, blijkbaar geen probleem meer. issue kan gesloten
