### ISSUE TITLE
Rechten vd Anker bij statische kaarten 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#607]
Reinier vd. Anker heeft nu rechten als beheerder. Het is de bedoeling dat hij de "gewone" rechten van een leverancier krijg, voor statische kaarten.

**Comment by SandroNeumann** [comment]
Is aangepast

**Comment by gerardnienhuis** [comment]
gebruiker gevraagd te testen

**Comment by gerardnienhuis** [comment]
issue kan gesloten, Reinier werkt niet meer bij de provincie (pensioen)
