### ISSUE TITLE
9 geselecteerd maar volgens scherm 0 verwijderd

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#61]
Als ik 9 records selecteer (met vinkje) en daarna op verwijder druk, dan krijg ik melding dat ik 0 records ga selecteren. Dat klopt niet, ik ga er 9 verwijderen (denk ik).
![bug_0_verwijderd_9_geselecteerd](https://cloud.githubusercontent.com/assets/9005444/13249194/28eaf51c-da23-11e5-8685-59d51ad3107d.jpg)

**Comment by SandroNeumann** [comment]
In hoeverre is dit een ander issue dan IDgis/geoportaal-test#59?

**Comment by gerardnienhuis** [comment]
Ik kan deze vraag niet goed beantwoorden: het lijkt er op alsof selecteren, daarna filteren en aanvinken (of andersom in volgorde) niet juiste resultaat oplevert.
Ik denk dat we dat ook eerder al gevonden hebben, voor deze test serie: mogelijk nog niet opgelost punt dus

Nu wacht ik even met verder testen van de 2 selectiemogelijkheden

Van: SandroNeumann [mailto:notifications@github.com]
Verzonden: dinsdag 23 februari 2016 11:59
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard)
Onderwerp: Re: [geoportaal-test] 9 geselecteerd maar volgens scherm 0 verwijderd (#61)

In hoeverre is dit een ander issue dan IDgis/geoportaal-test#59https://github.com/IDgis/geoportaal-test/issues/59?

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/61#issuecomment-187652702.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---
