### ISSUE TITLE
Rapportage/Statistieken WMS/WFS-requests

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#611]
Om te analyseren wat gebruik is, statistieken per laag, op ieder moment.

**Comment by gerardnienhuis** [comment]
Kijken of methode van provincie Utrecht bruikbaar is, en wat voor en nadelen zijn van dit rapport tov rapport "download". Daarna eventueel methode Utrecht ook bij rapporten opnemen.

**Comment by SandroNeumann** [comment]
We zijn voor de provincie Utrecht met een maat-oplossing waar we de log informatie in een database wegeschrijven en daar queries op kunnen doen. Dat is een betere oplossing en maakt awstats feitelijk overbodig. Dit komt tzt beschikbaar en maakt dit issue overbodig. We kunnen dit nog telefonisch bespreken.

**Comment by gerardnienhuis** [comment]
dit klinkt als een nuttig rapport. Onderzoeken of dit in volgende versie van geoportaal kan worden meegenomen. Omdat tool van Utrecht nog niet klaar is, nu niet in dit issue meenemen.

**Comment by SandroNeumann** [comment]
Net met @gerardnienhuis afgesproken dat we de voorgenoemde wens van Utrecht realiseren en deze maand ook aan Overijssel opleveren, inclusief de issues van 1.5.2 die al gerealiseerd zijn.

**Comment by SandroNeumann** [comment]
In de opdracht van Utrecht tonen we alleen de requests op de lagen (wms/wfs). Jullie willen meer requests zien? Daar zouden we dan nog een aparte rapportage voor kunnen maken en vervolgens in dit issue oppakken.

**Comment by gerardnienhuis** [comment]
hoe kan het dat er lege cellen zijn bij de kolom "layers"?
Er is wel request, maar geen layer? Kan dat of rapport fout, zie


22-2-2019 | acc-services | /geoserver/b82_volkshuisvesting/wms | getcapabilities |   | 6
-- | -- | -- | -- | -- | --
22-2-2019 | acc-services | /geoserver/b82_volkshuisvesting/wfs | getfeature |   | 6
17-1-2019 | acc-wmsonly-services | /geoserver/b41_bodem_alleen_wms/wms | getcapabilities |   | 1

**Comment by SandroNeumann** [comment]
Alleen bij getmaps zijn layers ingevuld.

**Comment by gerardnienhuis** [comment]
statuscode opnemen ook 200,404 loggen in rapport en in kolom erbij met goed of fout 400, 401 enz

**Comment by gerardnienhuis** [comment]
dus 2 kolommen erbij

**Comment by gerardnienhuis** [comment]
Ik neem aan dat er 2 urls zijn? Eén voor acceptatie en de andere voor productie? De acceptatieversie in ieder geval voor zekerheid nog een keer via mail opsturen, zodat ik zeker weet dat ik de juiste url test.

**Comment by gerardnienhuis** [comment]
statuscode en goed/fout zijn in rapport aanwezig. 2 urls ontvangen: 1 voor acceptatie en 1 voor productie. Acceptatieversie blijkt goed te werken, issue kan gesloten.
