### ISSUE TITLE
Aantal bijlagen vermeld in rapport statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#618]
Bij statische kaarten wordt vaak meer dan 1 bijlage bijgevoegd. Wens is om het aantal bijlagen ook in het rapport statische kaarten te laten terugkomen. 

Kolomnaam: count_attachment
plaats kolom: tussen attechment en attechment_size_in_mb

**Comment by NicoEilers** [comment]
In de rapportage van overige dataset is nu het veld 'count_attachment' te vinden.
In dit veld is het aantal bijlages te vinden die aan de metadata van een statische kaart zijn toegevoegd.

Issue kan worden gesloten.
