### ISSUE TITLE
0 records verwijderen met knop uitvoeren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#63]
Als je niets selecteerd, dan kan je wel knop "verwijderen" indrukken: je krijgt dan scherm dat je 0 
records gaat verwijderen. Knop verwijderen is ook in te drukken. Liever had ik een waarschuwing gekregen bij 0 records: U heeft geen records geselecteerd. Deze actie kan nu niet worden uitgevoerd. Met daaronder slechts 1 knop: de knop "Annuleren"

gevonden test 23-2-16

![wens_0_selectie_verwijderen](https://cloud.githubusercontent.com/assets/9005444/13249728/39d5eeec-da26-11e5-9e64-25b69bfa3833.jpg)

**Comment by gerardnienhuis** [comment]
Is nu wel opgelost bij verwijderen, maar werkt nog niet goed bij de statusveranderingen: als ik niets selecteer, dan kan ik knop concept, publiceren etc indrukken, maar ik krijg geen waarschuwing. Wens is om het niet alleen bij verwijderen zo te laten werken, maar ook bij de andere knoppen.

merk op: bij de knop verwijderen werkt het nu wel al goed, zie plaatje. Bij de overige knoppen werkt het nog niet goed.

![0_records_statusverandering](https://cloud.githubusercontent.com/assets/9005444/14138569/29efa716-f66e-11e5-8dd4-37103aeb2de4.jpg)

**Comment by gerardnienhuis** [comment]
is zelfde als https://github.com/IDgis/geoportaal-test/issues/73 ?
als dat zo is, dan samenvoegen?

**Comment by SandroNeumann** [comment]
Dat is inderdaad hetzelfde issue. Ik zou #73 sluiten, aangezien de titel van #63 concreter is.

**Comment by gerardnienhuis** [comment]
werkt nu goed
