### ISSUE TITLE
Herzien NGR en Atlas header kolommen rapportages

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#631]
De rapportages zijn niet logisch opgezet, hierdoor moet je onnodig zoeken. Titels zijn in Nederlands en Engels en volgorde van kolommen is niet altijd begrijpelijk. Dit is ontstaan omdat er steeds extra functionaliteit aan de rapportages is toegevoegd, zonder de structuur nader te controleren.

**Comment by gerardnienhuis** [comment]
Vooral de opties: In NGR en In Atlas zijn een lastige.
Deze graag aanpassen
Nu heb je een soort dubbele ontkenning, wat lastig is om te interpreteren.

Kolommen moeten gaan heten: In NGR en In Atlas

Staat er" mag niet in NGR" dan moet er "nee" staan bij In NGR
Staat dat er niet, dan "ja"

Staat er "mag niet in Atlas" dan moet er "nee" staat bij In Atlas
Staat dat er niet, dan "ja"

**Comment by SandroNeumann** [comment]
Zijn de NGR en Atlas kolommen de enige die aangepast moeten worden in dit issue of komen er meer?

**Comment by gerardnienhuis** [comment]
Er komt nu niet meer bij die issue.
Op dit moment zijn het de enige die last veroorzaken door de dubbele ontkenning. Daarom nu alleen deze aanpassen.

**Comment by gerardnienhuis** [comment]
Blijkt goed te werken. Gecontroleerd door alle 4 de mogelijkheden in rapport te controleren (wel niet Atlas en wel niet NGR). Issue kan gesloten.
