### ISSUE TITLE
Bij details van geodataset naam en volgorde urls overzichtelijker maken

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#632]
Op basis van https://github.com/IDgis/geoportaal-test/issues/358

Weergave van urls in details is door extra toevoegingen een rommelig geheel geworden. 

Vooral lastig dat je niet weet of het een WFS of WMS betreft, en ook "website" is verwarrend, want eigenlijk is het een link naar de viewer. Voorstel volgorde is: (let op witruimtes):

Download: https://acc-download.geoportaaloverijssel.nl:443/download/vector/bb4372ab-968e-4701-9235-4c56098f33da
 Website: https://acc-services.geodataoverijssel.nl:443/viewer/layer/B14_bestuurlijke_grenzen/B1_Gebiedsindeling_op_grond_van_de_wet_gemeenschappelijke_regelingen_lijn
 Dataset metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da
 Service metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/service/113a778c-514a-4daa-b9ad-ed1373159a47
 Service metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/service/8dcf22ab-c59d-47e3-bc5a-7df39cfa4e91
 OGC:WFS: https://acc-services.geodataoverijssel.nl:443/geoserver/B14_bestuurlijke_grenzen/wfs
 OGC:WMS: https://acc-services.geodataoverijssel.nl:443/geoserver/B14_bestuurlijke_grenzen/wms
 ArcGIS Rest: https://acc-arcgisrest.geodataoverijssel.nl:443/rest/services/B14_bestuurlijke_grenzen/FeatureServer
 XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da?noStyle=true

wordt:

Dataset metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da
 Download: https://acc-download.geoportaaloverijssel.nl:443/download/vector/bb4372ab-968e-4701-9235-4c56098f33da
 Viewer: https://acc-services.geodataoverijssel.nl:443/viewer/layer/B14_bestuurlijke_grenzen/B1_Gebiedsindeling_op_grond_van_de_wet_gemeenschappelijke_regelingen_lijn

1 regel wit <<<<

Dataset metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da
 WFS metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/service/113a778c-514a-4daa-b9ad-ed1373159a47
 WMS metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/service/8dcf22ab-c59d-47e3-bc5a-7df39cfa4e91

1 regel wit <<<<

OGC:WFS: https://acc-services.geodataoverijssel.nl:443/geoserver/B14_bestuurlijke_grenzen/wfs
 OGC:WMS: https://acc-services.geodataoverijssel.nl:443/geoserver/B14_bestuurlijke_grenzen/wms
 ArcGIS Rest: https://acc-arcgisrest.geodataoverijssel.nl:443/rest/services/B14_bestuurlijke_grenzen/FeatureServer

1 regel wit <<<<

XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da?noStyle=true

**Comment by SandroNeumann** [comment]
Onder milestone 1.3.4?

**Comment by gerardnienhuis** [comment]
excuses, zoals besproken pas in volgende versie, vooralsnog 1.5.

**Comment by SandroNeumann** [comment]
De dataset metadata url staat in het voorstel 2x (in de eerste twee alinea's de eerste regel). Dat is het idee of is dat een foutje?

**Comment by gerardnienhuis** [comment]
was typfout, tweede moet weg:

wordt:

Dataset metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da
Download: https://acc-download.geoportaaloverijssel.nl:443/download/vector/bb4372ab-968e-4701-9235-4c56098f33da
Viewer: https://acc-services.geodataoverijssel.nl:443/viewer/layer/B14_bestuurlijke_grenzen/B1_Gebiedsindeling_op_grond_van_de_wet_gemeenschappelijke_regelingen_lijn

1 regel wit <<<<

WFS metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/service/113a778c-514a-4daa-b9ad-ed1373159a47
WMS metadata url: https://acc-www.geoportaaloverijssel.nl:443/metadata/service/8dcf22ab-c59d-47e3-bc5a-7df39cfa4e91

1 regel wit <<<<

OGC:WFS: https://acc-services.geodataoverijssel.nl:443/geoserver/B14_bestuurlijke_grenzen/wfs
OGC:WMS: https://acc-services.geodataoverijssel.nl:443/geoserver/B14_bestuurlijke_grenzen/wms
ArcGIS Rest: https://acc-arcgisrest.geodataoverijssel.nl:443/rest/services/B14_bestuurlijke_grenzen/FeatureServer

1 regel wit <<<<

XML: https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/bb4372ab-968e-4701-9235-4c56098f33da?noStyle=true

**Comment by SandroNeumann** [comment]
is duplicaat van #459, na overleg wordt deze gesloten
