### ISSUE TITLE
Download link onjuist aanwezig bij Alleen WMS

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#633]
Fout gevonden in extern geoportaal.

Er is bij de metainformatie (onderdeel WAT) een downloadlink aanwezig, maar dat hoort niet als de service "alleen WMS is".  Je krijgt dan een foutmelding als je er op klikt.

Het probleem lijkt zichtbaar in het Geoportaal,  bij alle Alleen WMS services.
zie plaatje:

![fout_download_link_alleen_wms](https://user-images.githubusercontent.com/9005444/45134524-3d391b00-b19b-11e8-88e6-ec0378c551f2.jpg)

**Comment by gerardnienhuis** [comment]
zie:

https://www.geoportaaloverijssel.nl/metadata/dataset/456ce3e0-b471-4110-87f2-7b5d5ef5a3d9
Bestandsnaam: Beperkte versie van de Basisregistratie Kadaster BRK (zonder NAW gegevens).

fout is:
Forbidden
You don't have permission to access /download/vector/456ce3e0-b471-4110-87f2-7b5d5ef5a3d9 on this server.
Apache/2.4.18 (Ubuntu) Server at intern-download.geoportaaloverijssel.nl Port 443

**Comment by gerardnienhuis** [comment]
Hadden we een vergelijkbaar issue al eens niet eerder gehad? Is de bug weer teruggekomen? Simpelweg gezegd: als er staat Alleen WMS dan moet er geen WFS zijn, en ook mogelijk links naar download nooit voorkomen. Want: geen WFS, dan ook geen download.

Lijkt op gesloten issue: https://github.com/IDgis/geoportaal-test/issues/269

**Comment by SandroNeumann** [comment]
We hebben de check in de metadata stylesheet gemaakt voor de lijst van urls onder 'details', maar niet bij de download link onder 'wat'. Dat moeten we implementeren.

**Comment by gerardnienhuis** [comment]
Getest, werkt nu goed. Enkele steekproeven uitgevoerd. De download link bij het onderdeel WAT is nu afwezig. Zie bijvoorbeeld: 
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/50be3081-dd4f-4013-a61c-68bff6c702be
issue kan gesloten.

**Comment by gerardnienhuis** [comment]
dit probleem lijkt teruggekomen te zijn, zie:
https://www.geoportaaloverijssel.nl/metadata/dataset/456ce3e0-b471-4110-87f2-7b5d5ef5a3d9
bij het onderdeel "DETAILS" staat een download link die ook aanklikbaar is: je komt dan in een download scherm. 
Goede nieuws is dat download niet werkt, maar je zou dan ook bij de details geen link moeten zien.

**Comment by gerardnienhuis** [comment]
Dit issue onterecht weer geopend. Het probleem is zelfde als #269. Daarom #269 weer geopend en dit issue opnieuw gesloten.
