### ISSUE TITLE
Fout verkeerde slashes apart in rapport metadata van geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#637]
Nu wordt in het rapport metdata van geodata een \ in een url gezien als een fout, en ook in de kolom met fouten vermeld. Dat is verwarrend. Wens is om deze (technische) fout in een aparte kolom weer te geven en niet te vermelden in de kolom waar het nu in staat.

Nieuwe kolom gaat heten: slashfout en bevat de exacte url waarin deze \ voorkomt

**Comment by SandroNeumann** [comment]
Welke kolom is dit nu?

**Comment by SandroNeumann** [comment]
Graag nog op bovenstaande vraag reageren.

**Comment by gerardnienhuis** [comment]
de kolom heet nu: invalide_urls

Bedoeling is dat een beheerder kan controleren of alle urls nog kloppen. Dat kan nu niet, omdat er urls staan die gewoon benaderbaar zijn via internet.

In de huidige kolom staan nu alle fouten, maar sommige urls zijn niet echt "fout". Deze urls zijn gewoon benaderbaar, maar doordat er een \ ipv een / in staat, is dit formeel fout. Een beheerder wil echter niet de formele fout zien, maar alleen de praktische "echte" fouten.

Wens is dat er 2 kolommen komen:

invalide_urls_totaal:  laten staan zoals het nu is (dus totaal van fouten, alleen naam kolom anders)
invalide_urls_fout: hier alleen de echte fouten, dus negeren of er \ of / staat

**Comment by SandroNeumann** [comment]
Deze kolommen bestaan al (wel onder een andere naam):
- verkeerde slashes zijn "invalide_urls"
- url's die geen goede response opleveren zijn "http_errors_urls"

**Comment by gerardnienhuis** [comment]
mooi, dan stel ik voor om t.z.t. de namen van de kolommen aan te passen, maar nu geen verdere actie uit te voeren voor dit issue. We gaan eerst testen of we hier mee uit de voeten kunnen.

**Comment by gerardnienhuis** [comment]
Issue kan gesloten omdat functionaliteit al aanwezig was.
