### ISSUE TITLE
Interne url service moet niet in extern Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#646]
Als je in het externe Geoportaal bij de details van het bestand "eeuwenoud" bos kijkt, dan valt het op dat dit bestand via 2 services wordt ontsloten: alleen wms en volledig openbaar. 

zie: 
https://www.geoportaaloverijssel.nl/metadata/dataset/7b93abb6-f91b-47e0-a5ea-8e93b0552e2f 

Mogelijk is dat een fout gemaakt door een beheerder in de publicatieomgeving. 

Dat moet geen probleem zijn, normaal gesproken... 
Maar onwenselijk is het dat de interne url ook zichtbaar is. zie plaatje.

Als je er op klikt dan volgt een foutmelding: 

Forbidden You don't have permission to access /metadata/service/9c7f9ecb-cf7c-48ea-b814-520746157423 on this server. Apache/2.4.18 (Ubuntu) Server at intern.geoportaaloverijssel.nl Port 443

Wens is dat in het externe Geoportaal geen interne urls zichtbaar zijn.

![interne_service_url](https://user-images.githubusercontent.com/9005444/47214429-3575b480-d39e-11e8-8f0c-8189fc0eac2b.jpg)

**Comment by gerardnienhuis** [comment]
als de laag het kenmerk "alleen wms" heeft, dan moet alleen die info getoond worden, alsof de laag in 1 service is gezet, namelijk de "alleen wms" service. Dit geldt voor het externe Geoportaal.

Dus, onafhankelijk of een laag in een openbare service wordt gezet: er moet alleen de "wms" links getoond worden. Dus niet de wfs en ook niet de interne links.

In het interne geoportaal kan alles gewoon getoond worden.

**Comment by SandroNeumann** [comment]
We hebben hier te maken met de rariteit van vertrouwelijk + wmsonly. In dat geval is de service wel publiek beschikbaar, maar alleen als wms. Kortom, de service metadata is wel gewoon publiek. We zouden i.p.v. de interne link ook de publieke link in dat geval kunnen genereren (i.p.v. geheel weghalen).

Begrijp ik het goed dat als de dataset wmsonly is je alleen wmsonly service links wilt zien, ook als de dataset in een andere omgeving zit?

**Comment by gerardnienhuis** [comment]
Ziet er nu goed uit. Eeuwenoud bos gekeken, zowel intern als extern: bij details staan nu correct maar 2 services. De interne url ontbreekt. Issue kan gesloten
