### ISSUE TITLE
Niet in Atlas en niet in NGR opnemen geodata rapportage

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#651]
Er zijn 2 nieuwe beperkingen in gebruik. Dit zijn:
Niet in Atlas
Niet in Nationaal Georegister

Wens is deze ook in de rapportage van geodata terug te laten komen.

opnemen als aparte kolom, vergelijkbaar met Geoportaal extern
na de kolom data_publiek 2 kolommen toevoegen

namen: 
niet_in_Atlas
Heeft de waarde "Ja" als in beperkingen de tekst "niet in Atlas opnemen" aanwezig is
anders is de waarde "Nee"

niet_in_NGR
Heeft de waarde "Ja" als in beperkingen de tekst "niet in Nationaal Georegister opnemen" aanwezig is
Anders is de waarde "Nee".

**Comment by SandroNeumann** [comment]
Moet dit hoofdlettergevoelig zijn of juist niet?

**Comment by gerardnienhuis** [comment]
De exacte teksten zijn:

Mag niet in Nationaal Georegister
Mag niet in Atlas van Overijssel

**Comment by gerardnienhuis** [comment]
Eerste testen zien er goed uit. Twee kolommen zijn aanwezig op juiste plaats. Inhoud is "Nee". Nog te testen als inhoud "Ja" moet worden.

**Comment by gerardnienhuis** [comment]
Werkt goed, getest op ja in "mag niet in Atlas" en "mag niet in NGR": blijkt goed te werken. 

Issue kan gesloten. 


Hieronder enkele testresultaten.

Niet in Atlas is ja (1 gevonden)
Gemeentegrenzen, openbare data met CC mark
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/07b468df-3579-4b2f-9239-b8693dc522c5
bij details: Gebruiksbeperkingen: Mag niet in Atlas van Overijssel


In rapport: niet_in_ngr is ja (2 gevonden):

TEST Gemeentegrenzen ivm oplevering 1.3.2
bij details staat: Gebruiksbeperkingen: Mag niet in Nationaal Georegister
Gemeentegrenzen, openbare data met CC mark (20-01-2015, Provincie Overijssel)
bij details staat: Gebruiksbeperkingen: Mag niet in Nationaal Georegister
