### ISSUE TITLE
Alle gegevens organisaties en personen in rapport geodata opnemen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#652]
Nu zijn niet alle gegevens van organisaties en contactpersonen in het rapport van geodata opgenomen.
Wens is dat ze allemaal worden opgenomen.

Dus alle gegevens van de betreffende organisatie en persoon opnemen, niet een selectie.

Voorbeeld:
Distributeur van het bestand
Naam: Provincie Overijssel
Website: https://www.overijssel.nl
Naam: team Beleidsinformatie
Rol: beheerder
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: Nederland

Kolomnamen en volgorde van kolommen wordt bij dit voorbeeld:

Naam_organisatie_1 
Rol_organisatie_1
Website_organisatie_1
Naam_contactpersoon_1
Rol_contactpersoon_1
Email_contactpersoon_1
Adres_contactpersoon_1
Postcode_contactpersoon_1
Plaats_contactpersoon_1
Provincie_contactpersoon_1
Land_contactpersoon_1

Nu is aanwezig contact 1 en 2, daar komen er nog 4 bij.

**Comment by SandroNeumann** [comment]
Wil je altijd al deze kolommen (6x) en wanneer er minder contactgegevens zijn zijn de kolommen leeg?

**Comment by gerardnienhuis** [comment]
ja, graag altijd die kolommen en leeglaten als ze afwezig zijn

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Er komen nu veel kolommen bij waardoor het genereren van de rapportage geodata te lang duurt en er met een timeout uitklapt. We kunnen die timeout verhogen, maar een mooiere oplossing is om het structureel op te lossen. Ik denk dat dit een uurtje of 3 zal kosten. Dit valt echter eigenlijk buiten deze opdracht. Hoe sta jij hierin?

**Comment by gerardnienhuis** [comment]
Ik zal voor de structurele oplossing een nieuw issue in github aanmaken. Ik neem aan dat de oplossing er dan voor zorgt dat het maken van het rapport weer sneller gaat?
Mijn voorstel voor nu is om de time out te vergroten, zodat het nieuwe rapport niet er uit klapt. Het rapport wordt wel vaak gebruikt, maar als wij als beheerders weten dat het wat langer duurt dan gewoonlijk, dan hoeft dat nu geen probleem te zijn

**Comment by gerardnienhuis** [comment]
namen organisaties en personen zijn terug te vinden in het rapport. Dat lijkt allemaal te kloppen. Enkele details moeten nog nagezocht.

Opmerkelijk: 
in de stylesheet bij het onderdeel WIE staan ook termen die niet in het rapport terug te vinden zijn:

Beheerder van het bestand
Auteur bestandsbeschrijving
Distributeur van het bestand

zie bijvoorbeeld: 
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/b7a36899-ebe5-4ba1-b926-31b9ef54c87b

@SandroNeumann : enig idee hoe dat kan? Is dat een bug of zijn we die termen vergeten te vragen bij dit issue?

**Comment by SandroNeumann** [comment]
Dat is de rol van de organisatie. Die staat in de header van de contactgegevens, i.p.v. als element daaronder. De rol van de organisatie staat in het rapport.

**Comment by gerardnienhuis** [comment]
Gaat gedeeltelijk goed. Er is in het rapport nu extra ruimte gemaakt voor de info van 6 organisaties en contactpersonen (te zien aan de extra items in de header). Items en volgorde zijn ook correct. Maar nog niet alle gegevens worden correct ingevuld in het rapport. Bij een steekproef blijkt dat de helft van de items niet in het rapport zijn terug te vinden. Er staat wel info in het Geoportaal, maar dus niet in het rapport. Zie onderstaand voorbeeld:

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/7050618c-fc4a-4703-903a-9e1bdb7b98d5


Bestandsnaam: TEST Gemeentegrenzen ivm oplevering 1.3.2



Teruggevonden in rapportage
2 onderdelen uit WIE in metadata:


Beheerder van het bestand 


Eigenaar van het bestand 


Niet teruggevonden in rapportage:
2 onderdelen die ook bij WIE staan bij metadata

Auteur bestandsbeschrijving
Distributeur van het bestand

Volledige metadata bij dit bestand van deze 2 onderdelen:



Auteur bestandsbeschrijving
Naam: Provincie Overijssel
Website: www.overijssel.nl
Naam: team Beleidsinformatie
Rol: beheerder
E-mail: beleidsinformatie@overijssel.nl
Adres: Postbus 10078
Postcode: 8000 GB
Plaats: Zwolle
Provincie: Overijssel
Land: The Netherlands


Distributeur van het bestand
Naam: Provincie Overijssel
Website: www.overijssel.nl
Naam: team Beleidsinformatie

**Comment by SandroNeumann** [comment]
Ja, dat zijn andere metadata elementen. Ik kan deze dan nog toevoegen onder het kopje:

auteur_bestandschrijving_*
distributeur_*

**Comment by gerardnienhuis** [comment]
Na overleg met @SandroNeumann 

De volgorde wordt in rapportage wordt:
eerste set gegevens is van: auteur van de metadata
tweede set gegevens is van: distributeur
overige sets is van : contact1, 2, 3 en 4 (maximaal 4, in praktijk wordt nooit meer dan 4 ingevuld)

voorbeeld:

https://www.geoportaaloverijssel.nl/metadata/dataset/3aa4ddee-1362-4f56-8020-a259767cfaae
Bestandsnaam: Deltaplan Agrarisch Waterbeheer (Maaivelddaling)

in xml:<contact>
voorbeeld: CharacterString>Provincie Overijssel</gco:CharacterString>
Dit is de auteur van de metadata

<distributor>
voorbeeld: gco:CharacterString>Waterschap Drents Overijsselse Delta</gco:CharacterString>
Dit is distributeur

<pointOfContact>
voorbeeld: <gco:CharacterString>Waterschap Drents Overijsselse Delta</gco:CharacterString>
is contactpersoon, meerstal meerdere

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Het is aangepast en staat op acceptatie.

**Comment by gerardnienhuis** [comment]
Het werkt goed. Zojuist getest met aantal steekproeven en door controle van kolommen met contactgegevens. Voorbeelden hieronder. 

Issue kan gesloten


details controles, 2 voorbeelden:

Eerste voorbeeld:
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/fad3457d-da7c-470a-bb10-5ef67c87d708
Bestandsnaam: Risico op ondergrondverdichting in Nederland

in metadata stylesheet:
Eigenaar van het bestand
Naam: Alterra Wageningen UR
heet in rapport:
bron_naam_organisatie_1 = Alterra Wageningen UR
bron_rol_organisatie_1 = Eigenaar

in metadata stylesheet:
Auteur bestandsbeschrijving
Naam: Alterra
heet in rapport:
auteur_metadata_naam_organisatie: Alterra
auteur_metadata_rol_organisatie: eigenaar

in metadata stylesheet:
Distributeur van het bestand
Naam: Alterra
heet in rapport:
distributeur_naam_organisatie: Alterra
distributeur_rol_organisatie: Distributeur





Tweede voorbeeld:

Bestandsnaam: Natura 2000-gebieden in Nederland
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/2101e166-89d7-433c-ace3-2c67ff63b62f

Stylesheet:
Eigenaar van het bestand
Naam: Ministerie van Economische Zaken - Directie Natuur & Biodiversiteit
rapport:
bron_naam_organisatie_1: Ministerie van Economische Zaken - Directie Natuur &amp; Biodiversiteit
bron_rol_organisatie_1 = Eigenaar

in metadata stylesheet:
Auteur bestandsbeschrijving
Naam: Ministerie van Economische Zaken - GIS Competence Center
in rapport:
auteur_metadata_naam_organisatie: Ministerie van Economische Zaken - GIS Competence Center
auteur_metadata_rol_organisatie: Auteur

in metadata stylesheet:
Distributeur van het bestand
Naam: Publieke Dienstverlening op de Kaart (PDOK)

in rapport:
distributeur_naam_organisatie: Publieke Dienstverlening op de Kaart (PDOK)
distributeur_rol_organisatie: Distributeur

**Comment by gerardnienhuis** [comment]
Laatste controle uitgevoerd met extra invoer van contactpersonen.
Blijkt toch nog niet goed te werken, de volgorde in rapport is niet altijd correct.


https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/7050618c-fc4a-4703-903a-9e1bdb7b98d5

in rapportage lijkt het er op alsof gegevens van contactpersoon 5 en 6 verwisseld zijn
bij contactpersoon 5 is geen adres en postcode aanwezig, bij 6 wel, in de stylesheet van het Geoportaal
Maar in het rapport is dat net andersom

zie voorbeeld hieronder info uit onderdeel WIE van stylesheet bij testbestand.

Merk op:nb: dit is gecontroleerd met invoermodule Geosticker, waar deze info op zelfde manier in staat:
conclusie: metainfo bij WIE klopt, maar rapport klopt niet


Correct is:

Gebruiker van het bestand 

Naam: Provincie Overijssel; eenheid Publieke Dienstverlening

Website: www.overijssel.nl

Naam: Anker, Dhr. Reinier van den

Rol: eigenaar

E-mail: RJ.vd.Anker@overijssel.nl


Inwinner van het bestand 

Naam: Provincie Overijssel; eenheid Publieke Dienstverlening

Website: www.overijssel.nl

Naam: Bakker, Dhr. Sietze

Rol: eigenaar

E-mail: S.Bakker@overijssel.nl

Adres: Postbus 10078

Postcode: 8000 GB

Plaats: Zwolle

Provincie: Overijssel

Land: The Netherlands


in rapport staat bij vd Anker (contact 5) meer info (adres, postcode enz) dan bij Bakker.
Moet net andersom zijn.

**Comment by SandroNeumann** [comment]
Ik heb de volgorde gedaan zoals hierboven stond:

- auteur bestandsbeschrijving
- distributeur
- bronhouders (4x)

In de stylesheet is de volgorde anders. Daar worden eerst de bronhouders getoond, dan de auteur bestandsbeschrijving en dan de distributeur.

**Comment by gerardnienhuis** [comment]
volgorde klopt wel, maar vulling niet
bij contact 6 staat deel van de vulling van contact 5, dat lijkt onjuist

**Comment by gerardnienhuis** [comment]
Blijkt nu wel goed te werken. Getest met 2 datasets, waarin 4 contactpersonen aanwezig waren. 1 van beide testsets had bij contactpersoon 4 onvolledige informatie. Het blijkt nu allemaal correct in het rapport te komen. Issue kan weer gesloten.
