### ISSUE TITLE
Code voor Google analytics op iedere pagina metadata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#662]
Een eerste pragmatische benadering van tellen van gebruik van het geoportaal heeft er voor gezorgd dat er een google analytics teller op de homepagina staat. En op nog enkele andere pagina's. 
zie ook: https://github.com/IDgis/geoportaal-test/issues/598

Wens is om ook het gebruik van de stylesheets van individuele datasets te tellen. 

Dus voor al het gebruik van de stylesheets voor metadata van geodata, statische kaarten en services.

**Comment by gerardnienhuis** [comment]
er lijkt nu geen onderscheid gemaakt tussen interne en externe bezoekers, daarna graag op interne pagina's een andere code dan op de externe pagina's

**Comment by SandroNeumann** [comment]
duplicaat van #699

**Comment by gerardnienhuis** [comment]
is dubbel, wens staat ook in #699. Dit issue is daarom gesloten.
