### ISSUE TITLE
Aantal NGR ook opnemen in dashboard

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#668]
in het huidige dashboard staat alleen hoeveel datasets extern en intern beschikbaar zijn. Het aantal beschikbaar voor het NGR staat er niet in.  Wens is om het dashboard op dit punt uit te breiden, zie plaatje, bij (1). 

Omdat de lijst wel erg lang wordt, dreigt de info mbt statische kaarten (intern) niet meer zichtbaar te zijn (loop onder van scherm af). Het idee is om de lichtblauwe headers kleiner (minder hoog te maken). Tekst aanpassen.

Was:
Connectie GeoPublisher met gegevensbronnen van provider 
wordt:
Connectie GeoPublisher

Was: '
Laatste 10 systeemtaken GeoPublisher 
wordt
Systeemtaken GeoPublisher

Was:
Aantal datasets, services en statische kaarten in Geoportaal
wordt:
Aantal in Geoportaal
![dashboard_wensen](https://user-images.githubusercontent.com/9005444/49794288-8323f300-fd37-11e8-8b74-e51ae012960c.jpg)

**Comment by SandroNeumann** [comment]
Het minder hoog maken van de headers is niet echt nodig, want er komt in het geval het niet op 1 pagina past gewoon een scrollbar.

**Comment by gerardnienhuis** [comment]
ivm impact verplaatst naar milestone 1.5.2.

**Comment by SandroNeumann** [comment]
duplicaat van #696

**Comment by gerardnienhuis** [comment]
vergelijkbaar, bijna dubbel met #696. Dit issue is daarom gesloten.
