### ISSUE TITLE
Tekst aanpassen homepagina Geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#670]
Tekst op de homepagina is al paar jaar oud. Verzoek om dit te veranderen

is nu:

Geef je mening over het Geoportaal. Wat zou je graag willen? Meer services, meer bestanden of iets heel anders? Dit is je kans om je mening te geven. Met jouw hulp kunnen we het Geoportaal nog beter maken. Vul de korte vragenlijst in. Het kost slechts enkele minuten en het is nog leuk ook. Klik hier voor de vragenlijst.

wordt:

In het Geoportaal van Overijssel vindt u kaarten (pdf's), ruimtelijke (GIS) bestanden en services. Het beheer van data en de bijbehorende beschrijvingen wordt regelmatig uitgevoerd. Hieronder staan de meest actuele datasets. U kunt nu meteen beginnen met zoeken.  Bij "uitgebreid zoeken" of "bladeren" vindt u nog meer zoekmogelijkheden.

(en dan bij klikken op uitgebreid zoeken of bladeren naar het betreffende tabblad gaan)

**Comment by SandroNeumann** [comment]
Aanpassing moet gedaan worden in het deploy script en niet in de programmatuur.

**Comment by gerardnienhuis** [comment]
Ziet er goed uit. Tekst is correct overgenomen en doorklikken werkt ook. Issue kan gesloten worden.
