### ISSUE TITLE
Mogelijkheid om leveranciers te archiveren

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#672]
De wens is er om leveranciers uit de lijst (zoeken en aanpassen) te kunnen halen, maar de naam te bewaren om in een later stadium te koppelen aan metadata documenten in een nog te implementeren metadata veld.

**Comment by SandroNeumann** [comment]
Een kolom toevoegen aan de gebruikerstabel. Wanneer deze kolom de waarde 'true' heeft is de gebruiker niet actief, kan de gebruiker niet inloggen en komt de gebruiker ook niet voor in de dropdown lijstjes. Maar de naam van de gebruiker staat nog altijd in de database, waardoor deze in het toekomstige metadata veld alsnog ingevuld kan worden.

**Comment by SandroNeumann** [comment]
Op de volgende manier geïmplementeerd:

- een kolom 'archived' aan de gebruikerstabel toegevoegd
- wanneer de gebruiker 'archived' is wordt deze uit de dropdown lijsten gehaald en kan deze gebruiker tevens ook niet inloggen
- om de metadata documenten van deze gebruiker alsnog te kunnen vinden kan er in het vrije tekstveld op de naam van de gebruiker gezocht worden

**Comment by gerardnienhuis** [comment]
opzet lijkt goed, maar is alleen te testen door leverancier op archived te zetten. Voorstel is op leveancier "Nienhuis" op archived te zetten. Nu zijn er 11 records die horen bij leverancier Nienhuis. Die zouden dan door zoeken op Nienhuis wel nog vindbaar moeten zijn. Let op: er zijn nu 12 records (dus geen 11) die vindbaar zijn als Nienhuis in vrije tekst veld wordt gezocht. Deze 12 moeten dus ook nog steeds terugvindbaar zijn, ook als Nienhuis "archived" is.

**Comment by SandroNeumann** [comment]
De gebruiker 'Nienhuis' is gearchiveerd.

**Comment by gerardnienhuis** [comment]
Dit blijkt goed te werken. Effect is dat "Nienhuis" ook niet meer kan inloggen. Getest met archiveren van andere gebruiker (Maarse) geeft ook aan dat het goed werkt: alle statische kaarten van Maarse zijn terug te vinden door zoeken in vrije tekst, maar hij picklists (keuzelijsten) voor aanpassen leverancier of selecteren van statische kaarten is de naam Maarse niet meer terug te vinden. Omdat het goed werkt kan dit issue gesloten worden.
