### ISSUE TITLE
Geopackage exporteren

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#673]
Nu kan je wel bestanden als shape enz exporteren. Wens is om ook het modernere formaat geopackage te exporteren, naast de al aanwezige formaten. nb: alleen als WFS bestaat. 

Je hebt dan niet alleen de data, maar ook de kleurweergave en andere styling. Deze zou mogelijk afgeleid  kunnen worden uit de WMS.

**Comment by gerardnienhuis** [comment]
zie ook https://www.geopackage.org/

**Comment by SandroNeumann** [comment]
Hiervoor moet de GeoServer geopackage plugin geïnstalleerd worden en de download-tool moet uitgebreid worden met een extra output format.

**Comment by gerardnienhuis** [comment]
optie geopackage is inderdaad zichtbaar in download scherm, alleen volgorde is niet meer correct alfabetisch. Er staat nu:

SHP    Geopackage    CSV    DXF    GeoJSON    GML 2.1    GML 3.2    KML  

Dat moet worden:

SHP    CSV    DXF    GeoJSON    Geopackage    GML 2.1    GML 3.2    KML

**Comment by gerardnienhuis** [comment]
Test geslaagd: eeuwenoud bos als geopackage opgeslagen en daarna in Qgis als vectorlaag zonder problemen ingelezen. kaartbeeld ziet er goed uit, issue kan gesloten.
