### ISSUE TITLE
Te lange zoekterm geeft error

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#68]
Te lange zoekterm geeft error als op zoeken wordt geklikt.

Als voorbeeld is geprobeerd te vinden:

Hierbij is het van belang te weten wat er getest gaat worden (het testobject), de eisen, (de testbasis), wanneer er getest gaat worden en hoe er getest gaat worden (methode).

Deze tekst staat in de omschrijving van 1 van de succesvol opgeslagen velden aanwezig. Maar je kan dus niet op die tekst zoeken. Misschien dat de beperking er is: meer dan 5 zoektermen gaat fout? Moet wel meer duidelijk worden, wat beperkingen zijn aan in te voeren tekst. Bij te veel tekst moet waarschuwing komen, en niet een crash, zoals nu.

**Comment by SandroNeumann** [comment]
Gereproduceerd. Komt niet door het aantal zoektermen, maar door de haakjes.

**Comment by gerardnienhuis** [comment]
lijkt nu goed te werken, issue kan gesloten
