### ISSUE TITLE
Leverancier Storm opnemen 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#684]
Michelle van der Storm  als leverancier van statische kaarten opnemen:

M.vd.Storm@overijssel.nl

**Comment by SandroNeumann** [comment]
Ze was al toegevoegd in issue #671

**Comment by gerardnienhuis** [comment]
goed opgemerkt, ik zal haar vragen te testen of alles werkt.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
