### ISSUE TITLE
Reimert als leverancier statische kaarten toevoegen 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#685]
email: ea.reimert@overijssel.nl
naam: Ellis Reimert

graag toevoegen als leverancier van statische kaarten

**Comment by SandroNeumann** [comment]
De gebruiker is toegevoegd.

**Comment by gerardnienhuis** [comment]
gebruiker gevraagd om te testen

**Comment by gerardnienhuis** [comment]
Ik heb niets meer van gebruiker terug gehoord maar verwacht niet dat er problemen zijn. Dit issue kan gesloten. 

nb: er is nu een module waarin beheerders zelf leveranciers kunnen toevoegen. Omdat deze module goed werkt, ga ik er van uit dat vragen zoals in dit issue niet meer nodig zijn.
