### ISSUE TITLE
datum en tijd in rapportage filenaam

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#686]
Nu hebben rapportages een bestandsnaam waarin de datum maar niet de tijd verwerkt is. Bovendien is de datum van een onhandig format. Wens is om zowel datum als tijd (uren en minuten) in filenaam terug te laten komen. Merk op: dus datum in format: jjjj-mm-dd ipv zoals het nu is: jjjjmdd

Een rapport met downloadresultaten heet nu:

rapport_download_2019319.csv

als voorbeeld: dit bestand is aangemaakt op 9.18 uur

Een download rapport wordt dan:

rapport_download_2019_03_19_09_18.csv

**Comment by SandroNeumann** [comment]
Voorstel:

nieuwe bestandsnaam formaat: rapport_download_2019-03-19_09-18.csv

Op die manier houd je de datum en tijd beter uit elkaar.

**Comment by gerardnienhuis** [comment]
prima voorstel, zo wordt het nog leesbaarder.

**Comment by gerardnienhuis** [comment]
lijkt goed te werken, voorbeeld rapport geodata:
rapport_geodata_2019-05-07_10-43.csv (is inderdaad aangemaakt op 10.43 uur, op 7-5-2019)

**Comment by gerardnienhuis** [comment]
Ook de overige rapporten hebben zelfde opbouw van naam: alle rapporten zijn zojuist aangemaakt en gecontroleerd.

Dit werkt goed, issue kan gesloten.

**Comment by gerardnienhuis** [comment]
blijkt toch een onhandigheid te zijn: tijdstip in de naam wordt niet als 24 uur maar als 12 uur notatie geschreven. Wens is dat 15.00 uur ook echt 15.00 uur is, ipv 03 uur.

voorbeeld (rapport gemaakt op 15 uur 52 minuten):

is nu:
rapport_geodata_2019-05-22_03-52.csv

wordt:
rapport_geodata_2019-05-22_15-52.csv

**Comment by gerardnienhuis** [comment]
impact moet opnieuw ingeschat worden, label nu verwijderd

**Comment by SandroNeumann** [comment]
is duplicaat van #695

**Comment by gerardnienhuis** [comment]
Werkt goed. Uitgetest door voor en na 12 .00 uur een rapport van geodata te maken. Tijden zijn correct in de filenamen opgenomen. Ter controle ook de overige 3 rapporten getest (na 12 uur): ook deze tijden zijn nu correct. Voorbeeld: rapport_dublincore_2019-08-06_14-12.csv is nu inderdaad 12 over 2 (in de middag). Issue kan gesloten.
