### ISSUE TITLE
Noorloos beheerder statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#687]
Roderick Noorloos heeft al rechten als leverancier van statische kaarten. Wens is dat hij ook beheerdersrechten krijgt voor dit onderdeel. Hij moet dus ook statische kaarten kunnen beheren (publiceren, aanpassen, verwijderen enz).

zie #667

**Comment by SandroNeumann** [comment]
De gebruiker heeft beheerder rechten.

**Comment by gerardnienhuis** [comment]
Zojuist getest: Roderick blijkt inderdaad als beheerder te kunnen inloggen. Heeft zojuist succesvol enkele testbestanden verwijderd. Alles werkt goed. Issue kan dus gesloten
