### ISSUE TITLE
Zoekmethode moet beter uitgelegd

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#69]
Het is niet geheel helder hoe het zoeken werkt, als je meerdere zoektermen gebruikt:

zoek naar "test 23" geeft 3 resultaten:
test 11 23-2-16
Test 4 23-2-16
Test 1 23-2-16

maar zoek "test 16" geeft 1 resultaat:
test 2 22-2-16

Hoe kan dat? is zoeken hoofdlettergevoelig? Of wordt de 16 alleen herkend in speciale gevallen? Welke dan? Ik had verwacht dat zoeken op "test 16"in dit geval meer ipv minder resultaten zou opleveren.

En waarom vind ik '"Natura 2000-gebieden" wel en niet"
Natura 2000-geb"

**Comment by SandroNeumann** [comment]
Bij het zoeken worden woorden terug gebracht tot de stam. Waardoor alle woorden die van de stam afgeleid zijn het record vinden. Natura 2000-gebied levert dus bijvoorbeeld wel een resultaat op. Een woord als "geb" is geen officieel woord waardoor hij een exacte match met "geb" probeert te vinden en die is er niet.

M.b.t. het voorbeeld met test 23 en test 16: je zoekt op een deel van een datum. Een datum wordt gesplitst in drie delen. 23-2-16 wordt in 23, -2 en -16 gesplitst. Vandaar dat 23 een match vindt en 16 niet, want daar staat dat streepje voor. De vraag is of een deel van een datum een relevante zoekopdracht is, want als je op 23-2-16 zoekt wordt er wel een match gevonden.

**Comment by gerardnienhuis** [comment]
lijkt me heel verwarrend voor gebruikers: als je dus hondenhok hebt opgenomen in de tekst, en je zoekt op hok, dan vind je niets? maar je vind wel iets als je honden of hond gaat zoeken?

**Comment by SandroNeumann** [comment]
Elk woord wordt als geheel behandeld. In dit geval vind je alleen iets wanneer je op hondenhok of hondenhokken zoekt.

**Comment by gerardnienhuis** [comment]
Op zich wel lastig, deze zoekmethode. Maar omdat meestal alleen op id of teksten in titel wordt gezocht, lijkt me dit wel werkbaar. Zoeken met \* als wildcards kan dus niet meer, begrijp ik?

**Comment by gerardnienhuis** [comment]
blijkt geen bug te zijn (label kan hier verwijderd). Besloten is dat huidige zoekmethode eerst in praktijk wordt geprobeerd. Verandering van zoekmethode is nu niet voorzien, mogelijk als het in de praktijk echt te onhandig blijkt voor gebruikers (niet bij huidige versie dus). Issue ook dubbel opgevoerd, lijkt op #82.

**Comment by gerardnienhuis** [comment]
lijkt naar tevredenheid te werken, issue kan gesloten

**Comment by gerardnienhuis** [comment]
Zoeken werkt toch nog verwarring, omdat resultaten tegenstrijdig lijken. Hieronder 1 voorbeeld met toelichting, waarin lijkt dat zoeken bij 2 termen op verschillende manier wordt afgehandeld.

issue is weer geopend

Naam statische kaart: Hardlooproute Uelsen

https://acc-admin.geoportaaloverijssel.nl/metadata/1912cf13-75e9-43f7-91fd-dd0ca5726996

Hardlooproute   geeft wel kaart bij zoekresultaten

hard        geeft wel kaart
hardloo     geeft wel kaart

hardloop    geeft geen kaart
hoe kan dat?

werkt blijkbaar anders dan bij zoekterm Ethiopië 

Ethiopië   geeft wel kaart bij zoekresultaten
 Ethi       geeft wel kaart bij zoekresultaten
 Ethiop     geeft wel kaart bij zoekresultaten
 Ethiopi    geeft wel kaart bij zoekresultaten

**Comment by SandroNeumann** [comment]
Dit komt door de stemmer. Wanneer je een woord in een tekst veld zet wordt dat bij het zoeken tot het woord gereduceerd waarmee alle varianten gevonden kunnen worden. Voorbeeld: 'duurzame' wordt 'duurzam', zodat het record ook gevonden wordt wanneer je op 'duurzaamheid' zoekt. Want 'duurzaamheid' wordt tot dezelfde stam gereduceerd.

In het geval van het voorbeeld m.b.t. hardlooproute loop je tegen een geval van samengestelde woorden aan: hardlooproutes is een woord, maar hardloop ook en die wordt op een andere manier gestemd.

Concreet gebeurt er dit:

hardlooproute wordt hardlooprout
hard wordt hard
hardloo wordt hardloo

Je ziet dat het bovenste woord de twee onderste woorden bevatten en daarom wordt het record gevonden.

In het geval van hardloop gebeurt er dit:

hardloop wordt hardlop

Dit gebeurt doordat dit woord een apart eigen woord is en daarom op een andere manier gestemd wordt. Je kunt er ook 'hardloper' of 'hardlopen' van maken. Het woord 'hardlop' zit niet in het woord 'hardlooprout' en daarmee levert die zoekopdracht geen resultaat.

**Comment by gerardnienhuis** [comment]
Op 5 apr. 2016 om 12:15 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Dit komt door de stemmer. Wanneer je een woord in een tekst veld zet wordt dat bij het zoeken tot het woord gereduceerd waarmee alle varianten gevonden kunnen worden. Voorbeeld: 'duurzame' wordt 'duurzam', zodat het record ook gevonden wordt wanneer je op 'duurzaamheid' zoekt. Want 'duurzaamheid' wordt tot dezelfde stam gereduceerd.

In het geval van het voorbeeld m.b.t. hardlooproute loop je tegen een geval van samengestelde woorden aan: hardlooproutes is een woord, maar hardloop ook en die wordt op een andere manier gestemd.

Concreet gebeurt er dit:

hardlooproute wordt hardlooprout
hard wordt hard
hardloo wordt hardloo

Je ziet dat het bovenste woord de twee onderste woorden bevatten en daarom wordt het record gevonden.

In het geval van hardloop gebeurt er dit:

hardloop wordt hardlop

Dit gebeurt doordat dit woord een apart eigen woord is en daarom op een andere manier gestemd wordt. Je kunt er ook 'hardloper' of 'hardlopen' van maken. Het woord 'hardlop' zit niet in het woord 'hardlooprout' en daarmee levert die zoekopdracht geen resultaat.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/69#issuecomment-205743214

---

Ik begrijp het maar vrees dat gebruikers dit niet gaan begrijpen

We zullen zoeken na gebruikname gaan evalueren

Voor nu is het te laat om te veranderen

Issue zal ik sluiten
