### ISSUE TITLE
Intern geoportaal bij Uitgebreid zoeken: alleen zoeken archief

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#691]
Wens is om geodata beter te kunnen archiveren. Default niet zoeken in archief. Er is een extra optie in de gebruiksbeperkingen opgenomen: "Alleen beschikbaar in historisch archief"

Wens is om extra zoekoptie aan te brengen in het INTERNE geoportaal. Dus niet EXTERN, alleen intern. 

Nu staat er:

Zoeken naar GIS bestanden
Zoeken naar Services
Zoeken naar Statische kaarten

Dat moet worden:

Zoeken naar GIS bestanden
Zoeken naar GIS bestanden in archief
Zoeken naar Services
Zoeken naar Statische kaarten

De optie Zoeken naar GIS bestanden in archief is default uit.
Maar zet je deze aan, dan krijg je de meer metadata te zien, namelijk ook de metadata waarvan in de gebruiksbeperkingen staat "Alleen beschikbaar in historisch archief"

Standaard wordt dus niet in het archief gezocht bij GIS bestanden, en dan moeten dus alleen die metadatasets getoond worden, waarvan NIET in de gebruiksbeperkingen staat dat het alleen in het archief beschikbaar is.

Let op: ook bij de homepagina van het INTERNE geoportaal moeten alleen die metadatasets getoond worden, waarvan NIET in de gebruiksbeperkingen staat dat het "alleen in archief" beschikbaar is. Op de homepagina willen we dus alleen de actuele data laten zien, en niet de gearchiveerde datasets.

nb: geldt niet voor EXTERNE geoportaal, omdat altijd metadata die in het archief zit, alleen intern beschikbaar is. Gearchiveerde data wordt niet extern zichtbaar. Vandaar dat de wens is om alleen INTERN geoportaal aan te passen.

Voorbeeld eindresultaat:

![archief_wens](https://user-images.githubusercontent.com/9005444/56651843-4a533d80-668a-11e9-8c0c-599a744c130f.jpg)

**Comment by gerardnienhuis** [comment]
Eerste test ziet er goed uit. Alles lijkt te werken, zoals bedoeld. Getest met:

Gemeentegrenzen Overijssel (testdata)
Alternatieve titel: GISBASIH.gemgrens20190501_test (B1/B14)
 
Gebruiksbeperkingen:
Alleen beschikbaar in historisch archief
Mag niet in Atlas van Overijssel
Overige beperkingen:
alleen voor intern gebruik
 
Dit bestand is na een uur zichtbaar in het interne geoportaal
Zie: https://acc-intern.geoportaaloverijssel.nl/search?types=datasetArchived

**Comment by gerardnienhuis** [comment]
https://acc-intern.geoportaaloverijssel.nl/search?types=datasetArchived

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/e1434b09-d268-4adf-addb-fddbe6bcd723
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/b23366ad-6669-4bae-a1d4-eb85e9de55fc


lijkt nog niet goed te werken:


als je meteen selecteert: alleen zoeken in gis bestanden, dus 


default setting:

standaard 7796 resultaten
dan ook zoeken in archief aangezet: 7798 resultaten

en als ik zoeken van gis bestanden, services en statische kaarten dan uitzet: blijven er 2 resultaten over

is correct



zet ik daarna alle selecties weer aan
en alles uit
en weer aan, dan en uit, in een andere volgorde, dan blijkt soms bij een bepaalde combinatie slechts 1 van de 2 gevonden te worden.

dat is niet juist, in alle combinaties van aan en uitzetten van selecties moet het eindresultaat zijn, dat er 2 bestanden in het archief zitten.

**Comment by SandroNeumann** [comment]
Hoe moet ik dit reproduceren? Ik heb wat jij schrijft gedaan, maar ik kan het niet reproduceren.

**Comment by gerardnienhuis** [comment]
Dit lijkt een browserafhankelijk probleem te zijn. Het is nu alleen maar getest met een erg oude IE versie (in gebruik bij prov. Overijssel). Als je F5 (verversen) indrukt, dan is het probleem opgelost. Omdat prov. Ov. binnenkort overgaat naar meer moderne browsers dan is het probleem ook dan volledig opgelost. Voorlopig dus wordt dit gezien als een niet productieremmende bug. Issue kan gesloten
