### ISSUE TITLE
In archief in dashboard opnemen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#696]
Nu staat bij geodata alleen intern en extern geoportaal in het dashboard. Wens is om dit uit te breiden met "nationaal georegister" en "archief".

De kopjes onder "datasets" moeten dan gaan heten:
Nationaal Georegister
Extern Geoportaal
Intern Geoportaal
Archief

Omdat het belangrijk is om snel overzicht te krijgen is ook het voorstel om het onderdeel over services los te plaatsen en dat meer links in de pagina weer te geven (zie bijgevoegd plaatje) Tekst van headers zijn ook iets aangepast.

Wordt nu:

Connectie Geopublisher met provider
Aantal services in Geoportaal
Laatste 10 systeemtaken Geopublisher
Aantal datasets en statische kaarten

Merk op: de getallen die getoond worden bij "archief" hebben betrekking op alle metadatasets waarbij de woorden "Alleen beschikbaar in historisch archief" voorkomen bij de gebruiksbeperkingen. 

Let op: het totaal bij "Intern Geoportaal" dat betreft nu alle metadatasets die intern beschikbaar gesteld worden. Dat moet het aantal worden, wat intern beschikbaar wordt gesteld ZONDER dat bij gebruikersbeperkingen staat "Alleen beschikbaar in historisch archief". Anders zou je die metadatasets twee keer meetellen, zowel bij intern als bij archief.

![wens_ngr_archief_dashboard](https://user-images.githubusercontent.com/9005444/57624548-77f91b80-7592-11e9-9f83-f87f195206d3.jpg)

**Comment by gerardnienhuis** [comment]
nb: de tekst bij de i-knopjes moet ook worden aangepast, op basis van deze veranderingen.

**Comment by gerardnienhuis** [comment]
Is de impact ook "hoog" als alles onveranderd blijft, maar alleen "archief" wordt toegevoegd?

**Comment by SandroNeumann** [comment]
Dan wordt het "impact middel".

**Comment by gerardnienhuis** [comment]
OK, helder. Wat mij betreft nemen we dan NGR in een later issue mee. Dan nu alleen uitwerken voor "archief".

**Comment by SandroNeumann** [comment]
Dus ook niet de services in een apart blok weergeven?

**Comment by gerardnienhuis** [comment]
nee, graag wel services onderaan plaatsen, is minst relevant voor beheerders.
Dus van boven naar beneden eerst datasets, dan statische kaarten, daaronder als laatste services.
Ziet er dan zo uit:

![wens_alleen_archief_dashboard](https://user-images.githubusercontent.com/9005444/58561449-65841080-8227-11e9-820a-4991e87b9fda.jpg)

**Comment by SandroNeumann** [comment]
Dus dit issue gaat om deze twee dingen:
- archief blok
- service blok verhuizen

**Comment by gerardnienhuis** [comment]
klopt. verzoek bij dit issue is nieuw archief blok. Ik zal apart issue van maken voor het verplaatsen blok services

**Comment by gerardnienhuis** [comment]
als alleen archief en services betreft, dan is nog steeds de impact "hoog"? Of is het nu middel, omdat NGR niet meer meegenomen wordt in dit issue?

**Comment by SandroNeumann** [comment]
Wordt impact middel

**Comment by gerardnienhuis** [comment]
Archief is nu conform wens zichtbaar in het dashboard: issue kan gesloten
