### ISSUE TITLE
Ivm archivering statische kaarten locatie aanpassen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#698]
Deze actie is eerder op vergelijkbare manier uitgevoerd.

zie ook: https://github.com/IDgis/geoportaal-test/issues/514

Er zijn recentelijk weer een boel statische kaarten gearchiveerd. Wens is om dat ook in de metadata aan te passen.

2016 en ouder zit in het archief

Default locatie wordt dan: K:\BAB-Archief\
Met per jaar het betreffende jaar erachter

K:\BAB-Archief\2012
K:\BAB-Archief\2013
K:\BAB-Archief\2014 enz

Het jaar is de datum creatie

Dus voor alle statische kaarten van 2016 en ouder moet deze locatie aangepast worden.

**Comment by gerardnienhuis** [comment]
2018 zit ook in archief, dus graag actie herhalen voor 2018 en 2017

**Comment by SandroNeumann** [comment]
```
update gb.metadata set location = 'K:\BAB-Archief\' || split_part(location, '\', 4) || '\' || split_part(location, '\', 5)
where location like 'K:\\bab\\geo-informatie\\%'
and split_part(location, '\', 4) != ''
and split_part(location, '\', 5) != ''
and split_part(location, '\', 4)::int <= 2018
;
```

**Comment by gerardnienhuis** [comment]
dit lijkt niet volledig goed te zijn afgelopen:



https://acc-intern.geoportaaloverijssel.nl/metadata/dc/bae726f0-0773-4e11-84bb-e667d5c06b9d
Naam statische kaart: Zwemwater - overzicht provincie
Beschrijving: Zwemwater - overzicht provincie tbv observatie vanuit vliegtuig
Nummer: 09234171

daar staat nu:

Locatie: k:\bab\geo-informatie\2009\



dit is niet correct
locatie had moeten zijn:

K:\BAB-Archief\2009

**Comment by SandroNeumann** [comment]
Ik heb alleen locaties aangepast met een jaartal, een nummer en niets daarna.

Kennelijk moet het ook aangepast worden als er alleen een jaartal is?

**Comment by gerardnienhuis** [comment]
is juist, ook als er alleen jaartal staat.
voorbeeld:
Naam statische kaart: Toedeling gebieden per taakonderdeel
https://intern.geoportaaloverijssel.nl/metadata/dc/12b0e2de-f4a8-4aa0-9636-75b1a19ec881

daar staat als locatie:
Locatie: k:\bab\geo-informatie\2001\

dat had moeten zijn: K:\BAB-Archief\2001

**Comment by gerardnienhuis** [comment]
is nu wel allemaal OK: getest op acceptatie, rapport toont alleen maar K:\BAB-Archief, met uitzondering van nieuw aangemaakte statische kaart. Die staat correct op K:\bab\geo-informatie\2020\ . Issue kan nu gesloten.
