### ISSUE TITLE
Code google analytics interne geoportaal

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#699]
Wens is om voor het interne geoportaal (en ook bij dowload en andere schermen via interne geoportaal) een andere google analytics teller te gebruiken dan nu het geval is.

Nu is in analytics er geen onderscheid tussen intern en extern geoportaal mogelijk. Wens is dat dus in de pagina's (en ook op de stylesheets voor metadata) van het interne geoportaal er een tweede teller wordt gebruikt. De bestaande code moet dus vervangen worden door een nieuwe code van analytics.

**Comment by SandroNeumann** [comment]
De code wordt nog gestuurd?

**Comment by gerardnienhuis** [comment]
ja, via de mail

**Comment by gerardnienhuis** [comment]
Code is zojuist via mail opgestuurd, moet alleen worden toegepast voor interne pagina's zodat we onderscheid kunnen maken tussen intern en extern bezoek geoportaal. Issue kan gesloten. Uiteindelijke test zal in productiefase plaatsvinden.

**Comment by gerardnienhuis** [comment]
kan wel op acceptatie getest worden, dus issue nog open laten.

**Comment by gerardnienhuis** [comment]
De teller van analytics laat bezoek aan intern Geoportaal vanaf maandag 25 augustus zien. Werkt goed. Issue kan gesloten.
