### ISSUE TITLE
Beperking aantal tekens moet bekend zijn en fouten moeten afgevangen worden

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#70]
Het lijkt er op dat veel invoervelden (misschien allemaal?) een beperking hebben in het aantal tekens wat mag worden ingevoerd. Ga je over die grens heen, dan volgt bij opslaan een foutmelding. Bijvoorbeeld bij het veld waarbij je een andere eindverantwoordelijke kan invoeren: wordt het te veel tekens, dan error bij opslaan. Maar dit probleem speelt bij veel meer invoervelden.

Wensen zijn:

1) helder maken wat beperkingen van de velden zijn
2) gebruiker melden dat aantal tekens te veel is
3) geen crash als aantal tekens te lang is

![teveel_letters_crash](https://cloud.githubusercontent.com/assets/9005444/13252923/897f1f14-da39-11e5-962a-72ac492a518b.jpg)

**Comment by SandroNeumann** [comment]
Er kan ook een maximum op de invoervelden komen. Dan kun je niet meer tekens invoeren. Wat heeft je voorkeur?

**Comment by gerardnienhuis** [comment]
Minimum van 200 tekens, en dan zetten we in de help (bij de i-knop) dat die beperking er is. Mocht dat ooit te beperkend blijken, dan neem ik aan dat die grens zonder veel moeite op te hogen is, naar b.v. 300 or 500?

**Comment by gerardnienhuis** [comment]
nb: beperking tot 200 tekens bij alle tekst invoervelden, met uitzondering van de omschrijving en de locatie. Locatie op voorstel van Herman maximaal 2000 (formele grens van url?). Wat is het maximale aantal tekens nu, van de omschrijving?

**Comment by gerardnienhuis** [comment]
lijkt goed te werken, url met veel tekens, titel en ook omschrijving met erg veel tekens blijkt goed te werken. issue kan gesloten
