### ISSUE TITLE
Rapportage/Statistieken voor alle requests

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#705]
Rapportage maken voor alle requests. Er bestaat al een rapportage voor de WMS/WFS requests.

Zie #611

**Comment by gerardnienhuis** [comment]
requests die nog niet in #611 zijn opgenomen zijn bijvoorbeeld requests voor opvragen van metadata. Het kan erg nuttig zijn deze ook in dit rapport op te nemen. Niet in milestone 152 maar in 153, zodat in 152 ervaring met dit nieuwe rapport kan worden opgedaan.

**Comment by gerardnienhuis** [comment]
Huidige versie lijkt nog niet goed te werken (geheugenprobleem voor volledige serie onder meer). Daarom als bug gemarkeerd.

**Comment by gerardnienhuis** [comment]
Ik krijg nu wel een bestand, maar er lijken een boel requests te ontbreken.

Het rapport download start op 25-8-2016
Het rapport requests start pas op 31-12-2018

Hoe kan dat? 
Waar zijn de gegevens van voor 31-12-2018 dan gebleven?
Kan ik de volledige serie requests krijgen, dus vanaf 25-8-2016?


nb: de file die ik heb gekregen, die bevat 510495 regels (inclusief header)

laatste regel is: 

"62.210.187.223";"2018-12-31 15:18:19.0";"2018-12-31";"15";"18";"acc-www.geoportaaloverijssel.nl";"/wp-config.php_old";"";"";"302";"OK";

(gecontroleerd met notepad++ en excel)

**Comment by SandroNeumann** [comment]
Dit is correct. Er waren zo veel requests dat dat erg veel was om de eerste keer in te lezen. Om die reden hebben we met Utrecht destijds afgesproken dat we de requests vanaf circa 1 januari 2019 zouden oppakken.

**Comment by gerardnienhuis** [comment]
Helemaal goed: vanaf 1-1-2019 wordt alles bewaard, en dus kan vanaf dat moment het rapport met de request geleverd worden. Gegevens van voor die tijd zijn verwijderd en ook niet meer bij IDGis in backups terug te vinden (logisch, gezien omvang van de info). Dit issue kan daarom nu gesloten.
