### ISSUE TITLE
Kolom uuid-count na bronmetadata_aanwezig in rapport geodata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#707]
Nu zit de kolom uuid-count op heel onhandige plaats in het rapport van geodata: tussen kolommen die vooral datums beschrijven. 

Wens is dat deze kolom wordt geplaatst direct na (rechts van) de kolom bronmetadata_aanwezig.

**Comment by gerardnienhuis** [comment]
Dit lijkt niet goed te werken. Er zijn 3 uuid's opgenomen in het rapport van geodata. Geen van deze id's is dubbel, maar toch staat bij de uuid_count soms het getal 2. Gevonden door rapport te maken, en te filteren op count = 2.

**Comment by SandroNeumann** [comment]
Deze identifier wordt bekeken in de harvester van de GeoPublisher:

``/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:identifier/gmd:MD_Identifier/gmd:code/gco:CharacterString``

Dat is in de rapportage md_identifier.

Mocht je denken dat wanneer er bij uuid_count 2 staat er dan ook een tweede regel in de rapportage van de geodatasets met dezelfde identifier staat, dat is incorrect. Het gaat hier puur om hoe vaak een identifier in dezelfde harvest sessie langs komt. Per definitie moet een identifier uniek zijn en kan dus niet 2x voorkomen in de database.

**Comment by gerardnienhuis** [comment]
helemaal duidelijk nu:
- bij 2e keer zelfde uuid wordt de xml genegeerd: dit kan dus wijzen op een fout in de metadata en moet dus gezocht worden in de map met xmls (geowebfolder). Het is nu nog niet mogelijk om dus "dubbele" metadatasets in het rapport weer te geven (want 2e x zelfde uuid wordt genegeerd). Op termijn idee om een keer wel in het rapport op te nemen, want zoeken in xml map is erg lastig.

Maar voor nu is dit issue naar tevredenheid opgelost en kan dus afgesloten worden.
