### ISSUE TITLE
Geen bestanden "in archief" op homepagina intern laten zien

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#708]
Nu staan ook de gearchiveerde bestanden, als die zijn aangepast op de homepagina van het interne geoportaal. Dat is niet de bedoeling (geeft kans op verwarring). Daarom alleen de geodatasets  waarvan "in archief" is "nee" op de homepagina laten zien

Lijkt op het issue waarbij de services niet meer op de voorpagina worden weergegeven, zie:
https://github.com/IDgis/geoportaal-test/issues/679

**Comment by NicoEilers** [comment]
Deze issue is nog niet opgelost.
Als een history-dataset wordt gewijzigd en opnieuw gepubliceerd, komt deze niet in de 5 meest recente bestanden op de homepage van het geoportaal te staan.

**Comment by gerardnienhuis** [comment]
blijkt wel goed te werken, bedoeling is dat alle history datasets NIET op de home terecht komen. blijkt wel goed te werken en issue kan gesloten
