### ISSUE TITLE
Zoeken geeft foutmelding

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#71]
Het zoeken naar "Kolland & Overlangbroek" geeft een foutmelding. Komt dat door de & tussen die 2 woorden? De tekst staat wel letterlijk in metainfo uit het huidige geoportaal: http://gisopenbaar.overijssel.nl/geoportal_extern/catalog/search/resource/details.page?uuid=%7B71A4BB9C-D2CA-44B2-B308-7AABF81CD7DB%7D

Opvallend is dat zoeken naar "Schiepersberg en Savelsbos" geen fouten geeft.
Ook "Regeling Aankoop Gronden Overijssel 2013" wordt correct gevonden.

**Comment by SandroNeumann** [comment]
Komt inderdaad door het & teken.

**Comment by gerardnienhuis** [comment]
lijkt nu allemaal goed te gaan, fout treedt niet meer op: issue gesloten
