### ISSUE TITLE
problemen twee jaarlijks update frequentie

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#717]
De updatefrequentie van een bestand kan een aantal waarden hebben. Zoals twee-jaarlijks. Daarmee wordt bedoeld: 1 keer per 2 jaar. Nu kan je dat als beheerder wel in geosticker opgeven, maar in de xml komt te staan: 2annually. 

Dat komt niet overeen met de formele lijsten van iso19115. Daarin staat echter wel bij twee-jaarlijks: biannually. 

Probleem is dat nu in de xml uiteindelijk komt te staan: onbekend.

De bedoeling is dat als er in de geoweb xml staat: 2annually, er dan van gemaakt wordt: biannually.

**Comment by SandroNeumann** [comment]
Hoe gaan we met deze waarde om in de rapportage?

**Comment by gerardnienhuis** [comment]
In de rapportage komt nu al voor:
1 x per 2 weken
1 x per kwartaal

het beste lijkt mij, om een vergelijkbare tekst in het geoportaal en ook in de rapportage te laten zien.
Dat wordt dan: 1 x per 2 jaar

**Comment by gerardnienhuis** [comment]
in rapportage, herzieningsfrequentie is niet goed
daar staat nu:  onbekend

daar had moeten staan: 2-jaarlijks


nb: op het scherm bij tabblad wanneer is het wel correct, daar staat wel 2-jaarlijks

voorbeeld bestand:

Gemeentegrenzen Overijssel 2 jaarlijkse update

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/3e5c760c-9cb0-4157-b694-5346806f8f92

**Comment by gerardnienhuis** [comment]
Het werkt nu goed: er staat nu in het rapport 1 x per 2 jaar. Wat een veel betere omschrijving is dan "2 jaarlijks". 

getest met 
Gemeentegrenzen Overijssel 2 jaarlijkse update
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/3e5c760c-9cb0-4157-b694-5346806f8f92

Dit rapport is dus nu goed, hoewel het afwijkt van de tekst in de stylesheet. Om dat aan te passen wordt een nieuw issue aangemaakt. 

Maar dit issue over het rapport kan gesloten.
