### ISSUE TITLE
tekst die niet in samenvatting staat wordt nu niet gevonden.

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#719]
De bedoeling is dat alle tekst die in de metainformatie staat, ook wordt gevonden met zoeken in geoportaal. Dat is nu niet het geval. Hieronder enkele voorbeelden. Tekst in samenvatting wordt overigens wel gevonden (ook voorbeeld hieronder). Bedoeling is dat alle tekst gevonden wordt.

lijkt op eerdere issues:
https://github.com/IDgis/geoportaal-test/issues/268 
https://github.com/IDgis/geoportaal-test/issues/342 

**voorbeeld 1 (fout):**

Versie:  Wordt dagelijks geupdate
https://intern.geoportaaloverijssel.nl/metadata/dataset/81ef40eb-9a00-412f-bff6-b31441cdc929
Bestandsnaam: Dg Dialog BGT Gebouwen
als gezocht wordt naar "dagelijks" dan wordt deze metadata niet gevonden (zowel intern als extern geoportaal getest)

**voorbeeld 2 (fout):**

dit probleem lijkt ook op te treden bij attributen
zoek naar woord "Vogelkers"
komt voor in tekst van attributen van metadataset 
https://intern.geoportaaloverijssel.nl/metadata/dataset/7b93abb6-f91b-47e0-a5ea-8e93b0552e2f
Bestandsnaam: Eeuwenoud bos

**voorbeeld 3 (goed):** 

tekst wel gevonden in samenvattingen
gezocht naar het woord "brandharen"
gevonden: Bestandsnaam: Eikenprocessierups incl bestrijdingsstrategie (punten)
https://intern.geoportaaloverijssel.nl/metadata/dataset/b5fb5f33-1eb8-495e-a92d-6c55a012b25b

**Comment by SandroNeumann** [comment]
Dagelijks kan niet worden gevonden, want dat staat niet in de metadata. Wel de Engelse term uit de codelist 'daily'.

De attributen kan ik toevoegen in de harvester.

**Comment by gerardnienhuis** [comment]
Dagelijk

Verstuurd vanaf mijn iPhone

Op 30 jan. 2020 om 13:42 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Dagelijks kan niet worden gevonden, want dat staat niet in de metadata. Wel de Engelse term uit de codelist 'daily'.

De attributen kan ik toevoegen in de harvester.

**Comment by gerardnienhuis** [comment]
alles lijkt nu correct te werken, meerdere zoektermen geprobeerd, hieronder enkele voorbeelden van geslaagde resultaten: issue kan gesloten

testbevindingen, niet uitputtend maar enkele voorbeelden.
Alle zoekacties lijken nu correct te werken.

TEST 1:
Carpoolbezetting voor auto en fiets
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/d88549b0-e892-49e6-b806-c8bc4dee969d

TEST 2:
gaat goed, bezettingsgraad  gevonden met zoeken, zit in attribuutbeschrijving
ook oracle-tabel  gevonden, staat bij Algemene beschrijving herkomst: 

TEST 3:
personen ook gevonden, test Nienhuis
gevonden bij WIE in Wegbeheer, punten, van de provinciale infrastructuur
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/13871b5a-3a5f-499d-9942-5090d5eaff74

TEST4:
Downloadable ook gevonden: levert allemaal downloadbare lagen in services als zoekresultaat

TEST 5:
stautus gevonden, staat bij attributen omschrijving van bestand
Vervallen Beschermde Natuurmonumenten (30-05-2017, Provincie Overijssel) 
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/2d53e29a-6c61-4bf2-9f14-ff6d4e479e11

TEST 6:
Civiele ook correct gevonden,
staat bij onderwerp van statische kaart
Onderhoudswerkzaamheden N350
https://acc-intern.geoportaaloverijssel.nl/metadata/dc/016fa5d0-53cd-4258-b0eb-f9cc7c90b3ad

TEST 7: 
Versie: wordt daagelijks geupdate
daagelijks gezocht, ook correct gevonden bij:
Faunavoorzieningen, vlakken langs provinciale infrastructuur
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/85a2e3fd-f0ab-4563-8717-dbc4122efa96

===

**Comment by gerardnienhuis** [comment]
blijkt toch niet altijd goed te werken:

bestand: Agrarisch Natuur en Landschapsbeheer (ANLb)
https://intern.geoportaaloverijssel.nl/metadata/dataset/4bc8f454-a601-4d69-91f9-d2cc0c790644
bevat bij de attributen de omschrijving: Pakketvariantcode 

maar zoeken naar Pakketvariantcode  levert geen bestanden op.

**Comment by SandroNeumann** [comment]
Dat levert wel bestanden op:

https://intern.geoportaaloverijssel.nl/search?text=Pakketvariantcode&types=dataset

**Comment by gerardnienhuis** [comment]
Correct, bij mij nu ook weer. Kan probleem niet reproduceren, dus issue kan weer gesloten worden.

**Comment by SandroNeumann** [comment]
Typefoutje?

**Comment by gerardnienhuis** [comment]
Of teveel tegelijk getest? Niet meer reproduceerbaar helaas. 

Kan ook zijn dat ik alle vinkjes "uit" had staan bij de zoekmethodes: zoeken naar GIS bestanden, enz.. als daar niks is aangevinkt, dan vind je ook niks (logisch). 

Ik heb steekproefsgewijs nog wat getest maar fout is niet meer reproduceerbaar, dus issue kan gesloten blijven.
