### ISSUE TITLE
Tekst ====   niet gevonden

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#72]
In 1 record zit als tekst ====  Als ik deze tekst ga zoeken, dan levert dit echter geen zoekresultaten op. Wordt er alleen op letters en cijfers gezocht? Bedoeling is, dat alles wat wordt opgeslagen, ook inderdaad terugvindbaar is bij het zoeken naar tekst. 

nb: ====   komt voor in de het record met de titel "Aardwarmte Friesland"

**Comment by SandroNeumann** [comment]
Dit soort woorden worden genegeerd door de zoek engine. Net zoals veel voorkomende woorden als de, een, het.

**Comment by gerardnienhuis** [comment]
is prima als dit soort woorden niet meegenomen worden in zoekopdracht
