### ISSUE TITLE
2-jaarlijks in stylesheet vervangen door 1 x per 2 jaar

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#727]
Nu staat in het rapport als een dataset moet worden vervangen: 1 x per 2 jaar
maar in de stylesheet staat: 2-jaarlijks

Nu is 2-jaarlijks een veel lastiger eenduidig te begrijpen term, dan 1 x per 2 jaar.

Verzoek is om ook in de stylesheet de tekst 1 x per 2 jaar weer te geven.

**Comment by gerardnienhuis** [comment]
zie ook: https://github.com/IDgis/geoportaal-test/issues/717

**Comment by NicoEilers** [comment]
2-jaarlijks vervangen door 1 x per 2 jaar  is nog niet gebeurt.
Als is de metadata 2-jaarlijks wordt ingevuld wordt dit ook in metadata in het geoportaal te staan en niet 1 x per 2 jaar

**Comment by gerardnienhuis** [comment]
voorbeeld nog niet goed in stylesheet, nb: wel goed in rapport


https://www.geoportaaloverijssel.nl/metadata/dataset/774392cf-7d99-0b1f-d706-c8b17cb0ee5a 

Bestandsnaam: Top 250 raster van Nederland

Herzieningsfrequentie bestand: 2-jaarlijks

**Comment by SandroNeumann** [comment]
In de stylesheet staat 2-jaarlijks bij biannually en daar staat in de standaard dit bij:

`biannually | Data wordt twee keer per jaar geactualiseerd.`

https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#codelist-maintenancefrequencycode

Dus dan wordt het _2 x per jaar_.

**Comment by Maties-Casan** [comment]
Dit gaan we binnenkort testen.

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, zie bijvoorbeeld:
gezocht naar: biannually
gevonden:
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/1ba2959f-a1b9-45f8-a4c1-9ba4cff545b0
Bestandsnaam: Bestemmingsplan Objectklasse Enkel bestemming

Voltooiing bestand: 23-08-2018
Publicatie bestand: 17-01-2022
Laatste wijziging bestand: 01-01-2022
Herzieningsfrequentie bestand: 2 x per jaar
Laatste wijziging bestandsbeschrijving: 17-01-2022
issue kan gesloten
