### ISSUE TITLE
Request rapportage -> status code fout en pad lengte kleiner dan 14 tekens niet tonen

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#734]

**Comment by gerardnienhuis** [comment]
getest op acceptatie: levert geen output op. getest met 2 korte periodes (minder dan een maand) in 2019 en 2020: beide leveren heel snel resultaat (bestand is op te slaan). Alleen bij controle blijkt het bestand 0 Kb te zijn.

**Comment by SandroNeumann** [comment]
Ik had het gisteren namiddag gezien. Ik los dit zsm op.

**Comment by SandroNeumann** [comment]
Het is aangepast op de acceptatie-omgeving.

**Comment by gerardnienhuis** [comment]
Weer getest, ziet er nu goed uit. 

Requests lengte niet meer onder de 14, en geen fouten meer in het rapport. Getest met 3 perioden, zie hieronder. Werkt goed, dus issue kan gesloten.

https://acc-report.geodataoverijssel.nl/request?date_start=2020-02-25&date_end=2020-03-20
levert bestand van 4 Mb op

https://acc-report.geodataoverijssel.nl/request?date_start=2019-02-25&date_end=2019-03-20
levert bestand van 4 Mb oo

https://acc-report.geodataoverijssel.nl/request?date_start=2019-01-01&date_end=2019-08-01
levert bestand van 27 Mb op

**Comment by gerardnienhuis** [comment]
Dank
Werkt goed nu

Wil je deze versie uitrollen op productie?


Verstuurd vanaf mijn iPhone

Op 17 mrt. 2020 om 11:04 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Het is aangepast op de acceptatie-omgeving.

**Comment by SandroNeumann** [comment]
Het staat op productie.

**Comment by gerardnienhuis** [comment]
Dank
Ga ik asap proberen

Verstuurd vanaf mijn iPhone

Op 17 mrt. 2020 om 14:39 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Het staat op productie.
