### ISSUE TITLE
Rapport requests met alleen IP nummers en datum

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#735]
Verzoek is om een nieuw rapport te maken, wat net zo werkt als het bestaande rapport met requests. Wens is dat echter alleen de ip nummers  en datums in het rapport worden opgeslagen.

let op: wel dezelfde beperkingen: alleen als OK en als lengte request > 14 posities is: zelfde als huidige request rapport.

Wens is dat datum wordt weggeschreven, net als huidige request rapport, dus als JJJJ-MM-DD.
bijvoorbeeld: 2020-01-05, 2019-11-02 enz...

Manier van opstarten kan vergelijkbaar met huidige rapport voor requests:  door middel van een url met start en einddatum.

**Comment by gerardnienhuis** [comment]
zie: https://github.com/IDgis/geoportaal-test/issues/734

**Comment by gerardnienhuis** [comment]
huidige manier van request rapport opvragen is:
https://acc-report.geodataoverijssel.nl/request?date_start=2020-02-25&date_end=2020-03-20

nieuwe rapport mag heten: requestipdatum, op te vragen als:
https://acc-report.geodataoverijssel.nl/requestipdatum?date_start=2020-02-25&date_end=2020-03-20

**Comment by SandroNeumann** [comment]
Ik heb het op de acceptatie omgeving gezet. Op te vragen via deze url:

https://acc-report.geodataoverijssel.nl/request_ip?date_start=2019-01-01&date_end=2019-02-01

**Comment by gerardnienhuis** [comment]
Ik ga het meteen proberen
Dank voor dit nieuwe rapport




Met vriendelijke groet,


Gerard Nienhuis


g.nienhuis@overijssel.nl<mailto:g.nienhuis@overijssel.nl> / 038-4999476 / Kaarten, geodata en services: http://www.geoportaaloverijssel.nl<http://www.geoportaaloverijssel.nl/>





Van: SandroNeumann [mailto:notifications@github.com]
Verzonden: dinsdag 31 maart 2020 12:29
Aan: IDgis/geoportaal-test <geoportaal-test@noreply.github.com>
CC: Nienhuis, G (Gerard) <G.Nienhuis@overijssel.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [IDgis/geoportaal-test] Rapport requests met alleen IP nummers en datum (#735)


Ik heb het op de acceptatie omgeving gezet. Op te vragen via deze url:

https://acc-report.geodataoverijssel.nl/request_ip?date_start=2019-01-01&date_end=2019-02-01

**Comment by gerardnienhuis** [comment]
Deze versie van het rapport blijkt goed te werken, alleen zit er teveel informatie in.

Het ip-adres en de datum is voldoende. 

Wat weg kan zijn de kolommen:

- date_full
- hour
- minute

**Comment by SandroNeumann** [comment]
De rapportage is bijgewerkt

**Comment by gerardnienhuis** [comment]
Dit zie er goed uit nu. Rapportages zijn zeer veel kleiner dan de rapportages met alle gegevens. Voordeel is dat ze sneller beschikbaar komen en minder ruimte innemen. De gegevens van verschillende tijdstippen zijn gecontroleerd en ook vergeleken met de al bestaande rapportages.
 
https://acc-report.geodataoverijssel.nl/request_ip?date_start=2019-01-01&date_end=2019-02-01 ...
https://acc-report.geodataoverijssel.nl/request_ip?date_start=2019-04-01&date_end=2019-12-01
vergeleken met 1 mei 2019 van:
https://acc-report.geodataoverijssel.nl/request?date_start=2019-04-01&date_end=2019-05-01

Gegevens lijken correct. Rapport is goed bruikbaar en issue kan gesloten.
