### ISSUE TITLE
Rapport requests wordt 0 kB

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#738]
het lijkt wel alsof de rapportage voor requests niet meer goed werkt

urls voor opvragen request rapportages
(volledig, dus met ip, volledig request, tijdstip enz)

eerder vandaag (werkt goed):
https://report.geodataoverijssel.nl/request_ip?date_start=2018-12-30&date_end=2019-01-15
levert bestand van 39 MB

eerder vandaag (werkt goed):
https://report.geodataoverijssel.nl/request_ip?date_start=2019-01-16&date_end=2019-02-01
levert bestand van 52 MB

**fout, 15.20 uur, 8-4-2020:**
https://report.geodataoverijssel.nl/request_ip?date_start=2019-02_02&date_end=2019-02-15
**maakt bestand van 0 kB**

**fout, 15.25 uur, 8-4-2020:**
https://report.geodataoverijssel.nl/request_ip?date_start=2019-02_02&date_end=2019-02-06
fout, 15.20 uur, 8-4-2020:

**Comment by SandroNeumann** [comment]
Je hebt een foutje in de datum bij date_start. Er staat 2019-02_02, dit moet 2019-02-02 zijn.

**Comment by gerardnienhuis** [comment]
correct, is inderdaad typfout aan mijn kant: probleem is opgelost, issue kan weer gesloten.
