### ISSUE TITLE
Crash na goedkeuren als leverancier in Chrome

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#74]
Ik kan niet verder, nadat ik de knop "goedkeuren" heb ingedrukt. De knoppen worden lichtrood en niets werkt meer in de applicatie. Gebruikte browser: Chrome (meest recente versie d.d. 24-2-16). Voordat ik die knop heb gebruikt, werkte verwijderen van 1 reeds aangemaakt
![bug_crash_ter_goedkeuring](https://cloud.githubusercontent.com/assets/9005444/13278166/814ea5c2-dace-11e5-892e-7043df740898.jpg)
 record wel goed overigens

**Comment by gerardnienhuis** [comment]
Het lijkt er op alsof je als leverancier wel de knop goedkeuren of verwijderen kan indrukken, ook als de selectie reeds gepubliceerde kaarten bevat. Wat je zou willen is dat de actie alleen op nog niet gepubliceerde records wordt uitgevoerd en dat er een melding komt, voor de gebruiker:

De selectie bevat 1 of meerdere reeds gepubliceerde records. De status hiervan kan nu niet worden aangepast. Neem hiervoor contact op met de beheerders van het Geoportaal. Wilt u verder gaan met het aanpassen van de overige records?

En dan de knoppen "Annuleren" en "Status aanpassen"

**Comment by SandroNeumann** [comment]
In je screenshot worden de knoppen disabled, omdat je als leverancier bent ingelogd en een record geselecteerd hebt die gepubliceerd is.

**Comment by SandroNeumann** [comment]
Heeft dit issue nu enkel betrekking op de melding die er moet komen? Ik kan geen crash uit je screenshot opmaken, alleen dat de knoppen disabled worden bij het selecteren van een gepubliceerd record door een leverancier.

**Comment by gerardnienhuis** [comment]
is inderdaad geen bug: blijkt gewoon nu zo te werken, als je een reeds gepubliceerd record probeert te verwijderen. Label bug kan verwijderd. Wens is wel om betere melding te geven aan gebruiker, als dit voorkomt. Dit issue kan gesloten en samengevoegd met het issue waar hier aan aandacht voor wordt gevraagd: #79
