### ISSUE TITLE
Beleidsinformatie@overijssel.nl wordt kennishub@overijssel.nl

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#743]
Op 3 plaatsen in het Geoportaal staat nu de tekst beleidsinformatie@overijssel.nl

Dat moet, omdat het team beleidsinformatie van naam is veranderd, aangepast worden.
Het nieuwe emailadres is: kennishub@overijssel.nl

De onderdelen waar nu beleidsinformatie@overijssel.nl staat zijn:
- Over deze site (onderaan)
- Contact
- Download (onderaan)

**Comment by NicoEilers** [comment]
In acceptatie omgeving is het email adres beleidsinformatie@overijssel.nl op 3 plaatsen vervangen door: kennishub@overijssel.nl
Issue kan worden gesloten.
