### ISSUE TITLE
Onderzoeksbank Overijssel

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#746]
http://onderzoeksbank.brabant.nl/onderzoeksbank/

namaken, als #745 is afgerond

**Comment by gerardnienhuis** [comment]
voor een eerste versie layout conform http://onderzoeksbank.brabant.nl/onderzoeksbank/

**Comment by gerardnienhuis** [comment]
bedoeling dat opzet gebruikt wordt, en dan een eerste versie opleveren zonder toeters en bellen. Vervolgstap is dan gebruiken. Als het voldoet aan gebruikerswensen, dan aanpassen aan huisstijl Overijssel en aparte url gebruiken

**Comment by gerardnienhuis** [comment]
website wordt voorlopig: onderzoeksbank.dataportaaloverijssel.nl

**Comment by gerardnienhuis** [comment]
streven is om een eerste eenvoudige werkende versie te hebben, met als content de bestaande content (rapporten) die nu bij de statische kaarten staan. Vervolg is gebruiken, evalueren en dan zo nodig aanpassen (bijvoorbeeld conform huisstijl Overijssel, andere url enz)

**Comment by SandroNeumann** [comment]
- layout en opmaak maken (8 uur)
- home en contact pagina implementeren (5 uur)
- lijst met zoekopdracht implementeren (8 uur)
- bladeren met zoekopdracht en filtering implementeren (8 uur)
- server configuratie uitvoeren (3 uur)

totaal: 32 uur

**Comment by SandroNeumann** [comment]
Oplossingsrichting:

Uitwerken van een Geoportaal-achtige omgeving, maar dan alleen voor rapporten. Er moet een home, zoeken, bladeren en contact pagina komen. Het zoeken en bladeren werkt vergelijkbaar als het Geoportaal.

Activiteiten:

- layout en opmaak maken
- home en contact pagina implementeren
- api voor rapporten in geoportaal-beheer
- lijst met zoekopdracht implementeren
- bladeren met zoekopdracht en filtering implementeren
- server configuratie uitvoeren

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Een vraag over de onderzoeksbank:

In het voorbeeld van Brabant zie ik in het overzicht van een rapport een aantal zaken staan die wij niet tot onze beschikking hebben. Dat zijn:

- looptijd
- opdrachtgever
- uitvoerder
- auteurs
- soort
- onderzoeksvraag

Hetzelfde geldt bij uitgebreid zoeken (daar zou ik voor nu trouwens alleen vrije tekst zoeken implementeren). Daar mis ik de volgende zoek velden:

- status
- opdrachtgever
- uitvoerder
- soort onderzoek

**Comment by gerardnienhuis** [comment]
@SandroNeumann : het streven is dat we een eerste versie maken met de beschikbare metadata. en dan gaan uitproberen of dit werkt of dat er nog dringende uitbreidingen nodig zijn. nb: de eerste versie die we nu maken moet dus wel zoveel mogelijk de huidige metadata ondersteunen (dus de al ingevoerde metadata). En het moet via een aparte url te benaderen zijn.

**Comment by gerardnienhuis** [comment]
verzoek om 1 ding nu te controleren: 
https://onderzoeksbank.dataportaaloverijssel.nl lijkt niet te openen in IE-11. 

Wel in Firefox overigens. De bedoeling is dat alle browsers die in Overijssel gebruikt worden, ook worden ondersteund. Op dit moment zijn dat ook nog IE-11 en Firefox 68.4.1.

**Comment by KevinvdBosch** [comment]
Ook direct issue #743 meenemen voor de contact pagina

**Comment by gerardnienhuis** [comment]
Onderzoeksbank blijkt goed te werken, zowel onder IE-11 als FF 68.4.1.
Issue kan gesloten.
