### ISSUE TITLE
In geoportaal-beheer de controle van wachtwoord wijzigen / vergeten  hoofdletterongevoelig maken

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#747]

**Comment by gerardnienhuis** [comment]
Dit blijkt goed te gaan: inloggen met g.nienhuis@overijssel.nl gaat net zo goed als G.Nienhuis@overijssel. Geldt ook voor onderdeel voor veranderen van wachtwoord.

issue kan gesloten.
