### ISSUE TITLE
Zoeken in Chrome werkt niet

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#75]
Als ik in Chrome een zoekterm invoer, dan kan ik op "zoeken" klikken, maar verder levert dit geen zoekresultaten op. De selectie verandert niet. Alles blijft zichtbaar, ook als ik een zoekterm gebruik, die uniek is voor slechts 1 van de records. Dan had ik dus slechts 1 record moeten zien

![bug_zoeken_chrome](https://cloud.githubusercontent.com/assets/9005444/13278331/08ea1646-dad0-11e5-94df-a4434bf33aa2.jpg)
 (getest, 24-2-16, 8.24 uur)

**Comment by gerardnienhuis** [comment]
Geldt niet alleen voor zoekteksten, maar ook voor zoeken op datum. Getest met datum 5 december 2015. Zoeken naar kaarten uit die periode leverde alle records op, wat niet correct is.

**Comment by gerardnienhuis** [comment]
Zoeken in IE 11 lijkt ook niet goed te werken (zoeken naar zoektekst levert alle records, omdat zoektekst uniek was, klopt dat niet)

**Comment by SandroNeumann** [comment]
Je hebt niet goed op de zoekknop geklikt. Je kunt het aan de url zien, waar niets achter .nl staat. Vergelijk het met onderstaand screenshot.

![image](https://cloud.githubusercontent.com/assets/10757125/13280598/3c61e6de-dadf-11e5-969f-e5038e080b9c.png)

**Comment by gerardnienhuis** [comment]
zoektekst van alternatieve eindverantwoordelijke wordt niet gevonden. Wordt er wel op alle items gezocht, die kunnen worden ingevoerd? Ik heb een eindverantwoordelijke ingevoerd met de naam "alternatieve naam" maar bij zoeken is van dat record niets te vinden als je zoekt op "alternatieve" of op "naam".

**Comment by gerardnienhuis** [comment]
zoeken blijkt wel te werken als je zoekknop indrukt: bij enter lijkt zoeken niet altijd goed te gaan. Ik zoek voorbeelden die dit illustreren.

**Comment by gerardnienhuis** [comment]
Lijkt te maken te hebben bij opslaan en valideren (er was bij dit record ook geen onderwerp): 
issue gesloten, heeft te maken met andere issues die al opgevoerd zijn of worden
