### ISSUE TITLE
Statische kaarten wordt Overige data

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#752]
Wens is dat in het Geoportaal de term "statische kaarten" wordt vervangen door "overige datasets". 
Dat moet overal worden aangepast, dus zowel in het onderdeel "uitgebreid zoeken" als in de pagina waarop de metadata van de data zichtbaar is.

**Comment by SandroNeumann** [comment]
Het was al zo op acceptatie op de pagina uitgebreid zoeken:

https://acc-intern.geoportaaloverijssel.nl/search

Op de metadata pagina gaan we doen.

**Comment by gerardnienhuis** [comment]
Is nu correct bij de onderdelen UITGEBREID ZOEKEN en OVER DEZE SITE.  Issue kan gesloten.
