### ISSUE TITLE
Beleidsinformatie@overijssel.nl veranderen in kennishub@overijssel.nl

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#753]
Op een aantal plaatsen wordt nog Beleidsinformatie@overijssel.nl gebruikt. Dit moet worden veranderd in kennishub@overijssel.nl

**Comment by gerardnienhuis** [comment]
staat in download scherm van metadata, details tabl van metadata en help scherm

**Comment by SandroNeumann** [comment]
Ik zie dat kennishub staat op:

https://acc-intern.geoportaaloverijssel.nl/help
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/cd8e827d-fd3f-2e68-8aa4-dcd01ba7f254
https://acc-download.geoportaaloverijssel.nl/download/vector/abc26a8c-2aea-4356-8a89-0661522c48a8

Kijk je soms op productie?

**Comment by gerardnienhuis** [comment]
Vreemd: ik dacht dat volledige versie 1.5.4. op productie was gezet. Dat blijkt niet het geval. Op acceptatie staat het wel correct, maar op productie niet. Moet bij volgende productiegang dus opgelost worden. Nu staat het op productie niet goed, op acceptatie wel.

2 voorbeelden:

productie contact pagina:
De informatie in het Geoportaal wordt beschikbaar gesteld door het team Beleidsinformatie van de provincie Overijssel.
Heb je vragen, suggesties of tips, aarzel dan niet contact op te nemen.
Stuur je email naar: beleidsinformatie@overijssel.nl

Acceptatie contact pagina:
De informatie in het Geoportaal wordt beschikbaar gesteld door het team Beleidsinformatie van de provincie Overijssel.
Heb je vragen, suggesties of tips, aarzel dan niet contact op te nemen.
Stuur je email naar: kennishub@overijssel.nl


Productie help pagina:
Heb je vragen over het Geoportaal? Of heb je tips of suggesties? Of wil je op de hoogte blijven van de laatste ontwikkelingen?
Neem dan contact op met ons. Mail naar beleidsinformatie@overijssel.nl

Acceptatie help pagina:
Heb je vragen over het Geoportaal? Of heb je tips of suggesties? Of wil je op de hoogte blijven van de laatste ontwikkelingen?
Neem dan contact op met ons. Mail naar kennishub@overijssel.nl

**Comment by SandroNeumann** [comment]
De omgevingsvariabele op de productie server van die email vergeten te veranderen. Dat moet gebeuren.

Snelle fix. Maar we nemen dit mee met eventueel andere werk die we nog moeten verzetten.

**Comment by SandroNeumann** [comment]
Dit geldt ook voor de download mail en de stylesheet (metadata document).

**Comment by gerardnienhuis** [comment]
is niet te testen op acceptatie want de omgevingsvariabele is al aangepast op acceptatie. Gewoon productie controleren als het zover is (volgende productiegang)

**Comment by gerardnienhuis** [comment]
blijkt wel zichtbaar op acceptatie: zowel bij help als bij download pagina. werkt goed en issue kan gesloten worden
