### ISSUE TITLE
Request rapportage met extra kolommen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#754]
Wens via url rapport opvragen van requests, met aantal extra kolommen zoals ip_provincie (als ip adres van provincie is, dan is dit ja, en dus intern)

**Comment by SandroNeumann** [comment]
In de url komt een parameter waarmee je kunt aangeven of je de laatste 7, 31 of 365 dagen wilt downloaden.

Tevens worden er rapporten 'klaargezet' per jaar op de server in het geval die geraadpleegd willen worden.

**Comment by SandroNeumann** [comment]
De procedure rond het downloaden van een rapport gaat zo werken:

- je krijgt een tekst te zien dat het maken van het rapport gestart is en dat je een downloadlink te zien krijgt als het klaar is
- de download link wordt getoond en je kunt gaan downloaden
- het formaat van het bestand is een zip ipv een csv, in de zip zit uiteraard de csv

**Comment by gerardnienhuis** [comment]
optie komt beschikbaar bij de plaats waar nu de rapporten beschikbaar worden gesteld. Er staat nu;
- geodata
- services
- statische kaarten 
- download

Dat wordt dan:
- geodata
- services
- services gebruik
- statische kaarten
- download
-

**Comment by gerardnienhuis** [comment]
het blijkt erg lastig om de gegevens goed te verwerken. Voorstel is om het python script achterwege te laten (op dit moment).
Dus gewoon zoals in eerdere versies alle requests opslaan en als zip bestand leveren.
Voorstel is wel dat er een paar kolommen verwijderd of samengevoegd worden:
- datum_tijd: hoeft niet opgeslagen
- layer en layers: layer van maken, zijn altijd hetzelfde
- aantal en duur: kan weg

**Comment by gerardnienhuis** [comment]
Dit kan ik nog niet testen, want ik heb de url niet waarmee ik het rapport kan maken. Bedoeling is ook dat het rapport vergelijkbaar met de andere rapporten wordt gemaakt in het onderdeel rapporten. Ik wacht met testen, totdat het rapport van requests via deze manier beschikbaar is.

**Comment by gerardnienhuis** [comment]
zie ook: https://github.com/IDgis/geoportaal-test/issues/784

**Comment by gerardnienhuis** [comment]
per ongeluk gesloten en nu weer geopend:
 ik wacht nu op het correct werken van het andere issue:  https://github.com/IDgis/geoportaal-test/issues/784

**Comment by gerardnienhuis** [comment]
label gebruikerstest verwijderd, wacht op oplevering van #784

**Comment by gerardnienhuis** [comment]
date start en date time toevoegen: url is voor rest klaar. levert mogelijk groot bestand met kans op time out error, dus eerst proberen met beperkt aantal dagen

**Comment by SandroNeumann** [comment]
Het toevoegen van date_start en date_end aan de rapportage is toegevoegd.

Zie bijv:

https://acc-report.geodataoverijssel.nl/request_extra_info?date_start=2022-12-24&date_end=2022-12-31

**Comment by ReinderHoekstraPOV** [comment]
Ik zal dit binnenkort gaan testen.

**Comment by gerardnienhuis** [comment]
@ReinderHoekstraPOV : graag verschillende periodes testen en kijken of de bestanden nog gemaakt kunnen worden. Ook graag als voorbeeld een paar kleine bestanden bewaren voor inlezen tableau

**Comment by gerardnienhuis** [comment]
resultaat bestanden gecontroleerd: het lijkt alsof de kolommen en informatie voor download en statische kaarten ontbreken.

**Comment by SandroNeumann** [comment]
Dit rapport gaat alleen over de wms/wfs en restapi requests. Daar zijn de kolommen zoals je ziet ook op gestoeld (geodata).

We hebben aparte rapporten voor download en statische kaarten.

Misschien moeten we overleggen wat je precies wilt.

**Comment by gerardnienhuis** [comment]
Onze wens is om later in dit rapport deze informatie toe te voegen, als aparte kolommen. Rapport is goed leesbaar en bevat voldoende info. Als niet relevant, dan wordt de waarde niet ingevuld. Issue kan daarom gesloten.
