### ISSUE TITLE
Kolom aantal_gekoppelde_datasets_zonder_filter aan rapport dataset toevoegen

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#757]
Er is een kolom die heet aantal_gekoppelde_datasets. Daarnaast moet een kolom komen die heet aantal_gekoppelde_datasets_zonder_filter. Op basis daarvan kan bepaald worden 1) of er minimaal 1 dataset bestaat zonder filter (in het geval er sowieso minimaal 1 koppeling is) 2) hoeveel gefilterde datasets er bestaan

**Comment by gerardnienhuis** [comment]
Deze oplossing is technisch misschien correct, maar voor gebruikers van het rapport wel erg onduidelijk. Ik stel voor om 3 kolommen toe te voegen:

Data_gekoppeld: heeft als mogelijke vulling "ja" of "nee"
Filter: heeft als mogelijke vulling  "ja" of "nee"
Filter_zonder_datakoppeling: heeft als mogelijke vulling  "ja" of "nee"

Functioneel gebruik van deze informatie:

Data_gekoppeld is "nee": dan moet FB publicatieomgeving deze koppeling nog maken. "ja": geen acties nodig
Filter: heeft als mogelijke vulling  "ja" of "nee": ter info, hoef je nu nog niets meer te doen. Handig om te weten bij vragen.
Filter_zonder_datakoppeling: is "nee", dan moet FB publicatieomgeving alsnog de datakoppeling aanbrengen: let wel, dat is dus de koppeling naar het originele ongefilterde bestand. "ja" geen acties nodig

**Comment by SandroNeumann** [comment]
@gerardnienhuis 
Ik ga de kolommen noemen:

dataset_gekoppeld
dataset_heeft_filter
dataset_heeft_origineel_bestand

Mee eens?

**Comment by gerardnienhuis** [comment]
dataset_gekoppeld: **akkoord**
dataset_heeft_filter: **akkoord**

dataset_heeft_origineel_bestand: **niet akkoord**. ik begrijp nu niet hier mee wordt bedoeld. Voorstel:
dataset_met_filter_en_datakoppeling: als dat ja is, dan is alles goed, als het nee is, dan moet in publicatieomgeving iets worden aangepast

**Comment by SandroNeumann** [comment]
Persoonlijk vind ik dataset_met_filter_en_datakoppeling juist niet duidelijk omdat een filter ook een datakoppeling heeft. Dus mij zou die niet meer zeggen dan de kolom dataset_heeft_filter. Maar als dat voor jullie wel duidelijk is dan gebruik ik die naam.

**Comment by SandroNeumann** [comment]
Kolommen:

dataset_gekoppeld (ja/nee)
dataset_heeft_filter (ja/nee)
dataset_heeft_alleen_gefilterde_koppelingen (ja/nee/nvt)

**Comment by gerardnienhuis** [comment]
Dat wil dus zeggen dat als dataset_heeft_alleen_gefilterde_koppelingen = ja, er een probleem is.

in dat geval staat niet het originele bronbestand in het geoportaal en ook niet de gefilterde bestanden.

In geval van "nee": dan zijn er koppelingen zonder filter (is dus OK)
in geval van "nvt":  dan zijn er helemaal geen koppelingen van het bronbestand

**Comment by gerardnienhuis** [comment]
getest door nieuw rapport te maken: 

dataset_gekoppeld: lijkt onjuist, heeft waarde ja, nee en 0 (0 komt 1 keer voor, lijkt bug)

dataset_heeft_filter: lijkt correct, heeft alleen waarde ja en nee

dataset_heeft_alleen_gefilterde_koppelingen: kolom lijkt afwezig, had ik direct rechts van de 2 bovengenoemde kolommen verwacht

Er is wel een nieuwe kolom, maar daarvan ken ik betekenis niet: 
dataset_heeft_origineel_bestand

**Comment by SandroNeumann** [comment]
Ik denk dat dat je bij dataset_gekoppeld 0 ziet iets mis is met de excel instellingen want ik zie dat niet:

![image](https://user-images.githubusercontent.com/10757125/191196220-1709ac0f-050a-480a-aa61-901915d396fb.png)

Vermoedelijk zijn de kolom indelingen niet helemaal goed en komt die 0 uit de vorige kolom.

Mijn instellingen:

![image](https://user-images.githubusercontent.com/10757125/191196614-4408ce08-f4c8-4121-8786-7b06872c2496.png)

De kolom dataset_heeft_origineel_bestand betekent dat er een dataset is gekoppeld zonder filter (dus het volledige originele bestand). Ik zie nu dat we inderdaad de andere kolom hadden afgesproken: dataset_heeft_alleen_gefilterde_koppelingen. Dat ga ik wijzigen.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

De kolom is aangepast en staat op acceptatie.

**Comment by gerardnienhuis** [comment]
Nieuw rapport gemaakt, lijkt nu allemaal wel te kloppen.

dataset_gekoppeld: lijkt nog steeds onjuist, heeft waarde ja, nee en 0 (0 komt 1 keer voor, lijkt bug in excel niet in rapport, later een keer uitzoeken als het vaker voorkomt, nu geen verdere actie nodig)

dataset_heeft_filter: lijkt correct, heeft alleen waarde ja en nee

dataset_heeft_alleen_gefilterde_koppelingen: kolom is nu ook aanwezig en gevuld.

Issue kan gesloten
