### ISSUE TITLE
Fout verwerking creative commons

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#758]
Sinds wij de nieuwere versie van geosticker gebruiken, gaat er wat fout in de verwerking van de creative commons vermeldingen.

probleem lijkt te zijn dat geosticker de xml net op een andere manier in elkaar heeft gezet, hiervoor. Voorbeelden hieronder. Gevolg is dat de cc niet meer in het geoportaal bij de details zichtbaar is, en dat het ook in het rapport van geodata fout vermeld staat.

Wens is dat ook de nieuwe geosticker xml goed wordt verwerkt in het geoportaal. 

Details: 

2 voorbeelden: 

1 gaat wel goed, is oude geosticker xml versie,
2e gaat niet goed, is nieuwe xml versie

===============================================

oude xml versie, gaat wel goed:

bo.kmbolk_polygon.xml

resourceConstraints>
          MD_LegalConstraints>
            accessConstraints>
              MD_RestrictionCode codeList="./resources/codeList.xml#MD_RestrictionCode" codeListValue="otherRestrictions" />
            /accessConstraints>
            otherConstraints>
              gco:CharacterString>https://creativecommons.org/publicdomain/zero/1.0/deed.nl</gco:CharacterString>
            /otherConstraints>
          /MD_LegalConstraints>
        /resourceConstraints>

Bestandsnaam: Indeling km-hokken vlakken 1000 x 1000 m
https://intern.geoportaaloverijssel.nl/metadata/dataset/83e77f02-9966-4027-8cc0-d4fe96624755 

Laatste wijziging bestandsbeschrijving: 26-03-2020

Gebruiksbeperkingen: Geen gebruiksbeperkingen
Gebruiksbeperkingen: Geoportaal extern
Gebruiksbeperkingen: Downloadable data
Overige beperkingen: Geen beperkingen
Overige beperkingen: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
(Juridische) toegangsrestricties: Anders

=========================================

nieuwe xml, lijkt fout te gaan:
nb: eerste < weggehaald in xml code, anders was het niet zichtbaar in github...

bo.kmlijn.arc:

resourceConstraints>
MD_LegalConstraints>
accessConstraints>
MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions" codeSpace="ISOTC211/19115">otherRestrictions</MD_RestrictionCode>
/accessConstraints>
otherConstraints>
gco:CharacterString xlink:href="http://creativecommons.org/publicdomain/zero/1.0/deed.nl">Geen beperkingen</gco:CharacterString>
/otherConstraints>
/MD_LegalConstraints>
/resourceConstraints>

Bestandsnaam: Indeling km-hokken (lijnen)
https://intern.geoportaaloverijssel.nl/metadata/dataset/04d0e433-cf96-4074-bd2f-8ce7550442d4

Laatste wijziging bestandsbeschrijving: 31-03-2022

Gebruiksbeperkingen: Geen gebruiksbeperkingen
Gebruiksbeperkingen: Geoportaal extern
Gebruiksbeperkingen: Downloadable data
Overige beperkingen: Geen beperkingen
(Juridische) toegangsrestricties: Anders

**Comment by gerardnienhuis** [comment]
[fout_km_cc_zero.zip](https://github.com/IDgis/geoportaal-test/files/8395694/fout_km_cc_zero.zip)

hierbij ook de 2 xmls in zip, als voorbeeld

**Comment by SandroNeumann** [comment]
De creative commons is in de nieuwe situatie een xlink geworden en geen apart element. We moeten hierop controleren en er zo nodig een element van maken.

**Comment by SandroNeumann** [comment]
Het verschil is:

OUD:
```
<otherConstraints>
  <gco:CharacterString>Geen beperkingen</gco:CharacterString>
</otherConstraints>
<otherConstraints>
  <gco:CharacterString>https://creativecommons.org/publicdomain/zero/1.0/deed.nl</gco:CharacterString>
</otherConstraints>
```

NIEUW:
```
<otherConstraints>
  <gco:CharacterString xlink:href="http://creativecommons.org/publicdomain/zero/1.0/deed.nl">
    Geen beperkingen
  </gco:CharacterString>
</otherConstraints>
```

@gerardnienhuis 
De link zit dus in een attribuut en niet meer in een apart otherConstraints element. Is dit iets wat wij in onze metadata generator moeten regelen of kunnen jullie dit vanuit GeoSticker aangeven?

**Comment by gerardnienhuis** [comment]
dat kunnen we niet in Geosticker aangeven en ik hoop dat het aan jullie kant met de metadata generator kan worden gedaan

**Comment by SandroNeumann** [comment]
Ok, gaan we doen

**Comment by gerardnienhuis** [comment]
lijkt nog niet altijd goed te gaan, zie:

Digitale Vegetatiekaart Overijssel
B4.vegetatie_DVO (B4/B47)
https://intern.geoportaaloverijssel.nl/metadata/dataset/71f01a17-929b-475f-93a1-d50157a4bcc1

Bij DETAILS staat van alles, maar geen creative commons:


Trefwoord: Downloadable Data

Gebruiksbeperkingen: Geoportaal extern
Gebruiksbeperkingen: Alleen WMS extern

(Juridische) toegangsrestricties: Intellectueel eigendom
Metadata unieke identifier: 71f01a17-929b-475f-93a1-d50157a4bcc1
Metadata taal: Nederlands
Metadata karakterset: utf8
Metadata hiërarchieniveau: Dataset
Metadata standaard naam: ISO 19115
Metadata standaard versie: Nederlands metadata profiel op ISO 19115 voor geografie 2.0

Taal van de bron: Nederlands
Karakterset van de bron: utf8
Unieke identifier: 63a2bc7b-2cbb-435e-8931-a05cb30277b1
Niveau kwaliteitbeschrijving: Dataset
Niveau kwaliteitbeschrijving: Dataset

**Comment by SandroNeumann** [comment]
Dat komt omdat die dataset beperkingen heeft.

Wanneer je zoekt op "Geen beperkingen": https://intern.geoportaaloverijssel.nl/search?text=Geen+beperkingen&types=dataset

Dan zie je de creative commons url bij bijv: https://intern.geoportaaloverijssel.nl/metadata/dataset/82234fb2-eb09-4e4b-92e0-2d998b3bf936

**Comment by SandroNeumann** [comment]
Je ziet creative commons URL's alleen wanneer bij Overige beperkingen "Geen beperkingen" staat.

**Comment by gerardnienhuis** [comment]
Nee, dat is niet de bedoeling. Volgens mij heeft het altijd zo gewerkt. Als er een cc-url is ingevoerd in geosticker, dan komt deze in de xml. En als deze in de xml zit, dan moet deze altijd in het Geoportaal zichtbaar zijn.

**Comment by SandroNeumann** [comment]
Dat is het punt. Hij zit niet in de XML. Een creative commons URL betekent dat het open data is (althans als het mark of zero is) en dat is bij deze dataset niet het geval want er staat "(Juridische) toegangsrestricties: Intellectueel eigendom"

Wij tonen inderdaad altijd de creative commons URL als die bestaat. Ik geef alleen de reden aan waarom deze bij deze dataset ontbreekt.

**Comment by SandroNeumann** [comment]
In overleg met Gerard besproken dat de creative commons URL alleen getoond wordt bij open data. Dat is al het geval en daarom kan dit issue gesloten worden.
