### ISSUE TITLE
Trefwoorden en onderwerpen in rapport geodata toevoegen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#761]
graag 2 kolommen toevoegen aan rapport geodata: trefwoorden en onderwerpen

deze info zit wel in de xml, maar ontbreekt nog in rapport zelf

**Comment by gerardnienhuis** [comment]
omdat impact laag is, graag toevoegen aan meest recente versie (1.5.4.)

**Comment by gerardnienhuis** [comment]
Dit lijkt niet allemaal goed te gaan, zie onderstaand voorbeeld:

Bestandsnaam: Landelijk Grondgebruik Nederland - LGN2020
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/f77a1f4d-9ce7-40f6-ba4b-ebbff32cb13a

lijkt niet duidelijk waar keywords vandaan komen

bij details in metadata:

Onderwerp: Referentie materiaal aardbedekking

Thesaurus trefwoorden: GEMET - Themes, version 2.4
Publicatie datum thesaurus: 13-01-2010
Trefwoord: Landgebruik
Thesaurus trefwoorden: GEMET - INSPIRE themes, version 1.0
Publicatie datum thesaurus: 01-06-2008
Trefwoord: Landgebruik

volgens rapport:

keywords: bodem|bodemfunctie|bodem
topics: inlandWaters|imageryBaseMapsEarthCover

**Comment by SandroNeumann** [comment]
Ja, dat is de discrepantie tussen de echte waarde en het Nederlandse label. In de XML staat ook de echte waarde maar de XSLT maakt die vertaalslag.

Zal ik dat ook in het rapport doen?

**Comment by gerardnienhuis** [comment]
hoeft niet vertaald te worden, maar lijkt nu niet volledig correct

**Comment by SandroNeumann** [comment]
Ik zie dit in het rapport bij deze dataset:

Landgebruik|Landgebruik
imageryBaseMapsEarthCover

Dit komt overeen met de XML.

ID is 60915 en identification is 283bc358-ade6-4301-a093-2b446b85b683

Heb je misschien het rapport van productie opgehaald?

**Comment by SandroNeumann** [comment]
URL acceptatie is: https://acc-report.geodataoverijssel.nl/dataset

**Comment by gerardnienhuis** [comment]
Het lijkt goed te werken, steekproefsgewijs gecontroleerd. Zowel onderwerpen als trefwoorden staan in het rapport. Dit issue kan gesloten.
