### ISSUE TITLE
Nieuw keuzeveld in formulier om type onderzoek aan te geven

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/geoportaal-test#763]
In het formulier is een nieuw invoerveld bijgekomen om het type onderzoek aan te geven. Bij default is deze leeg. Mogelijke waardes die gekozen kunnen worden zijn:
- Beleidsrapport
- Notitie
- Onderzoeksrapport

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, gecontroleerd en de typen onderzoek zijn goed terug te vinden in de onderzoeksbank. Issue kan gesloten
