### ISSUE TITLE
Type onderzoek meenemen in metadata XML

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/geoportaal-test#764]
Het type onderzoek moet nog mee worden genomen in de metadata XML. Dit veld komt niet voor in de ISO standaard voor metadata.

@gerardnienhuis - hoe moet dit veld in de metadata XML terecht komen?

**Comment by gerardnienhuis** [comment]
Bij thema is dit al opgelost: 
"<dc:subject>theme: agroFood</dc:subject>"

kan er niet ook een onderdeel bij komen waarin het onderwerp staat, bijvoorbeeld onderwerp is xxxxx
"<dc:topic>topic: xxxxx</dc:topic>"

**Comment by SandroNeumann** [comment]
Na overleg met Gerard besloten dat we kunnen afwijken van de dublin core standaard

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Het element is het type onderzoek. Daar vond ik topic niet de lading dekkend dus ik heb het xml element zo genoemd:

`<dc:typeresearch>Beleidsrapport</dc:typeresearch>`

Ik hoor jouw ideeën daar graag over.

**Comment by gerardnienhuis** [comment]
prima, wat mij betreft

**Comment by gerardnienhuis** [comment]
alsnog uitbreiden: niet conform standaard is nu OK

**Comment by gerardnienhuis** [comment]
Getest, ziet er goed uit, xml gecontroleerd, bij notitie staat nu bijvoorbeeld:

<dc:typeresearch>Notitie</dc:typeresearch>

andere controle: Onderzoeksrapport ook goed:
<dcterms:relation>0000000</dcterms:relation>
<dc:type>Kaart</dc:type>
<dc:typeresearch>Onderzoeksrapport</dc:typeresearch>
<dc:creator>Provincie Overijssel: eenheid Bestuurs- en Concernzaken</dc:creator>

**Comment by gerardnienhuis** [comment]
vraag me alleen af of er nu echt een valide xml uitkomt als je NIETS invult. Dus geen type kiezen.
Dat levert op:


<dc:type>Kaart</dc:type>
<dc:typeresearch/>
<dc:creator>Provincie Overijssel: eenheid Bestuurs- en Concernzaken</dc:creator>
<dc:publisher>Provincie Overijssel</dc:publisher>

maar er is geen <dc:typeresearch> in de xml.
best om er dan van te maken:
"<dc:typeresearch><dc:typeresearch/>" denk ik

(nb: in view mode vallen tekens zoals > en < weg, hoop dat commentaar duidelijk is
in edit mode staan ze wel trouwens
beschermen met " " lijkt niet te werken

**Comment by SandroNeumann** [comment]
Wanneer het is ingevuld staat er bijv dit:
`<dc:typeresearch>Notitie</dc:typeresearch>`

Wanneer het niet is ingevuld staat er dit:
`<dc:typeresearch/>`

Dat is valide. In dat geval geef je aan dat er geen waarde is.

Je zou er ook dit van kunnen maken:
`<dc:typeresearch></dc:typeresearch>`

Maar daarmee lijk je een waarde te hebben maar heb je die eigenlijk niet (lege string). Dat is minder sterk.

**Comment by gerardnienhuis** [comment]
OK, dan begrijp ik hetnu beter. Mijn xml kennis ging niet zover, ik dacht dat een slash altijd voorgegaan moest worden door zelfde item zonder slash, maar blijkt niet geval te zijn. Ik vind de huidige gekozen oplossing prima. Issue kan gesloten worden.
