### ISSUE TITLE
Mogelijkheid voor het invullen van thema's realiseren

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/geoportaal-test#765]
In Geoportaal-beheer is een keuzelijst opgenomen voor diverse thema's. Deze komt alleen naar voren als er een type onderzoek is gekozen.

Er bestaat een keuze uit de volgende thema's:
- Agro-food
- Arbeidsmarkt
- Cultuur
- Economie
- Energie
- Landbouw
- Milieu
- Natuur
- Openbaar bestuur
- Retail
- Ruimtelijke ordening
- Sociaal
- Toerisme
- Verkeer
- Vervoer
- Water
- Wonen

**Comment by gerardnienhuis** [comment]
blijkt goed te werken, issue kan gesloten
