### ISSUE TITLE
ISO onderwerpen en thema's optioneel maken

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/geoportaal-test#767]
Afhankelijk van de keuze bij `type onderzoek` moeten er verschillende lijsten verplicht worden ingevuld.

Als er géén type onderzoek is ingevuld wordt alléén de lijst met ISO onderwerpen getoond en moet verplicht minimaal 1 onderwerp worden gekozen.

Als er wél een waarde voor type onderzoek is ingevuld wordt alléén de lijst met thema's getoond en moet er verplicht minimaal 1 thema worden gekozen.

Zie ook issues #765 en #766

**Comment by gerardnienhuis** [comment]
getest, werkt goed, vergeten te sluiten meteen. nu alsnog gesloten
