### ISSUE TITLE
Aanpassen geavanceerd zoeken met nieuwe onderzoeken

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/geoportaal-test#769]
Het standaard zoeken kon voorheen op basis van een 'gewoon' zoekterm. Daarnaast was een een optie voor uitgebreid zoeken waarbij ook op ISO onderwerpen gefilterd kon worden. Dit is nu niet meer van toepassing op onderzoeken.

Dit betekent de volgende wijzigingen voor het nieuwe geavanceerde zoeken:
- De optie om op ISO onderwerpen te zoeken is verwijderd
- Er is een zoekingang gekomen om te filteren op type onderzoek
- Er is een zoekingang gekomen om te filteren op thema

Uiteraard kunnen de verschillende opties ook gecombineerd worden voor een nog specifiekere zoekvraag.

**Comment by gerardnienhuis** [comment]
zoeken van verschillende mogelijkheden is getest: blijkt goed te werken. Issue kan gesloten.
