### ISSUE TITLE
Alleen onderzoeken tonen uit het geoportaal

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/geoportaal-test#771]
Voor de vernieuwde werking van de onderzoeksbank is het Geoportaal uitgebreid met een type onderzoek en daarbij keuze uit verschillende thema's. Om de werking van dit issue te kunnen tonen moeten er dus wel entries met een type onderzoek zijn opgeslagen.

Het testen of de juiste bestanden getoond worden is afhankelijk van de uitkomst van de volgende gebruikerstesten:
- [x] #763
- [x] #765

**Comment by gerardnienhuis** [comment]
Beide onderdelen werken goed. Getest bij invoer en ook bij onderzoeksbank zelf. Issue kan gesloten.
