### ISSUE TITLE
Sorteren Geoportaal werkt niet meer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#782]
Als je zoekt bij uitgebreid zoeken, dan kan je sorteren op:
datum datumset
datum beschrijving

Maar sorteren op datum beschrijving werkt niet meer.
Je kan die optie wel aanvinken, maar na indrukken van knop ZOEK
verspringt de selectie weer op "sorteren datumset". 

Het aanklikken van die opties heeft geen enkel effect

**Comment by SandroNeumann** [comment]
Ik denk dat dit simpelweg komt omdat de datum velden in het metadata bestand dezelfden zijn. Zie bijv: 

https://intern.geoportaaloverijssel.nl/metadata/dataset/8c9f038e-de56-49d6-83c7-5f735c1ca029

De velden die gebruikt worden zijn Laatste wijziging bestand en Laatste wijziging bestandsbeschrijving. Je ziet dat die hetzelfde zijn.

Wanneer ik hier op zoek:

https://intern.geoportaaloverijssel.nl/search?text=rups&types=dataset

Dan zie ik de volgorde ook niet veranderen (er zijn er maar 3) maar het datum veld in de titel verandert wel.

Je hoeft trouwens niet op zoek te klikken. Dan laadt hij weer de standaard instelling.

**Comment by SandroNeumann** [comment]
En hier zie je de eerste hit veranderen:

https://intern.geoportaaloverijssel.nl/search?text=drenthe&types=dataset

**Comment by gerardnienhuis** [comment]
blijkt inderdaad goed te werken, bijvoorbeeld

Bestandsnaam: Hottinger kaart 1787
https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/74d9ec7b-aec7-4ecd-a7cc-1595738a6096

Laatste wijziging bestand: 14-08-2013
Herzieningsfrequentie bestand: Niet gepland
Laatste wijziging bestandsbeschrijving: 09-02-2022

op de ene manier komt dit bestand bovenin de lijst. er wordt rekening gehouden met datum laatste wijziging bestand en datum wijziging bestandsbeschrijving. blijkt goed te werken, issue kan gesloten
