### ISSUE TITLE
Publicatiedatum weghalen in formulier geoportaal-beheer

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#786]
de publicatiedatum heeft geen rol meer bij invoeronderdeel van overige data en de onderzoeksbank
deze datum wordt namelijk overschreven als de metadata echt wordt gepubliceerd.
heeft hierdoor geen zin om nog keer apart in te laten voeren door een gebruiker

geeft bovendien bij rapporten en onderzoeken verwarring: welke datum moet nu ingevoerd worden.
door 1 datum te laten kiezen: creatie datum is dat probleem opgelost

**Comment by SandroNeumann** [comment]
De datum moet in de database blijven bestaan en het zetten ook. Het moet alleen niet meer door gebruiker ingevoerd kunnen worden. Dus opschonen uit de user interface.

**Comment by gerardnienhuis** [comment]
Dit blijkt goed te werken, publicatiedatum staat niet meer in de invoermodule. Issue kan gesloten.
