### ISSUE TITLE
Waarschuwing als leverancier status wil veranderen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#79]
Als je als leverancier je eigen records kan zien, dan is het mogelijk dat hier een aantal al gepubliceerd is. Na selecteren van zo'n record worden de knoppen voor de statusveranderingen dimmed. Logisch: je kan niet iets veranderen, als het al gepubliceerd is. 

Voor iemand die die logica niet goed kent (veel leveranciers) is dat lastig. Kan er een scherm komen, als er zo'n selectie is uitgevoerd. Voorstel tekst:

U heeft 1 of meerdere records geselecteerd, die reeds zijn gepubliceerd. U kunt hiervan niet de status veranderen. Wilt u toch de status veranderen, neem dan contact op met de beheerders van het Geoportaal. 

Knop eronder: "Ga verder"

![status_veranderen_kan_niet](https://cloud.githubusercontent.com/assets/9005444/13283423/094557b8-daee-11e5-9ae8-6eea0a65fc4d.jpg)

**Comment by SandroNeumann** [comment]
@gerardnienhuis: Wil je dit nog steeds? Ik meen me te herinneren dat je een keer zei dat de leveranciers dit toch wel goed vonden. Ik denk ook dat constant een pop-up bij selectie van een gepubliceerd record gaat irriteren. Misschien is het beter een stuk tekst parallel met het dimmen van de knoppen te implementeren, die dat uitlegt.

**Comment by gerardnienhuis** [comment]
Stuk tekst klinkt als prima voorstel.

Verstuurd vanaf mijn iPhone

Op 7 mrt. 2016 om 16:51 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis: Wil je dit nog steeds? Ik meen me te herinneren dat je een keer zei dat de leveranciers dit toch wel goed vonden. Ik denk ook dat constant een pop-up bij selectie van een gepubliceerd record gaat irriteren. Misschien is het beter een stuk tekst parallel met het dimmen van de knoppen te implementeren, die dat uitlegt.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/79#issuecomment-193310202.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
getest: blijkt nu goed te werken: heldere tekst
