### ISSUE TITLE
Thumbnails ontbreken (gevonden op 28-11-22)

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#790]
Het lijkt dat veel thumbnails ontbreken: gezien zowel in extern als intern geoportaal op 28-11-22. zie ook bijgevoegd plaatje. Lijkt vooral op te treden bij meest recent aangepaste metadatasets, maar ook oudere metadata heeft dit probleem. Deel thumbnails is wel aanwezig, deel is afwezig.

**Comment by gerardnienhuis** [comment]
![thumbnails_afwezig](https://user-images.githubusercontent.com/9005444/204230376-6118376c-7165-41ec-934c-27179d00fbd4.jpg)

**Comment by gerardnienhuis** [comment]
hierbij overzicht ontbrekende thumbnails, voorbeeld intern geoportaal

**Comment by SandroNeumann** [comment]
De harvesting naar het Geoportaal was gestopt sinds zaterdag avond. Ik heb dat component herstart en de thumbnails zijn ververst en dus weer te zien.

**Comment by gerardnienhuis** [comment]
Getest: gecontroleerd door meerdere pagina's door te bladeren: van alle geodatasets blijkt weer thumbnail aanwezig. Zowel recente als oudste metadata gecontroleerd en blijkt allemaal goed te zijn nu. Issue kan gesloten worden.
