### ISSUE TITLE
Reinder Hoekstra als beheerder toevoegen en email aanpassen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#791]
Hierbij verzoek om gegevens van Reinder Hoekstra aan te passen:
rol wordt: beheerder (dus niet leverancier)
email wordt: r.hoekstra@overijssel.nl

**Comment by SandroNeumann** [comment]
Hij was al beheerder maar onder r.hoekstra@zwolle.nl 

Ik heb dat veranderd naar r.hoekstra@overijssel.nl

Wachtwoord blijft dan hetzelfde en als hij dat niet meer weet dan kan hij het wachtwoord resetten.

**Comment by gerardnienhuis** [comment]
Reinder blijkt als beheerder onder zijn email van de provincie in te loggen. Issue is goed verwerkt en kan gesloten worden.
