### ISSUE TITLE
Bij grid download link en arcgis rest link onterecht aanwezig

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#798]
Grids kunnen nu nog gedownload worden, lijkt het. Maar dat is nu nog niet het geval. Toch wordt er een download link getoond, wat tot verwarring blijkt te leiden. Verzoek: als het een grid is, dan download link NOOIT tonen, zelfs niet als er staat: downloadable data, 
Ook arcgis rest niet tonen in dit geval

let op: WMS moet wel als link zichtbaar blijven

zie 

Bestandsnaam: Stedelijk hitte eiland effect
https://www.geoportaaloverijssel.nl/metadata/dataset/874ffdd7-c98f-45c2-9d2f-8462f8f09ae4

Alternatieve titel: LIP.Klimaat_Stedelijkhitteeiland

Status: Compleet
Download: https://download.geoportaaloverijssel.nl/download/raster/874ffdd7-c98f-45c2-9d2f-8462f8f09ae4
Viewer: https://services.geodataoverijssel.nl/viewer/layer/LIP/LIP_Stedelijk_hitte_eiland_effect
Dataset metadata url: https://www.geoportaaloverijssel.nl/metadata/dataset/874ffdd7-c98f-45c2-9d2f-8462f8f09ae4
Service metadata url: https://www.geoportaaloverijssel.nl/metadata/service/70101044-e736-44a5-97b8-43ef4b0c3919
OGC:WMS: https://services.geodataoverijssel.nl/geoserver/LIP/wms
ArcGIS Rest: https://arcgisrest.geodataoverijssel.nl/arcgis/rest/services/LIP/FeatureServer
XML: https://www.geoportaaloverijssel.nl/metadata/dataset/874ffdd7-c98f-45c2-9d2f-8462f8f09ae4?noStyle=true

**Comment by SandroNeumann** [comment]
Je kunt rasters wel downloaden.

Zie: https://www.geoportaaloverijssel.nl/metadata/dataset/35f35c7b-386a-4c02-8acb-fd46deedddee

Ik denk dat er iets mis is met de raster van de dataset uit de omschrijving.

Hoe het met de Rest-API zit moet uitgezocht worden. Op dit moment lijkt elke dataset (ook vector) een foutmelding te geven.

Eerst afstemming hierover voor inschatting.

**Comment by SandroNeumann** [comment]
Er zijn nieuwe inzichten. Zie: #823 #824

**Comment by gerardnienhuis** [comment]
De bedoeling is dat dit anders wordt opgepakt, zie ook meldingen #823 en #824. Dit issue hoeft daarom niet meer opgepakt te worden en kan gesloten worden.
