### ISSUE TITLE
Foutmelding bij opslaan DC metadata

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#8]
@PeterAukeNicolaij  meldt: Ik heb een record willen opslaan maar krijg de volgende melding:
![image](https://cloud.githubusercontent.com/assets/2979044/12481298/6fa5a352-c048-11e5-91a8-d348a150a10e.png)

**Comment by HermanAssink** [comment]
Hallo @PeterAukeNicolaij : Weet je hoe dit probleem kunnen reproduceren? Wij kunnen namelijk probleemloos records toevoegen

**Comment by gerardnienhuis** [comment]
Ik krijg vergelijkbare meldingen bij het toevoegen van grote bestanden of het toevoegen van veel middelgrote bestanden, die bij 1 bepaalde kaart horen

**Comment by gerardnienhuis** [comment]
lijkt heel erg op fout bij te veel of te grote bijlagen, zie https://github.com/IDgis/geoportaal-test/issues/29
fout is nu nog niet te reproduceren hier. In de gaten hoiuden, maar issue kan hier wel gesloten
