### ISSUE TITLE
Metadata zichtbaar op Home pagina op basis van datum laatste wijziging metadata

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#801]
Nu kan het gebeuren dat bij een test je het bestand wat je het laatst gemaakt hebt, niet terugziet op de HOME pagina van het Geoportaal. Dat komt dan omdat er wordt gesorteerd op datum laatste wijziging bestand ipv op datum laatste wijziging bestandbeschrijving. Wens is dat de sortering wel wordt gemaakt op basis van datum laatste wijziging bestandbeschrijving. 

Hierdoor zou de metadata die je op een gegeven moment hebt aangepast, ook altijd op de home pagina zichtbaar moeten komen (na een tijdje natuurlijk ivm de doorlooptijd van de harvesters).

**Comment by gerardnienhuis** [comment]
wordt getest, lastig ivm afwezigheid goede acceptatieomgeving met Geosticker. De oplossing:. xml van productie wordt verplaatst naar map acceptatieomgeving, die wel geharvest kan worden. Details:

Wel eerst metadata aanpassen, zodat datum laatste wijziging metadata verandert en dan publiceren
Maar niet wijziging datum bestand aanpassen.

[https://intern.geoportaaloverijssel.nl/metadata/dataset/5126bad2-7aca-4388-8019-54ca3675e039](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintern.geoportaaloverijssel.nl%2Fmetadata%2Fdataset%2F5126bad2-7aca-4388-8019-54ca3675e039&data=05%7C02%7CG.Nienhuis%40overijssel.nl%7Cae7258b00aee44a15c7c08dc4743d848%7C198fc6c4dbc7447182ef764d9e62caf1%7C0%7C0%7C638463603998221317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=8jLbvrzocrOCNEXWBHqAfeclXhkVnSfoVSRgcXBstmM%3D&reserved=0)
Bestandsnaam: Provinciegrenzen van Nederland - TEST TEST TEST
Voltooiing bestand: 13-06-2006
Publicatie bestand: 09-02-2024
Laatste wijziging bestand: 01-01-2023
Volgende herziening bestand: 20-03-2023
Herzieningsfrequentie bestand: Jaarlijks
Laatste wijziging bestandsbeschrijving: 09-02-2024

**Comment by gerardnienhuis** [comment]
Dit blijkt correct te werken, bestand met datum metadata "vandaag" staat nu wel op Home pagine.
Dit issue kan gesloten

**Comment by gerardnienhuis** [comment]
Deze oplossing blijkt voor gebruikers erg ongunstig. Bij het tabblad UITGEBREID ZOEKEN zie je iets anders (schijnbaar) dan bij de HOME pagina. Deze verwarring is zo groot dat het verzoek is om in versie 1.5.5. toch te sorteren op de home pagina op datum dataset (dus zoals het nu in de huidige productieversie al het geval is). Sorteren op datum metadata moet dus niet worden toegepast. Niet op HOME en ook niet default op UITGEBREID ZOEKEN. Verzoek is om dit issue dus niet uit te rollen op productie.

**Comment by gerardnienhuis** [comment]
Kan dat?

**Comment by SandroNeumann** [comment]
Ja, we gaan deze aanpassing terugdraaien.

**Comment by gerardnienhuis** [comment]
zojuist getest, sortering van "HOME" en "UITGEBREID ZOEKEN" zijn weer hetzelfde. Op basis van feedback van gebruikers bleek dit toch de voorkeur te hebben. Verschillende sorteringen blijken te verwarrend. Issue kan nu gesloten worden.
