### ISSUE TITLE
Metadata met herzieningsfrequentie wekelijks niet op HOME laten zien

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#805]
Wens is, vergelijkbaar met eerdere wens, om ook metadata van geodatasets met herzieningsfrequentie "wekelijks" niet op de HOME pagina van het Geoportaal weer te geven. Die filtering wordt nu al uitgevoerd voor "dagelijks", zie: 

https://github.com/IDgis/geoportaal-test/issues/718

**Comment by SandroNeumann** [comment]
Duplicaat van #808

**Comment by gerardnienhuis** [comment]
Dit is inderdaad een duplicaat, dit issue kan daarom gesloten worden.
