### ISSUE TITLE
Milou Nederstigt rechten beheerder

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#806]
Voor beheer van metadata heeft een nieuwe medewerker (Milou Nederstigt) extra rechten nodig. Ze heeft al rechten als leverancier van "overige data" maar ze moet ook als beheerder toegang krijgen zodat ze geleverde overige data kan publiceren.

naam: Milou Nederstigt
email: m.nederstigt@overijssel.nl

**Comment by SandroNeumann** [comment]
Ze heeft beheerder rechten gekregen

**Comment by gerardnienhuis** [comment]
Dit blijkt goed te werken, Milou heeft dit succesvol getest: issue kan gesloten
