### ISSUE TITLE
Attributen van een tabel onterecht niet aanwezig in Geoportaal bij DETAILS

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#807]
Hier lijkt sprake van een bug. Wij bieden van een dataset wel de attributen aan, aan het Geoportaal. Maar deze worden uiteindelijk niet zichtbaar in het Geoportaal (en ook niet in de xml die in het Geoportaal staat). Merk op: dit betreft een tabel, die gepubliceerd is in het interne Geoportaal. 

bestandnaam is:  LISA data geaggregeerd op sector
link naar de metadata: https://intern.geoportaaloverijssel.nl/metadata/dataset/c2b89281-2ba4-495c-8ccd-544dc1f78b9d

Bijgevoegd in zip is de xml die zoals die wordt aangeboden aan het Geoportaal.

nb: meestal bieden we Geodata aan, aan het Geoportaal. Maar ook tabellen komen voor, met attribuutinformatie. Wens is dat zowel tabellen als geodatasets goed worden verwerkt. Meestal is het ook het geval. Onduidelijk is, waarom de verwerking van de metadata van de attributen nu niet goed verloopt.

[Metadata_zonder_attributen_in_Geoportaal_XML.zip](https://github.com/IDgis/geoportaal-test/files/11554243/Metadata_zonder_attributen_in_Geoportaal_XML.zip)

**Comment by SandroNeumann** [comment]
Ik zie dat de tabel niet bestaat:

![image](https://github.com/IDgis/geoportaal-test/assets/10757125/f48c25a8-b87b-4a83-b4d6-ae457cfb9ba8)

Waarschijnlijk is dat de reden.

**Comment by mnederstigt** [comment]
We waren vergeten leesrechten aan het raadpleeg-account op deze tabel toe te kennen. Het probleem is nu opgelost.

**Comment by gerardnienhuis** [comment]
Probleem is opgelost, bleek inderdaad menselijke fout. Handleiding wordt aangepast. Dit issue kan gesloten.
