### ISSUE TITLE
verwijderen rechten Reinier vd Anker statische kaarten

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#809]
Mogelijk heeft Reinier vd Anker nog beheerrechten bij de module voor overige data (statische kaarten). Zie ook: https://github.com/IDgis/geoportaal-test/issues/607 

Wens is om Reinier wel als persoon (leverancier) aanwezig te houden, maar zijn beheerrechten (als die er nog zijn) moeten ingetrokken worden.

**Comment by SandroNeumann** [comment]
De gebruiker met email rj.vd.anker@overijssel.nl had al geen beheerrechten meer.

**Comment by gerardnienhuis** [comment]
issue kan gesloten.
