### ISSUE TITLE
Verwijderen 0 records fout

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#81]
Als ik uit de prullenbak een aantal dingen wil verwijderen, dan gaat er wat fout: ik heb 20 records geselecteerd, maar ik krijg de melding dat ik er 0 ga verwijderen. Dat is niet goed

![o_records_prullenbak_bug](https://cloud.githubusercontent.com/assets/9005444/13314332/fa164240-dba4-11e5-9a33-23f725cc898d.jpg)

**Comment by SandroNeumann** [comment]
Dit is dezelfde issue als #59.
