### ISSUE TITLE
kolom nummer in invoermodule overige data maximaal 15 tekens

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#811]
nu wordt het veld "nummer" in de invoermodule voor overige data (statische kaarten) ook gebruikt voor het opnemen van een link. Dat heeft als gevolg dat bij lange urls de hele kolom verminkt raakt, zie plaatje. Wens is om de kolom voor "nummer" maximaal 15 posities breed te laten zijn, en als het om bredere urls gaat dan 15 posities, dan aangeven met ...

dus nummer 12345678901234567890 wordt 123456789012345...
en bij urls ook op de zelfde manier tekst afkorten

![nummer_max_12_posities](https://github.com/IDgis/geoportaal-test/assets/9005444/a3dded93-e661-454b-8d73-2783d6c8da0e)

**Comment by SandroNeumann** [comment]
In de titel staat maximaal 12 maar in de omschrijving maximaal 15. Wat wordt het?

**Comment by gerardnienhuis** [comment]
Als 15 mogelijk is, zonder de tabel te breed te maken, dan graag 15. Anders 12. Bedoeling is dat de tekst in de kolommen weer netjes onder elkaar komt, in plaats van zoals nu door elkaar heen gaat lopen.

**Comment by SandroNeumann** [comment]
Is het ook de bedoeling dat het onmogelijk moet zijn (vanaf nu) om meer dan 15 tekens in te voeren? Of puur afkorten in de lijst? @gerardnienhuis

**Comment by gerardnienhuis** [comment]
nee, een gebruiker mag best meer tekens invoeren, maar in de lijst zie je alleen de eerste 12 of 13 of 14 of 15. Getal afhankelijk van hoe de lijst praktisch uit te lijnen is. Streven is 15, maar als minder moet dan is dat ook goed.

**Comment by gerardnienhuis** [comment]
dit blijkt goed te werken, getest met lange en korte nummers. functioneert nu zoals besproken. Issue kan gesloten.
