### ISSUE TITLE
WFS afwezig dan download link niet tonen bij details

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#813]
Nu komt het voor, meestal bij grids, dat de download link te zien is, zonder dat de WFS bestaat. Wens is dan om bij het tabblad DETAILS ook de download link niet te tonen (geeft grote verwarring en werkt ook nog eens niet).

**Comment by SandroNeumann** [comment]
Hoe is dit te reproduceren?

**Comment by SandroNeumann** [comment]
We gaan het op een andere manier oplossen.

**Comment by gerardnienhuis** [comment]
Issue kan gesloten, omdat een andere oplossingsrichting is gekozen.
