### ISSUE TITLE
Zoeken moet ook deel van een woord vinden

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#82]
Als ik een deel van een woord zoek, dan wil ook in de zoekresultaten alle records zien, waar dat woord in zit, ook als het een deel is van een groter woord. Bijvoorbeeld. In een bepaald record is het woord "konijnenhok" opgenomen. Dan wil ik graag dat een gebruiker die het woord "konijn" als zoekterm gaat gebruiken, ook het record met "konijnenhok" vind. En als ik "ree" zoek dan wil ik ook records vinden waar het woord "reeën" in zit.

Merk op: "reeën" zoeken en vinden gaat in huidige geoportaal soms fout, moet wel aantoonbaar goed gaan in nieuwe geoportaal. 

nb: Het risico dat je hiermee teveel resultaten krijgt, is minder ernstig, dan als je iets niet vind, wat je wel denkt dat aanwezig is. Bovendien kan je altijd nog de zoekterm uitbreiden met een tweede trefwoord. Omdat dat als AND werkt, kan je hier ook nog een keer elegant je zoekterm aanpassen.

**Comment by SandroNeumann** [comment]
Is het de bedoeling dat je ook het midden en het eind van een woord moet kunnen vinden, of is het begin voldoende? Dus moet je in het woord "konijnenhok" ook het record vinden wanneer je op "nijnen" of "hok" zoekt?

**Comment by gerardnienhuis** [comment]
Correct: als je hok zoekt, dan wil je ook konijnenhok vinden
Als je nijnen zoekt, dan ook
Dus de zoekterm die je gaat invoeren, die heeft altijd een \* ervoor en ook erachter (in huidige systeem moet je die \* neerzetten, in nieuwe systeem dus niet)

**Comment by SandroNeumann** [comment]
Met de huidige tooling gaat dit niet volledig werken. Er kan wel op een deel van een woord gezocht worden als de zoekterm het begin van het woord is. Maar als de zoekterm een middenstuk of het eind van een woord is wordt het record niet gevonden. Dus in geval van "konijnenhok" wordt het record gevonden wanneer je op konijnen zoekt, maar niet wanneer je op hok zoekt.

**Comment by gerardnienhuis** [comment]
Andere tooling in zetten?

Verstuurd vanaf mijn iPhone

Op 29 feb. 2016 om 10:44 heeft SandroNeumann <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Met de huidige tooling gaat dit niet volledig werken. Er kan wel op een deel van een woord gezocht worden als de zoekterm het begin van het woord is. Maar als de zoekterm een middenstuk of het eind van een woord is wordt het record niet gevonden. Dus in geval van "konijnenhok" wordt het record gevonden wanneer je op konijnen zoekt, maar niet wanneer je op hok zoekt.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/82#issuecomment-190126381.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
Omdat andere tooling niet eenvoudig inzetbaar blijkt, gaan we het gewoon uitproberen. Mocht het toch voor gebruikers onwerkbaar zijn, dan pas wordt herbouw (inzet van andere middelen voor zoeken) nader onderzocht. Issue kan gesloten worden daarom. Wordt nog niet in huidige versie opgepakt.
