### ISSUE TITLE
4 kolommen aanvullende informatie in rapport

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#822]
Wens is om 4 kolommen aan het rapport van geodata toe te voegen. Hierdoor kunnen wij als beheerders makkelijker vinden welke aanvullende informatie is gekoppeld en welk type informatie dat is.

na kolom layer_names (in excel is dit kolom AI)
voor kolom http_errors_urls (in excel is dit nu nog kolom AJ)

4 kolommen toevoegen:

aanvullend_compleet
aanvullend_url
aanvullend_naam
aanvullend_extensie

voorbeeld 1:

Bestandsnaam: Basisregistratie Adressen en Gebouwen (Adressen en verblijfsobjecten) (BAG versie 2)
https://www.geoportaaloverijssel.nl/metadata/dataset/a338d340-d6b4-4adf-a9c5-43d9003cf951

Daar staat: Aanvullende informatie: Productinformatie| https://metadata.geodataoverijssel.nl/attachment/188831/ProductinformatieBAGv2.pdf

Dat wordt in het rapport:

aanvullend_compleet : Productinformatie| https://metadata.geodataoverijssel.nl/attachment/188831/ProductinformatieBAGv2.pdf
aanvullend_url : https://metadata.geodataoverijssel.nl/attachment/188831/ProductinformatieBAGv2.pdf
aanvullend_naam : ProductinformatieBAGv2.pdf
aanvullend_extensie: pdf

Voorbeeld 2:

Bestandsnaam: Eeuwenoud bos
https://www.geoportaaloverijssel.nl/metadata/dataset/7b93abb6-f91b-47e0-a5ea-8e93b0552e2f

Daar staat: Aanvullende informatie: layerfile| https://metadata.geodataoverijssel.nl/attachment/186771/oudbos.lyr

Dat wordt in het rapport:

aanvullend_compleet : layerfile| https://metadata.geodataoverijssel.nl/attachment/186771/oudbos.lyr
aanvullend_url : https://metadata.geodataoverijssel.nl/attachment/186771/oudbos.lyr
aanvullend_naam : oudbos.lyr
aanvullend_extensie: lyr

**Comment by SandroNeumann** [comment]
Ik heb dit geïmplementeerd @gerardnienhuis . Op deze manier:

- aanvullend_compleet de hele string in het XML element
- aanvullend_url van het einde tot het het pipe teken tegenkomt
- aanvullend_naam van het einde tot het een van de slashes tegenkomt
- aanvullend_extensie van het einde tot het een punt tegenkomt

Dat gaat goed. Behalve soms de laatste twee bij bepaalde strings.

Bijvoorbeeld deze:
`Website omgevingsvisie 2017|https://overijssel.tercera-ro.nl/MapViewer/Default.aspx?id=NLIMRO9923OmgevingsvisieOv01-va01`
`Energieatlas|https://geo.overijssel.nl/viewer/app/master/v1?bookmark=4960f5d914bd49f5abdc044e73363496`

Leiden tot naam:
`Default.aspx?id=NLIMRO9923OmgevingsvisieOv01-va01`
`v1?bookmark=4960f5d914bd49f5abdc044e73363496`

En tot prefix:
`aspx?id=NLIMRO9923OmgevingsvisieOv01-va01`
`nl/viewer/app/master/v1?bookmark=4960f5d914bd49f5abdc044e73363496`

Dat klopt o.b.v. de regels en die kloppen voor bijna alle records. Maar een paar niet omdat het URL's zijn waar de punt m.b.t. een extensie ontbreekt en er tevens niet een naam na de laatste slash van te maken valt.

Hoe zie jij dit? Wil je dit herzien?

**Comment by gerardnienhuis** [comment]
lijkt me prima om het eerst zo te proberen.

**Comment by gerardnienhuis** [comment]
bezig met testen: kolommen zijn aanwezig en gevuld.

**Comment by gerardnienhuis** [comment]
De testen geven foutmelding bij verdere verwerking in python. Mogelijk bevat metainformatie fouten.

**Comment by SandroNeumann** [comment]
Waar valt de python verwerking over? @gerardnienhuis

**Comment by gerardnienhuis** [comment]
Ik verwacht dat het speelt bij de verwerking van de individuele velden. We hebben 1 record wat aantoonbaar fout is, daar is een datumveld foutief gevuld met "niet datum" waarden. Maar ook als je die fout uit het inputbestand verwijderd, dan blijft de fout bestaan. Het ligt waarschijnlijk aan de python scripts zelf dus niet aan de extra kolommen op zich. 

Wij zoeken het nu uit. Lukt het ons niet om dit probleem op te lossen, dan is de noodoplossing om deze 4 kolommen niet in het rapport op te nemen. En dus de situatie laten zoals het nu is.

**Comment by gerardnienhuis** [comment]
Het probleem van het python script is onderzocht. Er blijkt geen probleem te zijn. De verschijnselen die in python optraden hadden te maken met niet goed gevulde velden in de metadata zelf. Ze hadden niets te maken met de extra kolommen die zijn toegevoegd. Die kolommen blijken correct aanwezig en voorzien van de gevraagde inhoud. Het werkt dus goed en dit issue kan gesloten worden.
