### ISSUE TITLE
Wanneer er een raster gedownload mag worden die ook in de metadata bij de WAT en in Geoportaal tonen

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#824]
Dus:

Onder de beschrijving in de metadata en wanneer je zoekt in het geoportaal op de regel naast Meer informatie en Bekijk in viewer. Zoals dat ook bij vector bestanden het geval is.

**Comment by SandroNeumann** [comment]
Kun je een voorbeeld aandragen waar dit fout gaat, @gerardnienhuis ?

**Comment by gerardnienhuis** [comment]
Dit probleem blijkt niet op te treden. Er zijn wel grid-achtige bestanden in het Geoportaal, maar dat zijn grids, die zijn omgezet naar vlakken. En die worden gewoon correct weergegeven. Alle meer dan 150 bestanden met zoekwoord "raster" bekeken, en er zijn geen problemen gevonden. Als steekproef download van zo'n grid-achtig bestand getest en het blijkt dat de download gewoon correct een shape oplevert, als je dat als shape wilt downloaden. 

https://intern.geoportaaloverijssel.nl/metadata/dataset/2705c807-4958-48e3-8507-7c724eae6a04
Bestandsnaam: Concentratie van asbestverdachte daken
Ruimtelijk schema: Vector

Omdat het probleem niet aanwezig lijkt kan dit issue gesloten worden.
