### ISSUE TITLE
Toepassingsschaal dubbel punt ontbreekt bij WAT in stylesheet 

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#825]
Toepassingsschalen worden geschreven als 1:2500 of 1:100000 maar het getal wat nu bij de WAT te zien is, in het Geoportaal, dat is 2500 of 100000. De dubbele punt ontbreekt. 

![toepassingsschaal_dubbele_punt_ontbreekt](https://github.com/IDgis/geoportaal-test/assets/9005444/52e5bb43-0bfb-4c50-84c6-074fda304f8e)
Wens is om in de stylesheet van de pagina WAT een verandering aan te brengen. Neem wel de dubbele punt op. Let op: het kan voorkomen dat er 1 getal voor toepassingsschaal wordt genoemd. Maar soms zijn er ook 2 getallen hiervoor. 

In onderstaande plaatje een voorbeeld, hoe het er uit kan gaan zien. Hier is dus de dubbele punt toegevoegd aan het bestaande beeld, ter illustratie. Voorbeeld op basis van:
https://www.geoportaaloverijssel.nl/metadata/dataset/deeedbcb-d7e8-44e8-aceb-9d83bf64d285 
Bestandsnaam: Clustergebieden windenergie
Toepassingsschaal: 100000

**Comment by gerardnienhuis** [comment]
@SandroNeumann : dit issue is nieuw. Wil je hiervan nog de impact inschatten. Ik hoop laag, maar weet dat niet zeker, vandaar mijn vraag.

**Comment by SandroNeumann** [comment]
@gerardnienhuis 

Ik zie dat het in de XML ook als dat getal staat:

```
<spatialResolution>
  <MD_Resolution>
    <equivalentScale>
      <MD_RepresentativeFraction>
        <denominator>
          <gco:Integer>100000</gco:Integer>
       </denominator>
     </MD_RepresentativeFraction>
   </equivalentScale>
  </MD_Resolution>
</spatialResolution>
```

Maar dat is het element `gco:Integer` dus daarom ontbreekt die dubbele punt zeker want anders is het een `gco:CharacterString`.

We kunnen dit vrij eenvoudig implementeren.

**Comment by gerardnienhuis** [comment]
Goed te horen, dat het eenvoudig op te pakken is. Geldt dat ook als we 2 getallen voor de schaal gaan leveren? Dus min en max waarde? Ik heb eerdere voorbeelden gezien in het Geoportaal, waar dit goed ging (zonder punt). Maar vraag het even voor de zekerheid.

**Comment by SandroNeumann** [comment]
Heb je voorbeelden van hoe je het gaat schrijven met min en max?

**Comment by gerardnienhuis** [comment]
wij leveren 2 getallen, zoals ook in het verleden is gedaan. Het eerste getal is de minimum waarde, het tweede getal de maximum waarde, zie bijvoorbeeld 

Bestandsnaam: Vastgestelde zonering Monitoring Bedrijventerreinen
https://www.geoportaaloverijssel.nl/metadata/dataset/3ebcb077-644a-4c85-a9cd-aee2b5f2a890

bij de WAT staat:
Toepassingsschaal: 5000
Toepassingsschaal: 50000

Minimum waarde is als eerste geleverd, en is in dit voorbeeld 5000
Maximum waarde is als tweede geleverd en is in dit voorbeeld 50000
nb: meer dan 2 waarden worden nooit geleverd.

**Comment by gerardnienhuis** [comment]
Aan de volgorde en methode van verwerken van deze 2 waarden hoeft niks te veranderen, Maar in de stylesheet voor de WAT moet de dubbel punt worden toegevoegd, zowel als er 1 getal wordt geleverd en ook als er 2 getallen worden geleverd, zoals in voorgaand voorbeeld.

**Comment by SandroNeumann** [comment]
Dat zijn dezelfde elementen:

```
<spatialResolution>
  <MD_Resolution>
    <equivalentScale>
      <MD_RepresentativeFraction>
        <denominator>
          <gco:Integer>5000</gco:Integer>
        </denominator>
      </MD_RepresentativeFraction>
    </equivalentScale>
  </MD_Resolution>
</spatialResolution>
<spatialResolution>
  <MD_Resolution>
    <equivalentScale>
      <MD_RepresentativeFraction>
        <denominator>
          <gco:Integer>50000</gco:Integer>
        </denominator>
      </MD_RepresentativeFraction>
    </equivalentScale>
  </MD_Resolution>
</spatialResolution>
```

Dus dat gaat op dezelfde manier werken in de stylesheet.

Dus antwoord op de originele vraag:

>Geldt dat ook als we 2 getallen voor de schaal gaan leveren?

Ja.

**Comment by gerardnienhuis** [comment]
Het lijkt er op alsof dit nog niet goed werkt, zie bijvoorbeeld onderstaand voorbeeld:

https://acc-intern.geoportaaloverijssel.nl/metadata/dataset/f5e01248-5842-4ed1-a579-39584b78ea83
Bestandsnaam: Locatie van windturbines

er staat bij WAT:

Toepassingsschaal: 1:10000

dat had moeten zijn:

Toepassingsschaal: 1:10.000

**Comment by gerardnienhuis** [comment]
klopt dit wel?

**Comment by SandroNeumann** [comment]
Dat is een andere wens. Dit issue ging om de dubbele punt.

Het was:
`Toepassingsschaal: 10000`

Het is nu:
`Toepassingsschaal: 1:10000`

Wil je de aanpassing m.b.t. de punt nog in deze milestone meenemen?

**Comment by gerardnienhuis** [comment]
correct. Die : is nu goed zichtbaar, bijvoorbeeld te zien bij testbestanden. Bij de WAT staat:
Toepassingsschaal: 1:5000
Toepassingsschaal: 1:50000

Wat mij betreft akkoord, issue kan gesloten
nb: of er ook nog een punt tussen moet, dus 1:50.000 dat is inderdaad een ander issue, en zal ik apart voor een volgende versie opvoeren.
