### ISSUE TITLE
Fixen van gebroken rapport overige data

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#827]
De output van het rapport van overige data is incorrect wanneer er dubbele quotes (") in de data zit. Een regelmatig voorkomend geval is in de samenvatting. Er moet gecontroleerd worden of dat in de andere rapporten ook plaatsvindt. Want het rapport van overige data is de enige die niet via een generiek component gaat maar ingebakken is in het geoportaal.

Als het probleem alleen in overige data zit. Dit ook naar het generieke component verhuizen en uit het geoportaal halen. Als het probleem overal optreedt kijken hoe dit het beste te fixen.

**Comment by SandroNeumann** [comment]
De output wordt niet op een andere manier gegenereerd. Het goede nieuws is dat er ook geen gebroken output is. Ik had een verkeerde optie aanstaan bij het inladen van de csv in excel. Namelijk naast de puntkomma als kolom scheiding ook de spatie. Dat resulteerde in een nieuwe kolom bij elke `" `. Wat nogal eens voorkomt. Anders komt er alleen een nieuwe kolom bij de combinatie `";`. Theoretisch kan dat ook in de tekst voorkomen maar dat lijkt niet te gebeuren dusver. @gerardnienhuis

**Comment by gerardnienhuis** [comment]
Dit issue is niet erg urgent, omdat wij hebben afgesproken dat we het teken ; zoveel mogelijk vermijden. Veel mensen kennen de verschillen tussen : en ;  niet goed en om verwarring te voorkomen, streven wij er naar om in de metadata altijd : te gebruiken in plaats van ; ... dat zal 1 van de oorzaken zijn dat de combinatie ";  niet vaak in de metadata gaat voorkomen. Goed om te weten dat het kan voorkomen, maar geen reden om nu op te lossen. Issue kan gesloten worden op dit moment.
