### ISSUE TITLE
Locatie statische kaarten in metadata aanpassen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#841]
Vandaag zijn de laatste bestanden van 2018 en 2019 verplaatst van K:\BAB\ naar K:\BAB-Archief\
Verzoek is om ook in de metadata deze verandering te laten terugkomen. 
Deze actie is al vaker uitgevoerd, zie:

https://github.com/IDgis/geoportaal-test/issues/698
https://github.com/IDgis/geoportaal-test/issues/514

en zie bijgevoegde schermafdruk van de metainformatie zoals die nu zichtbaar is, als voorbeeld.

**Comment by gerardnienhuis** [comment]
![locatie_statische_kaart_groene_pijlen](https://github.com/user-attachments/assets/926331fa-2a37-4ee9-a95d-fff188dfe68c)

**Comment by SandroNeumann** [comment]
Query voor met jaartal en id:

```
update gb.metadata set location = 'K:\BAB-Archief\' || split_part(location, '\', 4) || '\' || split_part(location, '\', 5)
where location ilike 'K:\\bab\\geo-informatie\\%'
and split_part(location, '\', 4) != ''
and split_part(location, '\', 4) != 'Projectenkaart'
and split_part(location, '\', 5) != ''
and (split_part(location, '\', 4)::int = 2018
	or split_part(location, '\', 4)::int = 2019
)
```

Query voor met alleen jaartal:

```
update gb.metadata set location = 'K:\BAB-Archief\' || split_part(location, '\', 4)
where location ilike 'K:\\bab\\geo-informatie\\%'
and split_part(location, '\', 4) != ''
and split_part(location, '\', 5) = ''
and (split_part(location, '\', 4)::int = 2018
	or split_part(location, '\', 4)::int = 2019
)
```

@gerardnienhuis 

Het is uitgevoerd op acceptatie. Wil je er naar kijken?

**Ter info**:
Ik ben naast dat de locaties soms met kleine of grote letters geschreven worden nog wat opmerkelijke gevallen tegengekomen.

De gevallen van locaties die beginnen met:

- K:\BAB\Geo-informatie\Projectenkaart
- K:\bab\geo-informatie\20219
- K:\BAB-Archief\kaartarchief
- K:\BAB-Archief\Peilbestanden_WK
- K:\BAB-Archief\B150083AB
- K:\BAB-Archief\150248
- K:\BAB-Archief\200
- K:\BAB-Archief\150233
- K:\BAB-Archief\Offline_bestanden

**Comment by gerardnienhuis** [comment]
Het is zojuist getest op acceptatie, steekproeven uitgevoerd, de verandering van verwijzing lijkt goed te werken, zie details hieronder. De "vreemde" verwijzingen die gevonden zijn, die worden nader onderzocht (los van dit issue). Omdat het werkt op acceptatie, kan dit op productie worden uitgerold.

2019 met verwijzing naar K:\BAB-Archief: (correct)

Naam overige dataset: Evaluatie proef automatische verwerking cartografische milieu inventarisatiegegevens
https://acc-intern.geoportaaloverijssel.nl/metadata/dc/41d16436-063d-46ca-b5ac-db34505402ae
Nummer: 190100_024
Locatie: K:\BAB-Archief\2019\190100

2019 met verwijzing naar K:\BAB-Archief:  (correct)

Naam overige dataset: Twente, Ecologische differentiatie van laaggelegen cultuurgebieden
https://acc-intern.geoportaaloverijssel.nl/metadata/dc/beaac2dd-9a2c-4986-b70f-92d0ea3d257c
Nummer: 190129_038
Locatie: K:\BAB-Archief\2019\190129

2020 met verwijzing naar K:\bab (onveranderd, dus correct): 

Naam overige dataset: Agrarische bedrijven zonder bedrijfsopvolger
https://acc-intern.geoportaaloverijssel.nl/metadata/dc/b55823b5-7132-4b87-8cb0-bc32ba81e45c
Nummer: 240109
Locatie: K:\bab\geo-informatie\2024\

**Comment by gerardnienhuis** [comment]
Actie is correct uitgevoerd. Controle (op basis van verschillende steekproeven) laat geen problemen zien.
