### ISSUE TITLE
url direct naar editen van kaart

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#89]
Ik weet niet zeker of dit al werkt nu: ik zou graag een url willen kunnen gebruiken, waarbij ik direct in de editor van statische kaarten kom, zodat een persoon deze betreffende statische kaart ook direct kan gaan aanpassen. Ik vermoed dat dit nu al zou kunnen, door de url te kopieren die je ziet, als je de betreffende statische kaart aan het wijzigen bent, maar ik weet niet of dit ook in de productieversie zou blijft werken.

**Comment by SandroNeumann** [comment]
Ja, dat blijft zo werken. Ter info: dit werkt ook wat betreft de zoekopdrachten. Je kunt zoekopdrachten bookmarken, zodat je altijd de selectie van de zoekopdracht ziet.

**Comment by gerardnienhuis** [comment]
klinkt goed: ga ik testen bij de volgende testronde.

**Comment by gerardnienhuis** [comment]
werkt goed
