### ISSUE TITLE
Tekst voor het genereren van ID aanpassen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#9]
@PeterAukeNicolaij vraagt: Een ander punt is het genereren van het Unieke ID. Mijn vraag is wanneer gebeurt dit?  Als het bij opslaan gebeurt dan zou ik dat ook vermelden in het schermpje:
![image](https://cloud.githubusercontent.com/assets/2979044/12481414/43bba38a-c049-11e5-8177-1782efdc69b4.png)

**Comment by gerardnienhuis** [comment]
lijkt me niet de correcte verwijzing

**Comment by SandroNeumann** [comment]
Klopt, dat was een vergissing. De verwijzing in issue 59 verwijst nu wel naar de juiste issue.

**Comment by gerardnienhuis** [comment]
tekst is nu goed, id wordt ...
is goed nu / test 24-2-16
