### ISSUE TITLE
Bestandgrootte zichtbaar maken

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#92]
De bestanden die worden beschreven die kunnen mogelijk 100 Mb of groter zijn. Dat heeft de kans, dat hierdoor problemen ontstaan. Voor leveranciers en beheerders is het handig als te zien is, hoe groot een bestand is (afgerond in Mb). Voorstel is om dat bij een (reeds gekoppeld) bestand te vermelden, als het betreffende record is opgeslagen.

**Comment by gerardnienhuis** [comment]
![bestand_grootte_wens](https://cloud.githubusercontent.com/assets/9005444/13600120/07b6e1f8-e527-11e5-9254-8bba61bd990e.jpg)

**Comment by gerardnienhuis** [comment]
is gelukt, werkt prima. Getallen (in Mb) zijn niet zelfde als originele data (iets kleiner), mogelijk door andere opslag? Graag spatie tussen getal en tekst MB zelf, als het kan.

**Comment by SandroNeumann** [comment]
Niet elk systeem berekent de grootte op dezelfde manier. Kort gezegd moeten bytes twee maal door 1024 gedeeld worden, maar veel systemen delen simpelweg door één miljoen. Wij doen het op de eerste manier, dat is de echte omvang.

**Comment by gerardnienhuis** [comment]
ok, helder: werkt prima zo, issue kan gesloten
