### ISSUE TITLE
viewer in stylesheet metainfo voor data

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#93]
Als er van een dataset in de publicatieomgeving een wms van gemaakt is, dan zou ik die wms ook zichtbaar willen maken in de metainformatie van die betreffende dataset. het lijkt er op dat in de publicatieomgeving die link te maken zou moeten zijn, voorop gesteld dat de nieuwe atlassen van Overijssel het toestaan dat een wms meteen ook zo te koppelen is (direct uit database, of door url samen te stellen). Vraagt wat uitzoekwerk maar levert veel gemak voor gebruikers op, als je meteen een live-kaart hebt waarin de data benaderbaar is.

**Comment by gerardnienhuis** [comment]
![stylesheet_met_link_naar_atlas](https://cloud.githubusercontent.com/assets/9005444/13702363/6a7dcbf8-e78e-11e5-8838-733ae0210720.jpg)

**Comment by HermanAssink** [comment]
Om dit te laten werken is het nodig dat de Atlas een standaard manier heeft voor het tonen van een bepaalde kaartlaag van een WMS. Je kunt ook denken aan de preview-functie van GeoServer icm OpenLayers.

**Comment by gerardnienhuis** [comment]
Het lijkt een goed idee om de geo-server preview te gebruiken voor visualisatie van de wms: ik hoop dat de impact hiervan gering is, omdat deze preview ook al werkt in de publicatieomgeving,

**Comment by SandroNeumann** [comment]
opmerking van @gerardnienhuis : 
Als extra regel toevoegen: Bekijk hier in de viewer
en dan hele regel onderstreept, aanklikbaar en zorgen dat viewer wordt geopend
(op de plaats waar nu in voorbeeld: atlas van Overijssel staat).

**Comment by SandroNeumann** [comment]
let op: alleen als WMS aanwezig is natuurlijk, anders niet laten zien in stylesheet

**Comment by gerardnienhuis** [comment]
Alternatief wat sneller te realiseren is: open layers mogelijkheid van geoserver gebruiken.
Dus wel met de tekst: bekijk deze kaart in de viewer, dan daarna openen, zoals onderstaande 2 voorbeelden:

http://services.geodataoverijssel.nl/geoserver/B14_bestuurlijke_grenzen/wms?service=WMS&version=1.1.0&request=GetMap&layers=B14_bestuurlijke_grenzen:B1_Gemeentegrenzen_Overijssel_vlak&styles=&bbox=175000,450000,275000,550000&width=512&height=512&srs=EPSG:28992&format=application/openlayers 

http://services.geodataoverijssel.nl/geoserver/B14_bestuurlijke_grenzen/wms?service=WMS&version=1.1.0&request=GetMap&bbox=175000,450000,275000,550000&layers=B14_bestuurlijke_grenzen:B1_Gemeentegrenzen_Overijssel_vlak&styles=&width=812&height=512&srs=EPSG:28992&format=application/openlayers

**Comment by HermanAssink** [comment]
Dit werkt voor lagen, maar niet voor een service. Het lijkt me de moeite waard om te onderzoeken of de viewer van de publicatieomgeving hiervoor, met niet teveel werk, aan te passen is.

**Comment by gerardnienhuis** [comment]
Maar als ik als gebruiker de stylesheet van een downloadbare kaart voor mijn neus heb, dan is hiervan laaginformatie beschikbaar. Zou deze technische oplossing dan niet gewoon kunnen werken? nb: je mist natuurlijk wel een mooi achtergrond plaatje, wat er voor zou pleiten om inderdaad de viewer aan te passen... Tenzij in de openlayers opdracht die achtergrondkaart van bijvoorbeeld pdok meteen mee te nemen is in het zoomvenster?

Of is dat juist de aanpassing van de viewer in de publicatieomgeving die je bedoelt?

**Comment by gerardnienhuis** [comment]
merk op: in de http string staat wel een servicenaam en laagnaam, maar die zijn nu niet direct uit de metadata in de stylesheet terug te vinden. Deze namen zijn echter wel vindbaar in de rapportage van Geodata, dus de string **## B14_bestuurlijke_grenzen:B1_Gemeentegrenzen_Overijssel_vlak** kan nu al opgebouwd worden. En dus ook het volledige request, zoals in dit voorbeeld:

http://services.geodataoverijssel.nl/geoserver/B14_bestuurlijke_grenzen/wms?service=WMS&version=1.1.0&request=GetMap&bbox=175000,450000,275000,550000&layers=B14_bestuurlijke_grenzen:B1_Gemeentegrenzen_Overijssel_vlak&styles=&width=812&height=512&srs=EPSG:28992&format=application/openlayers

**Comment by gerardnienhuis** [comment]
Ik wil graag een viewer, die gebruik maakt van de achtergrondkaart van pdok, brt standaard pastel, met daarop de WMS. Ik wil graag dat dat zichtbaar wordt bij de zoekresultaten, als een WMS aaanwezig is.
je hebt dan nu:

Meer informatie Download 

Dat wordt dan

Meer informatie Bekijk kaart Download

**Comment by gerardnienhuis** [comment]
Hiermee volg ik dus de suggestie van Herman om de viewer van de publicatieomgeving ook hiervoor te gebruiken.

**Comment by SandroNeumann** [comment]
Zie ook #334

**Comment by SandroNeumann** [comment]
Moet dit alleen bij datasets of ook bij services?

**Comment by gerardnienhuis** [comment]
alleen bij datasets

**Comment by SandroNeumann** [comment]
De GeoPublisher-viewer haalt op dit moment alle services van een bepaalde omgeving op. Voor deze wens hebben we twee opties:

- De service en alle lagen ophalen en dan vervolgens de laag waarvan in de stylesheet op geklikt is initieel aangevinkt en dus zichtbaar
- Alleen de specifieke laag ophalen en dus in de inhoudsopgave alleen de service als kopje tonen en 1 laag daaronder

**Comment by gerardnienhuis** [comment]
graag 

•Alleen de specifieke laag ophalen en tonen

**Comment by HermanAssink** [comment]
Dit werk wordt op 13 uren geschat.

**Comment by gerardnienhuis** [comment]
Wens is om viewer in apart tabblad te openen, op maximale grootte.

**Comment by robstek** [comment]
Indien weinig impact, dan ook voor services

**Comment by robstek** [comment]
Niet alleen link in lijst van zoekresultaten, maar ook in de details van metadata.

In ieder geval bij geodata, indien weinig impact ook bij services

of in metadata xml  (bij voorkeur) of in stylesheet opnemen

**Comment by robstek** [comment]
Ook opnemen bij tabblad "Wat".

Link tekst wordt: "Bekijk de kaart in een viewer" tussen Samenvatting en Voorbeeld met witregels.

Bij "Wat" mag maar 1 link staan, ook als bij "Details" er meer staan.

wordt uitgezocht hoe technisch op te lossen

**Comment by SandroNeumann** [comment]
De viewer is aangepast.

Todo: xml en de stylesheet aanpassen

**Comment by SandroNeumann** [comment]
Bij het genereren van de url in de XML moet een onderscheid gemaakt worden of de laag in de service op hoofdniveau of in een groepslaag zit:

Voorbeeld:

Hoofdniveau:
http://acc-services.geodataoverijssel.nl/viewer/layer/B47_flora_en_fauna/B4_Weidevogel_en_ganzengebieden

In een groepslaag:
http://acc-services.geodataoverijssel.nl/viewer/layer/B47_flora_en_fauna/B47_flora_en_fauna:B4_Weidevogel_en_ganzengebieden [-eventueel volgnummer]

**Comment by gerardnienhuis** [comment]
Zou voor alle geodata waarbij een wms is gemaakt, moeten werken.
Als een download link aanwezig is, dan is er een wms en wfs, dus moet altijd link naar viewer er zijn.
Is niet altijd het geval. Hieronder 2 voorbeelden waar het wel goed werkt en 8 voorbeelden waar nog aandacht nodig is.

**voorbeeld 1:**
Bestandsnaam: Kansrijk zoekgebied voor windenergie
http://acc-services.geodataoverijssel.nl/viewer/layer/B42_energie/B4_Kansrijk_zoekgebied_voor_windenergie
bekijk in viewer werkt wel
download link correct aanwezig

**voorbeeld 2:**
Bestandsnaam: Historische infrastructuur
http://acc-services.geodataoverijssel.nl/viewer/layer/B73_Cultuur/B7_Historische_infrastructuur
bekijk in viewer werkt wel
download link correct aanwezig

**voorbeeld 3:**
Zandwinlocatie's in Overijssel
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/51f59aac-3c4b-4995-ab8e-c30c613823b1.xml
bekijk in viewer link aanwezig maar werkt niet: geeft error
This exception has been logged with id 72j07lomc.
nb; als extra test is de WMS in Qgis ingelezen, betreffende laag is probleemloos in kaart zichtbaar te maken.

**voorbeeld 4:**
Bestandsnaam: Ontgrondingen in Overijssel
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/d66cc0d3-9130-44b6-97f0-fd200f37e1a0.xml
bekijk in viewer werkt niet
This exception has been logged with id 72j07nil1.
nb; als extra test is de WMS in Qgis ingelezen, betreffende laag is probleemloos in kaart zichtbaar te maken.

**voorbeeld 5:**
Bestandsnaam: Bodemkaart, met veenkartering
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/17df64ef-bcbb-4c90-b3c3-9551143f32a4.xml
link bekijk in viewer is wel aanwezig, maar downloadlink is afwezig: vreemd.
bekijk in viewer werkt niet, geeft error
This exception has been logged with id 72j081bne.
nb; als extra test is de WMS in Qgis ingelezen, betreffende laag is probleemloos in kaart zichtbaar te maken.

**voorbeeld 6:**
Bestandsnaam: Stortplaatsen
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/1925b2f8-199d-4eea-bb90-f98ffe42d939.xml
bekijk in viewer werkt niet
This exception has been logged with id 72j083ge2.

**voorbeeld 7:**
Bestandsnaam: Beschermingsplan boomkikkers
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/c3ce8efd-74e8-488c-8f32-14651f45c024.xml
bekijk in viewer werkt niet
This exception has been logged with id 72j085887.
Opvallend is het dat "bekijk service in viewer" wel goed werkt, 
ook voor deze kaartlaag. Dus als je beschermingsplan boomkikkers aanvinkt,
dan wordt kaart correct weergegeven. 

**voorbeeld 8:**
Bestandsnaam: Begrenzing EHS en Zone Ondernemen met Natuur en Water
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/8dd25b28-366d-4ffe-9dfc-dba650ad4a0d
link naar bekijk in viewer ontbreekt, waarom? 
downloadlink is wel aanwezig.

**voorbeeld 9:**
Bestandsnaam: Gemeentegrenzen Overijssel (lijnen)
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/0918da6c-ffeb-4cec-8668-8b857b5f1cf8
bekijk in viewer werkt niet
This exception has been logged with id 72j08a8np.

**voorbeeld 10:**
Bestandsnaam: Nederzettingsvormen
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/c71504aa-9311-44d3-890f-6a9606714871.xml
link naar viewer:
http://acc-services.geodataoverijssel.nl/viewer/layer/B73_Cultuur/B7_Nederzettingsvormen
viewer opent wel, achtergrondkaart is zichtbaar maar kaart Nederzettingsvormen is niet zichtbaar

**Comment by gerardnienhuis** [comment]
Merk op: de link had ook in de lijst van zoekresultaten moet staan, daar ontbreekt dit ook nog. 
zie ook opmerking van @robstek van 16 december 2016.

**Comment by gerardnienhuis** [comment]
Merk op: de link had ook in de lijst van zoekresultaten moet staan, daar ontbreekt dit ook nog.
zie ook opmerking van mij van 8 december en van @robstek  van 16 december 2016.

Bij zoekresultaten ontbreekt de link nog. Er staat nu:

Meer informatie Download

Dat wordt dan:

Meer informatie Bekijk kaart Download

Omdat de lagen van de services ook bekeken kunnen worden, is het logisch als ook bij de zoekresultaten van de services de verwijzing naar het bekijken van kaarten komt te staan. Vergelijkbaar met geodatasets. Nu staat het al wel bij de WAT in de stylesheet van services, maar ook nog niet in de lijst met zoekresultaten. In geval van services geldt dus:

Er staat nu:

Meer informatie

Dat moet worden:

Meer informatie Bekijk kaarten

**Comment by gerardnienhuis** [comment]
Ook opvallend en nog niet goed:

Bestandsnaam: Actueel Hoogtebestand Nederland2, grid 5x5meter
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/62dfd05f-d53d-4f29-8154-f63eadad9301
hier staat wel link naar viewer
http://acc-services.geodataoverijssel.nl/viewer/layer/Raster/B0_Actueel_Hoogtebestand_Nederland_AHN5

De viewer opent ook, je ziet achtergrondkaart maar er komt geen kaartbeeld van de AHN
Merk op: dit is een grid, geen vectorbestand.

**Comment by SandroNeumann** [comment]
De error meldingen kwamen allemaal door een bug, die is nu opgelost. Verder wordt de pagina van één service nu standaard uitgeklapt weergegeven en staat op de pagina van de laag de service en laagnaam vermeld.

De link in het geoportaal (a la Meer informatie en Download) per record moet nog gedaan worden.

**Comment by gerardnienhuis** [comment]
Wens is om naast bovenstaande 3 situaties ook de veranderingen als notificatie weer te geven van onderstaande 2 statussen:

- downloadable data 
- alleen WMS beschikbaar

**Comment by gerardnienhuis** [comment]
Bovenstaande melding hoort bij 114 wordt straks verplaatst

**Comment by gerardnienhuis** [comment]
geweldig, naam en uitklappen zijn beslist van grote toegevoegde waarde. eerste testen zijn succesvol afgerond inmiddels

**Comment by gerardnienhuis** [comment]
8 van de 10 situaties die hiervoor zijn geschetst, die werken nu. Was eerst: 2 van de 10. Nog 2 openstaande vragen:

**voorbeeld 8:**

Bestandsnaam: Begrenzing EHS en Zone Ondernemen met Natuur en Water
https://acc-www.geoportaaloverijssel.nl/metadata/dataset/8dd25b28-366d-4ffe-9dfc-dba650ad4a0d
link naar bekijk in viewer ontbreekt, waarom?
downloadlink is wel aanwezig.

**voorbeeld 10:**

Bestandsnaam: Nederzettingsvormen
https://acc-metadata.geodataoverijssel.nl/metadata/dataset/c71504aa-9311-44d3-890f-6a9606714871.xml
link naar viewer:
http://acc-services.geodataoverijssel.nl/viewer/layer/B73_Cultuur/B7_Nederzettingsvormen
viewer opent wel, achtergrondkaart is zichtbaar maar kaart Nederzettingsvormen is niet zichtbaar

**Comment by SandroNeumann** [comment]
De eerste komt omdat de laag in een beveiligde service zit. Equivalent van Herman's opmerking in #349 

De tweede komt door het missen van een font:
`Rendering process failed The specified mark ttf://Wingdings#171 was not found!`

**Comment by SandroNeumann** [comment]
@gerardnienhuis Begrijp ik het goed dat de link naar de WMS op het niveau van 'Meer informatie' en 'Download' bij zoekresultaten pas in versie 1.2 moet gebeuren? Gezien dat in issue #334 staat en die onder milestone 1.2 staat.

**Comment by gerardnienhuis** [comment]
Nee, wens is dat in de huidige versie op te nemen, zoals beschreven op 16 december door @robstek

**Comment by gerardnienhuis** [comment]
werkt goed, zowel intern als extern geoportaal getest, issue kan gesloten

**Comment by gerardnienhuis** [comment]
Dit blijkt na uitrol op productie in versie 113  toch niet volledig goed te werken. Zie #436 . Dit issue kan gesloten worden, omdat #436 hier verder op ingaat.
