### ISSUE TITLE
Bij conversie eerst database legen

### ISSUE THREAD

**Issue by gerardnienhuis** [IDgis/geoportaal-test#97]
Ik begreep van Herman dat het wordt overwogen om de nieuwe oplevering van de beheeromgeving te gaan doen met de conversie van de data erbij: we krijgen dan dus alle data te zien (Nico in ieder geval, want ik wil graag dat Nico als leverancier wordt vermeld): bij de huidige records is namelijk geen eigenaar bekend). Maar ik wil dan ook graag dat de bestaande testdata wordt verwijderd. Dus aub voordat alle data geconverteerd wordt, de eerdere testinvoer verwijderen: van alle leveranciers.

**Comment by SandroNeumann** [comment]
De aankomende oplevering vindt op een nieuwe omgeving plaats, dus dat is automatisch het geval daardoor.

**Comment by gerardnienhuis** [comment]
klinkt prima, ik wacht af.

**Comment by gerardnienhuis** [comment]
is gedaan, issue kan gesloten worden
