### ISSUE TITLE
Interpretatie van element <supplementalInformation> voor download

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#98]
In het element <supplementalInformation> staan vaak additionele bestanden, zoals bijv. een .lyr bestand, die bij de download gevoegd moeten worden. In dit element staat vaak een string die het bestandtype aangeeft gevolgd door een "|" teken en vervolgens de url, bijv: "layerfile|http:\gisopenbaar.overijssel.nl\Geoportal\MIS4GIS\Lyr\rayonwk_arc.lyr". Toelichting: deze notatie met "|" teken wordt automatisch gegenereerd door GeoSticker.
Afgesproken is dat het element <supplementalInformation> tbv download als volgt geïnterpreteerd zal worden: Zoek naar het laatste "|" teken en gebruik de string daarachter als url mits deze begint met "http:" of met "https:" Als het "|" teken niet gebruik dan de hele waarde van <supplementalInformation> als url mits deze begint met "http:" of met "https:"
@robstek Implemteer jij het zo in de downloadtool?

**Comment by gerardnienhuis** [comment]
werkt goed, issue kan gesloten
