### ISSUE TITLE
Hosting van additionele bestanden in metadata van geodata door IDgis

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#99]
Vraag van Overijssel: Worden de additionele bestanden in metadata van geodata, bijv. .lyr files, gekopieerd naar en gehost door de servers van IDgis? Het is onduidelijk in hoeverre dit onderdeel is van de verleende opdracht.

**Comment by gerardnienhuis** [comment]
Dit soort bestanden moet inderdaad geharvest worden, en beschikbaar komen via servers van IDGis.
voordeel is dan dat niet beschikbaar zijn van servers van Overijssel geen directe invloed hebben op Geoportaal., zie verder ook blz 20, FO versie 5 jan 2015:

• In het Geoportaal moet bij geodata ook andere gerelateerde bestanden (zoals .lyr bestanden) geharvest en aangeboden worden vanaf de IDgis omgeving
 (ophalen van: /MD_Metadata/identificationInfo/MD_DataIdentification/supplementalInformation)

**Comment by gerardnienhuis** [comment]
lijkt al goed te werken, kan getest worden

**Comment by gerardnienhuis** [comment]
blijkt goed te gaan, issue kan gesloten
